### ISSUE TITLE
Document how to use the Flux REPL

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#1006]
Currently we only document how to start and end the REPL. We need to document using it.

- [ ] Setting variables and how they behave (they're immutable)
- [ ] Returning values (don't need yields, press `return`)
    - Mention what `yield()` does in the REPL (provides a name in the result column)
- [ ] Single-line vs multiple lines
- etc.

**Comment by pierwill** [comment]
Closed in https://github.com/influxdata/docs-v2/pull/1355.
