### ISSUE TITLE
Update Cloud sign up instructions for social sign on

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#1010]
We need to update the InfluxDB Cloud getting started "sign up" section to include information about Social Sign On. It should include:

- Options for creating an account (Google or email)
- Note that Google social sign on does **not** support email aliases.
- If a user wants to enable social sign on after creating an account using the "email" option, they can, but must use the same email address.

We may consider creating a standalone doc for creating an InfluxDB account if this adds too much detail to the Get started doc. I think we definitely want to document the most common path in getting started, but if users need more detail, we can link them to the account creation doc. Just something to consider.

##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/get-started/#sign-up

**Comment by Asalem1** [comment]
@sanderson this issue looks great. Some points we may want to consider:

- If all goes well, Github as a social identity provider should hit the app on Monday

> If a user wants to enable social sign on after creating an account use the "email" option, they can, but must use the same email address.

- re: the quote above - if a user does use a different email address than the one they have already signed up with, they will simply be creating a new profile (so it's not that the email address must be the same, it's the email address address must be the same if they want to merge their existing profile)

- if a user signs up using a social identity provider (Google, Github, etc...), they will not be able to sign-up / log-in later with that email address using the form (I'm not sure how relevant it is to include this in the documentation, but I figured I'd mention it just in case)
