### ISSUE TITLE
Data is not inserting in InfluxDB 2.0 through python client influxdb_client

### ISSUE THREAD

**Issue by ssaurav-1987** [influxdata/docs-v2#1011]
_Describe the issue here._
I have written python script in that I am collecting data from spreadsheet and making list of json data that will be json object that have list of json data. I have configured bucket, organisation, token. And tried to insert DB but it is not inserting into DB and even I am not getting error into that
Please find below my code and kindly help me where I am missing:

#!/opt/anaconda3/bin/python3
from influxdb_client import InfluxDBClient
from influxdb_client.client.write_api import ASYNCHRONOUS
import random
import json
from datetime import datetime
import pandas as pd
import logging

logging.basicConfig(filename='/InfluxDB/test.log', format='%(filename)s: %(message)s',level=logging.DEBUG)
excel_data_df = pd.read_excel('/RouterSwitchData.xlsx')
json_data = json.loads(excel_data_df.to_json(orient='records'))
series=[]
counter=0
json_body={}
for item in json_data:
    current_traffic_signal = random.uniform(1.00,8.00)
    json_body = {
         "measurement": "devicelink",
        "tags": {
            "devicename": item["DeviceName"],
            "device_circle": item["Circle"],
            "device_subcircle":item["SubCircle"],
        },
        "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f"),
        "fields": {
            "device_name": item["DeviceName"],
            "device_ip_address":item["IP_Address_Device"],
            "device_port":item["port"],
            "device_circle":item["Circle"],
            "device_subcircle":item["SubCircle"],
            "neighbour_device_name":item["Neighbour_Device"],
            "neighbour_device_ip_address":item["IP_Address_Neighbour_Dev"],
            "neighbour_device_port": item["Neighbour_dev_port"],
            "neighbour_device_circle":item["Neighbour_Circle"],
            "neighbour_device_subcircle":item["Neighbour_subcircle"],
            "device_link_capacity":item["capacity_of_link(gig/sec)"],
            "device_threshold%":item["Threshold(%)"],
            "current_taffic_signal":(current_traffic_signal),
            "current_traffic_rate %":((current_traffic_signal/int(item['capacity_of_link(gig/sec)']))*100)

        }
    }
    series.append(json_body)
    #jsondata= json.dumps(series)
    counter=counter+1
    print("Total record : ",counter)  

URL="http://localhost:9999"
TOKEN=$TOKEN
ORG="analytics"
BUCKET="DeviceAnalysis"
client = InfluxDBClient(url=URL, token=TOKEN, org=ORG)
write_api = client.write_api(write_options=ASYNCHRONOUS)
datasave = write_api.write(BUCKET, ORG, series)   #Writing to InfluxDB
print("DB Written : ",datasave)

##### Relevant URLs
- _Provide relevant URLs_

##### What products and version are you using?
Using InfluxDB 2.0

**Comment by sanderson** [comment]
@ssaurav-1987 This issue may be better served if submitted to the client repo itself. I'd transfer the issue to that repository, but I don't have the necessary permissions. Could you recreate this issue on the [influxdb-client-python repsoitory](https://github.com/influxdata/influxdb-client-python)?

I'm going to close this issue here for now.
