### ISSUE TITLE
Add an example to delete-predicate that shows a full call with time range

### ISSUE THREAD

**Issue by nisley** [influxdata/docs-v2#1021]
I initially landed on this page looking to delete a set of data over a time range:
https://v2.docs.influxdata.com/v2.0/reference/syntax/delete-predicate/

After reading that doc I was left with the impression I could not use delete with predicate over a time range.  An example with a time range would help.

**Comment by sanderson** [comment]
@nisley This doc is for the delete predicate syntax, which does not support deletions based on `_time` values (as noted [here](https://v2.docs.influxdata.com/v2.0/reference/syntax/delete-predicate/#limitations). The time range to delete data from is specified in the delete API call, not the predicate syntax (unless this has changed).

https://v2.docs.influxdata.com/v2.0/reference/cli/influx/delete/

There are examples in a pending PR that covers deleting data, but as I understand it, this feature isn't fully released, so this PR hasn't been merged: https://github.com/influxdata/docs-v2/pull/621/files

**Comment by sanderson** [comment]
Closing this issue for now. Examples that show data deletion by time range will roll out when delete functionality is fully supported.
