### ISSUE TITLE
Image is corrupted

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1024]
_Describe the issue here._
https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/manual-config/
![image](https://user-images.githubusercontent.com/23535264/81506991-e9a39c80-92ae-11ea-8c9b-e890e0be9787.png)

Confirmed on multiple devices/browsers:
Chrome and Edge on Windows 10 and Safari on mobile

**Comment by noramullen1** [comment]
Still broken! trying a couple other things
