### ISSUE TITLE
Update/reorg secrets topics 

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#1027]
Update (or reorganize?) secrets topics to eliminate duplicate "Use secrets in a query" procedure. Questions to consider:

- Does it make sense to split the "Store and use secrets page (/v2.0/security/secrets/) into two separate procedures?  
- What about adding links for "storing" and "using" secrets on the Manage secrets page on the same level as Add, View, Update, Delete?
- What's the difference between adding a secret and storing a secret? Do you add a secret to secret store? 
- Can you manage Vault secrets via the CLI?

**Comment by russorat** [comment]
@kelseiv we are close to adding secrets management in the UI. can we add those docs here?

**Comment by kelseiv** [comment]
Thank you, @russorat ...curious how close? ...to help @pierwill prioritize in queue as needed :-)
