### ISSUE TITLE
Document that tokens are only visible to the user that created them

### ISSUE THREAD

**Issue by nisley** [influxdata/docs-v2#1028]
Related to this issue - https://app.zenhub.com/workspaces/applicationecommerce-5cf5c37ac6deac1e99bc6284/issues/influxdata/quartz/2630

Beyond just highlighting the fact that users will only see their tokens, we should document a best practice of creating a generic IT user for creating non-user specific tokens for writing data in.  These tokens will continue functioning if/when individual users leave the Account/Company.

**Comment by sanderson** [comment]
Related issue: https://github.com/influxdata/influxdb/issues/18155
