### ISSUE TITLE
review: menu vs. content

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1053]
_Describe the issue here._
I think we need to revisit the menu structure of the Write Data section and how this compares/contrasts with the content within the actual page.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/write-data/

<img width="560" alt="Screen Shot 2020-05-20 at 10 18 47 AM" src="https://user-images.githubusercontent.com/23535264/82476727-56731f80-9a83-11ea-9766-1bafaabe54d7.png">

<img width="368" alt="Screen Shot 2020-05-20 at 10 17 33 AM" src="https://user-images.githubusercontent.com/23535264/82476733-583ce300-9a83-11ea-99af-9316124ac9c2.png">

Seems like these are not well aligned.  If I just looked at the menu, I would think that Telegraf and Scrapers are the only ways to get data in?

**Comment by kelseiv** [comment]
100%. Sharing related thoughts I had when adding 3rd party:
- Drop "Other ways to write data" at bottom and list things up top
- "Sample data" and "best practices for writing data" don't fit under "Other ways to write data"
- Remove "What you'll need" section (some conceptual content mixed in as procedural) 
- Write data: 
   - Quick start
   - UI (scrapers, Telegraf)
   - CLI
   - API
   - 3rd party
   - Client libraries

**Comment by timhallinflux** [comment]
There is some confusion re: Telegraf....like what is it.  Stating it's a data collection agent....which you need to deploy might help!

So my breakdown would be:

Write Data:
- Agent-based with Telegraf
- Scrapers
- CLI
- API
- 3rd Party
- Client libraries

**Comment by sanderson** [comment]
Add "CSV" somewhere to the list: https://github.com/influxdata/docs-v2/pull/1050
