### ISSUE TITLE
Add note to add missing third-party integrations

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#1063]
_Describe the issue here._
A lot of new third-party integrations for Cloud 2 will be built by the community.  Add a note to open an issue to add a new integration that may be missing from the existing page. 

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/write-data/#third-party-technologies

**Comment by noramullen1** [comment]
@sjwang90 Any specifics on this available now? Just added the logs sink one.

**Comment by sjwang90** [comment]
More of something can we add a note to open a docs issue if there's a third-party integration out there that we don't know about since they'll be built by community members
