### ISSUE TITLE
More details for our Cloud 2 locations

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1077]
We have customers who want to know where our Cloud 2 on Azure instance is. Currently it states "West Europe". 

![image](https://user-images.githubusercontent.com/20701/83312086-14a25180-a1c6-11ea-8d94-12381f833cb0.png)

But that's not helpful for determining compliance requirements. For instance, Germany is in western Europe, but has data privacy laws that go beyond EU regulations:

https://www.complianceweek.com/data-privacy/germanys-dual-approach-to-data-regulation-under-the-gdpr/28386.article

--

Other issues:

#2

Admittedly nitpicky, but we say "Frankfurt" and not "Frankfurt, Germany". I deal with enough customer emails to not be surprised if someone might scan this and think it's Frankfurt Kentucky/Alabama/Illinois/Indiana/Kansas/Maine/etc.

![image](https://user-images.githubusercontent.com/20701/83311927-99d93680-a1c5-11ea-89f2-b971f6529e7e.png)

#3 

We don't explicitly name which regions we're in. We state "US West", not "US West 2" for instance. At volume, I worry about someone saying that our doc only said "US West", and claim they purchased thinking we were in Northern California (AWS US West 1 region). 

Yes, these would be silly objections, but it'd burn up cycles needlessly defending against. It the history of business disputes, there have been sillier claims made.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/reference/urls/

##### Proposed solution

Be explicit about where we are running. In the **Region** column, state the exact region that each of the cloud providers use the following, respectively:

us-west-1
eu-central-1
us-central1
westeurope-1

Create a new column, **Location**, with the city (if well-known), state (if well-known) and country. So use the following, respectively:

Oregon, USA
Frankfurt, Germany
Iowa, USA
Amsterdam, Netherlands

**Comment by noramullen1** [comment]
Hi @alsargent , thanks for this issue.

We can definitely include the country for Frankfurt and add the city/country for the Azure data center. 

But not sure what you're asking for re. # 3 above:

> We don't explicitly name which regions we're in. We state "US West", not "US West 2" for instance. At volume, I worry about someone saying that our doc only said "US West", and claim they purchased thinking we were in Northern California (AWS US West 1 region).

The screenshot you took very clearly says Oregon? I'm not sure if you're referring to a different place in the docs or you somehow didn't see that. Can you clarify?
