### ISSUE TITLE
Getting started guide -- Client Library

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1093]
Our getting started guide feels very focused on the browser-based tools that we've provided.

There are other onramps to the platform and we want to start highlighting.

One very specific guide that we should create focused on what a developer needs to do to get started using a client library along with the VS code editor and Flux plugin.  We should pull through a specific example -- perhaps by looking at the examples which we provide in-app and/or exist within the associated github repos for the client libraries themselves.

The Python library has some content already within our doc set (as opposed to exiting to github... I'd like to see us expand both this one and the other client libraries.... in this direction as well).

**Comment by noramullen1** [comment]
@pierwill I'm going through our docs issues and thought this one looked good for you because you've done CL stuff in the past :)

**Comment by jstirnaman** [comment]
Closing this b/c we now have more complete guides for "VS code editor and Flux plugin" and Python client library and a plan to build out more CL docs.
