### ISSUE TITLE
Broken link for HTTP guide config

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#1106]
_Describe the issue here._
Citibike HTTP/JSON link is broken 

##### Relevant URLs
- _Provide relevant URLs_
https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/use-telegraf-plugins/use-http-plugin/

Configuration file needs to be updated as well.  

Station status information HTTP plugin config: 
```
[[inputs.http]]
  interval = "1m"
  urls = [
    "https://gbfs.citibikenyc.com/gbfs/en/station_status.json"
  ]
  name_override = "citibike_gbfs"
  tagexclude = ["url"]
  method = "GET"
  timeout = "5s"
  data_format = "json"
  json_query = "data.stations"
  tag_keys = [
    "station_id"
  ]
  json_string_fields = []
  json_name_key = ""
  json_time_key = "last_reported"
  json_time_format = "unix"
```

**Comment by noramullen1** [comment]
This is now fixed on their end!

**Comment by PrplHaz4** [comment]
The documentation still seems to reference the old feed (`https://feeds.citibikenyc.com/stations/stations.json`), which does not seem to exist anymore.

**Comment by noramullen1** [comment]
Thanks @PrplHaz4 , this is now updated.
