### ISSUE TITLE
Expand Client Libraries information

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#1109]
_Describe the issue here._
Feedback from "why do users go inactive" user research is for better client library support in v2 docs.  Right now all documentation is linked to the client library's GitHub page.  Include more getting started information (can be taken from CL GitHub readmes) for client libraries in the docs. 

An "how to install" for each client library would be good to include on the docs page that is similar to the [Python v1 docs](https://docs.influxdata.com/influxdb/v1.8/tools/api_client_libraries/#install-and-use-the-python-client-library)

##### Relevant URLs
- _Provide relevant URLs_
https://v2.docs.influxdata.com/v2.0/reference/api/client-libraries/

Starting with python, javascript, C#, then moving down the list would be the priority. 
Top Client Libraries in Cloud2
![image](https://user-images.githubusercontent.com/32681364/84836555-cde89000-afea-11ea-92a8-a02592f67870.png)

**Comment by sjwang90** [comment]
Similar to #1093

**Comment by sanderson** [comment]
Thanks @sjwang90. We have this PR from @Anaisdg currently open which expands the Python, JS, and Go client library docs: https://github.com/influxdata/docs-v2/pull/945

I plan on re-reviewing this PR this week and it merge it.

**Comment by sjwang90** [comment]
Thanks @sanderson. 

For when this gets rolled out, another note of feedback was the hierarchy of the CL docs wasn't high enough - nothing about in the "Write Data" section. It may be useful to put a whole Influx v2 APIs portion under Write Data since seeing APIs is something a lot of developers are familiar with. 

![image](https://user-images.githubusercontent.com/32681364/84923936-c07be600-b07c-11ea-9bf4-ded14e28fdee.png)

**Comment by sjwang90** [comment]
Closing this as PR #945 addressed python, js, and go client libs. I'll #1093 open until more are merged.
