### ISSUE TITLE
Provide curl and Postman examples in our API documentation

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1110]
We provide a lot of information on our API on this page:

https://v2.docs.influxdata.com/v2.0/api/

... but no examples of what an actual curl command or Postman request would look like for each of these operations, similar to what we do on https://v2.docs.influxdata.com/v2.0/reference/api/#authentication:

![image](https://user-images.githubusercontent.com/20701/84928430-37b47880-b083-11ea-898a-cd4e1122ff35.png)

Please provide more curl  and Postman examples on 
https://v2.docs.influxdata.com/v2.0/api/. Thanks.

Reason I ask: I'm helping a user figure out how to send queries with Postman to InfluxDB Cloud 2, and there's nowhere I can point him. Thanks.

**Comment by alsargent** [comment]
For instance, here's a more detailed curl command that one of our users recently shared with us:

curl --location --request POST 'https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/query?org=xxxxxxxxxxxx' \
--header 'Authorization: Token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=' \
--header 'Accept: application/csv' \
--header 'Content-Type: application/vnd.flux' \
--data-raw 'from(bucket: "xxxxxxxxxxxxxx")
  |> range(start:-30d)
  |> filter(fn: (r) => r["_measurement"] == "weather")'

... it'd be great if our documentation had more detailed examples like this.

**Comment by timhallinflux** [comment]
Using Postman with our APIs is certainly something we should provide examples around.  Using curl is the lowest level tooling, but there are so many API developers who use Postman for debugging and more, we should review the basics in terms of the header setup and ensure that this is documented so we don't have people repeating the "hours" worth of self-discovery.

**Comment by kelseiv** [comment]
@pierwill verified this has been incorporated into the docs
