### ISSUE TITLE
Dynamic Cross-Linking

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#1115]
_Describe the issue here._
Currently: Links in the app were added before the Cloud/OSS split in the documentation with the customized URL to different instances.  
Request: Cloud/OSS link dynamically depending if you're looking at Cloud or OSS documentation

@mnorriswalker feel free to add more context based off user research

**Comment by noramullen1** [comment]
@mnorriswalker, @sjwang90,

Thanks for reaching out. When you say the "Cloud/OSS split", are you referring to the option in this window? 

![image](https://user-images.githubusercontent.com/42354779/84956238-9b539b80-b0ad-11ea-9ecd-c19dccf4127e.png)

That option affects what URLs appear in the code blocks in the body of the articles, but not the URLs of any of the documentation. So the links are the same whether you've selected OSS or any of the Cloud options. 

Let me know if I've misunderstood!

**Comment by mnorriswalker** [comment]
Hi Nora,

The point from research is that we know the user's Cloud provider in the app, so when we link to documentation like "How to Manually Configure Telegraf" we could automatically apply the settings from "Where are you running InfluxDB?"?

_Another way of saying this..._

Given: I am user with a Cloud instance on AWS US West (Oregon)
When: I click on a Docs link in the UI
Then: The code blocks in the Documentation are configured to say `https://us-west-2-1.aws.cloud2.influxdata.com` automatically

This is especially important for the Writing Data Section of the Docs site and any forthcoming content around Client Libraries as we want to reduce ALL friction we possibly can to get new Cloud users to write data.

**Comment by noramullen1** [comment]
@sanderson Is there an attribute we can set when linking from the UI to the docs to set the URL option based on the URL the user's working from?

**Comment by sanderson** [comment]
Possibly. There are a couple of things we can do. I'll do a little research.
