### ISSUE TITLE
Add warning to both `group` and `sort` sections that `group()` causes data to return out of order

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#1129]
## Describe the issue here ##

When applying a `group()` function to a query, the data is no longer guaranteed to arrive in order.  This causes a wonkiness in line graphs that look like the below examples.  It requires the use of `sort(columns: ["_time"])` in the query to avoid this issue in visualization.  In the `group()` docs, I feel it would suffice to warn the user of this behavior and show the function application needed to avoid the problem as well as a link to the `sort()` function docs.  In the `sort()` docs, perhaps it would be good to include that this is often used in tandem with `group()` as grouping has behavior that often necessitates it:
<img width="522" alt="Screen Shot 2020-06-16 at 9 29 54 AM" src="https://user-images.githubusercontent.com/4852912/85327167-5780dd80-b483-11ea-924b-27e6bdc081cc.png">

Or:

![Screen Shot 2020-06-22 at 11 10 21 AM](https://user-images.githubusercontent.com/4852912/85327194-61a2dc00-b483-11ea-894d-2c3b51146e2e.png)

### Relevant URLs
https://v2.docs.influxdata.com/v2.0/query-data/flux/group-data/
https://v2.docs.influxdata.com/v2.0/query-data/flux/sort-limit/

### Impact

I believe our users will hit this issue rather often as it's not a common behavior among dashboarding tools.  Some may figure out how to solve it but I think it's important explicitly call out this behavior so it doesn't surprise anyone.

**Comment by samhld** [comment]
this may actually be a UI bug that will be fixed in: https://github.com/influxdata/influxdb/issues/18642

TBD

**Comment by sanderson** [comment]
Thanks @samhld. This is a known issue with `group()` and I'll add a warning. `group()` currently does not guarantee the sort order of its output.
