### ISSUE TITLE
Add gzip to best practices for writes

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1134]
In https://v2.docs.influxdata.com/v2.0/write-data/best-practices/optimize-writes/, we describe best practicers for writes.

One best practice, not included, is to turn on compression using `content_encoding = "gzip"` in a Telegraf config file. You can see this in context in this sample config file:

https://github.com/alsargent/telegraf-cloudwatch/blob/master/cloudwatch.telegraf.conf

In our benchmarking, we've found this to speed up ingest by about 5x.

##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/write-data/best-practices/optimize-writes/

**Comment by sanderson** [comment]
Thanks @alsargent. To add to this, we should mention enabling gzip compression the the following contexts:

- In Telegraf
- Raw API write requests
- Client libraries

@alsargent Thanks for the performance benchmark. Were there any benchmarks on system load with gzip enabled? It does make writes faster, but the compression/decompression does add load to the system, I just don't know how much.
