### ISSUE TITLE
Cloud2 "what is telegraf frame has broken link"

### ISSUE THREAD

**Issue by gomazu** [influxdata/docs-v2#1138]
_Describe the issue here._
404 error from embedded link in cloud2 interface.   https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/

##### Relevant URLs
- _Provide relevant URLs_
https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/

##### What products and version are you using?
Cloud2

**Comment by gomazu** [comment]
![Screen Shot 2020-06-23 at 2 52 30 PM](https://user-images.githubusercontent.com/63891737/85468399-427a7c00-b561-11ea-9244-ad37f54fbb0e.png)

**Comment by noramullen1** [comment]
Hi @gomazu , thanks for letting us know. The link above has been updated to redirect to the new documentation location.

Nora
