### ISSUE TITLE
Document Microsoft SQL Server support in sql.from

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1139]
Microsoft SQL Server support has been merged in:

https://github.com/influxdata/flux/pull/2847

... but is not yet in our documentation:

https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/sql/from/

Customers are asking about this, so it'd be good to have in the doc. Thanks!

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/sql/from/

**Comment by sanderson** [comment]
SQL Server support has been merged, but it has not been released. It will be part of the next Flux release (likely 0.70). Once that release is cut, the [docs for SQL Server](https://github.com/influxdata/docs-v2/pull/1048) will go live.
