### ISSUE TITLE
Missing "Data columns" info

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs-v2#1146]
https://v2.docs.influxdata.com/v2.0/reference/key-concepts/data-schema/

This page is missing an entry for "Data columns."

**Comment by sanderson** [comment]
It doesn't need a "Data columns" section. It has a section called "Data rows" and whatever is linking to `#data-columns` should be linking to `#data-rows`.

**Comment by kelseiv** [comment]
fix link by changing "Data columns" to "Other columns"
