### ISSUE TITLE
Add new Extended CSV processing options

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#1164]
PR: https://github.com/influxdata/influxdb/pull/18779

##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/reference/syntax/annotated-csv/extended/
- https://v2.docs.influxdata.com/v2.0/reference/cli/influx/write/

**Comment by kelseiv** [comment]
[Duplicate](https://github.com/influxdata/docs-v2/issues/1444) actively being worked
