### ISSUE TITLE
Update pricing

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#1171]
Post updated pricing docs before release on September 1st. 
- Users will no longer be charged for query duration. 
- Users will be charged for the following:
   - Total number of query requests (including tasks)
   - Total amount of data transferred out
- Request from Tim:
   - Contact Balaji for pricing deck walkthrough
   - Work with marketing to ensure language aligns. 

Notes:
- CSV Download does not affect charges. (Initial query brings the data to the browser. The CSV Download button simply packages up the data resident in the browser with no additional Flux query invocation.) Only charge for the initial query (API call - 1 count) and the data transfer cost.
- Writing Data Back into Influx does not affect charges. Only charge for initial query (API call - 1 count). No data transfer cost bc data is not transferred (moved through an internal gateway call).

##### Relevant URLs
We could add details on this page (we currently don't tell them how they're charged).
https://v2.docs.influxdata.com/v2.0/account-management/pricing-plans/

**Comment by timhallinflux** [comment]
@gunnaraasen can you review the timeline and content with @noramullen1 ?
