### ISSUE TITLE
Documentation on integrating with Raspberry Pi

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1201]
We don't have any documentation pages talking about how to integrate InfluxDB with Raspberry Pi. This is surprising, given how many of our users are working with IoT, and the popularity of Raspberry Pi within IoT.

Request: explain how to work with Raspberry Pi, Telegraf, and InfluxDB. Is the MQTT plugin the best way to go? 

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/

**Comment by timhallinflux** [comment]
There is no use case here... 

what problem are you trying to solve?

Example:
do you mean: how does one monitor the system resources of a Raspberry Pi (similar to say monitoring a Linux or Windows server)?
or do you mean something else?  Because the "something else" needs more definition.

**Comment by alsargent** [comment]
Sure, the use case is this: A user searches "influxdb raspberry pi"...

https://www.google.com/search?q=influxdb+raspberry+pi

... and we (InfluxData) only provide one result in the top 10, on how to install InfluxDB on Raspberry Pi (https://www.influxdata.com/blog/running-the-tick-stack-on-a-raspberry-pi/). It'd be ideal if we described the full range of options for interacting with Raspberry Pi. Those could include the following use cases:

- How to pull time-series data off Raspberry Pi (probably points to our MQTT doc)
- How to install InfluxDB on Raspberry Pi (point to blog post above)
- How to monitor Raspberry Pi itself using Telegraf and plugins like mem

Does that answer your question?

**Comment by timhallinflux** [comment]
Do we have any other documentation which does this?  I'm not saying that we shouldn't create this.  But, if what you are after is having more explicit cookbooks by technology.... I'm not sure that starting with RaspPi is where I would begin.

The pattern is largely the same... independent of the tech.

**Comment by kelseiv** [comment]
Thank you, @alsargent, @timhallinflux. 

Going to add keys to community templates in frontmatter, so if folks search for Raspberry Pi in the docs, they'll get a hit.

**Comment by kelseiv** [comment]
Two next steps:

- [ ] @mluu12 working to add Raspberry pi monitor template to docs
- [ ] @pierwill working on install instructions and how to use/use cases above and examples

**Comment by pierwill** [comment]
See https://github.com/influxdata/docs-v2/pull/2879 for work on installation instructions.
