### ISSUE TITLE
Document how to create tokens in InfluxDB Cloud 2

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1220]
A customer is asking me how to create tokens in InfluxDB Cloud 2. I'm pointing him to:

https://v2.docs.influxdata.com/v2.0/security/tokens/

... but that only talks about how to create tokens in the CLI, not the Cloud 2 web UI. So, I need to write up a quick guide in my email response.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/security/tokens/

##### What products and version are you using?

Cloud 2

**Comment by pierwill** [comment]
Thanks, @alsargent. The docs linked to from https://v2.docs.influxdata.com/v2.0/security/tokens/ under "Create a token" do cover both the OSS UI and Cloud UI. The steps are the same in both UIs,

**Comment by sanderson** [comment]
This content exists: https://v2.docs.influxdata.com/v2.0/security/tokens/create-token/#create-a-token-in-the-influxdb-ui
