### ISSUE TITLE
Add write via CLI as an option to the no-code write page

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#1264]
https://v2.docs.influxdata.com/v2.0/write-data/no-code/

the influx write command in the CLI should be a "no-code" option on this page.

**Comment by noramullen1** [comment]
Hi @russorat, we have that in the Developer Tools section: https://v2.docs.influxdata.com/v2.0/write-data/developer-tools/. We decided it fit best next to client libraries and API. Closing this for now, but let me know if you feel strongly about recategorizing it and we'll discuss as a team.

**Comment by russorat** [comment]
IMO, `Influx CLI` can stay in the developer tools section, but "Write CSV data" should go in the No-code solutions" section.
