### ISSUE TITLE
Update documentation to make it clear how to connect to InfluxDB Cloud via the CLI

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#1277]
Links shared with user:
https://v2.docs.influxdata.com/v2.0/write-data/developer-tools/influx-cli/
https://v2.docs.influxdata.com/v2.0/reference/cli/influx/config/

Feedback from user:
from this it is still not immediately clear how to setup the cli to connect to cloud v2. it would be nice to have it in the getting started area. it only has a short bit about how to use the cli, but not how to set it up. i initially went to cli setup and did not see anything pointing me towards config

I found this section confusing: https://v2.docs.influxdata.com/v2.0/get-started/#use-the-influx-cli

although it is mentioned there, its not in the influx cli setup and the majority of the content is about tokens and the create command is thrown in there as opposed to being something a bit more explicit

**Comment by kelseiv** [comment]
Thank you, @russorat!

Clarified how to set up the `influx` CLI to connect to Cloud. Also updated confusing content in this section:  https://v2.docs.influxdata.com/v2.0/get-started/#use-the-influx-cli
