### ISSUE TITLE
Docs need to explain how to get a dashboard ID

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1278]
Our v2 docs don't explain how to get the ID of a dashboard, AFAICT.

**Relevant URLs**
https://v2.docs.influxdata.com

**Context**
I'm writing a blog post that requires the user to look up the dashboard ID of one of their  InfluxDB Cloud 2 dashboards, and I can't find any doc that describes how to do this. Tried both a google search and our doc search.

**Comment by noramullen1** [comment]
@alsargent is there any time they'd need to do this other than for your blog? i.e. what is the use case?
