### ISSUE TITLE
Documentation on how to write MQTT data into InfluxDB

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1282]
I'm seeing user questions on how to write MQTT data into InfluxDB. Our [Telegraf MQTT input plugin page](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mqtt_consumer) doesn't have a lot of detail. Also we don't have a dedicated topic on https://v2.docs.influxdata.com/. There are [third party articles](https://www.google.com/search?q=mqtt+influxdb), but some of these are older and refer to InfluxDB v1. 

More broadly, we're seeing lots of interest from users with IoT use cases, and MQTT is often a way that they're looking to send us data.

My request: please provide more details on writing MQTT data into InfluxDB. Thanks.

**Comment by jstirnaman** [comment]
Comment from `docs-feedback`:

[Doc the Docs Bot](https://app.slack.com/team/BG2D62K6H)
APP  [2:40 PM](https://influxdata.slack.com/archives/C03HRU09PHA/p1658691601996589)
New user feedback!
Page: https://docs.influxdata.com/resources/videos/using-mqtt-and-influxdb-for-iot/
Feedback: It would be really helpful if you showed the actually MQTT topics and message and how they are mapped by Telegraf into bucket, measurement, etc
