### ISSUE TITLE
Variable names must begin with a letter or underscore

### ISSUE THREAD

**Issue by AlirieGray** [influxdata/docs-v2#1300]
Small change to Variable name validation, documentation may be helpful. Users will see a clear error if they try to make an invalid Variable. 

##### Relevant URLs
https://github.com/influxdata/influxdb/pull/19317

**Comment by pierwill** [comment]
@AlirieGray, is this the pages that needs updating, then? https://v2.docs.influxdata.com/v2.0/visualize-data/variables/create-variable/

**Comment by pierwill** [comment]
Does this change need to be documented in the InfluxDB docs, Flux docs, or both?

**Comment by AlirieGray** [comment]
I think just InfluxDB.
