### ISSUE TITLE
Wrong description for Update Telegrafs

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#1335]
https://v2.docs.influxdata.com/v2.0/reference/cli/influx/telegrafs/#subcommands

the `update` command says `List Telegraf configurations`, but it should say `Update Telegraf configuration`

**Comment by pierwill** [comment]
`Update Telegraf configuration`, or `configurations` (plural)?

**Comment by russorat** [comment]
based on the other descriptions on that page, `Update a Telegraf configuration` seems better
