### ISSUE TITLE
Clarify connecting Grafana to InfluxDB with InfluxQL connector

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1340]
Our [docs page describing how to connect Grafana to InfluxDB using the InfluxQL connector](https://docs.influxdata.com/influxdb/v2.0/tools/grafana/#configure-grafana-to-use-influxql) has a couple of things that could make it more clear to users:

#1 

![image](https://user-images.githubusercontent.com/20701/90667917-18150a00-e204-11ea-8eac-5be515b43bed.png)

Today the page states, _The database to use when querying InfluxDB 2.0_. This is confusing, because InfluxDB 2.0 doesn't have a concept of multiple databases, only multiple buckets. To add to the confusion, the user is pointed to the [Database and retention policy mapping page](https://v2.docs.influxdata.com/v2.0/reference/api/influxdb-1x/dbrp/), which talks about a lot of things unrelated to connecting to Grafana.

Instead, please simply tell the user to list the InfluxDB 2.0 bucket in the database field.

After doing so, it's fine to point the user to the [Database and retention policy mapping page](https://v2.docs.influxdata.com/v2.0/reference/api/influxdb-1x/dbrp/) if they want to go further.

#2 

Having tabs like this one for Flux and InfluxQL on our pages:

![image](https://user-images.githubusercontent.com/20701/90668385-e05a9200-e204-11ea-81e2-e538157abfbd.png)

... presents challenges for communicating with our customers, because we can't just point them to a URL to answer a question. We have to both provide a URL AND state what tab to click on. If we don't tell customers to click on a tab, they can scroll right past the information they need. This is awkward for blog posts, customer decks, social media, webinars, and more.

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/tools/grafana/#configure-grafana-to-use-influxql/

##### What products and version are you using?

InfluxDB Cloud 2.0
Grafana 7.1
InfluxQL Connector

**Comment by sanderson** [comment]
@alsargent Once #2210 merges, you'll be able to add a query parameter to URLs to trigger tabs. In this first pass, you have to manually add the param, but I'm going to come back and make it add/update the param whenever you click a tab. So for example, if you want the OSS 2.0 "Get started" page to open with the Linux install instructions, the following link will do it (once the PR merges):

https://docs.influxdata.com/influxdb/v2.0/get-started/?t=Linux

You'll also be able to scroll to anchors in non-default tabs:

https://docs.influxdata.com/influxdb/v2.0/get-started/?t=Linux#place-the-executables-in-your-path
