### ISSUE TITLE
Fix the example for duration

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#1368]
https://docs.influxdata.com/flux/v0.65/stdlib/built-in/transformations/type-conversions/duration/#examples

The example here attempts to set a duration as a column value, which won't work.

```
from(bucket: "sensor-data")
  |> range(start: -1m)
  |> filter(fn:(r) => r._measurement == "system" )
  |> map(fn:(r) => ({ r with uptime: duration(v: r.uptime) }))
```

**Comment by sanderson** [comment]
This is already fixed in the most recent Flux docs. The Flux v0.65 docs are going away and will redirect to the appropriate InfluxDB v2.0 page.

**Comment by kelseiv** [comment]
Thank you, @russorat, @sanderson! Rolled example into 1.x for good measure.
