### ISSUE TITLE
Cloud sign-up links in cloud docs

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#1373]
We should put a sign up link/button/call-to-action in cloud-specific docs.

##### Relevant URLs
- /influxdb/v2.0/account-management/*

**Comment by kelseiv** [comment]
@sanderson does this [doc](https://docs.influxdata.com/influxdb/cloud/sign-up/) address? If yes, close this issue?  If no, any thoughts/suggestions?

**Comment by sanderson** [comment]
No, the thought here is to add a persistent link in the header that goes to cloud. This would only be in the Cloud docs.

**Comment by kelseiv** [comment]
Thank you, @sanderson, gotcha, so all Cloud docs links back to https://cloud2.influxdata.com/signup

To be sure, should the relevant URL be influxdb/cloud/* now?

**Comment by sanderson** [comment]
Yeah, the relevant URLs would be `influxdb/cloud/*`.
