### ISSUE TITLE
Supports multiple languages

### ISSUE THREAD

**Issue by oiooj** [influxdata/docs-v2#1403]
[Hugo supports the creation of websites with multiple languages side by side.](https://gohugo.io/content-management/multilingual/#readout)

We also need supports multiple languages.

add i18n dir:

```
|-- i18n
|   |-- en.toml
|   `-- zh.toml
```

config file:

```
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    weight = 2
  [languages.zh]
    languageName = "中文"
    weight = 1
```

content:

```
|-- account-management
|-- backup-restore
|-- example.md
|-- get-started.md
|-- get-started.zh.md
```

**Comment by sanderson** [comment]
@oiooj We are in the process of building out multilingual support for the documentation. Closing this issue for now.

**Comment by oiooj** [comment]
Could you share any proposal or issue link to the public ? @sanderson

**Comment by sanderson** [comment]
@oiooj We are using Hugo's multilingual functionality and are working with partners in regions around the world to provide translations. We don't have a specific timeframe for supporting new languages, but it is in the works.
