### ISSUE TITLE
Update Query InfluxDB API docs

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#1411]
- Update Query InfluxDB swagger docs (https://docs.influxdata.com/influxdb/v2.0/api/#operation/PostQuery) to include the response format. 
- Refer to response format here for more detail: https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/

**Comment by sanderson** [comment]
This is going to take engineers to do. The API docs are generated from the swagger in the InfluxDB repo. I'm VERY hesitant to start diverging from the swagger that's there.

**Comment by kelseiv** [comment]
Closing this issue and moved it to [influxdb repo](https://github.com/influxdata/influxdb/issues/19528).

@influxdata/docs-team, for API doc issues, we can add issue to[ influxdb repo](https://github.com/influxdata/influxdb/issues), add label for `team/compute` and `area/api-docs` and cc @stephanie-engel and @rhajek
