### ISSUE TITLE
Chronograf Settings -- clarify command-line and env-vars (multiple entries)

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1414]
Community user is confused about how to send all of the etcd endpoints to Chronograf.  The documentation shows an example of sending 1 -- but I believe the default setup for etcd is to provide 3 so that if one fails, the others can be contacted.

https://community.influxdata.com/t/chronograf-high-availability/15895

We should modify the setup to show how to provide multiple etcd endpoints via both the command line input string and via environment variables.

The confusing part is that the syntax is different depending on which mechanism you use.  
Apparently for ALL command line flags/environment variables which are plural such as:
`etcd-endpoints`, 
`google-domains`, 
`generic-scopes`, 
`generic-domains`, 
`auth0-organizations`
and two that aren't:
`github-organization`,
`heroku-organization`
the following applies. 

For the command line, you can use the input flag multiple times:
```
chronograf --etcd-endpoints=localhost:2379 --etcd-endpoints=192.168.1.61:2379 --etcd-endpoints 192.192.168.1.100:2379
```
But for the environment variables you provide a comma separated list:
```
ETCD_ENDPOINTS=localhost:2379,192.168.1.61:2379,192.192.168.1.100:2379
```

##### Relevant URLs
https://docs.influxdata.com/chronograf/v1.8/administration/create-high-availability/#start-chronograf
These tables should also be revised based on the appropriate guidance:
https://docs.influxdata.com/chronograf/v1.8/tools/chronograf-cli/#authentication-option-flags

The guidance in the table options are inconsistent.  For example:
OAuth has: 
`
Auth0 organization membership required to access Chronograf. Organizations are set using an organization key in the user’s app_metadata. Lists are comma-separated and are only available when using environment variables.
`

Github has no mention of multiple orgs:
`Specify a GitHub organization membership required for a user. Optional.`

Heroku has:
`Heroku organization membership required to access Chronograf. Lists are comma-separated.`

##### What products and version are you using?
Chronograf 1.8+

I reviewed this with @glinton -- you can follow-up with him if you need more!

**Comment by timhallinflux** [comment]
now we have a customer support ticket about this same issue.  Please address this...

**Comment by noramullen1** [comment]
- [ ] Update example to show three `etcd` endpoints

- [ ] Make guidance in table options consistent
