### ISSUE TITLE
Chronograf service flag table -- cut off

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1416]
Table is cut off....please widen.

##### Relevant URLs
https://docs.influxdata.com/chronograf/v1.8/tools/chronograf-cli/

![image (15)](https://user-images.githubusercontent.com/23535264/92644126-b5111300-f297-11ea-8cae-135e519808cb.png)

**Comment by noramullen1** [comment]
Hi @timhallinflux, there's a scroll bar at the bottom of the table to see the final column. Not sure if there's much we can do about this table's width (four columns compared with three for the others on this page) -- @sanderson can you confirm?

**Comment by sanderson** [comment]
We'd have to look at restructuring this table if we don't want it to scroll, but all tables do scroll if they extend beyond the max column width.
