### ISSUE TITLE
Page does not exists in InfluxDB API Reference

### ISSUE THREAD

**Issue by Soumyank** [influxdata/docs-v2#1426]
I click on FLUX link in the API reference, the page does not exists. 

URL where I see the FLUX link - https://docs.influxdata.com/influxdb/v1.8/tools/api/#ping-http-endpoint
URL of the FLUX page that does not exists - https://docs.influxdata.com/flux/latest/

##### What products and version are you using? -- InfluxDB v1.8 Documentation

![image](https://user-images.githubusercontent.com/30456892/92736584-09032100-f398-11ea-8cb9-411b97e8e85e.png)
![image](https://user-images.githubusercontent.com/30456892/92736654-19b39700-f398-11ea-8c14-e32af9d0e4de.png)

**Comment by noramullen1** [comment]
Thanks @Soumyank , we've updated this.

**Comment by Soumyank** [comment]
Thanks nora
