### ISSUE TITLE
 tik-docker-tutorial.tar.gz link dead

### ISSUE THREAD

**Issue by fbonelle** [influxdata/docs-v2#1437]
Reading this: https://docs.influxdata.com/kapacitor/v1.5/introduction/install-docker/, it's not possible to download the example tar.gz. 

##### Relevant URLs
- https://docs.influxdata.com/downloads/tik-docker-tutorial.tar.gz - link dead

**Comment by timhallinflux** [comment]
looks like a migration issue -- as we just overhauled the docs.influxdata.com site.  Thanks @fbonelle for pointing this out.  We'll dig in and get it tidied up.

**Comment by sanderson** [comment]
Thanks for reporting @fbonelle. I've deployed a fix. Can you confirm?

**Comment by fbonelle** [comment]
Hello,

Thanks. It's OK now
