### ISSUE TITLE
Document new CSV capabilities

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#1444]
these new enhancements will most likely need docs updates. https://github.com/influxdata/influxdb/pull/18779

**Comment by pierwill** [comment]
The following pages need updating:

https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/extended/
https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/write/
https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/csv/

**Comment by pierwill** [comment]
#1520 has merged. Closing.
