### ISSUE TITLE
Revise hardware sizing chart

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs-v2#1445]
The memory-to-cardinality graphic on the hardware sizing page is not accurate. We should revise to use benchmarked numbers.

##### Relevant URLs

- https://docs.influxdata.com/img/influxdb/1-3-series-cardinality.png

##### What products and version are you using?

InfluxDB open source

**Comment by noramullen1** [comment]
Hi @gunnaraasen, where can we find the benchmarked numbers?

**Comment by kelseiv** [comment]
Thank you, @gunnaraasen, @noramullen1 

@noramullen1, to resolve this issue, let's delete the graphic the following line right above the graphic:
The increase in RAM needs relative to series cardinality is exponential where the exponent is between one and two.
