### ISSUE TITLE
Broken link in Flux documentation (InfluxDB 1.7)

### ISSUE THREAD

**Issue by PoloKltz** [influxdata/docs-v2#1450]
On the **Getting started with Flux** page, the link pointing to _options for writing and running Flux queries_ is broken

##### Relevant URLs
- Dead link: https://docs.influxdata.com/influxdb/v2.0/reference/flux/guides/executing-queries
- Page to update: https://docs.influxdata.com/influxdb/v1.7/flux/get-started/
##### What products and version are you using?
- InfluxDB v1.7

**Comment by pierwill** [comment]
@sanderson, does an equivalent page for this link still exist?

**Comment by sanderson** [comment]
This link should be updated to point here: `/influxdb/v1.7/flux/guides/execute-queries/`

**Comment by PoloKltz** [comment]
Thank you !!

**Comment by pierwill** [comment]
Thanks for the tip, @PoloKltz. 👍
