### ISSUE TITLE
Tools: Visual Studio Code Flux extension - Update instructions and usage

### ISSUE THREAD

**Issue by mdevy-influxdata** [influxdata/docs-v2#1466]
The VS Code Flux language extension could use some clarifications in the following areas:
- Configuration steps for use with InfluxDB 1.x and 2.0
- Instructions on how to "Run Query" (it's somewhat context menu)
- Upgrading the extension

###### URL for relevant page?
https://marketplace.visualstudio.com/items?itemName=influxdata.flux
https://github.com/influxdata/vsflux

###### What products and version are you using?
InfluxDB 1.x and Cloud 2.0
Visual Studio Code v1.45.1
Flux extension v0.5.5

**Comment by ElisaPiccin** [comment]
Hi @mdevy-influxdata I agree with your requests about the need on instructions and configuration steps. 
After some attempts, I've been able to connect and run some queries successfully: https://github.com/influxdata/docs-v2/issues/1781.
