### ISSUE TITLE
Add additional path for OSS to Enterprise migration

### ISSUE THREAD

**Issue by noramullen1** [influxdata/docs-v2#1470]
###### URL for relevant page?

https://docs.influxdata.com/enterprise_influxdb/v1.8/guides/migration/

@timhallinflux 's  notes:

Did some digging and the team does not typically use this approach.  Support ran into issues that were reported and fixed.  However they typically preach another method that is a best practice for large data sets and zero downtime.  We should have both documented as suggested approaches but for different scenarios.  The approach typically recommended by support involves:
1. Set up the cluster
2. Take a portable backup from OSS
3. Restore on the cluster
4. Dual write
5. Export the data from the time the backup was taken to when the dual write started
6. Import the data

This gives them 100% uptime with a fresh replicated cluster and the ability to do a full test and acceptance cycle

**Comment by kelseiv** [comment]
Closed with https://github.com/influxdata/docs-v2/pull/1305
