### ISSUE TITLE
telegraf Getting Started missing instructions 

### ISSUE THREAD

**Issue by nigelargriffiths** [influxdata/docs-v2#1473]
This will be very simple to fix up

Telegraf docs = getting started
This page
1) Assumes the output is going to influxDB
2) does not instruct users to run the influx command
3) does not instruct readers to first type: use telegraf (terrible and confusing name for the database)

###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.14/introduction/getting-started/

###### What products and version are you using?
telegraf/v1.14

###### Where did you look before opening the issue?
Page missing instructions

**Comment by pierwill** [comment]
Looks like these docs have been updated to take a more general approach to introducing Telegraf. Closing this.
