### ISSUE TITLE
mention that max-select-point only checks every 1 second

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#1498]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/troubleshooting/query_management/#max-select-point

According to this pr from a few years ago, this only checks every second: https://github.com/influxdata/influxdb/pull/8480/files

We should mention that in the docs.

**Comment by jstirnaman** [comment]
@kelseiv How far back should we add this? The commit first appears in tag sgc-pre-batch (d1cfc9f71991c448b1a0e8f61426d7c3fa5d1fb8)

**Comment by kelseiv** [comment]
> @kelseiv How far back should we add this? The commit first appears in tag [sgc-pre-batch ](https://github.com/influxdata/influxdb/commit/d1cfc9f71991c448b1a0e8f61426d7c3fa5d1fb8)

@jstirnaman, we typically maintain docs for the past two versions of 1.x, so fixing in 1.7 and 1.8 should be good. If it's easy, and you'd like, you can go back to 1.4. :-)
