### ISSUE TITLE
Docs: Generate Telegraf docs from in-tree plugin markdown files

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs-v2#1499]
## Overview

Turn some Telegraf project readmes into fulll pages on pages in docs.influxdata.com. Pull directly from GitHub readme so when readme is updated so does the docs page. 

All Markdown documents in the Telegraf repo are now fully linted and linted before every check-in. Every file was gone through and standardized on a set of header levels and patterns.

## Proposal

GitHub pages to include:

- All plugins
- https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md

## Use case

- A better experience for users via:
  - some may get distracted when they go from docs to GitHub, end up giving up
  - create a cohesive InfluxData experience
  - up to date docs
- Less maintenance burden on docs team
- Gain analytics to see who's viewing the plugin readmes, which ones are giving users more trouble

## Next Steps

* Docs team to investigate how this could be done
* Docs team to let Telegraf team know if Markdown files are meeting their standard or if templates need updates

**Comment by kelseiv** [comment]
related: https://github.com/influxdata/docs-v2/issues/3264

**Comment by sjwang90** [comment]
@popey Assigning this issue to you since you mentioned you could write the Hugo scripts
