### ISSUE TITLE
Document Telegraf setup for collecting metrics from AWS services

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs-v2#1500]
Some users find it hard to discover which AWS services can be monitored by Telegraf and how to configure that monitoring.

Metrics from AWS services can be collected via the [AWS CloudWatch plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cloudwatch) in most cases or by setting up a file plugin to ingest S3 logs in some other cases (ELB logs, DynamoDB). The final configuration is not obvious. I'd like to suggest that we add the following to the Telegraf docs.

- Separate configuration pages for AWS services that explain how to set up monitoring of those services, e.g. a Telegraf config and examples of AWS IAM permissions required and the metrics returned when monitoring different services.
- An overview page for AWS monitoring using Telegraf that lists all the AWS services that can be monitored by Telegraf.
- AWS service configuration pages should also be included in the [main plugin list](http://docs.influxdata.com/telegraf/v1.11/plugins/plugin-list/).

###### URL for relevant page?
I think we should use Datadog's AWS page as an example of which AWS services Telegraf can monitor. `https://www.datadoghq.com/aws-monitoring/`

###### What products and version are you using?
Telegraf

###### Where did you look before opening the issue?
(Telegraf plugin list)[http://docs.influxdata.com/telegraf/v1.11/plugins/plugin-list/]

We may also want to link to dashboards for each service when available.

**Comment by kelseiv** [comment]
check with @noramullen1 do devrels have blog up about this
