### ISSUE TITLE
Get started with Flux gif should show 'and' not 'AND'

### ISSUE THREAD

**Issue by mathispesch** [influxdata/docs-v2#1501]
###### URL for relevant page?

https://docs.influxdata.com/flux/v0.50/introduction/getting-started/

###### What products and version are you using?

InfluxDB 2.0.0-alpha.21

###### Where did you look before opening the issue?

Open issues on GitHub

---

The animation in the documentation shows `AND` as being a valid operator while this should be `and`. The correct operator is used for instance on https://docs.influxdata.com/flux/v0.50/introduction/getting-started/syntax-basics/.
Using capitalized operators triggers `expected an operator between two expressions`.

**Comment by kelseiv** [comment]
Thank you @mathispesch! This has been addressed.
