### ISSUE TITLE
Link goes to 404

### ISSUE THREAD

**Issue by dwgibbons** [influxdata/docs-v2#1503]
"Data Explorer" link at the end of the first paragraph links to https://docs.influxdata.com/chronograf/v1.7/guides/visualization-types/ which is 404

###### URL for relevant page?
https://docs.influxdata.com/chronograf/v1.7/guides/visualization-types/

###### What products and version are you using?
N/A? / Chronograph 1.7

###### Where did you look before opening the issue?
Searched the docs

**Comment by sanderson** [comment]
I think this how now been fixed. Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/181484/93386077-6548c380-f824-11ea-8335-51d7991d690e.png)

**Comment by kelseiv** [comment]
Thank you, @dwgibbons @sanderson, this has been resolved.
