### ISSUE TITLE
Broken link in Flux documentation - transform-data guide (InfluxDB 1.7)

### ISSUE THREAD

**Issue by PoloKltz** [influxdata/docs-v2#1509]
On the **Transform data with Flux** page, the link pointing to _create custom functions_ is broken

[EDIT] same dead link is found on **Flux syntax basics** page, link points to _Custom functions_ documentation. 

##### Relevant URLs
- Dead link: https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/custom-functions/
- Page to update: 
    - https://docs.influxdata.com/influxdb/v1.7/flux/get-started/transform-data/
    - https://docs.influxdata.com/influxdb/v1.7/flux/get-started/syntax-basics/

##### What products and version are you using?
- InfluxDB v1.7

**Comment by pierwill** [comment]
@sanderson: would you be able to take a look at this?

**Comment by kelseiv** [comment]
@pierwill, let's link to this page:
 /influxdb/v2.0/query-data/flux/custom-functions/

**Comment by pierwill** [comment]
Thanks, @PoloKltz! Fixing now.
