### ISSUE TITLE
Dashboard auto refresh control was removed

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1510]
Because Cloud users complained about inadvertently racking up large bills due to automated query refresh, this control has been removed.  Docs need an update to reflect this for OSS and Cloud.

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/visualize-data/dashboards/control-dashboard/#select-auto-refresh-interval

**Comment by PrplHaz4** [comment]
Any chance that access to this control will be moving into an admin setting?

**Comment by timhallinflux** [comment]
@PrplHaz4 -- we are discussing the mechanisms by which auto refresh could be re-introduced.  The challenge was that we had a few folks inadvertently leave this on....and that drove up their bill.  While, yes, that is user error -- we are re-evaluating what criteria should be used to allow for auto refresh.  For example:
1. no keyboard/mouse inputs for x mins
2. presentation mode only
3. admin controls to select the options (# of mins to timeout, availability of the feature, etc.)

Would welcome your feedback on the above...

**Comment by PrplHaz4** [comment]
I can see all of those being applicable in some manner - and it does sound risky to re-introduce a feature that could have runaway charges without any guard rails.

I think we'd prefer a combo of approaches - allowing admins to make it available (globally or for specific users), then a sensible default sleep timeout and/or refresh interval for "live" dashboards/presentation mode.
