### ISSUE TITLE
Add higher precedence to the power operator

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#1514]
Add higher precedence to the power operator so exponents are evaluated before other multiplicative operators (multiplication, division, modulus). (Currently, exponents are evaluated with the same precedence.)

Example
5 * 1 ^ 5 // currently returns 3125 
// after change, returns 5
8 / 2 ^ 2 // currently. returns 16
// after change, returns 2

PR that includes include breaking changes:
https://github.com/influxdata/flux/pull/3197

**Comment by pierwill** [comment]
See https://github.com/influxdata/docs-v2/pull/1609#discussion_r501226026.
