### ISSUE TITLE
click to get started link doesn't work

### ISSUE THREAD

**Issue by LachelleF** [influxdata/docs-v2#1516]
click to Get Started Guide link returning 404 error

##### Relevant URLs
https://docs.influxdata.com/enterprise_influxdb/v1.8/introduction/installation_guidelines/

##### What products and version are you using?
![Screenshot from 2020-09-19 15-10-19](https://user-images.githubusercontent.com/25691600/93687258-4b101f00-fa8a-11ea-99ae-0147538965d8.png)
- InfluxDB

**Comment by kelseiv** [comment]
Thank you for reporting, @LachelleF!  Fixed.
