### ISSUE TITLE
Document how to get data from Raspberry Pi

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1530]
If you do a google search for "[influxdb raspberry pi](https://www.google.com/search?client=firefox-b-1-d&q=influxdb+raspberry+pi)", there's no good documentation on how to pull data off a Raspberry Pi. The first two pages aren't even from InfluxData.

We should provide information on how to get data off of a Raspberry Pi in three scenarios:

1. Pi --> telegraf --> InfluxDB 1.x
2. Pi --> telegraf --> InfluxDB 2 OSS
3. Pi --> telegraf --> InfluxDB 2 Cloud

##### Relevant URLs
https://www.google.com/search?q=influxdb+raspberry+pi

##### What products and version are you using?

InfluxDB OSS and Cloud

**Comment by kelseiv** [comment]
Maybe related to https://github.com/influxdata/docs-v2/issues/1201

Work on these two issues together

**Comment by timhallinflux** [comment]
Is the problem marketing or docs?  This sounds like an SEO problem and not a technical one.

We now have a Rasp PI template, can that be leveraged for the SEO and we can just leave it at that?

**Comment by alsargent** [comment]
Instead of doc, we'll address this via a template page and an integration page.

**Comment by kelseiv** [comment]
Thank you for resolving this issue, @timhallinflux, @alsargent!
