### ISSUE TITLE
Document InfluxDB OSS and Enterprise TLS options

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs-v2#1546]
InfluxDB and InfluxDB Enterprise have several different options for configuring TLS on the nodes via the `[tls]` section in the config file. We should mention the TLS options available, like setting enforcing a minimum TLS version and restricting ciphers.

InfluxDB open source TLS config

```
[tls]
  # Determines the available set of cipher suites. See https://golang.org/pkg/crypto/tls/#pkg-constants
  # for a list of available ciphers, which depends on the version of Go (use the query
  # SHOW DIAGNOSTICS to see the version of Go used to build InfluxDB). If not specified, uses
  # the default settings from Go's crypto/tls package.
  # ciphers = [
  #   "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
  #   "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  # ]

  # Minimum version of the tls protocol that will be negotiated. If not specified, uses the
  # default settings from Go's crypto/tls package.
  # min-version = "tls1.2"

  # Maximum version of the tls protocol that will be negotiated. If not specified, uses the
  # default settings from Go's crypto/tls package.
  # max-version = "tls1.2"
```

InfluxDB Enterprise TLS config

```
[tls]
  # Determines the available set of cipher suites. See https://golang.org/pkg/crypto/tls/#pkg-constants
  # for a list of available ciphers, which depends on the version of Go (use the query
  # SHOW DIAGNOSTICS to see the version of Go used to build InfluxDB). If not specified, uses
  # the default settings from Go's crypto/tls package.
  # ciphers = [
  #   "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
  #   "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  # ]

  # Minimum version of the tls protocol that will be negotiated. If not specified, uses the
  # default settings from Go's crypto/tls package.
  # min-version = "tls1.2"

  # Maximum version of the tls protocol that will be negotiated. If not specified, uses the
  # default settings from Go's crypto/tls package.
  # max-version = "tls1.2"
```

##### Relevant URLs
- [Enterprise HTTPS setup guide](https://docs.influxdata.com/enterprise_influxdb/v1.8/guides/https_setup/)
- Maybe a new page specifically for InfluxDB open source?

##### What products and version are you using?

InfluxDB 1.7 and later
InfluxDB Enterprise 1.7 and later

**Comment by kelseiv** [comment]
Add note to doc above pointing to latest TLS settings; verify OSS also has TLS

**Comment by pierwill** [comment]
@gunnaraasen: I could have sworn we had this content for Enterprise and OSS 2.x! But I must have been remembering this: https://docs.influxdata.com/influxdb/v1.8/administration/config/#recommended-server-configuration-for-modern-compatibility

I'll add this content for Enterprise and OSS 2.x.

**Comment by pierwill** [comment]
Actually, we do have this: https://docs.influxdata.com/enterprise_influxdb/v1.9/administration/config-data-nodes/#recommended-server-configuration-for-modern-compatibility
