### ISSUE TITLE
Add troubleshooting FAQ section for "Unable to open..." and "permission denied" errors

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs-v2#1550]
When an InfluxDB package is installed on an instance with systemd, an `influxdb` user and group is automatically created. If the user runs an `influxd` process directly with their login shell (typically `root`), it can generate new series files not accessible by the `influxdb` user. When systemd starts the InfluxDB service (via `sudo systemctl start influxdb`), the InfluxDB process will exit because it cannot access the leftover files owned by the `root` user. The error in the InfluxDB logs (via `journalctl -u influxdb` typically includes text like:

- `error msg="Unable to open series file"`
- `run: open server: open tsdb store: mkdir /var/lib/influxdb/data/_internal/_series/00: permission denied`

The resolution is to set all files in the InfluxDB directories to be owned by the `influxdb` user and group.

```
sudo chown -R influxdb:influxdb /var/lib/influxdb/*
``` 

Or reset the database by removing all files.

##### Relevant URLs
- https://docs.influxdata.com/platform/troubleshoot/
- or similar page, maybe the FAQ

##### What products and version are you using?

InfluxDB 1.x
InfluxDB Enterprise 1.x

**Comment by pierwill** [comment]
Thanks, @gunnaraasen! We'll get this documented.
