### ISSUE TITLE
Document Chronograf basic auth options

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#1557]
https://github.com/influxdata/chronograf/pull/5577

**Comment by kelseiv** [comment]
On this page: https://docs.influxdata.com/chronograf/v1.6/administration/managing-security/

- Remove “On this page”
- Add option to “Configure Chronograf to authenticate with a username and password” at the top of page
- Under Chronograf security, we can say:

To set security Chronograf, choose between the following options:
- Username and password access control
- Role-based access control in Chronograf and enhanced security are provided using two configurable options:

- Also under Chronograf security, we can add a new section for “Username and password authentication” that includes the following: 

**<warning>** Only use this type of authentication in cases where OAuth integration is not possible. When using basic authentication, Chronograf authorization rules are not enforced. Basic authentication controls who can access Chronograf, and all users have SuperAdmin status. For more information, see [Cross-organization SuperAdmin status](/chronograf/v1.6/administration/managing-chronograf-users/#cross-organization-superadmin-status).

Turn on HTTP basic access authentication to restrict HTTP requests to Chronograf to selected users. Use `chronograf` CLI with `—htpasswd <path to .htpasswd file>` or `HTPASSWD` environment variable.

The .htpasswd file contains users and their passwords. For more information about managing the htpasswd utility, see [NGINX documentation](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/).


On this page https://docs.influxdata.com/chronograf/v1.8/tools/chronograf-cli/, perhaps under General authorization flags?:
 `—htpasswd <path to .htpasswd file>` or `HTPASSWD` environment variable
