### ISSUE TITLE
Document InfluxDB tracing

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#156]
There are two options for tracing:

- log
- jaeger

## Jaeger
If the tracing type flag == `jaeger`, then we use the Jaeger library to configure a Jaeger tracing destination.
https://sourcegraph.internal/github.com/influxdata/influxdb/-/blob/cmd/influxd/launcher/launcher.go#L360-374

Jaeger has great docs for this.
https://www.jaegertracing.io/docs/1.11/client-libraries/
https://www.jaegertracing.io/docs/1.11/client-features/

In the second Jaeger link, you’ll find a section “Tracer configuration via environment variables”. At a minimum, the InfluxDB OSS 2.x user will need to set these env vars:
`JAEGER_AGENT_HOST` - Jaeger agent host name or IP address
`JAEGER_SERVICE_NAME` - “service name” added to each trace

**Comment by noramullen1** [comment]
@sanderson doesn't think we're going to expose this--closing
