### ISSUE TITLE
Add call-out for how to use quotes with `influx write`

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#1561]
Regarding: https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/influx-cli/

This command returns a parsing error (`invalid boolean`):
```
influx write  "test_measurement,test_tag=tv test_field='fv' 1601403177"
```

This command works: 
```
influx write  'test_measurement,test_tag=tv test_field="fv" 1601403177'
```

The only difference is that the outer quotes are single and the quoting around the Field value is double.   This is finicky and will probably trip people up.

**Comment by pierwill** [comment]
Will test this out and document any gotchas. Thanks, @samhld!

**Comment by pierwill** [comment]
Hi @samhld. Got around to looking into this, and am running into the same issue myself. Will open an issue in `influxdb` before making a bit of a clunky doc change. This might be an easy fix...
