### ISSUE TITLE
Notebooks: As an early access user I can learn how to use notebooks

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/docs-v2#1595]
NOTE: This will be behind a feature flag so only early access users will be able to see it

**Comment by alexpaxton** [comment]
Left this blank to be not prescriptive about how to document Flows features

**Comment by mnorriswalker** [comment]
Common Use Cases to highlight documentation:

1. Downsampling
2. Data Cleaning with Normalization (map function?)
3. One off writing to buckets
4. Runbook
5. Create a dashboard cell (priority: low)

**Comment by mnorriswalker** [comment]
@noramullen1 - do you have a URL you can share?
