### ISSUE TITLE
chrono 1.8.7: make session inactivity duration configurable

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#1612]
https://github.com/influxdata/chronograf/pull/5585

**Comment by kelseiv** [comment]
Under `--auth-duration=` in this section:
https://docs.influxdata.com/chronograf/v1.8/administration/config-options/#authentication-options

Add the following:
	
**--inactivity-duration=**
The duration that a token is valid without any new activity."

Default value: `5m`

Environment variable : `$INACTIVITY_DURATION`
