### ISSUE TITLE
Task configuration options doc page, offset example mistyped

### ISSUE THREAD

**Issue by FlorianSG** [influxdata/docs-v2#1615]
_Task configuration options doc page, `offset` example mistyped:_

```
options task = {
  // ...
  offset: "0 * * * *",
}
```

_Should be something like:_

```
options task = {
  // ...
  offset: 10m,
}
```

##### Relevant URLs
- _https://docs.influxdata.com/influxdb/v2.0/process-data/task-options/_

**Comment by pierwill** [comment]
Thanks for this, @FlorianSG!
