### ISSUE TITLE
Typo on holtWinters() page

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1624]
The Holt-Winters Flux function page says "minutes" when it should say "months". See screenshot below, with minutes highlighted where it should say months.

![image](https://user-images.githubusercontent.com/20701/95406914-77bc9700-08d0-11eb-974c-6ca302630ce6.png)

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/holtwinters/

**Comment by sanderson** [comment]
This isn’t a typo. `2m` is 2 minutes. A 2 month duration value would be `2mo`.

**Comment by kelseiv** [comment]
Thank you, @alsargent and @sanderson !
