### ISSUE TITLE
404s for "influxdb delete predicate" google search

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1625]
The top two search results for [influxdb delete predicate](https://www.google.com/search?client=firefox-b-1-d&q=influxdb+delete++predicate) lead to 404 pages. These pages are:

https://docs.influxdata.com/influxdb/v2.0/reference/syntax/delete-predicate/

https://docs.influxdata.com/influxdb/v2.0/tags/delete/

![image](https://user-images.githubusercontent.com/20701/95409090-c7ea2800-08d5-11eb-9e3a-6f8f87252d13.png)

Here are the 404 pages:

![image](https://user-images.githubusercontent.com/20701/95409203-ff58d480-08d5-11eb-8b92-6d3f0d266176.png)

![image](https://user-images.githubusercontent.com/20701/95409218-07187900-08d6-11eb-8fa3-c38372ae2d4c.png)

We should probably 301 those pages somewhere relevant.

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/reference/syntax/delete-predicate/

https://docs.influxdata.com/influxdb/v2.0/tags/delete/

**Comment by kelseiv** [comment]
Thank you, @alsargent added redirects. Running indexing now...should be resolved in 20 min or so

**Comment by kelseiv** [comment]
Resolved. Thanks again, @alsargent!
