### ISSUE TITLE
Invalid HTTP Listener v2 description on page

### ISSUE THREAD

**Issue by mnowak82** [influxdata/docs-v2#1626]
Hello, on page https://docs.influxdata.com/telegraf/v1.15/plugins/#http_listener_v2 you have wrong description of HTTP Listener v2:

page says:

```
The HTTP Listener v2 input plugin listens for messages sent via HTTP POST. **Messages are expected in line protocol format ONLY (other Telegraf input data formats are not supported). This plugin allows Telegraf to serve as a proxy or router for the /write endpoint of the InfluxDB v2110 HTTP API.**
```

But:
1. HTTP Listener v2 input plugin on Github (https://github.com/influxdata/telegraf/blob/release-1.15/plugins/inputs/http_listener_v2/README.md)
```
HTTP Listener v2 is a service input plugin that listens for metrics sent via HTTP. **Metrics may be sent in any supported data format**.
```

2. InfluxDB Listener https://docs.influxdata.com/telegraf/v1.15/plugins/#influxdb_listener

```
This plugin was previously known as http_listener. **To send general metrics via HTTP, use the HTTP Listener v2 input plugin instead.**
```

Best regards,
Maciek

**Comment by kelseiv** [comment]
Updated. Thank you, @mnowak82!
