### ISSUE TITLE
Telegraf 1.16 output plugins

### ISSUE THREAD

**Issue by noramullen1** [influxdata/docs-v2#1631]
- [x] [dynatrace](/plugins/outputs/dynatrace/README.md) Dynatrace output plugin - Contributed by @thschue
 - [x] [sumologic](/plugins/outputs/sumologic/README.md) Sumo Logic output plugin - Contributed by @pmalek-sumo

**Comment by pmalek-sumo** [comment]
Not sure if that's relevant but the links seem to be incorrect.
Should be:

* https://github.com/influxdata/telegraf/blob/master/plugins/outputs/dynatrace/README.md
* https://github.com/influxdata/telegraf/blob/master/plugins/outputs/sumologic/README.md

respectively

**Comment by noramullen1** [comment]
> Not sure if that's relevant but the links seem to be incorrect.
> Should be:
> 
> * https://github.com/influxdata/telegraf/blob/master/plugins/outputs/dynatrace/README.md
> * https://github.com/influxdata/telegraf/blob/master/plugins/outputs/sumologic/README.md
> 
> respectively

Thanks, @pmalek-sumo !

**Comment by noramullen1** [comment]
Added to Telegraf 1.16 branch
