### ISSUE TITLE
Problems when trying curl code in documentation

### ISSUE THREAD

**Issue by wolfig** [influxdata/docs-v2#1641]
In the documentation about using secrets together with influxdb, the documentation mentions test code which I tried to execute with my own Bearer token:

    curl -XGET "http://myhost.xyz.com:8086/query?db=mydb" --data-urlencode "q=SHOW MEASUREMENTS" --header "Authorization: Bearer <mytoken>"

When executing this code, I persistently got a "missing required parameter /"q/"" error. I could get cross this error by using

    curl -XPOST ...

instead of "curl -XGET ..."

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/

##### What products and version are you using?

I am running a self-hosted InfluxDB 1.8

**Comment by russorat** [comment]
It seems to work with `curl -G` instead of `curl -XGET` on my machine. not sure why. we will look to update the docs.

**Comment by kelseiv** [comment]
Thank you @wolfig, @russorat, will update. 

Looks like POST is required in our API. `curl -g/--globoff` turns off URL "globbing" so folks can use `{ } [ ]` characters in the URL.

**Comment by russorat** [comment]
@kelseiv i don't think POST is required here. `http://localhost:8086/query?db=telegraf&q=show%20measurements` works just fine in my browser

**Comment by kelseiv** [comment]
Thank you @wolfig 
@russorat, pointed out that our 1.x API is sometimes a [GET and sometimes a POST](https://docs.influxdata.com/influxdb/v1.8/tools/api/#query-http-endpoint). For this SHOW 
example, it requires a GET request.

The `curl -XGET...` command doesn't accept a `--data` parameter, hence the error. 
We've updated this example to use `curl -G`, which sends a GET request that accepts the `--data` parameter and appends data to the URL.

We're reviewing all curl examples in our docs to ensure that we're using consistent and accurate standards across the board. Thank you for bringing this error to our attention!
