### ISSUE TITLE
Update to CLI docs to match update in influxdb v2

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/docs-v2#1647]
_Describe the issue here._

small addition to the influx CLI

##### Relevant URLs
- https://github.com/influxdata/influxdb/pull/19732

##### What products and version are you using?
- v2

**Comment by kelseiv** [comment]
Thank you, @jsteenb2. Looks like the `--limit` flag default is up-to-date: https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/task/list/

To be sure, is there another place you noticed?
