### ISSUE TITLE
Upgrade to InfluxDB OSS v2.0.rc0 URL 404

### ISSUE THREAD

**Issue by danielwilson654** [influxdata/docs-v2#1679]
Upgrade to InfluxDB OSS v2.0.rc0 URL 404

##### Relevant URLs
Upgrade to InfluxDB OSS v2.0.rc0
https://docs.influxdata.com/influxdb/v2.0/reference/rc0-upgrade-guide/

**Comment by pierwill** [comment]
Thank you, @danielwilson654!
