### ISSUE TITLE
Upgrade guide 1.8 -> 2.0 rc1

### ISSUE THREAD

**Issue by vlastahajek** [influxdata/docs-v2#1680]
InfluxDB 2 RC 1 introduces the ability to upgrade from InfluxDB 1.x to InfluxDB 2 performed by the `influxd upgrade` command.

```
> influxd upgrade --help

    Upgrades a 1.x version of InfluxDB by performing the following actions:
      1. Reads 1.x config file and creates 2.x config file with matching options. Unsupported 1.x options are reported.
      2. Copies and upgrades 1.x database files.
      3. Creates a script for creating 1.x users and their permissions. This script needs to be revised and run manually after starting 2.x.

    If the config file is not available, 1.x db folder (--v1-dir options) is taken as an input.
    Target 2.x database dir is specified by the --engine-path option. If changed, the bolt path should be changed as well.

Usage:
  influxd upgrade [flags]
  influxd upgrade [command]

Available Commands:
  v1-dump-meta Dump InfluxDB 1.x meta.db
  v2-dump-meta Dump InfluxDB 2.x influxd.bolt

Flags:
  -m, --bolt-path string             path for boltdb database (default "/<user-home>/.influxdbv2/influxd.bolt")
  -b, --bucket string                primary bucket name
      --config-file string           optional: Custom InfluxDB 1.x config file path, else the default config file
  -e, --engine-path string           path for persistent engine files (default "/<user-home>/.influxdbv2/engine")
  -f, --force                        skip confirmation prompt
  -h, --help                         help for upgrade
      --influx-command-path string   path to influx command (default "/usr/bin/influx")
      --log-path string              optional: custom log file path (default "/<user-home>/upgrade.log")
  -o, --org string                   primary organization name
  -p, --password string              password for username
  -r, --retention string             optional: duration bucket will retain data. 0 is infinite. Default is 0.
      --security-script string       optional: generated security upgrade script path (default "/<user-home>/influxd-upgrade-security.sh")
  -t, --token string                 optional: token for username, else auto-generated
  -u, --username string              primary username
      --v1-dir string                path to source 1.x db directory containing meta, data and wal sub-folders (default "/<user-home>/.influxdb")
  -v, --verbose                      verbose output (default true)
```
**Prerequisities**
 - Stopped InfluxDB 1.x.
 - Installed, but not started and not initialized InfluxDB 2 rc1 and above. If InfluxDB 2 has already been initialized (created admin user), either the data files (`engine` folder) and the bolt file (`influxdb.bolt`) must be deleted or upgrade must be run against different folder and bolt file, which they must be user later when starting server. E.g.:
`influxd upgrade --engine-path /mnt/data/influxdb2/engine --bolt-path /mnt/data/influxdb2/influxdb.bolt`
After upgrade:
`influxd  --engine-path /mnt/data/influxdb2/engine --bolt-path /mnt/data/influxdb2/influxdb.bolt`
  
**Running upgrade**
Important paths to validate: 
 - InfluxDB 1 config file (--config-file): Config file of the InfluxDB 1 server. Path to data dirs (Data, Wal, and Meta) is read from it and all supported options are written to new config for InfluxDB 2. Default `/etc/influxdb/influxdb.conf`.
- InfluxDB 2 engine path (-e, --engine-path): Path for persistent InfluxDB 2 engine files. Default `/<user-home>/.influxdbv2/engine`. It must be empty or not exist before starting upgrade.
- InfluxDB 2 bolt path (-b, --bolt-path):  Path for InfluxDB 2  boltdb database.  Default `/<user-home>/.influxdbv2/influxd.bolt`. It must not exist before starting upgrade.

run: `influxd upgrade`, or with additional options.

When the upgrade is started and no flags are specified, the default paths are considered as inputs and a user is interactively asked to enter org, user name, user password, bucket, and retention parameters.

If InfuxDB 1 contained users with defined privileges, influxd upgrade will create a script that will allow creating authorization tokens with privileges to the same data. This script should be revised and that run after starting the server with upgraded data.

**After the upgrade**
The new config file can be applied in two ways:
 - Use env var: Set config file path to INFLUXD_CONFIG_PATH env var.
-  Place config file in the same folder ad `influxd`. The config file must have name 'config.yaml`.

Start the server.

Run the script for creating privileges.

**Comment by pierwill** [comment]
Thanks for this, @vlastahajek. 🙏

**Comment by vlastahajek** [comment]
@pierwill, small update for `influxd upgrage --help`, if needed.
```
   Upgrades a 1.x version of InfluxDB by performing the following actions:
      1. Reads 1.x config file and creates 2.x config file with matching options. Unsupported 1.x options are reported.
      2. Copies and upgrades 1.x database files.
      3. Creates a script for creating tokens that correspond to 1.x users. This script needs to be revised and run manually after starting 2.x.

    If the config file is not available, 1.x db folder (--v1-dir options) is taken as an input.
    Target 2.x database dir is specified by the --engine-path option. If changed, the bolt path should be changed as well.

Usage:
  influxd upgrade [flags]
  influxd upgrade [command]

Available Commands:
  v1-dump-meta Dump InfluxDB 1.x meta.db
  v2-dump-meta Dump InfluxDB 2.x influxd.bolt

Flags:
  -m, --bolt-path string             path for boltdb database (default "/home/ubuntu/.influxdbv2/influxd.bolt")
  -b, --bucket string                primary bucket name
      --config-file string           optional: Custom InfluxDB 1.x config file path, else the default config file (default "/etc/influxdb/influxdb.conf")
  -e, --engine-path string           path for persistent engine files (default "/home/ubuntu/.influxdbv2/engine")
  -f, --force                        skip the confirmation prompt
  -h, --help                         help for upgrade
      --influx-command-path string   path to influx command (default "/mnt/c/git/influxdb/bin/linux/influx")
      --log-path string              optional: custom log file path (default "/home/ubuntu/upgrade.log")
  -o, --org string                   primary organization name
  -p, --password string              password for username
  -r, --retention string             optional: duration bucket will retain data. 0 is infinite. The default is 0.
      --security-script string       optional: generated security upgrade script path (default "/home/ubuntu/influxd-upgrade-security.sh")
  -t, --token string                 optional: token for username, else auto-generated
  -u, --username string              primary username
      --v1-dir string                path to source 1.x db directory containing meta, data and wal sub-folders (default "/home/ubuntu/.influxdb")
  -v, --verbose                      verbose output (default true)
```

**Comment by alespour** [comment]
> ```
>       3. Creates a script for creating 1.x users and their permissions. This script needs to be revised and run manually after starting 2.x.
> ```

`3. Creates a script for creating tokens that correspond to 1.x users` is more accurate

> **After the upgrade**
> The new config file can be applied in two ways:
> 
> * Use env var: Set config file path to INFLUXD_CONFIG_PATH env var.
> * Place config file in the same folder ad `influxd`. The config file must have name 'config.yaml`.

Why not just point the user to [https://docs.influxdata.com/influxdb/v2.0/reference/config-options/](https://docs.influxdata.com/influxdb/v2.0/reference/config-options/) in order to learn about v2 configuration options. It is described in detail there.
