### ISSUE TITLE
As a developer, I want reference documentation for the Query API endpoint

### ISSUE THREAD

**Issue by rbetts** [influxdata/docs-v2#1688]
_Describe the issue here._

As a developer using the API, I want to be able to easily find examples showing the query API and a reference for the API. A google search returns unhelpful SEO results:

![Screen Shot 2020-10-20 at 12 11 07 PM](https://user-images.githubusercontent.com/158141/96613762-56df4300-12cd-11eb-9fdf-95bef4258095.png)

The best of these is "Different ways to query influxdb": https://docs.influxdata.com/influxdb/v2.0/query-data/execute-queries/

From that page, there is a link to an API example - but no cross linking or reference to the actual API documentation. (Also, it only shows flux and not influxql).

Clicking the `query` tag below shows an unorganized group of pages.

From the full API documentation, https://docs.influxdata.com/influxdb/v2.0/api/, there is no preface or introductory material explaining anything about the API.  And clicking on "Query" (https://docs.influxdata.com/influxdb/v2.0/api/#operation/PatchDashboardsIDCellsIDView) from the ToC leads to a bunch of endpoints that are unlikely what the user wants (like PostQueryAst).

**Comment by timhallinflux** [comment]
While we have the underlying Swagger as a reference for the API, it seems like we have a big gap here in terms of developer oriented content -- working with the API.  

I'd like to see a Working with the API section -- this may be part of the developer's guide.  But, we need to cover the basics -- rapidly -- and then decide how much we want to cover beyond that.

Basics:
/v2/write & /write (v1 compat)
/v2/read & /read (v1 compat)
/v2/authorizations
/v2/secrets
...

**Comment by kelseiv** [comment]
@pierwill, tagging you re the new "Working with the API section" we discussed. Let's put that in new PR.

Remaining items in this issue have been addressed https://github.com/influxdata/docs-v2/pull/1737

**Comment by sanderson** [comment]
We broken out all of the different methods for querying InfluxDB into separate pages and have added content to each. These new pages are now live. One is "Query with the InfluxDB API" which acts as a landing page for this particular search. We've requested that Google to reindex the site, so now it's just a waiting game.
