### ISSUE TITLE
Update sample data

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#1696]
Update sample data doc as needed to ensure the data works with free tier accounts w 30 day retention policy.
https://docs.influxdata.com/influxdb/v2.0/reference/sample-data/#air-sensor-sample-data

Query provided by @abalone23 to limit points to last 30 days:
```
import "experimental/csv"
// get duration between 30 days ago and start of csv file timestamp to timeshift points within last 30 days
dur = duration(v: uint(v: now()) - uint(v: 30d) - uint(v: 2019-08-17T00:00:00Z))
csv.from(url: "https://influx-testdata.s3.amazonaws.com/noaa.csv")
    |> filter(fn:(r) => r._measurement == "average_temperature")
    |> timeShift(duration: dur)
    |> to(bucket:"mybucket", org:"me@example.com")
```

**Comment by sanderson** [comment]
We should probably note that this is only necessary in Cloud.

**Comment by sanderson** [comment]
I used a different strategy than described here. Many of the sample data sets have data that spans much more than 30 days. This method would write many points into the future. Instead, the method I used makes all the timestamps relative to when the import takes place (`now()`). This way nothing gets written into the future.
