### ISSUE TITLE
Feature Request: Static LHS Docs Index

### ISSUE THREAD

**Issue by Nishant-Mishra** [influxdata/docs-v2#1697]
It would be helpful to have the Docs Index (on Left Hand Side) to be Static. Scrolling the docs should not scroll the Index.

**Comment by kelseiv** [comment]
Thank you, @Nishant-Mishra! 
We agree and have an [open issue](https://github.com/influxdata/docs-v2/issues/1556) to resolve this, so closing this issue.

I've updated the language in the original issue so anyone like you who searches for "index" or "left" or "navigation" will get a hit.
