### ISSUE TITLE
Adding link to download CLI

### ISSUE THREAD

**Issue by bckeene** [influxdata/docs-v2#1704]
_Describe the issue here._
Just a request, but it could be really helpful to point users to the CLI download page if they are looking at these docs. 

##### Relevant URLs
https://portal.influxdata.com/downloads/

##### What products and version are you using?
InfluxDB Cloud.

**Comment by timhallinflux** [comment]
https://docs.influxdata.com/influxdb/v2.0/get-started/#optional-download-install-and-use-the-influx-cli

There is a big button which by-passes the downloads page today.
