### ISSUE TITLE
Docker tag incorrect / not uploaded

### ISSUE THREAD

**Issue by ptxmac** [influxdata/docs-v2#1705]
The docker installation guide mentions the tag `2.0.0-rc2`, but it does not exists
##### Relevant URLs
- [Docs link](https://docs.influxdata.com/influxdb/v2.0/get-started/#start-with-influxdb-oss)
- [Docker Tags](https://quay.io/repository/influxdb/influxdb?tag=latest&tab=tags)

##### What products and version are you using?

Attempt to use influxdb 2

**Comment by ptxmac** [comment]
The last change to that part of the documentation was 7313220 by @kelseiv

**Comment by kelseiv** [comment]
Thank you, @ptxmac - updated
