### ISSUE TITLE
Are there docs for the flux function syntax?

### ISSUE THREAD

**Issue by Kungitoo** [influxdata/docs-v2#1710]
So I'd like to be able to define some functions but I cannot for the life of me find syntax for it. Only mention of functions I found is this https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/aggregates/aggregatewindow/#function-definition

Is it even possible to write functions like this? Do I pass the table like it says in this function definition at the end with `, tables=<-)` ?

**Comment by sanderson** [comment]
@Kungitoo This is probably what you're looking for: https://docs.influxdata.com/influxdb/v2.0/query-data/flux/custom-functions/

What search terms did you use? I can tweak our search settings to help others find this doc.

**Comment by Kungitoo** [comment]
My bad, I don't know how I missed it. And I wanted to make sure I didn't miss it before I opened the issue...

**Comment by sanderson** [comment]
@Kungitoo If you weren't able to find it, that's a problem that I think we can fix. Do you remember what search terms you used when you first tried?
