### ISSUE TITLE
double quotes don

### ISSUE THREAD

**Issue by jacky4631** [influxdata/docs-v2#1715]
_Describe the issue here._

##### Relevant URLs
- _Provide relevant URLs_

##### What products and version are you using?

](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/)
![image](https://user-images.githubusercontent.com/7930908/97242335-91e1f900-182e-11eb-8426-6f78e0feaec8.png)
I try to use double quotes in select sql, the result is ok when i don't add escape, 
but there is an error when I use single quotes in select sql,  after i escapes single quote, the result is ok.
is there an error in this docs?

**Comment by timhallinflux** [comment]
Can you provide an example of what you are doing?

**Comment by jacky4631** [comment]
write one:
SELECT MAX("filesize") FROM "flogstat" WHERE "name"='/opt/probe/sysprobe_rh6_64_p2.7.0.303/tm p\'".log'

wrong one:
SELECT MAX("filesize") FROM "flogstat" WHERE "name"='/opt/probe/sysprobe_rh6_64_p2.7.0.303/tm p'".log'

only one difference: backslash

**Comment by jacky4631** [comment]
soo

> Can you provide an example of what you are doing? This documentation reference is for line protocol which is about formatting the data for writing into InfluxDB. But, your question(s) appear to be about querying with InfluxQL.

sorry, can you provide any url which about special characters of querying with InfluxQL, i can't find it. thank you.

**Comment by timhallinflux** [comment]
Those two examples look identical to me. You start the value reference with a single quote and it ends with the next single quote. So everything after the p' should be truncated.

First off, if you really have stuffed `/opt/probe/sysprobe_rh6_64_p2.7.0.303/tm p'.log` into the name `field`, I think you have a problem with the data ingest.   It might be worth addressing that.

But in the meantime, I think you are better off with a regex at this point.  So try, `SELECT MAX("filesize") FROM "flogstat" WHERE "name"=~ /*opt/probe/sysprobe_rh6_64_p2.7.0.303/tm*/`

**Comment by timhallinflux** [comment]
https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#strings

**Comment by jacky4631** [comment]
> https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#strings
> `SELECT MAX("filesize") FROM "flogstat" WHERE "name"='/opt/probe/sysprobe_rh6_64_p2.7.0.303/tm p\'".log'`
> 
> should do it.

thank you
