### ISSUE TITLE
Calling delete on the API returns 501 not implemented

### ISSUE THREAD

**Issue by doivosevic** [influxdata/docs-v2#1718]
I'm trying to invoke the https://docs.influxdata.com/influxdb/v2.0/api/#/paths/~1delete/post to delete some data. I specify the correct org and bucket and start/stop but the response I get is 501 not implemented. The response code isn't even listed in the docs.
![image](https://user-images.githubusercontent.com/6378638/97315659-35e89600-1869-11eb-87c9-b06c9ca84153.png)

**Comment by Kungitoo** [comment]
https://github.com/influxdata/influxdb/blob/e405398ac1095248f6ac7a281156f850f70caf28/http/delete_handler.go#L118
Does this method just not work right now? Is there a way to delete data without deleting the bucket? How am I supposed to delete logs of ran tasks?

**Comment by jstirnaman** [comment]
I don't see a `predicate` sent in the request. Example request body:

```
{
  "predicate": "tag1=\"value1\" and (tag2=\"value2\" and tag3!=\"value3\")",
  "start": "2019-08-24T14:15:22Z",
  "stop": "2019-08-24T14:15:22Z"
}
```

The `/api/v2/delete` is implemented now.
