### ISSUE TITLE
Confusion in example query script

### ISSUE THREAD

**Issue by juangallostra** [influxdata/docs-v2#1722]
The provided [example query script](https://docs.influxdata.com/influxdb/v2.0/tools/client-libraries/python/#complete-example-query-script) might lead to some confusion. In the first line the `query_api` variable is defined

```python
query_api = client.query_api()
```
but later on, when making the query, the call being made is

```python
result = client.query_api().query(org=org, query=query)
```

which doesn't make use of the previously defined variable. I would either remove the first variable definition or change the call to

```python
result = query_api.query(org=org, query=query)
```

The complete example is:
```python
query_api = client.query_api()
query = ' from(bucket:"my-bucket")\
|> range(start: -10m)\
|> filter(fn:(r) => r._measurement == "my_measurement")\
|> filter(fn: (r) => r.location == "Prague")\
|> filter(fn:(r) => r._field == "temperature" )'
result = client.query_api().query(org=org, query=query)
results = []
for table in result:
    for record in table.records:
        results.append((record.get_field(), record.get_value()))

print(results)
[(temperature, 25.3)]
```

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/tools/client-libraries/python/#complete-example-query-script

##### What products and version are you using?

InfluxDB 2.0

**Comment by jstirnaman** [comment]
This was fixed in #2890. 4e84ac2 will fix the 404 from the old URL.
