### ISSUE TITLE
Chronograf pre-created dashboards: postgresql plugin 404 not found 

### ISSUE THREAD

**Issue by martaferg** [influxdata/docs-v2#1723]
Page not found error when following a link appearing in 2.0 documentation.

##### Relevant URLs
404 error: https://docs.influxdata.com/telegraf/v1.16/plugins/inputs/#postgresql
Accessed from https://docs.influxdata.com/chronograf/v1.8/guides/using-precreated-dashboards/#postgresql -> postgreSQL input plugin

**Comment by kelseiv** [comment]
Thank you, @martaferg! Updated link.
