### ISSUE TITLE
Fix table formatting

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#1727]
Update Flag table on this page https://docs.influxdata.com/influxdb/v2.0/reference/cli/influxd/

refers to Layouts\shortcodes\cli\influxd-flags

Maybe an extra column?

**Comment by pierwill** [comment]
The markdown looks correct here. Thought on the CSS, @sanderson?

**Comment by sanderson** [comment]
The problem is the length of the flags, specifically `--storage-series-file-max-concurrent-snapshot-compactions`. With the additions of the new flags, this section may be better suited for a TOC/heading structure for the flags.
