### ISSUE TITLE
Document new OSS backup and restore

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#1747]
PR: https://github.com/influxdata/influxdb/pull/19864

- [x] (re)add the commands to the v2 CLI
- [x] Provide task based docs for each process

**Comment by kelseiv** [comment]
Thank you for adding detail, @sanderson. 
@noramullen1, this issue duplicates https://github.com/influxdata/docs-v2/issues/1603, so adding you here and closing the other.
