### ISSUE TITLE
Fix Telegraf plugins link

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#1752]
Fix link on https://docs.influxdata.com/telegraf/v1.14/plugins/plugin-list/

Link goes here:
https://docs.influxdata.com/telegraf/v1.16/plugins/plugin-list/

Should go here:
https://docs.influxdata.com/telegraf/v1.16/plugins/

**Comment by sanderson** [comment]
Just add `/telegraf/v1.16/plugins/plugin-list/` as an alias on `content/telegraf/v1.16/plugins.md`.

**Comment by kelseiv** [comment]
Thanks, @sanderson - issue resolved
