### ISSUE TITLE
Band chart: needs much more documentation about how to use it

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1753]
The new band chart is a very powerful visualization type.  However, to take advantage of this, it really needs more description and examples.  Because of the complexity that comes along with the power --- the current doc is too brief to guide a user to success.

There are some different behaviors as well -- one when using the query builder and how to make it function as expected.  The other is using the query editor -- and again how to make it function there.  We'll need a clear example of each.

One of the powerful things that this chart type allows is essentially the ability to visualize 3 different series --- which have been named (via yield). 

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/visualize-data/visualization-types/band/

**Comment by sanderson** [comment]
My wife has a Dr appoint at this time, so I’ll be on kid duty. Could we do it later in the day?

Scott Anderson
scott@influxdata.com

**Comment by noramullen1** [comment]
This is fixed in PR #1754 , which is going out with OSS GA.
