### ISSUE TITLE
Update schema best practices in 2.0

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#1756]
Review 1.x and 2.0 schema content to determine what we need to add to 2.0.  For example, best practices, limits, high cardinality issue, etc.

**1.x**
https://docs.influxdata.com/influxdb/v1.8/concepts/schema_and_data_layout/

**2.0.** 
Potentially related content (add links amongst related content): 
https://docs.influxdata.com/influxdb/v2.0/write-data/best-practices/optimize-writes/
https://docs.influxdata.com/influxdb/v2.0/reference/key-concepts/data-schema/
https://docs.influxdata.com/influxdb/v2.0/query-data/flux/explore-schema/

Please tag Brian Keene and Max Printz on review.

**Comment by timhallinflux** [comment]
We use series cardinality in a number of places in the docs and on the website, it's listed in the Glossary.  I believe we need to link this topic to the best practices as well.

**Comment by timhallinflux** [comment]
When we have the URL for this content, we need to provide to marketing so they can associate it with the Cloud pricing page on the website -- to educate folks about what series cardinality is and best practices for working with InfluxDB.
