### ISSUE TITLE
What is the type of x in getRecord() example?

### ISSUE THREAD

**Issue by Kungitoo** [influxdata/docs-v2#1759]
https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/stream-table/getrecord/

What is the type of x in the example. Is it a variable which can be used for calculating e.g. in map?

**Comment by sanderson** [comment]
`x` is just a variable that shows how how you can use scalar values extracted from a record from a stream of tables. For example, the operations above will return the first row of the first table in the query output that has `cpu` as the measurement and `usage_idle` as the field. The record it returns will look something like:

```js
r0 = {_measurement: "cpu", _field: "usage_idle", host: "example-host", _time: 2020-01-01T00:00:00Z, _value: 95.23}
```

So in the definition of `x`, all operands are strings, so `x` will be a string:

```js
x = r0._field + "--" + r0._measurement

// x returns "usage_idle--cpu"
```
