### ISSUE TITLE
get dbrps example is wrong

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#1774]
https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/#manually-create-and-manage-dbrp-mappings

the example to get all the dbrps is incorrect. https://docs.influxdata.com/influxdb/v2.0/api/#tag/DBRPs

the only required param is orgID and it is a query string param

**Comment by kelseiv** [comment]
Thanks, @russorat, to be extra sure, has this functionality been updated in the last month?

When we tested `/dbrps` either `organization_id` or `organization` appeared to work (although organization ID did take precedence)....and `orgID` wasn't working, but the plan was indeed to eventually shorten the naming conventions to match others in the API
https://influxdata.slack.com/archives/D019HA0KEDC/p1601915194006500

Also, we had [this issue](https://github.com/influxdata/influxdb/issues/19689), which appears @stephanie-engel closed after we updated the docs....so not 100% this is stiall an issue in the API?

**Comment by sanderson** [comment]
@kelseiv I've tested the updated commands in #1776 and they work as expected. It appears the API has changed since this doc was originally written.

**Comment by kelseiv** [comment]
Excellent, thank you @sanderson
