### ISSUE TITLE
Add AWS US-East-1 (Virginia) and fix broken link

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1777]
Cloud is now available on AWS US-East-1 (Virginia) -- we need to add the URL.

https://us-east-1-1.aws.cloud2.influxdata.com/

<img width="636" alt="Screen Shot 2020-11-06 at 3 17 52 PM" src="https://user-images.githubusercontent.com/23535264/98423368-40faad80-2043-11eb-819c-d7de893b3efc.png">

Also -> Clicking on InfluxDB URLs via (https://docs.influxdata.com/influxdb/influxdb/reference/urls/) yields a 404.

Correct URL is -> https://docs.influxdata.com/influxdb/v2.0/reference/urls/

**Comment by sanderson** [comment]
Closed via #1782
