### ISSUE TITLE
Cloud URLs page, etc. are missing AWS us-east-1

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1799]
On our [Cloud URLs page,](https://docs.influxdata.com/influxdb/v2.0/reference/urls/) the URL for AWS us-east-1 is missing. Please add it.

Also, the "Where are you running InfluxDB" configuration setting is missing AWS Virginia:

![image](https://user-images.githubusercontent.com/20701/98752142-686cb580-2376-11eb-938e-1f403df5aa3e.png)

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/reference/urls/

**Comment by noramullen1** [comment]
This is fixed in our upcoming OSS GA/separate cloud branch. Closing.
