### ISSUE TITLE
influxd CLI reference docs show unavailable subcommands

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#1812]
The reference docs for the `influxd` CLI show commands that have been commented-out in the codebase. The commands that are no longer available are:
* `influxd generate` and all subcommands
* All subcommands of `influxd inspect`, except for `influxd inspect export-instance`

##### Relevant URLs
- `influxd` [reference docs](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influxd/)
- `influxd inspect` [reference docs](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influxd/inspect/)

##### What products and version are you using?
influxd OSS v2.0.1

**Comment by sanderson** [comment]
@danxmoran Is this a permanent change or will these subcommands come back?

**Comment by danxmoran** [comment]
@sanderson we have issues in the backlog to restore them, I'm not sure where they fall on the roadmap

**Comment by sanderson** [comment]
Thanks @danxmoran. I just marked them all as draft so when they do come back, it’ll be easy to bring the docs back.
