### ISSUE TITLE
influxd CLI reference docs are missing info on `upgrade` subcommands

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#1813]
The reference docs for `influxd upgrade` are missing references to its 2 subcommands:
1. influxd upgrade v1-dump-meta
2. influxd upgrade v2-dump-meta

##### Relevant URLs
- influxd upgrade [docs](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influxd/upgrade/)

##### What products and version are you using?
influxd OSS v2.0.1

**Comment by pierwill** [comment]
Hi @danxmoran! In previous discussions, we'd decided that these were internal facing tools and therefore we preferred not to document them. Can you confirm this is still the case, @stuartcarnie?

**Comment by pierwill** [comment]
(See https://github.com/influxdata/influxdb/pull/20076.)
