### ISSUE TITLE
InfluxDB shell 1.8.3 points to broken v2.0 docs

### ISSUE THREAD

**Issue by blalor** [influxdata/docs-v2#1821]
The output of `help` in the `influx` shell points to https://docs.influxdata.com/influxdb/latest/query_language/spec/, which is broken, and would be wrong even if it did work, as 1.8.3 is "latest" for a finite period of time.

```
🌴 mainline(+45/-0)* ± influx -host …
Connected to http://…:8086 version 1.8.3
InfluxDB shell version: 1.8.3
> help
Usage:
…

        A full list of influxql commands can be found at:
        https://docs.influxdata.com/influxdb/latest/query_language/spec/
```

**Comment by sanderson** [comment]
Thanks @blalor! I just pushed a fix for this.
