### ISSUE TITLE
Last has an column parameter

### ISSUE THREAD

**Issue by nathanielc** [influxdata/docs-v2#1823]
The docs for the `last()` function do not document its `column` parameter. 

https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/selectors/last/

Here is the official type of the `last` function https://github.com/influxdata/flux/blob/master/stdlib/universe/universe.flux#L44

**Comment by sanderson** [comment]
@nathanielc What exactly is the behavior of the `column()` parameter. Does it define a column to sort by? In my testing, changing the column has no discernible difference. Does the `column` parameter have a default value?

**Comment by nathanielc** [comment]
It only has an effect if the value in the column is null. So if the last row in a table is null for the specified column that row is NOT returned, rather the previous row would be. 

As a result most of the time it doesn't matter, only when the data has nulls.
