### ISSUE TITLE
Can we programatically generate a dashboard with flux queries running?

### ISSUE THREAD

**Issue by Kungitoo** [influxdata/docs-v2#1824]
I'm trying to read the API docs but you left the properties completely unexplained. Can we provide flux code for the cell? Is there some other API which does this?

**Comment by sanderson** [comment]
@Kungitoo you absolutely can. This is why [InfluxDB templates and stacks](https://docs.influxdata.com/influxdb/v2.0/influxdb-templates/) were developed. You can build an entire dashboard, export it as a template, and import everything you need into another instance of InfluxDB, all through the API. Our API docs are lacking some detail and that's work we've prioritized over the next few months.

**Comment by sanderson** [comment]
I'm going to close this issue for now. Please feel free to add questions or make other suggestions.
