### ISSUE TITLE
Broken api doc link on dockerhub

### ISSUE THREAD

**Issue by CaptainPi-PiLabs** [influxdata/docs-v2#1828]
You've put a nice message in your 404 asking me to come here :P 

https://hub.docker.com/_/influxdb

Under 'Exposed Ports' I think the link needs to be changed from:
https://docs.influxdata.com/influxdb/latest/concepts/api/
to
https://docs.influxdata.com/influxdb/latest/reference/api/

**Comment by kelseiv** [comment]
Thank you, @CaptainPi-PiLabs -resolved!
