### ISSUE TITLE
What happens to the tags when pivoting?

### ISSUE THREAD

**Issue by Kungitoo** [influxdata/docs-v2#1836]
Could you please tell me what happens to the tags when pivoting and add that information to the docs https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/pivot/

**Comment by sanderson** [comment]
@Kungitoo `pivot()` will drop any columns that:

1. Are **not** part of the group key
2. Are **not** specified in the `rowKey`, `columnKey` and `valueColumn` parameters

By default, InfluxDB includes all tags in the group key and tags define how tables in a stream of tables are partitioned. If tags are in the group key, `pivot()` will output a table for each unique tag set and the tags are preserved.
