### ISSUE TITLE
Add consolidation of Flux stdlib dropdowns [food for thought]

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#1843]
_Describe the issue here._

Idk how pervasive this is but I find the list of dropdowns for the Flux stddlib docs difficult to navigate.  It's a little long and the pattern seems just slightly inconsistent. Given that I'm already familiar with our docs and Flux, I can't imagine our users (especially new ones) have it any easier.

![Screen Shot 2020-11-17 at 8 23 59 AM](https://user-images.githubusercontent.com/4852912/99417206-85414580-28ae-11eb-9ef3-2ef3466796ae.png)

Seems to me the endpoints like Pagerduty, Slack, and Pushbullet could be conslidated, as well as all the InfluxDB ones? 

The changes to the InfluxDB-specific docs with "Write Data" and "Query Data" made a lot of sense.  I feel like something along those lines could be applied here.

**Comment by sanderson** [comment]
Thanks @samhld, the Flux docs are about to undergo a bit of an overhaul, so good timing.

**Comment by sanderson** [comment]
@samhld I'm working on the restructure and have decided to structure the standard lib docs to match the structure of the standard library itself. Thoughts?

![image](https://user-images.githubusercontent.com/181484/104776679-a8b23080-5737-11eb-8f30-3f59d34e4b8a.png)

**Comment by samhld** [comment]
@sanderson I assume you mean following [this structure](https://github.com/influxdata/flux/tree/master/stdlib)?

If so, I would probably say the same thing about it.  An example of what I would think is a net positive consolidation would a structure grouping `http`, `json`, `csv`, `array`, `sql`, `kafka`, `socket`, etc. like this:

* I/O
  - Inputs
    - http
    - socket
    - json
    - csv
    - array
    - sql
    - kafka
  - Outputs
    - http
    - socket
    - json
    - csv
    - array
    - sql
    - kafka

To a new user, all of that would look like:
* I/O


There are probably a lot of other ways organize that (i.e., you could pull out `http` and `socket` into a category called `network` or something)

You could also store `pagerduty`, `slack`, `victorops`, etc., into `monitor` or `alerting` or something.
