### ISSUE TITLE
No "Load Data" in the Tokens area

### ISSUE THREAD

**Issue by davidgs** [influxdata/docs-v2#1845]
_Describe the issue here._

Documentation describes "In the navigation menu on the left, select Data (Load Data) > Tokens." This does not exist in the 2.0.1OSS UI. 
##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/security/tokens/update-tokens/

**Comment by sanderson** [comment]
@davidgs Are you not seeing this in your UI? This is from my InfluxDB 2.0.1 running locally for me:

![image](https://user-images.githubusercontent.com/181484/99431566-34d6e180-28c8-11eb-8bd0-60037eeaf852.png)

**Comment by davidgs** [comment]
```
[davidgs@whm ~]$ which influxd
/usr/bin/influxd
[davidgs@whm ~]$ /usr/bin/influxd version
InfluxDB 2.0.1 (git: 37cc047133) build_date: 2020-11-11T03:53:31Z
```
So that looks right. 
The UI only reports 2.0.0 but I saw elsewhere that this was a reported issue. 

This is what my UI looks like in the Load Data tab. 
![Screen Shot 2020-11-17 at 1 40 43 PM](https://user-images.githubusercontent.com/2071898/99432725-8ab48500-28da-11eb-9797-dd0c81331500.png)

**Comment by sanderson** [comment]
So with the left nav condensed, you won't see the lists of sections under each main nav item, but these just correspond to the tabs available in each section. You have a "Tokens" tab on the far right of your top nav. The challenge we tried to solve with the phrasing, **Load Data > Tokens** , is accurately describing UI structure for both states of the left nav (expanded vs collapsed).

**Comment by davidgs** [comment]
A) How do I 'expand' the nav? and b) the 'Tokens' tab still does not have a 'load' ability. 
![Screen Shot 2020-11-17 at 2 27 39 PM](https://user-images.githubusercontent.com/2071898/99437969-2943e480-28e1-11eb-8703-4416dc94bcaa.png)

**Comment by mhall119** [comment]
A) there's a button at the very bottom of the nav to expand/collapse it

B) I don't think tokens are editable in 2.0. Maybe they were in an earlier alpha or beta, but I'm pretty sure they're not currently.

**Comment by davidgs** [comment]
So there's no way to import a token, which means that not only did the data storage change mean all my old data is gone, but now all the configuration of every device/remote telegraf instance has to be updated with new token data. **Massive** amount of work.

**Comment by sanderson** [comment]
@davidgs The alpha/beta to GA upgrade guide covers how to move all that over:

https://docs.influxdata.com/influxdb/v2.0/upgrade/v2-beta-to-v2/

**Comment by davidgs** [comment]
Yeah, I've tried that doc. Doesn't actually work. :-(

**Comment by sanderson** [comment]
@davidgs Where are you running into issues?

**Comment by mhall119** [comment]
Upgrading from a pre-RC 2.0 to a post-RC 2.0 is a separate issue from this. 

Can this one be closed or does the doc still need to be changed for clarity?

**Comment by kelseiv** [comment]
token import not supported in ui - closing this issue - if migration doc has also been updated
