### ISSUE TITLE
DBRP: Replace raw API calls with CLI-based examples 

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1851]
_Describe the issue here._
Now that the CLI has been enhanced to support management of the DBRP mappings, I'd suggest we relegate the API calls to the reference guide.

Drive all examples through the DBRP CLI commands.

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/#map-unmapped-buckets

https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/dbrp/
We should reference the CLI commands from this page as well ^

##### What products and version are you using?
2.0.2 OSS

**Comment by pierwill** [comment]
I'll take a crack at this one: https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/#view-all-dbrp-mappings.

**Comment by timhallinflux** [comment]
The API-based examples are simply wrong.  They contain parameters which do not function and are causing issues with end users.  We need to urgently address this.

See: https://github.com/influxdata/influxdb/issues/20134
