### ISSUE TITLE
Document external Telegraf plugins

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#1863]
Using the `execd` plugin(s), you can use "external" Telegraf plugins. Document exists in the Telegraf repo, but we need to document how to use these plugins in the docs.

##### Relevant URLs
- List of external plugins: https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md
- What are external plugins: https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md
- How to write your own (including using the Go shim): https://github.com/influxdata/telegraf/tree/master/plugins/common/shim#telegraf-execd-go-shim

Topics we need to cover: 
 - What is an external plugin? Where can I find them?
 - How can it be used with the execd?
 - How can I write my own external plugin?
   - Using the Go Shim

**Comment by timhallinflux** [comment]
This should also be in the concepts section of the Telegraf docs.  There is no conversation about this at all in our current doc set.

**Comment by sjwang90** [comment]
Just adding some things:

The two main ideas around this would be 1) how to write my own external plugin 2) how to run external plugins with `execd`. Have both of these ideas on a main concept page of this would be very useful. 

--

All contributed plugins should have their own configuration and installation steps that would include (sorta what's mentioned in here: https://github.com/influxdata/telegraf/tree/master/plugins/common/shim#steps-to-build-and-run-your-plugin)
1. cloning the external plugin repo 
2. building the binary 
3. how to use the external plugin with Telegraf by adding `execd` to telegraf.conf
```toml
[[inputs.execd]]
  command = ["/path/to/rand", "-config", "/path/to/plugin.conf"]
  signal = "none
```
