### ISSUE TITLE
Dead Link: InfluxDB Configuration Doc Link on Docker Hub 

### ISSUE THREAD

**Issue by jehanalvani** [influxdata/docs-v2#1866]
On the [InfluxDB Docker Hub Page](https://hub.docker.com/_/influxdb), at the bottom of the "Configuration" section, the link in this text is dead. 

> Examples:
> 
> ```
> INFLUXDB_REPORTING_DISABLED=true
> INFLUXDB_META_DIR=/path/to/metadir
> INFLUXDB_DATA_QUERY_LOG_ENABLED=false
> ```
>
> Find more about configuring InfluxDB [here](https://docs.influxdata.com/influxdb/latest/introduction/installation/).

##### Relevant URLs
- https://docs.influxdata.com/influxdb/latest/introduction/installation/

##### What products and version are you using?

Appears to be InfluxDB 2.0 documentation.

**Comment by pierwill** [comment]
@influxdata/docs-team Looks like we might want to consider submitting a PR at https://github.com/docker-library/docs/tree/master/influxdb.

**Comment by kelseiv** [comment]
Thank you, @jehanalvani @pierwill this page has been updated
