### ISSUE TITLE
series do not contain fields

### ISSUE THREAD

**Issue by Normay22** [influxdata/docs-v2#1877]
_Describe the issue here._

##### Relevant URLs
- _Provide relevant URLs_

##### What products and version are you using?

![image](https://user-images.githubusercontent.com/39002833/99943719-b341f080-2dac-11eb-82fc-432024640fba.png)

**Comment by Normay22** [comment]
v1.7

**Comment by sanderson** [comment]
@Normay22 A series definition does include the field key, but not the field value. When stored in the storage engine, you essentially have a series file defined by a series key. The series key is the measurement, tag set, and field key. For example:

##### Example series key
```
mem, host=host1, user=user1, used_percent
```

The series file contains the timestamps and field values for that specific series:

##### Example series file
```
00000000001 50.0
00000000002 51.3
00000000003 49.2
00000000004 48.1
```

Jacob Marble, one of InfluxData's storage engineers, provides an in-depth walkthrough of the TSM storage engine here: https://www.youtube.com/watch?v=8dOZGnSwKmo&ab_channel=InfluxData
