### ISSUE TITLE
Link on the Time-series-platform page for InfluxDb is broken

### ISSUE THREAD

**Issue by shravan4000** [influxdata/docs-v2#1878]
_The Getting Started link for InlfuxDb under "Components of the TICK Stack" section on page  https://www.influxdata.com/time-series-platform/ is broken._

##### Relevant URLs
- _https://docs.influxdata.com/influxdb/v2.0/introduction/getting-started/

##### What products and version are you using?

InfluxDB 2.0
Telegraf
Chronograf
Kapacitor

**Comment by sanderson** [comment]
Thanks @shravan4000. A fix has been merged into master and will shortly be live.
