### ISSUE TITLE
HTTP input plugin with Citi Bike issue

### ISSUE THREAD

**Issue by Zaf97** [influxdata/docs-v2#1879]
Url: https://feeds.citibikenyc.com/stations/stations.json is not working any more. Also there is no json structure sample. In result the example is hard to be figured out.

**Comment by kelseiv** [comment]
related: https://github.com/influxdata/docs-v2/issues/2078

**Comment by noramullen1** [comment]
Closed by https://github.com/influxdata/docs-v2/pull/3640
