### ISSUE TITLE
write command documentation doesn't describe how it maps CSV to line-protocol

### ISSUE THREAD

**Issue by rogpeppe** [influxdata/docs-v2#1892]
The documentation for the `influx write` command says that it can read CSV
data, but doesn't describe how it maps that data into line-protocol to upload.
How does it decide which field is the measurement name, for example?

The overall page could use more of a high level explanation of what the command does too,
even if it's just "The write command uploads the data specified in the `--file` flag value file
into InfluxDB".

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/write/

**Comment by sanderson** [comment]
@rogpeppe The bulk of those details are covered in https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/csv/. I'll make sure to add that page as a related page on the `influx write` command doc.

**Comment by rogpeppe** [comment]
One other thing, while I'm here: from looking at the code, it seems like you can pass multiple instances of the `--file` flag to get it to read multiple files, but that's not mentioned in the docs.

TBH, it would be more intuitive if it took files as arguments, but that would be a more significant change.

**Comment by sanderson** [comment]
I'll add that as well. That is demonstrated here: https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/csv/#use-files-to-inject-headers

**Comment by rogpeppe** [comment]
Currently the docs are spread between three pages:

https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/write/
https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/
https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/csv/
 
It would perhaps be nice to consolidate a little. The last page seems like it could be more
of a tutorial, with the definitive reference split between cli/influx/write (the definitive reference
for the `write` command) and `syntax/annotated-csv` (the definitive reference for the
annotated CSV format).

**Comment by sanderson** [comment]
@rogpeppe Thanks for the feedback. The documentation is split into two main doc types: task-based and reference. Looking at the left navigation menu, docs under the "Reference" section are definitive reference docs. Docs above that are task-based (how-to's).

##### Task-based
- https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/csv/

##### Reference
- https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/write/
- https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/

Annotated CSV is not unique to writing data. It's the CSV format used by Flux as well, both for ingesting CSV data, but also raw query output. That's why it's structured as a standalone document.

**Comment by rogpeppe** [comment]
I'd hope that the reference documentation would include a full reference description of the command, and that the task-based documentation could be used as an optional adjunct to that, for further discussion and illumination.

That doesn't appear to be the case here - the task-based doc contains information that's not available from the reference docs.

**Comment by sanderson** [comment]
While the `influx write` command doesn't explicitly explain how annotated CSV is parsed into line-protocol, I did add multiple links to all of the associated reference documentation (line protocol, annotated CSV, and extended annotated CSV). Closing this issue for now.

**Comment by rogpeppe** [comment]
Thanks for adding those links. The "extended CSV" one in particular is exactly what I was looking for.

Am I right in thinking that the CSV format _must_ be extended CSV because otherwise the `write`
command won't know how to map the CSV into line-protocol format?

The `write` docs say:

> Write data using line protocol, annotated CSV, or extended annotated CSV.

which seems to indicate that non-extended annotated CSV is acceptable, but from a quick experiment, it seems that it's not (I get a `Failed to write data: line 5: no measurement column found` error).

I'd suggest that the documentation be amended to say that only line-protocol or extended annotated CSV
are acceptable (or else indicate how to update non-extended annotated CSV if that's not the case).

**Comment by sanderson** [comment]
@rogpeppe You can use regular annotated CSV, but it must have all the annotation rows and columns required to write to InfluxDB (`_measurement`, `_field`, and `_value). If you take the raw annotated CSV returned by a Flux query, you can write that back to InfluxDB.

I've added the following note to the `influx write` doc:

>#### Required columns
>To write data to InfluxDB, you must provide a **measurement**, **field**, and **value** for each row.
>
>##### Annotated CSV
>In **annotated CSV**, these are represented by the `_measurement`, `_field`, and
>`_value` columns and their types are determined by CSV annotations.
>To successfully write annotated CSV to InfluxDB, include all
>[annotation rows](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/#annotations).
>
>##### Extended annotated CSV
>In **extended annotated CSV**, these columns and types are determined by
>[CSV annotations](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/extended/#csv-annotations).

**Comment by rogpeppe** [comment]
Thanks for that further explanation. I was still a little confused for a moment though, until I thought a bit harder about it.
Maybe an example of using the non-extended CSV as input might be good, as it's less documented than the extended CSV?

**Comment by sanderson** [comment]
https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/write/#write-annotated-csv-data-via-stdin
