### ISSUE TITLE
Group geo-temporal data: Wish for sample-output

### ISSUE THREAD

**Issue by wetterfrosch** [influxdata/docs-v2#1898]
I'd like to see some sample output of the geo-data-functions, in particular for `groupByArea()` I wonder if the result contains a distance so one could use this function for finding a nearest-neighbor.

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/query-data/flux/geo/group-geo-data/#group-data-by-area

##### What products and version are you using?
An older version of InfluxDB and I wonder if switching to a version including the geo-package would help :) Thanks!

**Comment by sanderson** [comment]
@wetterfrosch This won't include a distance. `groupByArea()` adds the `s2_cell_id` column to the group key to group data by s2 cell IDs. However you could use [`geo.ST_Distance()`](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/experimental/geo/st_distance/`) to calculate the distance between a fixed point and all points in each table returned by the query.

For example, if you have a specific geographic point and you want to find the nearest neighbor:

```js
import "experimental/geo"

fixedLocation = {lat: 40.7, lon: -73.3}

from(bucket: "example-geo-bucket")
  |> range(start: -1d)
  |> filter(fn: (r) => r._measurement == "example-m")
  |> map(fn: (r) => ({ r with _value: geo.ST_Distance(region: {lat: r.lat, lon: r.lon}, geometry: fixedLocation )}))
  |> min()
```

I'll add this example to the `geo.ST_Distance()` documentation.
