### ISSUE TITLE
Missing image comparing-two-measurements.png

### ISSUE THREAD

**Issue by Zurlys** [influxdata/docs-v2#1912]
https://docs.influxdata.com/img/kapacitor/comparing-two-measurements.png is missing. 

##### Relevant URLs
- https://docs.influxdata.com/kapacitor/v1.5/guides/two-measurement-alert/
- https://docs.influxdata.com/img/kapacitor/comparing-two-measurements.png

**Comment by sanderson** [comment]
Thanks @Zurlys. Just deployed a fix for all the Kapacitor images.
