### ISSUE TITLE
InfluxDB Cloud -- Data Durability Guarantees (aka backup procedures).

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1915]
_Describe the issue here._

There are questions about the service which are related to our data durability within Cloud.
What our recovery point objectives are.

Occasionally, this gets asked like this, "What is your back up strategy in Cloud?"
This is very different from "how can I receive a backup of my data from Cloud?"

There are other requests like this: overall SLA, disaster recovery (loss of an AZ)...
So, we should think about how to capture these kinds of operational cloud characteristics.

### Data Durability within InfluxDB Cloud
All inbound writes to InfluxDB Cloud lands in a durable message queue.
That data is archived to an Object Storage location as Line Protocol -- this is known as an out-of-band-backup.
That data is also written to the live storage service, replicated twice across two geographic locations, and made available for use by the running service.

The underlying storage engine continues to process and compress the data over time, known as compaction, and once the compaction cycle completes these compressed files are also uploaded to an Object Storage location.

As a result, InfluxDB Cloud has two "backup" copies of data. 
1) all Line Protocol within an Object Storage location with minimal code between the ingest and the backup (minimizes potential data loss due to defects introduced within the broader service). 
2) all compressed data in the file format used by InfluxDB for query, tasks, etc.

The durability of the message queue is currently 72 hours, implying that we can sustain a failure of our underlying storage tier and/or Object Storage services for up to 72 hours.

#### Recovery
Recovery then is from Object Storage (historic based on the standard file format used by the service) and via the message queue (Line Protocol which is based on the inbound stream and most current arriving data).

The Recovery Point Objective (RPO) is any accepted write.
However, the Recovery Time Objective (RTO) is harder to definitively predict as the various potential failure modes can really vary. While many of the most common failure modes can be resolved within minutes or hours, under a more catastrophic or extreme failure mode it may take longer. For example, if we need to rebuild everything from the Line Protocol backup, it could take 24 hours or longer.

#### Verification 
InfluxDB Cloud has two services running 24x7 for data verification. There is an underlying entropy-detection service which is responsible for ensuring that the replicated data is consistent.  There is also a backup verification service which validates .....and ensures that the underlying backups can be read?  @8none1  <<--- can you review and comment here?

**Comment by timhallinflux** [comment]
> _Describe the issue here._
> 
> There are questions about the service which are related to our data durability within Cloud.
> What our recovery point objectives are.
> 
> Occasionally, this gets asked like this, "What is your back up strategy in Cloud?"
> This is very different from "how can I receive a backup of my data from Cloud?"
> 
> There are other requests like this: overall SLA, disaster recovery (loss of an AZ)...
> So, we should think about how to capture these kinds of operational cloud characteristics.
> 
> ### Data Durability within InfluxDB Cloud
> All inbound writes to InfluxDB Cloud lands in a durable message queue.
> That data is archived to an Object Storage location as Line Protocol -- this is known as an out-of-band-backup.
> That data is also written to the live storage service, replicated twice across two geographic locations, and made available for use by the running service.
> 
> The underlying storage engine continues to process and compress the data over time, known as compaction, and once the compaction cycle completes these compressed files are also uploaded to an Object Storage location.
> 
> As a result, InfluxDB Cloud has two "backup" copies of data.
> 
> 1. all Line Protocol within an Object Storage location with minimal code between the ingest and the backup (minimizes potential data loss due to defects introduced within the broader service).
> 2. all compressed data in the file format used by InfluxDB for query, tasks, etc.
> 
> The durability of the message queue is currently 72 hours, implying that we can sustain a failure of our underlying storage tier and/or Object Storage services for up to 72 hours.
> 
> #### Recovery
> Recovery then is from Object Storage (historic based on the standard file format used by the service) and via the message queue (Line Protocol which is based on the inbound stream and most current arriving data).
> 
> The Recovery Point Objective (RPO) is any accepted write.
> However, the Recovery Time Objective (RTO) is harder to definitively predict as the various potential failure modes can really vary. .. if we have to rebuild everything from the LP archive, it could be 24 hours.
> 
> #### Verification
> InfluxDB Cloud has two services running 24x7 for data verification. There is an underlying entropy-detection service which is responsible for ensuring that the replicated data is consistent. There is also a backup verification service which validates .....and ensures that the underlying backups can be read? @8none1 <<--- can you review and comment here?

**Comment by 8none1** [comment]
> #### Verification
> InfluxDB Cloud has two services running 24x7 for data verification. There is an underlying entropy-detection service which is responsible for ensuring that the replicated data is consistent. There is also a backup verification service which validates .....and ensures that the underlying backups can be read? @8none1 <<--- can you review and comment here?

The entropy-detection service is not live across the production cluster yet.  It will be soon, but isn't right now.  (Likely a week or two)

The verification service doesn't actually verify the backups, it verifies that the data that's being written to InfluxDB can be read back correctly. It does this by writing the same values to a Postgres database and Influx, and then reading back and comparing the two results.  This ensures that the data being written in to Influx isn't getting mangled in some way.  That does run 24 x 7 x 365.

We are in the process of rewriting the out-of-band backup system at the moment.  It is now live across the prod clusters but running in parallel with the old system.  We will do some verification of the backups before we cut over.
