### ISSUE TITLE
Subcommand table in "influxd inspect" reference docs shows attempted HTML comment-out of missing commands

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#1922]
See this screenshot:
![Screen Shot 2020-12-02 at 9 08 46 AM](https://user-images.githubusercontent.com/2755881/100883198-12bf9080-347e-11eb-826c-3adbac3ba2ae.png)

The rows with `<!--` in the 1st column are the subcommands that haven't been ported to V2 yet. It looks to me like somebody tried to comment-out the rows as part of fixing #1812, but the comments aren't parsing properly.

##### Relevant URLs
- Reference docs: https://docs.influxdata.com/influxdb/v2.0/reference/cli/influxd/inspect/

**Comment by pierwill** [comment]
Thanks, @danxmoran!
