### ISSUE TITLE
Create docs for Tick Configuration

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/docs-v2#1924]
The UI has a new feature in the view options that allows the user to specify how the axes should mark the ticks on each axis. The user can select in any combination: total ticks, tick start, tick step.

##### Relevant URLs
https://github.com/influxdata/docs-v2/issues/1825

##### What products and version are you using?
Cloud v2 UI

**Comment by kristinarobinson** [comment]
FYI: This feature is behind a feature flag.  It is not yet available in production.  It is available in Tools.

**Comment by sjwang90** [comment]
Feature flag: `influx.set("axisTicksGenerator", true)`
