### ISSUE TITLE
Create docs for legendOrientation and legendThreshold

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/docs-v2#1933]
Adds legend orientation options for threshold and opacity. Threshold is the highest column count at which the legend will stay in a horizontal flow (current behavior). Column counts above the threshold will cause the legend to flow vertically. Opacity is the transparency of the entire legend, allowing the user to see both the legend and the graph underneath.

##### Relevant URLs
https://github.com/influxdata/ui/pull/95

##### What products and version are you using?
Cloud v2 UI

This feature is behind a feature flag and will not be available in production until the documentation is completed.  This feature is available in Tools.

**Comment by sjwang90** [comment]
Feature flag: `influx.set("legendOrientation", true)`

**Comment by timhallinflux** [comment]
@kelseiv -- can you please review?  I believe this is live and has docs which are on a per dashboard cell type basis.
Example: 
https://docs.influxdata.com/influxdb/cloud/visualize-data/visualization-types/graph/#legend

**Comment by noramullen1** [comment]
Addressed by #2798
