### ISSUE TITLE
[2.0] working with Docker images

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1947]
Folks picking up the Docker images are looking for additional guidance about how to consume the image and effectively work with it.

1) volume mounts -- folks want to persist their data outside the docker image.  Looks like everything resides within `/root/.influxdbv2`.  
2) creating a config file -- assuming the volume mounts are made, should they be able to drop a config.toml into the same directory and have the influxd process pick that up and read it.  Let's show an example.

**Comment by timhallinflux** [comment]
Another request for help outlined here: https://www.orpiske.net/2020/12/using-go-and-influxdb-to-find-the-best-time-to-go-the-gym/

**Comment by danxmoran** [comment]
@kelseiv I took a 1st stab at docs for the new DockerHub build, it's in review at docker-library/docs#1871

**Comment by pierwill** [comment]
Checking in on this.

Wow, @danxmoran! A lot of great info in that PR! I've got the basics working with the `-v` flag in Docker. First thing I'll do to address @timhallinflux's item 1 above is to add a minimal example of persisting data outside the Docker contain in the Docker section of https://docs.influxdata.com/influxdb/v2.0/get-started/.

Next, we can make sure we have easy access to instructions for picking up a config file from the mounted volume. That might be a minimal example plus a link to `docker-library`.
