### ISSUE TITLE
Improvements on documentation discussing core concepts and functions

### ISSUE THREAD

**Issue by mkarlesky** [influxdata/docs-v2#1958]
### Issue
My team is beginning to get down into the nitty-gritty details of Flux for creating queries. It's been a bit of a bumpy learning journey. A significant contributing factor is aspects of the current documentation. That said, I suspect the documentation may reflect a certain lack of clarity that yet exists in Flux's development as a language.

To be clear, the documentation does largely communicate concepts and functions correctly. But, we've found a solid understanding of Flux and its core concepts is first necessary in order to grasp a number of subtleties within the documentation.

**Disclaimer:** Perhaps it is we who do not fully grasp Flux definitions and concepts. We are still learning. Everything that follows has been written for clarity and with an amount of certainty that may well be misplaced. By all means, please educate us if we are simply missing the intent of the Flux developers and the documentation authors.

### Discussion
I've collected examples and loosely categorized them in the URL lists below.

In the category of what I'm calling _Conceptual Documentation_, a fuller and clearer distinction of streams and tables would be especially helpful. A _stream_ as a collection of tables is a wonderfully effective term, but the word _stream_ is used far too infrequently. It's a core concept incredibly helpful to understanding Flux and to distinguishing the operations of the various functions within the language. Throughout the documentation the singular _table_ or the plural _tables_ is often used when _stream_ or _stream of tables_ is more appropriate.

For instance, we were greatly confused by the operation of _Selectors_ in trying to extract scalar values until the documentation for _Stream and Table Functions_ clued us in. While selectors actually operate on streams, the documentation for selectors only speaks in terms of tables. This is confusing for a number of reasons but especially so given that other functions like `tableFind()` return a table.

The list of _Function Documentation_ below provides further examples of our confusion. As I've already noted, the documentation for these functions explains that they operate on tables when, more correctly, they operate on streams. Further, each of these functions listed below speaks of returning a record. This is misleading. While, yes, these functions do return singular records, those records are contained within tables of one row within a stream of one or more tables. Given that a record is a tuple primitive that a developer can create, this terminology is confusing.

Moreover, the documentation and Flux code examples available in the docs and more widely largely intermix use of the terms _record_ and _row_. As discussed in the preceding paragraph this can be unhelpful. Using the current terminology, a record can exist on its own or can be contained within a table. However, the means of accessing the contents of a record in those contexts is quite different.

### Proposal
Fundamentally, I'm unsure if the feedback I'm providing here regards solely the documentation or core concepts of the Flux language itself. I see a relevant Github issue dealing with uncertainty on terminology and construction in the Flux project itself: [Specify the primitive types that make up stream and table types #463](https://github.com/influxdata/flux/issues/463). In an attempt to be helpful I'm linking this present issue here in the discussion of that issue over there.

I'd like to propose the following refinements for terminology in Flux documentation (and possibly even Flux itself?):
* A **record** is a tuple of named values and is represented using a record type.
* A **table** contains one or more **rows** each containing a **record**.
* A **stream** is a collection of one or more **tables**.

Some notes on using the above:
- **stream** should be used whenever one or more **tables** exist in a collection. The plural _tables_ should be reserved for discussing the contents of streams or multiple individual tables outside of a collection (e.g. the results of two independent `tableFind()` function calls).
- Whenever discussing operations wherein the results remain as tables, the term **rows** should be used in favor of **records** when speaking of horizontal table entries. The term **record** should be reserved for discussing the primitive type or the content of a **row**.

### Relevant URLs
* _Conceptual Documentation_
  * [Get Started with Flux](https://docs.influxdata.com/influxdb/v2.0/query-data/get-started/)
  * [Flux Data Model](https://docs.influxdata.com/influxdb/v2.0/reference/flux/language/data-model/)
  * [Flux stream and table functions](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/stream-table/)
  * [Flux built-in selector functions](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/selectors/)

* _Function Documentation_
  * [Selector: first() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/selectors/first/)
  * [Selector: last() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/selectors/last/)
  * [Selector: max() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/selectors/max/)
  * [Selector: min() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/selectors/min/)

### What products and version are you using?
1. InfluxCloud v2
1. InfluxDB 2.0.2
1. Flux (REPL) 0.98.0

**Comment by sanderson** [comment]
Thank you very much for the feedback @mkarlesky. I'm actually in the process of revamping the Flux documentation and this definitely helps. I agree with everything you've pointed out. The current Flux documentation as it stands suffers from an additive process we've used as the language has matured. Much of the terminology and core concepts were still being fleshed out as the current content was written. It's not a small project, so it will take time, but thank you again for this feedback.

**Comment by mkarlesky** [comment]
@sanderson I've been coming to understand Flux a bit better. Out of a Slack community discussion, I think I've refined my previous proposed definitions a bit:

- A **record** is a tuple of named values and is represented using a record type. A record can exist independent of a container.
- A **table** is a container of one or more **rows** wherein each row is a container for a single record.
- A **series** is a container defined by a series key as a result of grouping. A series contains one or more tables.
- A **stream** is a container of one or more series. By extension, a stream is a container of one or more tables and is also a container of one or more records.

Perhaps this is useful to you.

**Comment by sanderson** [comment]
Thanks @mkarlesky. I'll definitely be incorporating this. A few corrections on your suggestions:

The concept of a "series" doesn't exist inside of Flux. This concept belongs to InfluxDB, or from the perspective Flux, the underlying data source. The `from()` function returns data grouped by series, but this is unique to InfluxDB. In InfluxDB, a series is defined by a common measurement, tag set, and field key. So the **group key** that InfluxDB returns just happens to also be an InfluxDB series key. Other data sources can return data grouped differently. I'd update the following:

- A **record** is a tuple of named values and is represented using a record type. A record can exist independent of a container.
- A **table** is a container of one or more rows where each row is a container for a single record. Tables are defined by a **group key**, a list of columns for which all records in the table have the same values.
- A **stream of tables** is a container of one or more tables.

**Comment by mkarlesky** [comment]
@sanderson Thank you for that helpful clarification.

> Tables are defined by a group key, a list of columns for which all records in the table have the same values.

I think there's a slight problem with this statement. Or, rather, I would suggest a bit of clarification. I've noticed in the various forums a common assumption that a single table is attached to a group key. By and large, I believe this is typically true in InfluxDB data sets. However, it's not the only option. Using a Flux query against an InfluxDB bucket, I can produce a stream containing a group key with multiple tables organized beneath that group key. The wording above (I recognize it from the existing Flux documentation) _could_ be read to infer that a group key yields a single table.

I would suggest this wording:

> Tables are defined by a group key that contains a list of columns for which all records in a table have the same values. A group key may yield one or more tables.

 ---

Let me also share a particularly significant _ah ha_ moment I had recently that is directly in line with your clarification of Flux vs. InfluxDB and group keys vs. series.

I only just came to understand that fields and tags are InfluxDB concepts and not Flux concepts. I now understand that Flux understands only columns when field and tag data is queried from InfluxDB.

That Flux has a data model distinct from InfluxDB was not entirely clear and plain to me until very, very recently. For those of us learning Flux, anything that can be done to make this distinction crystal clear in the documentation, guides, and blog posts would be incredibly helpful. I'm sure the core concepts of Flux are largely properly addressed; it's this clear distinction between the data models of Flux and InfluxDB (and any other database Flux works with) that was missing for me. If this was emphasized and made very clear I think my Flux learning curve would have been much less steep.

 ---

Thank you again for the dialogue on all this. It's very helpful to me. It's almost like thinking out loud. I hope it's useful to you and your colleagues as you wrangle the language and documentation around Flux.

**Comment by jsternberg** [comment]
> I think there's a slight problem with this statement. Or, rather, I would suggest a bit of clarification. I've noticed in the various forums a common assumption that a single table is attached to a group key. By and large, I believe this is typically true in InfluxDB data sets. However, it's not the only option. Using a Flux query against an InfluxDB bucket, I can produce a stream containing a group key with multiple tables organized beneath that group key. The wording above (I recognize it from the existing Flux documentation) could be read to infer that a group key yields a single table.

Can you expand on what you mean by this? To my knowledge, there is only one table per group key even in InfluxDB datasets. Flux transformations are written so they process parts of that table so the entire table isn't in memory at the same time, but this is mostly an implementation detail and isn't part of the data model. I am wondering why you think that a group key can contain multiple tables as I think it will reveal a miscommunication in the core concepts and hopefully reveal a way that we can communicate that better.

**Comment by sanderson** [comment]
> I think there's a slight problem with this statement. Or, rather, I would suggest a bit of clarification. I've noticed in the various forums a common assumption that a single table is attached to a group key. By and large, I believe this is typically true in InfluxDB data sets. However, it's not the only option. Using a Flux query against an InfluxDB bucket, I can produce a stream containing a group key with multiple tables organized beneath that group key. The wording above (I recognize it from the existing Flux documentation) could be read to infer that a group key yields a single table.

Yeah, I've found it hard to accurately explain how group keys work. Each individual tables have a group key, but I think where the misunderstanding happens is in how group keys are structured. Essential, a group key containing only column labels is applied to a stream of tables. For example: `_measurement, _field, tag1, tag2`,  but for each of the tables in the stream of tables, the _actual_ group key a collection of key-value pairs. For example, the following group keys represent 3 separate tables in a stream of tables:

```
_measurement="m", _field="foo", tag1="foo", tag2="bar"
_measurement="m", _field="foo", tag1="foo", tag2="baz"
_measurement="m", _field="foo", tag1="foo", tag2="quz"
```

> That Flux has a data model distinct from InfluxDB was not entirely clear and plain to me until very, very recently. For those of us learning Flux, anything that can be done to make this distinction crystal clear in the documentation, guides, and blog posts would be incredibly helpful. I'm sure the core concepts of Flux are largely properly addressed; it's this clear distinction between the data models of Flux and InfluxDB (and any other database Flux works with) that was missing for me. If this was emphasized and made very clear I think my Flux learning curve would have been much less steep.

Great point! Thank you!

**Comment by jsternberg** [comment]
@sanderson I like your explanation but I would like to bounce a few suggestions and reasons why. I'm curious to hear both of your opinions on if this helps.

> A **record** is a tuple of named values and is represented using a record type. A record can exist independent of a container.

This is a good way to explain it, but the underlying type signature for a "record" is that it's an anonymous struct. If you were to translate flux code to C code, you would use a struct. Tuple is also a good word. I wonder if struct would end up being more clear though?

> A table is a container of one or more rows where each row is a container for a single record. Tables are defined by a group key, a list of columns for which all records in the table have the same values.

I would nix the "one or more". Tables can have zero rows.

I wonder if it would be good to organize this concept around columns instead. The flux engine is organized so a table is a collection of columns. The functions that operate on rows will iterate over the columns and read them into a struct as if you were doing this in C:

```
struct vector {
    float64 x;
    float64 y;
};

struct table {
   float64[] x;
   float64[] y;
   int len;
};

struct vector v;
for (int i = 0; i < t.len; i++) {
    v.x = t.x[i]
    v.y = t.y[i]
}
```

I don't know if using columns instead of rows would be better for understanding or if the two are equivalent. But, internally, flux has no concept of a list or collection of rows. It has a collection of columns that get read as a row for certain transformations.

> A stream of tables is a container of one or more tables.

Nix the "one or more" portion again. A stream can have no tables. I would be very open to a new name for this as I find it a common point of confusion since tables themselves are also streamed. Maybe a collection of tables or a dinner party 😛 ?

**Comment by sanderson** [comment]
> This is a good way to explain it, but the underlying type signature for a "record" is that it's an anonymous struct. If you were to translate flux code to C code, you would use a struct. Tuple is also a good word. I wonder if struct would end up being more clear though?

I'm fine with either. We'll have to define them both for users less-familiar with programming languages and concepts.

> I wonder if it would be good to organize this concept around columns instead. The flux engine is organized so a table is a collection of columns. The functions that operate on rows will iterate over the columns and read them into a struct as if you were doing this in C...
> I don't know if using columns instead of rows would be better for understanding or if the two are equivalent. But, internally, flux has no concept of a list or collection of rows. It has a collection of columns that get read as a row for certain transformations.

I like this shift. I think this helps to clarify how group keys and transformations work.

> Nix the "one or more" portion again. A stream can have no tables. I would be very open to a new name for this as I find it a common point of confusion since tables themselves are also streamed. Maybe a collection of tables or a dinner party 😛 ?

- I'd be all for moving away from "stream of tables" to "collection of ..." or "set of tables."

**Comment by mkarlesky** [comment]
@jsternberg I'm still learning here so please correct me if the example I'm sharing here misconstrues the concepts.

<img width="588" alt="InfluxDB Tables B" src="https://user-images.githubusercontent.com/1048550/107404311-29184700-6ad4-11eb-9b25-582e287d7e4c.png">

I interpret the content of the screenshot I inserted as showing three tables (indices 0, 1 & 2) organized beneath a single group key. I understand each of those three tables to contain two rows each.

From my (albeit limited) understanding, I read that screenshot like this:

- 1 stream containing 3 tables and 6 records
- That same single stream containing a single group key with those 3 tables organized beneath it
- Each of three tables containing 2 rows which means, in turn, 2 records

Am I misunderstanding how tables beneath a group key and within a stream are demarcated?

**Comment by mkarlesky** [comment]
@jsternberg @sanderson As I mentioned I just recently came to understand that Flux is built around the idea of a columnar abstraction. It seems wise to orient Flux concepts and education around columns. So many of the Flux calls contain a `columns:` parameter, after all. It makes sense to me that the data model discussion for Flux should emphasize and orient itself around columns.

That said, I think it also makes a lot of sense to emphasize the difference between columns and rows—particularly in the context of when to think about them and how to think about them. Tables are so core to Flux that I see a clear need for some kind of thinking toolbox for approaching columns and rows. I assume the appropriate context is how columns relate to grouping and how rows relate to grouping.

**Comment by sanderson** [comment]
I almost feel like we need to introduce the concept of a "stream ..." or "collection key" along with a "group key." The stream/collection key would just be a list of columns by which all tables are grouped. The group key includes each key in the stream/collection key, but with a value. For example:

```javascript
// Stream/collection key
[_start, _stop, _measurement, _field, tag1, tag2]

// Group keys for each table
(_start=2021-01-01T00:00:00Z, _stop=2021-02-01T00:00:00Z, _measurement="m", _field="total", tag1="foo", tag2="bar")
(_start=2021-01-01T00:00:00Z, _stop=2021-02-01T00:00:00Z, _measurement="m", _field="total", tag1="foo", tag2="quz")
(_start=2021-01-01T00:00:00Z, _stop=2021-02-01T00:00:00Z, _measurement="m", _field="total", tag1="baz", tag2="quz")
```

**Comment by jsternberg** [comment]
I need to get better at managing my notifications... I just saw the additional messages on this issue just now.

> I interpret the content of the screenshot I inserted as showing three tables (indices 0, 1 & 2) organized beneath a single group key. When I read these results, I understand each of those three tables to contain two rows each.

This is a misinterpretation. There are three group keys in this example. Each table has their own group key which signals the common keys _and_ values for the table. The CSV encoding is just optimized so it won't repeat the header for each table if the column names don't change. This allows for a more efficient representation, but it seems to have caused some confusion in the concept.

> That said, I think it also makes a lot of sense to emphasize the difference between columns and rows—particularly in the context of when to think about them and how to think about them. Tables are so core to Flux that I see a clear need for some kind of thinking toolbox for approaching columns and rows. I assume the appropriate context is how columns relate to grouping and how rows relate to grouping.

This is an interesting observation and so I'm just going to try and brain dump to see if I can help advance this. I can see some functions are generally understood to be column based, such as the aggregation and selector functions, while some are more row based such as filter and map. While InfluxDB is a columnar store and Flux's data representation is columnar, we have generally observed that row-based thinking is generally how people understand transforming data.

To clarify, what I'm describing here is not how the engine handles the data, but a useful abstraction for thinking about it.

The way I would think about grouping is to consider the data model the same way the type system does. Treat the data as if it were one gigantic table and the data was organized (not sorted) into partitions by a set of common column values. Some partitions may not have values for some of the columns (these are nulls) and different partitions can have different types for the values contained in that column. Each transformation operates on the _partitions_, not the larger table. So you cannot operate on data from multiple partitions in a single transformation without regrouping the data so they are in the same partition. You can reorganize what data is in which partition by using functions like `group()` or `window()`. The `group()` function will redefine which columns define the partitions and `window()` will take the existing partitions and further divide them based on the time. The schema mutation functions, like `keep()` and `drop()`, will also change the partitioning _if_ you end up dropping a column associated with the grouping. Within a partition, a column can only have data of a single type. If you try and reorganize the partitions and it causes two partitions with different types for a column to try and join together, you will get an error.

**Comment by mkarlesky** [comment]
@jsternberg This is the first coherent set of abstractions and explanations that have clicked for me.

Let me speak to what is working for me in case it's useful toward further refinement on everything in this thread.

1. A compact CSV representation has indeed been a bit misleading for me. I'd ask that either table representations be more verbose to make clear the abstractions or that great care be given to documenting how to read CSV representation with regard to the relevant abstractions.
1. If the nomenclature of your most recent post here were to “stick” I'd love for some updated labels inside the CSV representation wherever appropriate.
1. You are correct that it has been much easier for me to think of manipulations as per row than per column. This may be a specific experience of anyone coming from InfluxDB 1 or a general experience of anyone new to columnar databases.
1. Though you didn't speak to it specifically in your most recent post this thread gets at a sorely needed distinction in explaining InfluxDB and Flux to new users; InfluxDB is a columnar database while Flux is a language able to manipulate tables. It took me a while to grasp that Flux was more than a functional language evolution. of InfluxQL. For me InfluxQL was tightly tied to the underlying database structure while Flux is free of such coupling.
1. I like the word “segment”—not so much because of the word itself but because it is removed from other words in use around Flux and InfluxDB to date. It's terse, free of any previous InfluxData baggage, and embodies appropriate meaning for the ideas you attached it to.
