### ISSUE TITLE
Annotations:  New feature for Cloud 2, simple point annotations

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/docs-v2#1972]
Releasing new feature for Cloud v2:
Ability to annotate an event in a line, band chart, or potentially XY scatter (still TBD) chart with a start date/time and description of event.  Tentative release date for mid-January 2021.

##### Relevant URLs
https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/giraffe/413
https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/20180

##### What products and version are you using?
Cloud v2 UI

**Comment by mnorriswalker** [comment]
Also we have a YouTube video which is currently private until the feature flag is removed publicly:
https://youtu.be/5NEplCesNAc

Can we add this in?
