### ISSUE TITLE
New Feature: Map Geo graph type

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/docs-v2#1973]
Release new graph type: geographic map (supported by MapBox API)
Tentative release date in mid-January 2021

##### Relevant URLs
https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/giraffe/416
https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/idpe/8888

##### What products and version are you using?
Cloud v2 UI

**Comment by timhallinflux** [comment]
Tools cluster has geo data that can be used to drive examples.  See `telemetry_curated` bucket and the `influxdb_info_geo` measurement.
