### ISSUE TITLE
Invalid example for monitor.notify

### ISSUE THREAD

**Issue by philomory** [influxdata/docs-v2#1974]
The example code for `monitor.notify()` is invalid for at least two reasons:
* First, the example shows a call to `slack.endpoint()` passing `name` and `channel` parameters, but the only parameters `slack.endpoint()` takes are `url` and `token`.
* Second, the example shows a call to `monitor.notify()` passing only an `endpoint` parameter, but, `monitor.notify()` _requires_ you pass an explicit `data` parameter. The documentation states that "InfluxDB populates notification data", but, it doesn't clarify what that actually _means_; it definitely _doesn't_ mean the parameter can be simply omitted.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/monitor/notify/
- https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/monitor/notify/

##### What products and version are you using?

InfluxDB Cloud 2.0

**Comment by sanderson** [comment]
Thanks @philomory. See #1977 for the proposed fixes.

**Comment by philomory** [comment]
Thanks @sanderson. I made a couple of comments on the PR, but even without those being addressed it's a big improvement.
