### ISSUE TITLE
slack.endpoint function documentation recommends using non-existent defaults

### ISSUE THREAD

**Issue by philomory** [influxdata/docs-v2#1976]
The documentation for the `slack.endpoint()` function explicitly recommends relying on the default value of `mapFn`:
>You should rarely need to override the default `mapFn` parameter. To see the default `mapFn` value or for insight into possible overrides, view the [`slack.endpoint()` source code](https://github.com/influxdata/flux/blob/master/stdlib/slack/slack.flux).

However, if you follow the link to actually _view_ the `slack.endpoint()` source code, you will observe that `mapFn` _has_ no default, and indeed, trying to call the function returned by `slack.endpoint()` without an explicitly value for `mapFn` results in the error, "missing required argument mapFn".

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/slack/endpoint/
https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/slack/endpoint/

##### What products and version are you using?
InfluxDB Cloud 2.0

**Comment by philomory** [comment]
It seems possible that the "default mapFn" is meant to be the `slack.message()` function, but, if that is the case, it should actually _be_ the default; that is, `slack.endpoint()` should return a function whose signature is `(mapFn=message) => ...`, not `(mapFn) => ...`.

**Comment by sanderson** [comment]
Thanks @philomory. See #1977 for the proposed fixes.

**Comment by philomory** [comment]
Thanks @sanderson. I made a couple of comments on the PR, but even without those being addressed it's a big improvement.
