### ISSUE TITLE
Download link for 2.0.3 gives 404 error

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#1988]
The link for ARM64 linux binaries (https://dl.influxdata.com/influxdb/releases/influxdb2_2.0.3_linux_arm64.tar.gz) gives a 404 error. The correct link is https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.3_linux_arm64.tar.gz.

**Comment by noramullen1** [comment]
Closing -- this is the portal downloads page, not the docs
