### ISSUE TITLE
macOS download link broken for OSS 2.x

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#1990]
On the "Get started with InfluxDB" page, the "InfluxDB v2.0 (macOS)" button navigates to an S3 404 page instead of launching a download.

The link is pointing at https://dl.influxdata.com/influxdb/releases/influxdb-2.0.3_darwin_amd64.tar.gz
The correct link is https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.3_darwin_amd64.tar.gz

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.0/get-started/
![Screen Shot 2020-12-15 at 12 19 44 PM](https://user-images.githubusercontent.com/2755881/102268233-e66d3080-3ecf-11eb-80b1-83f4514455d2.png)

**Comment by sanderson** [comment]
Fixed in 1b514943ce9473e5f7b3420feb17a425acddd4dd
