### ISSUE TITLE
macOS download button broken

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1996]
To replicate:

1. Go to https://docs.influxdata.com/influxdb/v2.0/get-started/
2. Click on the blue download button:

![image](https://user-images.githubusercontent.com/20701/102434157-0fbdb780-3fc9-11eb-83ed-bc7ec22e6398.png)

3. You get sent to this error page (I was expecting a download): https://dl.influxdata.com/influxdb/releases/influxdb-2.0.3_darwin_amd64.tar.gz

![image](https://user-images.githubusercontent.com/20701/102434202-23691e00-3fc9-11eb-9b3e-f2cc5a9155a3.png)

What should happen is that this URL should load: 
https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.3_darwin_amd64.tar.gz

The problem: the current URL is missing a "2" after "influxdb".

**Comment by noramullen1** [comment]
Thanks Al -- just fixed this and verified it works.

**Comment by alsargent** [comment]
Shortest-lived issue ever! That was open all of 9 minutes, and during the evening to boot. Thanks.
