### ISSUE TITLE
can't import influxdata/influxdb/schema

### ISSUE THREAD

**Issue by mfdefs** [influxdata/docs-v2#2002]
_Describe the issue here._
run statement:
import "influxdata/influxdb/schema"
schema.measurements(bucket: "example-bucket")
error happen:
 error @1:1-1:36: invalid import path influxdata/influxdb/schema
##### Relevant URLs
- _Provide relevant URLs_

##### What products and version are you using?
Version 2.0.0 (50964d7)

**Comment by sanderson** [comment]
@mfdefs The `schema` package was introduced in Flux 0.88.0. I'm not sure which version of Flux is packaged with your build of InfluxDB, but you can check by running the following query in your data explorer:

```js
import "runtime"
import "experimental/array"

array.from(rows: [{_value: runtime.version()}])
```

If that's true, you can just use the `v1` package instead. The `schema` package is a port of the `v1` package.

```js
import "influxdata/influxdb/v1"
v1.measurements(bucket: "example-bucket")
```
