### ISSUE TITLE
Document the ability to upload CSV files to InfluxDB

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#2007]
PR: https://github.com/influxdata/ui/pull/421

I don't know exactly when this will land in Cloud or OSS, but we should prepare for it.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/write-data/developer-tools/csv/

**Comment by sjwang90** [comment]
I don't think we have docs on LP file upload either. A section addressing "File Upload" for both LP and CSV would be good. 

![image](https://user-images.githubusercontent.com/32681364/103826815-6fd5d580-502c-11eb-880f-ccc350ae8f1f.png)

**Comment by sanderson** [comment]
@sjwang90 Writing raw LP and LP from a file through the UI was documented at one point, but it appears to have been removed. We'll be sure to add this back in.

**Comment by sjwang90** [comment]
feature flag: `influx.set("csvUploader", true)`

**Comment by sjwang90** [comment]
The CSV and LP uploader were also added to the data sources page:
![image](https://user-images.githubusercontent.com/32681364/114471897-2efad900-9ba6-11eb-9b99-12ba436f4b0a.png)

**Comment by noramullen1** [comment]
Assigning to Michelle per conversation with Kelly
