### ISSUE TITLE
Option -d missing in docs for "influx auth create" command

### ISSUE THREAD

**Issue by sbollain** [influxdata/docs-v2#2014]
Option -d missing in docs for "influx auth create" command
It is documented when running:
$ influx auth create -h
-d, --description string         Token description

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/auth/create/#flags

##### What products and version are you using?
Influx CLI 2.0.3

**Comment by sanderson** [comment]
Thanks @sbollain. This will be resolved by #2001 which should merge later today.
