### ISSUE TITLE
wrong order of operation

### ISSUE THREAD

**Issue by cocampbe** [influxdata/docs-v2#2021]
You cannot do an ldap verify of your toml file before you restart influxdb-meta. The way the doc reads, you edit the conf files, test an auth via curl (is that supposed to be ldap? Because it is not configured yet). Create an ldap toml file, verify and push it, then restart services. You cannot verify it until  you restart At least the meta nodes. 

##### Relevant URLs
https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/ldap/

##### What products and version are you using?

influxdb enterprise 1.8.

**Comment by pierwill** [comment]
Thanks @cocampbe! Looks like the docs could be a bit more clear here.
