### ISSUE TITLE
OSS delete-with-predicate docs mention a feature that doesn't work

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#2025]
The docs say [here](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/delete-predicate/#delete-points-with-a-specific-field) that delete-with-predicate based on `_field` is valid. A user [reported](https://github.com/influxdata/influxdb/issues/20399) that using the field doesn't actually work.

##### What products and version are you using?
InfluxDB OSS v2.0.3

**Comment by kelseiv** [comment]
Thank you, @danxmoran, will hide this example until/if this functionality is implemented.
