### ISSUE TITLE
Inaccurate screenshot in Grafana doc page

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#2031]
On our page describing how to connect InfluxDB to Grafana:
https://docs.influxdata.com/influxdb/v2.0/tools/grafana/

... we have a screenshot that's not accurate:

![image](https://user-images.githubusercontent.com/20701/103721069-a3a7f100-4f81-11eb-95e0-0a97cec0593d.png)

The specific issues are towards the bottom:

- Database: listed as "mydb". This implies that the user should enter the bucket NAME. But what they actually need to do is enter the bucket ID, which will typically be a long hexadecimal string, e.g., ad1351bc3f. 
- User: not filled in. In InfluxDB Cloud, this will be an email (johndoe@acme.com); in InfluxDB OSS, it'll be a string (johndoe).
- Password: not filled in. When filled in, this will say "configured".

Also, I've found it very helpful to name my Grafana connections _InfluxDB-InfluxQL_ and _InfluxDB-Flux_ to keep things straight. It'd be good to do the same in our doc.

Putting all this together, here's what the configuration looks like in my local Grafana instance:

![image](https://user-images.githubusercontent.com/20701/103721436-7e67b280-4f82-11eb-96b8-5ece608dfee6.png)

Let me know if you'd like me to create a version of this with _johndoe@acme.com_ as the username, if that saves you a bit of time.

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/tools/grafana/ (click InfluxQL)

##### What products and version are you using?

My screenshot above is using Grafana 7.3.6.

**Comment by kelseiv** [comment]
Excellent detail. Thank you, @alsargent!... re johndoe version, yes please...that'd be much appreciated!

**Comment by sanderson** [comment]
@alsargent Once #2210 merges, you'll be able to add a query parameter to URLs to trigger tabs. In this first pass, you have to manually add the param, but I'm going to come back and make it add/update the param whenever you click a tab. So for example, if you want the OSS 2.0 "Get started" page to open with the Linux install instructions, the following link will do it (once the PR merges):

https://docs.influxdata.com/influxdb/v2.0/get-started/?t=Linux

You'll also be able to scroll to anchors in non-default tabs:

https://docs.influxdata.com/influxdb/v2.0/get-started/?t=Linux#place-the-executables-in-your-path

**Comment by sanderson** [comment]
Closed in #2210
