### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by cgfoed** [influxdata/docs-v2#2037]
"Related" section is broken.

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/transformations/keyvalues/
https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/keyvalues/

BTW: Finding this I was looking for a method to query with a filter like
**Give me _value of _field == A if _value < 20 of _field == B**
I've done it with a join but it's very inefficient and takes forever with big sets of data.

**Comment by sanderson** [comment]
Thanks for reporting this @cgfoed. I'm looking into fixing the related links.

In regards to the query you're after, you need to query both field A and B, and then pivot the results so a column for each field exists in each row. You can then use the kind of logic you're hoping to use:

```js
from(bucket: "example-bucket")
  |> range(start: -1d)
  |> filter(fn: (r) => r._field == "A" or r._field == "B")
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> filter(fn: (r) => r.B < 20)
  |> rename(columns: {A: "_value"})
```
