### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by 780Farva** [influxdata/docs-v2#2052]
I've found a broken link.

##### Relevant URLs
The "retention policy" link under the log data retention policies header on [this page](https://docs.influxdata.com/platform/troubleshoot/disk-usage/#log-data-retention-policies) is broken.

The url it links to is:
https://docs.influxdata.com/influxdb/v2.0/query_language/database_management/#retention-policy-management

**Comment by noramullen1** [comment]
Thanks @780Farva! We've updated this.
