### ISSUE TITLE
regexp =~ /cpu[0-2]/ can not match cpu0,cpu1,cpu2

### ISSUE THREAD

**Issue by YexinZhang** [influxdata/docs-v2#2053]
https://docs.influxdata.com/influxdb/v2.0/query-data/flux/regular-expressions/#use-a-regex-to-filter-by-tag-value

"r.cpu =~ /cpu[0-2]/  -->  it will match many point that cpu field value contains 0,1,2
![image](https://user-images.githubusercontent.com/42562246/104297191-87fe9680-54fd-11eb-8fa5-9ff1bc8bee68.png)

to use =~ /cpu[0-2]$/  --> it match cpu0 cpu1 cpu2
![image](https://user-images.githubusercontent.com/42562246/104297253-9ba9fd00-54fd-11eb-9e08-795d68e86b05.png)

**Comment by noramullen1** [comment]
Thanks @YexinZhang! This is updated.
