### ISSUE TITLE
Http link poiting to non-existent resource in Influx DB2 Client README

### ISSUE THREAD

**Issue by ondrej-ivanko** [influxdata/docs-v2#2064]
Http link poiting to non-existent resource

in string `Query data in InfluxDB 1.8.0+ using the InfluxDB 2.0 API and Flux (endpoint should be enabled by flux-enabled option)` -> the flux enable option anchor points to 404 page.

##### Relevant URLs
https://github.com/influxdata/influxdb-client-python#influxdb-1-8-api-compatibility
![Screenshot from 2021-01-14 15-02-29](https://user-images.githubusercontent.com/44980578/104600712-a6899c80-5679-11eb-8c15-16de5a7cc573.png)

**Comment by kelseiv** [comment]
Thank you, @ondrej-ivanko!
