### ISSUE TITLE
Broken link within Blog post

### ISSUE THREAD

**Issue by shalyng** [influxdata/docs-v2#2068]
URL Broken in blog post

##### Relevant URLs
Blog post URL - https://www.influxdata.com/blog/how-grafana-dashboard-influxdb-flux-influxql/
Broken link - https://v2.docs.influxdata.com/v2.0/visualize-data/other-tools/grafana/

##### What products and version are you using?
Influx Blog article

**Comment by kelseiv** [comment]
Thank you, @shalyng! Fixed

**Comment by shalyng** [comment]
🎉 What an awesome turnaround time! Thank you!!
