### ISSUE TITLE
I have the ability to create users in InfluxDB UI, though the docs say they can't be

### ISSUE THREAD

**Issue by tara-influxdata** [influxdata/docs-v2#2074]
"Additional users cannot be created in the InfluxDB UI." is in documentation. I am able to create users in InfluxDB UI.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.0/users/create-user/

##### What products and version are you using?
Cloud 2

**Comment by sanderson** [comment]
@tara-influxdata the doc you linked is for OSS. You can’t use the OSS UI to create users. In cloud, you can invite users to join your organization.
