### ISSUE TITLE
Telegraf v1.17-docs-"Guides-Using the HTTP plugin" - issue

### ISSUE THREAD

**Issue by shazhiju** [influxdata/docs-v2#2078]
_Describe the issue here._

##### Relevant URLs
https://docs.influxdata.com/telegraf/v1.17/guides/using_http/#

##### What products and version are you using?
product version:
influxdb v2.0
telegraf v1.17
local dev enviroment : windows 10
 question i met: 
 i follow  "Using the HTTP input plugin with Citi Bike data" this article,  correspongding url  https://docs.influxdata.com/telegraf/v1.17/guides/using_http/#
it seems this congiuration item **json_time_key = "lastCommunicationTime"** not works correct,  powershell  appear like this 

`" E! [inputs.http] Error in plugin: [url=https://feeds.citibikenyc.com/stations/stations.json]: The system cannot find the path specified."`

when set like this **json_time_key = ["lastCommunicationTime"]**,  this works properly

i‘m not sure whether i operated corrrect in local dev environment, so i commit this issue, hoping offical to verify this issue.
thank you !

**Comment by kelseiv** [comment]
related https://github.com/influxdata/docs-v2/issues/1879

**Comment by noramullen1** [comment]
Closed by https://github.com/influxdata/docs-v2/pull/3640
