### ISSUE TITLE
Missing example of influx write with user and password

### ISSUE THREAD

**Issue by CarstenH5** [influxdata/docs-v2#2083]
The influx write example for a file input doesn't work.
It produces this error:

Error: Failed to write data: unauthorized access.
See 'influx write -h' for help

There is no hint that a user or password must be given or that an other method of authentication must be used to run the command.

##### Relevant URLs
- _Provide relevant URLs_

##### What products and version are you using?
Influx CLI 2.0.3 (git: fe04d346df) build_date: 2020-12-15T01:00:16Z

**Comment by sanderson** [comment]
@CarstenH5 there's a note above the examples that explains the recommended way for providing authentication credentials: https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/write/#examples.

All the examples assume that authentication credentials are provided via the active `influx` CLI connection configuration. The note linked to above above points [here](https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/#provide-required-authentication-credentials), where it walks through creating a new CLI config.
