### ISSUE TITLE
Broken Link Kapacitor 1.5 docs

### ISSUE THREAD

**Issue by amaciuszonek** [influxdata/docs-v2#2087]
Broken link from page:
https://docs.influxdata.com/kapacitor/v1.5/guides/join_backfill/

to page:
https://docs.influxdata.com/downloads/pages.zip/

Page Section:
The Data generator

Data for such a website can be primed and generated to InfluxDB using the Python 3 script rolled into page.zip(sha256) and created for this purpose. It leverages the InfluxDB-Python library. See that Github project for instructions on how to install the library in Python.

**Comment by kelseiv** [comment]
Thank you, @amaciuszonek - resolved in https://github.com/influxdata/docs-v2/pull/2189.
