### ISSUE TITLE
Document CLI commands for finding and rerunning failed tasks

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#2095]
PR: https://github.com/influxdata/influxdb/pull/20307

- [ ] Add `influx task retry-failed` command

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/task/
- https://docs.influxdata.com/influxdb/cloud/process-data/manage-tasks/

**Comment by danxmoran** [comment]
Confirming from the OSS side that this merged to `master`, and we plan to include it in the 2.0.5 release
