### ISSUE TITLE
InfluxDB 2: Documentation for InfluxDB 1.x compatibility API should be improved!

### ISSUE THREAD

**Issue by virtualdreams** [influxdata/docs-v2#2100]
It is nowhere pointed out that you have to do a DBRP mapping. The corresponding example is also incorrect, as it does not mention that the Org is also a required field.
https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/#map-unmapped-buckets

The documentation for the "v1 compatibility API documentation" is just a bad joke
https://docs.influxdata.com/influxdb/cloud/api/v1-compatibility/

The query parameters "u" and "p" are simply not pointed out.
https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/

It is also not mentioned anywhere that you have to add an extra token on the command line for the V1 API. Why this can not be done in the web interface is also very questionable.

Why can't the tokens from the web interface be used to authenticate against the V1 API?

I could only find a final "help" via the GitHub Issues.

To speak of "compatibility" here is very debatable.

A very frustrating migration experience.

**Comment by danxmoran** [comment]
Transferred from `influxdb` to the docs repo.

**Comment by timhallinflux** [comment]
@virtualdreams -- curious what process did you follow to upgrade from 1.x to 2.x?  The bulk of the things that you mention here are done for you as part of the upgrade script that is provided.  Looks like you are trying to upgrade from 1.x OSS to 2.x Cloud?  We haven't build the upgrade automation script for that specific path yet, but we are kicking off that work next Monday.

So, if you are pursuing a more manual upgrade -- I think your feedback is pretty clear and we can work on improving/addressing this items quickly.    Sorry about the frustration and we appreciate the specifics here...  any other feedback you've got, is welcome as we work through this.

**Comment by virtualdreams** [comment]
I followed the process described in https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/. From 1.x OSS to 2.x OSS.

The migration itself was not the problem, it worked great. The problems first appeared when I tried to write to the DB with icinga2, which led to authentication errors.

I also completely overlooked the part with `v1 auth`, especially since the tokens cannot be created via the web interface.

I also did not migrate any users from 1.x OSS.

At https://docs.influxdata.com/influxdb/cloud/api/v1-compatibility/ it also says that `p` is now a token instead of a password.

Tokens in the web interface and under `auth list`, `v1 auth` is simply not noticed.

**Comment by virtualdreams** [comment]
After reading the migration guide i used `influxd upgrade --config-file <path to v1 config file>`. The migration was from a restored backup in a very new instance with no authentication enabled.

**Comment by virtualdreams** [comment]
Oh, I see that I mixed OSS and cloud documentation. But the content was almost the same in both.

**Comment by timhallinflux** [comment]
Thanks @virtualdreams -- I'm still a little confused and appreciate your patience as we really want to get this right and clarify this for others.

So, you were running OSS 1.x -- and you were running without any username/password setup.  Because of that, you were forced to create some in 2.x because we no longer support unauthenticated access?

If I understood this correctly, it means that we really should account for this case more clearly in the docs outlining:
1) a `v1 auth` setup -- how to add a `v1 auth` username/password combo which would probably be the easiest?
or
2) a token-based setup which might make things easier (i.e. fewer things to change for the future)

The API doc would be clearer if it said password -- also it seems like based on your use case we could enrich/enhance these docs too: https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/write/
meaning, it shows how to formulate the API call with the 2.0 token based scheme, but as it appears ichinga2 really only supports the 1.x setup.  The easiest path to success would be path 1) (create a `v1 auth`).

Did I understand this correctly?

**Comment by virtualdreams** [comment]
The starting point was the test of a restore from a backup into a completely new InfluxDB 1.x OSS environment. For the sake of simplicity, I did not enable authentication and create users.

I also used this new environment to test a migration to InfluxDB 2.x OSS. I was aware that in this case I have to create a user in InfluxDB 2.x OSS during the setup.

I therefore also ignored the "post-upgrade" part in the migration instructions, it was not relevant in this case.

I was also aware that icinga2 is not compatible with the new V2 API. For this purpose there was the compatibility API V1, see https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/. In this as already mentioned, also the reference is missing, that one can still use `u` and `p`.
At https://docs.influxdata.com/influxdb/v2.0/api/v1-compatibility/ `p` is used to indicate a token (which is wrong by the way, because it is V1 password ;) ).

My assumption was that a user or a token from the setup of the Influx 2.x OSS version would be sufficient to authenticate against the V1 API. That this is not the case is now obvious. :)

As already said, the authentication of icinga2 against InfluxDB 2.x OSS failed.
On the page https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/ it is not mentioned anymore that `v1 auth` is necessary for the authentication. I only found this out via the GitHub Issues.

**What I would have expected from the migration page?**

A hint that for the compatibility API further steps are necessary, e.g. the creation of a V1 user and the DBRP mapping. 
I would also have expected that both can be set up via the web interface.

I hope I can bring some clarity and maybe the documentation can be improved here and there.

**Comment by kelseiv** [comment]
Thank you for all of your feedback, @virtualdreams! We've recently updated several docs to address the issues that you surfaced, including:
- New doc to describe how to [manually upgrade from InfluxDB 1.x to 2.0](https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/manual-upgrade/)
- Updated post-upgrade steps for folks using the automatic upgrade: https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/automatic-upgrade/#post-upgrade
- Clarified that org and token are required to map buckets: https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/#map-unmapped-buckets
- Updated username and password content for basic auth in [InfluxDB 1.x compatibility API doc](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/#1x-compatible-authorizations)
- Added [issue](https://github.com/influxdata/influxdb/issues/20902) in our influxdb repository to update [AuthPassV1 parameter description](https://docs.influxdata.com/influxdb/v2.0/api/v1-compatibility/) to v1 password,   and clarified all 2.0 requests require 1.x-compatible authorizations or token authentication.

Thanks again for surfacing these issues and helping to improve our documentation! Please let us know if we missed anything at all, we really appreciate your support!

**Comment by virtualdreams** [comment]
Hello,

thank you also for updating the documentation. It all looks very good!

**Comment by kelseiv** [comment]
Excellent, thank you @virtualdreams!
