### ISSUE TITLE
Can't Download the influx CLI

### ISSUE THREAD

**Issue by ihsienlee** [influxdata/docs-v2#2106]
Can't Download the influx CLI

Dear all:

I can't download the influx CLI for Linux version.
https://dl.influxdata.com/influxdb/releases/influxdb_client_2.0.3_linux_amd64.tar.gz
Please help me.

I-hsien Lee

**Comment by pierwill** [comment]
Hello @ihsienlee. The correct link should be https://dl.influxdata.com/influxdb/releases/influxdb_client_2.0.3_linux_amd64.tar.gz. We are updating the docs now.

**Comment by pierwill** [comment]
Fixed in #2108.
