### ISSUE TITLE
Add 'influx-inspect report-disk' command

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#2112]
PR: https://github.com/influxdata/influxdb/pull/20647/files

This addition will be associated with an InfluxDB 1.x release, but I'm not sure which.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v1.8/tools/influx_inspect/

**Comment by timhallinflux** [comment]
Looks like both 1.8.5 OSS and then 1.9 Enterprise too...
