### ISSUE TITLE
Typo in restore usage command - influxd instead of influx

### ISSUE THREAD

**Issue by Ob1A** [influxdata/docs-v2#2113]
_Describe the issue here._
Usage section : influxd instead of influx

##### Relevant URLs
- _Provide relevant URLs_
https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/restore/#usage

##### What products and version are you using?
InfluxDB 2.0 OSS

**Comment by pierwill** [comment]
Thanks, @Ob1A – fixing now.
