### ISSUE TITLE
Notebooks: Combine and rewrite data use case

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/docs-v2#2133]
Add another use case to the notebooks documentation for combining data from multiple buckets, apply a simply multiplication, and rewrite.

Excerpt from user research explaining the use case (only accessible to InfluxData employees):
https://drive.google.com/file/d/1kD9b5AKgRiFvFN2ku6YKEaqSIKz1TnKl/view?usp=sharing

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud/notebooks/

##### What products and version are you using?

InfluxDB Cloud

**Comment by noramullen1** [comment]
Closing this per discussion with @russorat
