### ISSUE TITLE
tik docker tutorial doesn't use influxdb 2.0

### ISSUE THREAD

**Issue by craph** [influxdata/docs-v2#2160]
Hi,

I open this issue because I can see a difference between two docker images.

When I try to follow / use the [tik docker stack](https://docs.influxdata.com/downloads/tik-docker-tutorial.tar.gz) I'm unable to access the influxdb UI on port `8086`

The only way to do is to use the influxdb image from quay.io instead of the one from dockerhub.

Is the example in the documentation wrong and should be updated ?

Is it possible to have the same tutorial example with influxdb 2.0 ?

Thank you very much for your help.

Best regards,

**Comment by craph** [comment]
Hi @danxmoran ,

Thank you very much.
Can I contribute for the tutorial ?

I think the image name should be changed in the docker-compose.yml for influxdb for sure but may be some other things for kapacitor too ? refering my issue about kapacitor and influxdb 2.0

**Comment by timhallinflux** [comment]
yeah, this is an artifact of moving the `:latest` tag in DockerHub.  We'll fix that in the tar.gz and repost.  It will be pinned to `influxdb:1.8`

If you are working with this tutorial --- you are using the 1.x TICK stack.  In 2.0, the task system is integrated in with InfluxDB itself.
