### ISSUE TITLE
Metaquery templates in Chronograf

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2164]
Issue:
We currently don't describe Metaquery Templates; we reference them in the “Explore data with InfluxQL” procedure, but text is cutoff in [step 4](https://docs.influxdata.com/chronograf/v1.8/guides/querying-data/#explore-data-with-influxql).

Fixes:
- Add text to describe a meta query template in [Explore data with InfluxQL- step 4](https://docs.influxdata.com/chronograf/v1.8/guides/querying-data/#explore-data-with-influxql). Link to docs that cover functionality in metaquery templates (managing users, dropping/deleting data, and so on).
- Add a new doc to describe how to delete or drop data in Chronograf (cover both UI and CLI)
- Reference metaquery templates in [Step 3: Create your query](https://docs.influxdata.com/chronograf/v1.8/guides/create-a-dashboard/#step-3-create-your-query)

**Comment by sanderson** [comment]
Fixes 1 and 3 are addressed in #2781. For fix 2, dropping or deleting data isn't necessarily a function of Chronograf. It's a function of InfluxDB accomplished through queries `DROP ...`. These queries are already documented in the InfluxDB documentation.
