### ISSUE TITLE
Series and points written 'ingress metrics' for influxdb v1

### ISSUE THREAD

**Issue by lesam** [influxdata/docs-v2#2170]
PRs:
https://github.com/influxdata/influxdb/pull/20700
https://github.com/influxdata/influxdb/pull/20687
https://github.com/influxdata/influxdb/pull/20677

Adding series creation and ingress metrics to influxdb v1, not sure if this is for 1.9.0 or 1.8.5.

##### Relevant URLs
- _Provide relevant URLs_

##### What products and version are you using?

influxdb v1.8.5 or v1.9.0, not yet decided.

**Comment by lesam** [comment]
This is now officially targeted for v1.9.0

**Comment by pierwill** [comment]
#2511 was a duplicate of _this_.
