### ISSUE TITLE
Inconsistent Instructions for InfluxQL Grafana Instructions

### ISSUE THREAD

**Issue by ytechie** [influxdata/docs-v2#2211]
The [documentation for configuration Grafana using InfluxQL against Influx 2.0](https://docs.influxdata.com/influxdb/v2.0/tools/grafana/) says  __Enter the ID of the bucket to query__ but the screenshot says __mydb__ which is a name. It's unclear to me which is correct.

It also says nothing about the basic authentication checkbox, but the screenshot shows it checked, with values.

__Steps to reproduce:__
Just look at the [docs here](https://docs.influxdata.com/influxdb/v2.0/tools/grafana/), and click the "InfluxQL" section.

__Environment info:__

Influx 2.0, InfluxQL

**Comment by sanderson** [comment]
@ytechie There is a PR in progress that updates the Grafana instructions: #2210.

**Comment by ytechie** [comment]
Thanks! That helped. The key was the database name. I had no idea that I needed to create the db/rp mapping to the bucket to access it with InfluxQL.
