### ISSUE TITLE
Flux reference docs show an example that doesn't work

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#2212]
The Flux reference docs show using `fixedZone` to set the time zone. Copy-pasting the example produces an error.

The Flux team says the function is in the spec as something to-be-done. I'm not sure if the doc pages are auto-generated from the spec, but it would be nice to call out / hide things that aren't completed yet.

##### Relevant URLs
- Original bug report: influxdata/influxdb#20804
- Doc page: https://docs.influxdata.com/influxdb/v2.0/reference/flux/language/options/#location

**Comment by kelseiv** [comment]
Related:
https://github.com/influxdata/flux/issues/406
