### ISSUE TITLE
Clarify that the --rp argument used when creating DBRPs doesn't actually affect bucket retention

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#2215]
Reported on community slack: some users who are manually setting up DBRPs are confused about the meaning of the `--rp` flag, and what value(s) they should use for it. One user suggested that we clarify `--rp` has no affect on the target bucket's retention policy, and is purely a label.

We could also expand on examples & recommendations for different use-cases:
* Setting up a bucket that will only ever have one DBRP? Use `--rp autogen --default`
* Mimicking a 1.x-style setup with multiple RPs under the same DB? Use `--rp <string form of the target bucket's retention policy>`

Any recommendations we give should make clear that the chosen value of `--rp` doesn't matter, but following our suggestions could help align with other tooling that expects 1.x conventions (i.e. Grafana)

##### Relevant URLs
- The "Map unmapped buckets" section of the docs: https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/#map-unmapped-buckets

**Comment by timhallinflux** [comment]
We had a new InfluxDB OSS user who wanted access to InfluxQL via Grafana, but didn't understand the whole DB and/or RP setup.  So, they needed a little more guidance about these mapping "names".

**Comment by sanderson** [comment]
So this is addressed in https://github.com/influxdata/docs-v2/commit/85c72965a547d471ce9bf0d248af6741f0335713, however I think the location of this content is just temporary. Related to #2206, this content will eventually land in a task-based doc devoted to guiding users through a manual migration process.
