### ISSUE TITLE
Misc Kapacitor doc issues 

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2220]
Kapacitor is still targeting InfluxDB's v1 APIs. You can still use it with a 2.x deployment, but it'll take a little more setup work. On the InfluxDB side, you'll need to:

1. Create a bucket, and retrieve the bucket ID
2. Define parameters to use for v1 mappings:
    - Name of the database to map to specified bucket
    - Name of the retention policy to map to specified bucket
    - Username and password to access the specified bucket
3. On the command-line, create V1 compatibility mappings:
    -  Create a DBRP mapping: influx v1 dbrp create --org <your-org> --db <db-name> --rp <rp-name> --bucket-id <your-bucket-id>
   -  Create a V1 token: influx v1 auth create --org <your-org> --username <user-name> --password <password> --write-bucket <your-bucket-id> # Or maybe --read-bucket <your-bucket-id>
4. Configure Kapacitor using the DB/RP and username+password (similar to connecting to a v1 instance).

**Comment by timhallinflux** [comment]
This will only work for OSS.  Since in Cloud there is no V1 auth.

So, OSS will need instructions (using v1 auth or tokens) and Cloud will need slightly different instructions (token only).
