### ISSUE TITLE
InfluxDB 2.0.5: New flag for `influx write`

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#2240]
**PR:** influxdata/influxdb#20846

* `influx write` now accepts an optional `--compression` flag. The valid values are "none" and "gzip"
* If `--compression` isn't specified, it will be inferred based on file extension (files ending with `.gz` are assumed to be gzip)
* The new feature works along with existing `influx write` conveniences:
   * CSV inputs can be gzipped. They will be auto-detected based on the `.csv.gz` extension if the flags aren't specified
   * URL inputs can return gzipped data. If the flag isn't specified, GZIP will be inferred if (1) the URL ends with `.gz` or (2) the response from the server has a `Content-Encoding: gzip` header

**Comment by pierwill** [comment]
Closed by https://github.com/influxdata/docs-v2/pull/2243.
