### ISSUE TITLE
Telegraf 1.18 Release

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#2247]
Telegraf 1.18.0 Release targeted for March 15, 2021
- [Changelog](https://github.com/influxdata/telegraf/blob/v1.18.0-rc0/CHANGELOG.md#v1180-rc0-2021-03-03)
- Mac/Windows Signing might need docs around it? @pierwill

Plugins:

#### New Input Plugins

-   [Beat Input Plugin 2](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/beat) (ravendb) - Contributed by @[nferch](https://github.com/nferch)

-   [CS:GO Input Plugin 1](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/csgo) (csgo) - Contributed by @[oofdog](https://github.com/oofdog)

-   [Directory Monitoring Input Plugin 2](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/directory_monitor)(directory_monitor) - Contributed by [@InfluxData](https://community.influxdata.com/groups/influxdata)

-   [RavenDB Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ravendb) ( ravendb ) - Contributed by @[ml054](https://github.com/ml054)

- [NFS Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nfsclient) (`nfsclient`) - Contributed by @[pmoranga](https://github.com/pmoranga)  --- not in rc0 but will be in rc1 

#### New Output Plugins

-   [Grafana Loki Output Plugin 1](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/loki) (loki) - Contributed by @[Eraac](https://github.com/Eraac)

-   [Sensu Output Plugin](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/sensu) (sensu) - Contributed by @[calebhailey](https://github.com/calebhailey)

-   [SignalFX Output Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/signalfx) ( signalfx) - Contributed by @[keitwb](https://github.com/keitwb)

#### New Aggregator Plugins

-   [Derivative Aggregator Plugin ](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/derivative)(derivative) - Contributed by @[KarstenSchnitter](https://github.com/KarstenSchnitter)

-   [Quantile Aggregator Plugin ](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/quantile)(quantile) - Contributed by @[srebhan](https://github.com/srebhan)

#### New Processor Plugins

-   [AWS EC2 Metadata Processor Plugin ](https://github.com/influxdata/telegraf/tree/master/plugins/processors/aws/ec2)(aws_ec2) - Contributed by @[pmalek-sumo](https://github.com/pmalek-sumo)

#### New Parser Plugins

-   [XML Parser Plugin ](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xml)(xml) - Contributed by @[srebhan](https://github.com/srebhan) --- not in rc0 but will be in rc1

**Comment by sjwang90** [comment]
Target release date moved to March 17 ☘️

**Comment by sjwang90** [comment]
Release Announcement [doc](https://docs.google.com/document/d/1ojxcL3M1OE2DYhnfqUoyiQPyYFZZJBpXcjlLIH9oZ3s/edit#)

**Comment by pierwill** [comment]
Looks like this was closed in https://github.com/influxdata/docs-v2/commit/d170ba3b36f432ee813da3298becf0308b12d595.
