### ISSUE TITLE
Minor Edit: Mosaic

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#2250]
Looks like a review comment didn't make it into the final edit...

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud/visualize-data/visualization-types/mosaic/

Current:
The mosaic visualization displays string values in a graph.

Proposed: 
The mosaic visualization allows you to view state changes in your time series data. This visualization type is particularly useful in  cases where you have a defined set of string values which represent state that can change over time.

**Comment by timhallinflux** [comment]
I also feel like we need a real example of showing how to use this....  Where can that land??

**Comment by sanderson** [comment]
I can drop an example in.
