### ISSUE TITLE
Removal of Flux REPL in 1.x

### ISSUE THREAD

**Issue by lesam** [influxdata/docs-v2#2258]
See the issue description: https://github.com/influxdata/influxdb/issues/20852

In short, there are significant changes in 1.9 to the `influx` cli's handling of flux queries. We used to have a repl similar to the `flux repl` command line tool, but that is going away and we will only support the `execute` argument or a script piped to stdin. We lose code completion etc (these are still available in the `flux` command).

We are also fixing an issue that the wrong API path was previously used to query flux. See the commit message on the PR for more examples of the new version of the command in action. This was bug https://github.com/influxdata/influxdb/issues/18947

PR link: https://github.com/influxdata/influxdb/pull/20889

**Comment by sanderson** [comment]
**Pages this will affect (in the 1.9 docs):**

- https://docs.influxdata.com/influxdb/v1.8/flux/guides/execute-queries/
- https://docs.influxdata.com/influxdb/v1.8/tools/influx-cli/
- https://docs.influxdata.com/influxdb/v1.8/flux/get-started/
- https://docs.influxdata.com/influxdb/v1.8/flux/get-started/syntax-basics/
- We'll also probably want to call this out in the 1.9 release notes as a breaking change.
