### ISSUE TITLE
date.truncate() documentation does not mention the epoch and how it affects truncation

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs-v2#2260]
##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/date/truncate/
- https://github.com/influxdata/flux/issues/3538

The `date.truncate()` function should mention that weeks start on Thursday. This is consistent with InfluxQL as seen in https://github.com/influxdata/influxdb/issues/7594.

This should be mentioned as it can be quite surprising behavior.

**Comment by kelseiv** [comment]
Related:
https://github.com/influxdata/docs-v2/issues/2776
https://github.com/influxdata/docs-v2/issues/2267

**Comment by taufikp** [comment]
To me this epoch thing was the biggest surprise in 2020 when I had a job to create a week by week chart in Grafana. I was quite dissapointed that this very important information is not mentioned in the documentation.
