### ISSUE TITLE
Deprecate 'influx transpile' command

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#2266]
The `influx transpile` command will soon be removed from the `influx` CLI. Because it still exists in previous patch version of 2.0, we shouldn't just remove the `influx transpile` doc. We need to do the following:

- Remove the `transpile` command from the `influx` CLI landing pages
- Add deprecation/removal warning messages to the `influx transpile` pages that identify the specific version the command will be / was removed.
- Remove the `menu` frontmatter from each of the `influx transpile` pages to hide it from the the menu, but still publish the page.

Essentially there won't be any way to navigate to the page, but external links will still work and people may still be able to find it if they're looking for it, but we make it clear that it's no longer available after InfluxDB 2.0.x.

##### Relevant URLs
- https://github.com/influxdata/influxdb/issues/20905
- https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/
- https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/
- https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/transpile/
- https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/transpile/

**Comment by danxmoran** [comment]
influxdata/influxdb#20913 will remove the command from `master`. The plan is to backport the change onto `2.0` in time for the 2.0.5 release.
