### ISSUE TITLE
Clarify data returned weekly by epoch

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2267]
Clarify across docs (Flux functions and content referencing time returned in weeks) that epoch time starts on a Thursday. We need to point this out when it affects the results of data being returning, for example, when data is truncated by week. [Issue](https://github.com/influxdata/flux/issues/3538) reported in Flux repo.

##### Potentially relevant URLs
- https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/date/truncate/  
- https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/date/week/
- https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/query/#epoch
- https://docs.influxdata.com/influxdb/v2.0/reference/glossary/#unix-timestamp

- Check with Flux team for other potentially affected Flux functions

**Comment by alksinflux** [comment]
@sanderson - Any ideas when this DAR is addressed to clarify that epoch time starts on Thursday and the impact is has on aggregateWindow etc.? This should be addressed asap imho.
