### ISSUE TITLE
Flux support in InfluxDB Enterprise 1.9

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2273]
- Add InfluxQL and Flux content to support the latest Flux version (pull content from OSS); no more 32bit support; includes Flux query controls and Flux pushdowns.

**Comment by pierwill** [comment]
Is this 0.112.1?

**Comment by kelseiv** [comment]
@pierwill, looks like Sam updated to [flux v0.113.0](https://github.com/influxdata/plutonium/pull/3396).

To verify, we can double-check line 24(ish) in [plutonium/go.mod](https://github.com/influxdata/plutonium/blob/master/go.mod) in the release branch.

**Comment by pierwill** [comment]
Closed in https://github.com/influxdata/docs-v2/commit/5c9207db8723bd67022022d12ff3e8a6f16ec9dd.
