### ISSUE TITLE
OSS 2.x Getting Started w/ Docker shows command that fails

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#2274]
Original report at influxdata/influxdata-docker#468

The docs recommend running:
```
$ docker run -p 8086:8086 \
      -v $PWD/config.yml:/etc/influxdb2/config.yml:ro \
      influxdb:2.0.4
```

Apparently the `:ro` causes a failure with some of the logic used by the container to run as a non-root user (thought I'd tested it, my bad 🤦)

Removing it from the example command makes things work. I'll update the DockerHub side of things.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.0/get-started/?t=Docker#configure-influxdb-with-docker

**Comment by sanderson** [comment]
Thanks @danxmoran, I'll also update the docker upgrade guide.
