### ISSUE TITLE
InfluxDB 2.0.5 adding support for setting/updating bucket shard-group durations

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#2283]
**PR:** https://github.com/influxdata/influxdb/pull/20911

We are exposing shard-group durations to users, so they can specify / modify custom values. This functionality was part of InfluxQL in 1.x (users could specify `SHARD GROUP DURATION` as part of `CREATE RETENTION POLICY` and `ALTER RETENTION POLICY`). Instead of restoring the InfluxQL commands, we've extended the `influx` CLI.

* `influx bucket create` now takes a `--shard-group-duration` option to explicitly specify a value. If not set, the server will pick a duration that "makes sense" given the bucket's retention policy. An error will be returned if `--shard-group-duration` is set to a larger value than `--retention`
* `influx bucket update` now takes a `--shard-group-duration` option to modify the value. If not set, the value won't be modified. An error will be returned if an update would make the shard-group duration larger than the retention duration.
* `influx bucket list` output now includes an extra column for "Shard group duration"

##### Relevant URLs
- The docs for the 1.x / InfluxQL version of this feature are [here](https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/#shard-duration).

**Comment by danxmoran** [comment]
This feature also modified the Swagger API spec

**Comment by sanderson** [comment]
@danxmoran I assume these don't work with Cloud. We manage shards for users in Cloud, right? Will passing these flags to a Cloud instance return an error?

**Comment by danxmoran** [comment]
@sanderson sorry for the delay. Correct, these new APIs don't work against Cloud (because Cloud fully manages shards for users). Passing these new options to the Cloud API will result in a Not Implemented error.
