### ISSUE TITLE
2.x installation instructions for Linux mention redundant downloads

### ISSUE THREAD

**Issue by franck102** [influxdata/docs-v2#2285]
Unless I am missing something the apt package contains the influx & influxd binaries, so for Linux installs the 
https://docs.influxdata.com/influxdb/v2.0/get-started/?t=Linux#download-and-install-influxdb-v20

and the 
https://docs.influxdata.com/influxdb/v2.0/get-started/?t=Linux#place-the-executables-in-your-path

sections of the instructions should be skipped?

**Comment by pierwill** [comment]
@franck102: thanks for the comment. Download the binary and placing it in the executable path and installing via a package manager are two different options for installation that we're describing for users here.
