### ISSUE TITLE
Debian installation instructions highly insecure

### ISSUE THREAD

**Issue by charlemagnelasse** [influxdata/docs-v2#2286]
The docs specify following instruction how to install influxdb on debian.

```
wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/lsb-release
echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
```

This is highly insecure as it is adding non-Debian keys to the global trusted keyring - and will stop working in the near future. See

* https://michael-prokop.at/blog/2021/02/16/how-to-properly-use-3rd-party-debian-repository-signing-keys-with-apt/
* https://wiki.debian.org/DebianRepository/UseThirdParty
* https://manpages.debian.org/testing/apt/apt-key.8.en.html

Correct instructions are:

```
sudo mkdir -p /etc/apt/keyrings
wget -qO- https://repos.influxdata.com/influxdb.key | gpg --dearmor | sudo tee /etc/apt/keyrings/influxdb.gpg > /dev/null
source /etc/lsb-release
echo "deb [signed-by=/etc/apt/keyrings/influxdb.gpg] https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
```

**Comment by pierwill** [comment]
Thanks, @charlemagnelasse! Your instructions look good here. We'll dig into the articles you linked to a bit and get the docs updated.

**Comment by pierwill** [comment]
Many thanks for this, @charlemagnelasse!
