### ISSUE TITLE
Documentation for using Prometheus Histograms in Flux

### ISSUE THREAD

**Issue by wolffcm** [influxdata/docs-v2#2287]
I recently wrote up a how-to document for a customer on how to use Prometheus histograms from Flux. Histograms are incredibly handy for lots of monitoring use cases, but they are also very difficult to use in Flux. It'd be great if my document could be adapted and published in our public docs. It would also be good to link it to the existing `histogramQuantile` doc page at: https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/aggregates/histogramquantile/

I will paste my writeup on histograms below. I've tried to make it generic enough to use without many modifications. Of course I am open to suggestions on how it could be improved.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/aggregates/histogramquantile/

---
# Using Prometheus Histograms in Flux

It's a common use case to have a service that has been instrumented with a `/metrics` endopint, and to use that in conjunction with InfluxDB and Telegraf for monitoring. In this configuration, Telegraf scrapes `/metrics` at regular intervals (10s by default) and sends those metrics to an instance of InfluxDB.

One of the more powerful metrics that can be produced by Prometheus are its [histograms](https://prometheus.io/docs/practices/histograms/). Prometheus histograms can be used to measure the distribution of a variable. Often this variable is the time it takes a server to respond to a request. The discussion below applies to this use case, but can be adapted to others.

Prometheus represents histograms as many sets of buckets (not to be confused with the InfluxDB concept of bucket).
There is one set of buckets for each unique set of labels, and within that set each bucket is labeled with an upper bound.
The upper bound label is `le` and it stands for "less than or equal to." In the example output from `/metrics` below, there is a bucket for requests that take less-than-or-equal-to 0.005s, 0.01s, and so on, up to 10s and then +Inf. Note that the buckets are cumulative, so if a request takes 7.5s, Prometheus will increment the counters in the buckets for 10s as well as +Inf.

Here is some sample output from a `/metrics` endpoint on an instance of InfluxDB OSS 2.0, including two histograms for requests served by the `/api/v2/write` and `/api/v2/query` endpoints.
```
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="0.005"} 0
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="0.01"} 1
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="0.025"} 13
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="0.05"} 14
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="0.1"} 16
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="0.25"} 16
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="0.5"} 16
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="1"} 16
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="2.5"} 16
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="5"} 16
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="10"} 16
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf",le="+Inf"} 16
http_api_request_duration_seconds_sum{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf"} 0.354163124
http_api_request_duration_seconds_count{handler="platform",method="POST",path="/api/v2/write",response_code="204",status="2XX",user_agent="Telegraf"} 16
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="0.005"} 0
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="0.01"} 16
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="0.025"} 68
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="0.05"} 70
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="0.1"} 70
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="0.25"} 70
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="0.5"} 70
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="1"} 71
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="2.5"} 71
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="5"} 71
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="10"} 71
http_api_request_duration_seconds_bucket{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome",le="+Inf"} 71
http_api_request_duration_seconds_sum{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome"} 1.4840353630000003
http_api_request_duration_seconds_count{handler="platform",method="POST",path="/api/v2/query",response_code="200",status="2XX",user_agent="Chrome"} 71
```

Flux provides a function for dealing with data like this called `histogramQuantile()`:
https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/aggregates/histogramquantile/

It does what its name suggests: it converts a Prometheus histogram to the quantile requested by the caller.
It expects a stream of input tables where each table has the following form:
- Each row represents one bucket of a histogram, where the upper bound of the bucket is defined by the
  argument `upperBoundColumn`. By default, this is `le`.
- There is a value column that represents the number of items (requests, events, etc) in the bucket.
  By default, this is `_value`.
- Buckets are strictly cumulative, so if e.g. for some reason the `+Inf` bucket had a count of 9,
  but the `10s` bucket had a count of 10, an error would be thrown:
  "histogram records counts are not monotonic".

Since Prometheus just increments the counts in each bucket continually as the process runs, whatever was most recently scraped from `/metrics` would be a histogram of all the requests (events, etc) since the process started, which could be days or weeks or longer. This is not typically useful, which is why Telegraf scrapes at regular intervals. We can subtract adjacent samples from the same bucket to discover the number of new items in that bucket for a given interval.

It's quite common to want to transform a set of cumulative histograms collected over time and visualize that as some quantile (e.g., 50th percentile or 99th percentile) as it has changed over time. The high level the transformations needed for this are:
- Downsampling the data to the desired time resolution (e.g., if we want to see how the 50th percentile changes over a month, we can first downsample to a resolution of 1h to get better performance from our query)
- Subtract adjacent samples so that buckets contain only the new counts for each period
- Sum data across the dimensions that we aren't interested in. For example, in the Prometheus data from above there is a label for `path`, but we may not care to break out http requests by path. If this is the case, we would ungroup the path dimension, and add corresponding buckets together.
- Reshape the data such that all the duration buckets for the same period are in their own tables, with an upper bound column that describes the bucket represented by each row
- Finally, transform each table from a histogram to a quantile with `histogramQuantile`

The following query performs the above steps.
```js
import "experimental"

// The "_field" is necessary. Any columns following "_field" will be used
// to create quantiles for each unique value in that column.
// E.g., put "path" in here to see quantiles for each unique value of "path".
groupCols = ["_field"]

// This is a helper function that takes a stream of tables,
// each containing "le" buckets for one window period.
// It uses histogramQuantile to transform the bin counts
// to a quantile defined in the "q" parameter.
// The windows are then reassembled to produce a single table for each
// unique group key.
doQuantile = (tables=<-, q) => tables
  |> histogramQuantile(quantile: q)
  |> duplicate(as: "_time", column: "_stop")
  |> window(every: inf)
  |> map(fn: (r) => ({r with _measurement: "quantile", _field: string(v: q)}))
  |> experimental.group(mode: "extend", columns: ["_measurement", "_field"])

histos =
  from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "http_api_request_duration_seconds"
    and r._field != "count" and r._field != "sum")
  // Downsample the data. This helps a lot with performance!
  |> aggregateWindow(fn: last, every: v.windowPeriod)
  // Calling difference() transforms the cumulative count of requests
  // to the number of new requests per window period.
  |> difference(nonNegative: true)
  // Counters may be reset when a server restarts.
  // When this happens there will be null values produced by difference().
  |> filter(fn: (r) => exists r._value)
  // Group data on the requested dimensions, window it, and sum within those dimensions, for each window.
  |> group(columns: groupCols)
  |> window(every: v.windowPeriod)
  |> sum()
  // Fields will have names like "0.001", etc. Change _field to a float column called "le".
  // This also has the effect of ungrouping by _field, so bucket counts for each period
  // will be within the same table.
  |> map(fn: (r) => ({r with le: float(v: r._field)}))
  |> drop(columns: ["_field"])

// Compute the 50th and 95th percentile for duration of http requests.
union(tables: [
  histos |> doQuantile(q:  0.95),
  histos |> doQuantile(q:  0.5)
])
```

If this has been done correctly, the tables flowing into the call to `histogramQuantile` will look similar to this (note that I have sorted the rows by `le` so it's clear that the counts increase for larger upper bounds):
![Screen Shot 2021-03-11 at 5 47 20 PM](https://user-images.githubusercontent.com/7902964/110973405-1468e200-8312-11eb-9eb3-2e2164d1a44f.png)

The visualized result will look something like this in the UI:
![Screen Shot 2021-03-12 at 7 48 52 AM](https://user-images.githubusercontent.com/7902964/110973450-2054a400-8312-11eb-80c0-ed9b20885e3e.png)

**Comment by sanderson** [comment]
Thanks @wolffcm!
