### ISSUE TITLE
Update string interpolation

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2314]
**PR:** https://github.com/influxdata/flux/pull/3556

Updates to string interpolation behavior. Previously, the string interpolated segment had to be a string. Now, any expression that resolves to a basic type (String, Int, Uint, Bool, Time, Duration) can be used in the string interpolated segment. 

https://docs.influxdata.com/influxdb/v2.0/reference/flux/language/string-interpolation/

Contact @Bolladeen with questions/review.

**Comment by rbetts** [comment]
(From the linked duplicate issue - also referenced here: https://docs.influxdata.com/influxdb/cloud/monitor-alert/checks/create/#tags)
