### ISSUE TITLE
Getting started with docker mentions ".influxdbv2" directory but  should be ".influxdb2"

### ISSUE THREAD

**Issue by robinrottier** [influxdata/docs-v2#2324]
Docker instructions tell you to map external drive to directory "`.influxdb2`"  but example code mentions  "`.influxdbv2`" for the container directory. My instance used ".influxdb2" so its the "infuxdbv2" thats wrong.

(although my preference woul dbe for the "v2" to indicate its a new version of the database, rather than influxdb2 sounds more like 2nd instance of the database)

https://docs.influxdata.com/influxdb/v2.0/get-started/?t=Docker

From within your new directory, run the InfluxDB Docker container with the --volume flag to persist data from /root/.influxdb2/ inside the container to the current working directory in the host file system.

docker run \
    --name influxdb \
    -p 8086:8086 \
    --volume $PWD:/root/.influxdbv2 \
    influxdb:2.0.4

**Comment by sanderson** [comment]
Related to #2385

**Comment by pierwill** [comment]
Closed in #2468.
