### ISSUE TITLE
Broken link from chronograf

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#2329]
on the load data page of chronograf, there is a link:
https://docs.influxdata.com/influxdb/latest/write_protocols/line_protocol_tutorial/

which seems to 404. could we add a redirect to the correct page? It might be this one? https://docs.influxdata.com/influxdb/v1.8/query_language/

**Comment by sanderson** [comment]
It should point to https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/
