### ISSUE TITLE
Upgrade to Cloud

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#2332]
We need to describe the different paths for upgrading to InfluxDB Cloud. Part of this will be a new section in the Cloud docs:

**Upgrade to Cloud**
- [x] Upgrade from OSS 2.x _(outline below)_
- [x] Upgrade from OSS 1.x _(later)_
     - [x] Migrate CQs _(just duplicate from OSS)
- [ ] Upgrade from Enterprise _(later, will cover both cloud 1 and enterprise)

---

**Upgrade from OSS 2.x to Cloud**:

1. Register for a cloud account
2. Create buckets
3. Generate new tokens
4. Distribute new tokens and begin dual write
5. Discuss handling of existing data (similar to the 1.x to Cloud path with exporting data to LP) and then importing using CLI. 
6. Create a migration template (using InfluxDB templates feature) to move resources (dashboards, labels, tasks, etc.) between. 
7. No scrapers -- use Telegraf with the Prom input instead. 
8. Users: invite additional users to the Cloud account.

---

**Upgrade from OSS 1.x to Cloud**

This will be very similar to [manually upgrading from 1.x to 2.0](https://github.com/influxdata/docs-v2/blob/master/content/influxdb/v2.0/upgrade/v1-to-v2/manual-upgrade.md), excluding:

- Installing OSS 2.0 (but they'll still want to install the CLI)
- Migrating custom config settings
- Creating 1.x compatible authorizations _(they have to use token auth)_

---

**Upgrade from Enterprise**
We're waiting on tooling for this, so we can circle back.

**Comment by sanderson** [comment]
We need to create a new section in the cloud docs for **upgrading** to InfluxDB Cloud. @timhallinflux, I'm updating the name and summary of this issue to cover this entire body of work.

**Comment by sanderson** [comment]
Other references provided by @8none1:

- https://docs.influxdata.io/operations/guides/importing_bulk_lp_to_c2/
- https://docs.influxdata.io/operations/guides/importing_portable_backup_to_c2/
