### ISSUE TITLE
`influx restore` can't restore to an existing bucket

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#2333]
Our docs for `influx restore` show an example of restoring to an existing bucket. This doesn't actually work at the moment. The restriction is consistent with 1.x, which didn't allow users to restore to an existing DB.

##### Relevant URLs
- Original user report: influxdata/influxdb#20758
- Example in 2.x docs: https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/restore/#restore-backup-data-to-an-existing-bucket
- Parallel 1.x docs showing the restriction there: https://docs.influxdata.com/influxdb/v1.8/administration/backup_and_restore/#restore-examples

**Comment by danxmoran** [comment]
The linked OSS issue has a comment detailing a work-around that could be nice to include in our docs

**Comment by sanderson** [comment]
@danxmoran How do the `--bucket` and `--bucket-id` flags with `influx restore`? Do they simply restore data from a single bucket inside a backup that has multiple buckets?

**Comment by danxmoran** [comment]
Yes, they set the single "source" bucket to restore. By default the bucket will be restored using the same name; `--new-bucket` is used to set a new name.

**Comment by sanderson** [comment]
Gotcha, so if a user wants to export a "snapshot" of all buckets or a particular bucket, then restore that snapshot, they'd have to delete the existing buckets before restoring to use the same bucket names?

**Comment by danxmoran** [comment]
Yup!
