### ISSUE TITLE
Request to add link to templates on InfluxDB templates doc

### ISSUE THREAD

**Issue by bckeene** [influxdata/docs-v2#2339]
_Describe your proposal here._
It would be great to have a link to our [community templates](https://github.com/influxdata/community-templates/) on [this doc](https://docs.influxdata.com/influxdb/v2.0/influxdb-templates/#template-resources).

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/influxdb-templates/#template-resources

**Comment by kelseiv** [comment]
Absolutely, thank you, @bckeene!
