### ISSUE TITLE
Doc search for v1.18 doesn't work

### ISSUE THREAD

**Issue by ingria** [influxdata/docs-v2#2362]
[1.18](https://docs.influxdata.com/telegraf/v1.18/):
![118](https://user-images.githubusercontent.com/2178368/112873755-bc302f00-90ca-11eb-80b5-c2482684dafc.png)

[1.17](https://docs.influxdata.com/telegraf/v1.17/) and older:
![117](https://user-images.githubusercontent.com/2178368/112873768-c0f4e300-90ca-11eb-8f82-d05df95df863.png)

**Comment by sanderson** [comment]
Thanks @ingria. This should be fixed in the next 30 minutes or so.

**Comment by sanderson** [comment]
Telegraf v1.18 is now indexed and search results are appearing. Sorry about the hiccup.
