### ISSUE TITLE
Telegraf as a Windows Service Doc Issue

### ISSUE THREAD

**Issue by pkropf** [influxdata/docs-v2#2386]
The documentation on installing Telegraf on Windows has the .exe and .conf copied to 

`C:\Program Files\InfluxData\Telegraf\
`

However when installing Telegraf as a Windows service, the default location for the .conf file that the service uses is in 

`C:\Program Files\Telegraf\
`

To help users be more successful, either the installation docs should be changed to put the .exe and .conf in 

`C:\Program Files\Telegraf\`

or the Telegraf --service install command should default to the .conf file being in 

`C:\Program Files\InfluxData\Telegraf\`

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1.18/introduction/installation/?t=Windows
- https://docs.influxdata.com/telegraf/v1.18/administration/windows_service/

**Comment by pierwill** [comment]
Thanks for this, @pkropf! We'll look into this.

**Comment by pierwill** [comment]
I agree that changing the default service install directory to `C:\Program Files\InfluxData\Telegraf\` makes sense. That seems to be the pattern for Windows software...
