### ISSUE TITLE
Parameterized queries

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#2391]
This feature allows users to define the values of variables in a separate field in a request payload, allowing our servers to interpret the parameters and run the related query.

**User benefit:** This can allow for users to dynamically change a value that is referenced by a parameter and query, without having to write a query over and over again. It can provide an extension upon the current dashboard variables feature, which is a limited subset of predefined values, and can also play nicely with the current UI work that is happening here: https://github.com/influxdata/ui/pull/652

**Usage:** When using the `api/v2/query` API, pass query parameters using the `params` field in the request body.

**Comment by kelseiv** [comment]
Pull in examples from blog:
https://www.influxdata.com/blog/tldr-influxdb-tech-tips-parameterized-flux-queries-with-influxdb/
