### ISSUE TITLE
Update docs to highlight notification endpoints

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2405]
On the [Manage notification endpoints](https://docs.influxdata.com/influxdb/v2.0/monitor-alert/notification-endpoints/) doc and/or [Monitor data and send alerts](https://docs.influxdata.com/influxdb/v2.0/monitor-alert/) doc, add narrative/links to let folks know all the 3rd party endpoints that alerts can be sent to:
- [Telegram](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/contrib/telegram/endpoint/)
- [Discord](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/contrib/discord/endpoint/)
- [Opsgenie](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/contrib/opsgenie/endpoint/)

**Comment by Anaisdg** [comment]
- [VictorOps](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/victorops/)
- [Microsoft Teams](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/teams/)
- [bigpanda](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/bigpanda/)
- [Discord](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/discord/)
- [Zenoss](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/zenoss/)
- [PusBullet)(https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/pushbullet/)
- [Sensu](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/sensu/)

Thank you!

**Comment by sanderson** [comment]
This is will be resolved when the `flux-restructure` branch merges. Here's the complete list:

- BigPanda
- Discord
- HTTP
- Opsgenie
- PagerDuty
- Pushbullet
- Sensu
- Slack
- Microsoft Teams
- Telegram
- VictorOps
- Zenoss
