### ISSUE TITLE
`influx transpile` removed for OSS 2.05

### ISSUE THREAD

**Issue by philjb** [influxdata/docs-v2#2412]
The next release of influxdb 2.x (2.05 I believe) will have the `transpile` command removed from the `influx` command line tool. This will impact cloud 2 docs and influx OSS 2 docs.

##### Relevant URLs

* Ticket removing the feature: https://github.com/influxdata/influxdb/pull/20913
* Existing documentation: https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/transpile/

**Comment by sanderson** [comment]
Thanks @philjb. This is duplicate of #2266 and is addressed in #2304.
