### ISSUE TITLE
Incorrect documentation for CLI

### ISSUE THREAD

**Issue by oddlittlebird** [influxdata/docs-v2#2415]
_Describe the issue here._

Documentation in the URL below is incorrect. This screenshot shows the incorrect portion. 
The --name should be --config-name

![image](https://user-images.githubusercontent.com/52059945/114622286-9f673000-9c62-11eb-86ea-7a870e448769.png)
`

Also, you should note that the name won't work if it includes "influxdb" anywhere in it.

##### Relevant URLs
- _Provide relevant URLs (the doc page in question, project issues, community threads, etc.)_

https://docs.influxdata.com/influxdb/cloud/tools/grafana/?t=InfluxQL#download-and-set-up-the-influx-cli

**Comment by sanderson** [comment]
Thanks @oddlittlebird. You are correct. It should be `--config-name`. This is related that a set of changes I'm currently working and will be fixed in the next day or two.
