### ISSUE TITLE
InfluxDB v2.0 Retention Policy

### ISSUE THREAD

**Issue by madkiwi69** [influxdata/docs-v2#2416]
Trying to setup Grafana to use InfluxDB v2 with InfluxQL
As I've found with a lot of this documentation the most obvious things are NOT documented.

Part of this requires DBRP mapping to be setup
https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/v1/dbrp/create/

Example given is:
influx v1 dbrp create \
  --bucket-id 12ab34cd56ef \
  --database example-db \
  **--rp example-rp \**
  --default

However **NOWHERE** does it tell you where you get this retention policy **NAME** from. (--rp)
Do you just make something up?!

To make it even more "interesting" nowhere in the Influxdb v2 doc's does it tell you how to query these or even create a retention policy with a name.

Already spent 2 days searching through all the doc's and googling, absolutely no hint of how to do this, something that should be a simple thing to do?!?!?!

**Comment by sanderson** [comment]
@madkiwi69 Sorry for the frustration. We can look at ways to make this more obvious in the documentation. A "retention" policy is an InfluxDB 1.x convention that no longer exists in the 2.0. However, InfluxQL (built for InfluxDB 1.x) expects a retention policy when querying data. DBRP mappings take database and retention policy combinations and map them to a specific bucket.

In 1.x, the default retention policy name is "autogen" and in Grafana, I believe they simply use "default". However, you may have other retention policy names as well. This is especially important if you're migrating from 1.x to 2.0 and want to continue to use Grafana without having to change the Grafana configuration.

In the GIF below from Grafana's InfluxDB documentation, the cell in the top line that says "default" is where you select which retention policy you're querying.

![https://grafana.com/static/img/docs/v45/influxdb_query.gif](https://grafana.com/static/img/docs/v45/influxdb_query.gif)

The retention policy name can be whatever you want, but it needs to match whatever InfluxQL queries you're using against InfluxDB 2.0
