### ISSUE TITLE
Marathon services discovery in Kapacitor 1.6 config changed

### ISSUE THREAD

**Issue by lesam** [influxdata/docs-v2#2418]
https://github.com/influxdata/kapacitor/pull/2536/files#r613542653

The `Timeout` config parameter to the marathon service discovery was removed to stay in sync with the prometheus implementation we depend on.

https://github.com/prometheus/common/pull/123

This is planned for Kapacitor 1.6.0.

**Comment by kelseiv** [comment]
Hi guys, did we update for Kapa 1.6.1?

**Comment by pierwill** [comment]
Looking at this now—

**Comment by pierwill** [comment]
@lesam Is this the configuration parameter that needs to be removed from docs?  https://github.com/influxdata/docs-v2/blame/f134584c79d6289e5ac9283637bc8a31b926376c/content/kapacitor/v1.6/working/scraping-and-discovery.md#L74

**Comment by pierwill** [comment]
Looks like we don't have docs specific to marathon, so this doesn't need a docs update at this time. However, the sample `kapacitor.conf` likely needs to be updated in the Kapacitor repo: https://github.com/influxdata/kapacitor/blob/b5af8896689fde42a883e6460a6cf76f23cfb8e6/etc/kapacitor/kapacitor.conf#L828-L838
