### ISSUE TITLE
Add docs about how to use Prometheus Remote Write Parser

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#2419]
**PR:** https://github.com/influxdata/telegraf/pull/8967
Will be included in the Telegraf 1.19.0 release

_Describe the new feature here._
- Prometheus Remote Write Parser plugin
- Can be used with `inputs.http_listener_v2` and setting `data format = "prometheusremotewrite"` 
- InfluxDB 1.x users that had been using the [Prom remote write endpoint](https://github.com/react-monaco-editor/react-monaco-editor) to write in metrics can migrate to 2.0 and use this parser to collect their prometheus metrics. For the metrics to completely align with the 1.x endpoint they must add a starlark processor laid out [here](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/prometheusremotewrite#for-alignment-with-the-influxdb-v1x-prometheus-remote-write-spec)

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v1.8/supported_protocols/prometheus/
- https://github.com/influxdata/telegraf/tree/master/plugins/parsers/prometheusremotewrit

**Comment by pierwill** [comment]
@sjwang90 : Did you mean to link "Prom remote write endpoint" to https://github.com/react-monaco-editor/react-monaco-editor above?

**Comment by sjwang90** [comment]
Lol no. sorry about that. 

I have this blog that I want turned into docs. It hasn't been reviewed by everyone necessary quite yet. 
https://github.com/influxdata/feature-requests/issues/279
