### ISSUE TITLE
Broken link in Docker hub Telegraf description page

### ISSUE THREAD

**Issue by Cougar** [influxdata/docs-v2#2431]
Link from [Docker hub](https://hub.docker.com/_/telegraf) points to https://docs.influxdata.com/telegraf/latest/introduction/getting_started/ which redirects to missing page https://docs.influxdata.com/telegraf/v1.18/introduction/getting_started/ that suggests to open a case here.

**Comment by kelseiv** [comment]
Thank you, @Cougar! submitted PR to fix this link

**Comment by kelseiv** [comment]
Updated the wrong file in PR above. 
New PR to resolve this issue merged: https://github.com/docker-library/docs/pull/1929
