### ISSUE TITLE
[DOC] Missing doc 2.0.4

### ISSUE THREAD

**Issue by SebastianThorn** [influxdata/docs-v2#2433]
_Add codumentation for all configuration-options._

I compared the info on https://docs.influxdata.com/influxdb/v2.0/reference/config-options with what o got from `influxd print-config` in the 2.0.4 docker-container.
Are these because i run in docker?

## Options i found that were missing in doc
feature-flags: {}
key-name: ""

## Options i found that are missing in my config-file
new-meta-store
new-meta-store-read-only
testing-always-allow-setup: false

### query-initial-memory-bytes: 0
What does 0 mean?
### query-max-memory-bytes:0
What does 0 mean?

## Things not in alphabetical order
vault-client-timeout: 0s

**Comment by sanderson** [comment]
Closed in #2450
