### ISSUE TITLE
Update "authentication tokens" to "API tokens"

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#2436]
@russorat has proposed that we update the term "authentication token" to "API token" throughout the 2.0 docs.

I'm fine with this change, but it will need to be done carefully. There may be references to "authentication tokens" for third parties for which the term is appropriate.

Does anyone have any concerns about this change?

**Comment by pierwill** [comment]
Not opposed... Do other projects use the term "API token"?

**Comment by pierwill** [comment]
Looks like this proposal is gaining support. :)

**Comment by kelseiv** [comment]
@pierwill gaining support :-) ...and let us know if it gets tricky
