### ISSUE TITLE
Updates for moving OSS 1.8 content to Enterprise 1.9

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2445]
- [ ] Note to clarify OSS 1.8 is last 1.x OSS release, and reference 2.0
- [x] Move Downloads above Getting Started
- [ ] Expand Getting Started content to include how to configure and manage clusters, monitor InfluxDB, log and trace, manage security, and backup/restore
- [x] Move concepts up a level out of reference
- [x] (lower priority) Enterprise features should be rephrased/reworked, for example "Managing users" and "Working with clusters"
- [x] Verify front matter menu names are correct (some weren't showing up in TOC)

**Comment by pierwill** [comment]
Addressing these in https://github.com/influxdata/docs-v2/pull/2421.
