### ISSUE TITLE
Best practices docs

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#245]
We need to create best practices and info docs for 2.0. Examples from 1.x:

- [x] [Schema and data layout](https://docs.influxdata.com/influxdb/v1.7/concepts/schema_and_data_layout/)
- [x] [Insights and tradeoffs](https://docs.influxdata.com/influxdb/v1.7/concepts/insights_tradeoffs/)
- [x] [Storage Engine](https://docs.influxdata.com/influxdb/v1.7/concepts/storage_engine/)

Other thoughts:
- [ ] Using Organization IDs vs Organization names in queries. (#204)

**Comment by kelseiv** [comment]
**Schema and data layout:**
- InfluxDB data elements: https://v2.docs.influxdata.com/v2.0/reference/key-concepts/data-elements/
- InfluxDB table structure: https://v2.docs.influxdata.com/v2.0/reference/key-concepts/table-structure/

**Insights and tradeoffs**:
- InfluxDB design principles: https://v2.docs.influxdata.com/v2.0/reference/key-concepts/design-principles/

@pierwill working on Storage Engine best practices

**Comment by kelseiv** [comment]
@sanderson @pierwill closing re work tracking in #399
