### ISSUE TITLE
Influx V1 DBRP Example outdated

### ISSUE THREAD

**Issue by kubedzero** [influxdata/docs-v2#2451]
https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/v1/dbrp/create/ has the below Example:

```
Create a DBRP mapping
influx v1 dbrp create \
  --bucket-id 12ab34cd56ef \
  --database example-db \
  --rp example-rp \
  --default
```

However, `--database` is not a valid term. When running it (as an example, `influx v1 dbrp create --bucket-id a9869c951166b7de --database local_reporting --rp autogen`) I get the error `unknown flag: --database`. I think that the Example should be updated to `--db` instead of `--database` or the full `--database` flag should be added.

**Comment by kelseiv** [comment]
Thank you, @kubedzero - we've updated to reflect the correct --db flag
https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/v1/dbrp/create/
