### ISSUE TITLE
Refresh the telegraf troubleshooting page

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#2465]
https://docs.influxdata.com/telegraf/v1.18/administration/troubleshooting/

- Add the `--test` option as the first thing in the list
- Add the `use a file output to standard out` as the second item in the list

**Comment by timhallinflux** [comment]
A re-look and update of the troubleshooting instructions seems in order for sure.  Other guidance for troubleshooting telegraf once it's running as a service --- or perhaps before you activate it as a service would be good.  
- Validate the config using --test
- Where to look for the logs once it's running as a service? (by platform: linux and windows)

**Comment by sjwang90** [comment]
Another item
- Setting `debug = true`
