### ISSUE TITLE
Chronograph release date error in the doc

### ISSUE THREAD

**Issue by Poutshi** [influxdata/docs-v2#2469]
Hello,

The release date of Chronograph v1.8.10 is wrong. I think you meant [2021-02-08]  instead of  [2020-02-08]. 
The date is correct in the [github release page](https://github.com/influxdata/chronograf/releases) 
![image](https://user-images.githubusercontent.com/36883072/116872255-ddc68e00-ac15-11eb-9efe-2341cffb0461.png)
but wrong in the [documentation page](https://docs.influxdata.com/chronograf/v1.8/about_the_project/release-notes-changelog/)

![image](https://user-images.githubusercontent.com/36883072/116872289-e9b25000-ac15-11eb-84bb-7edf41e53b04.png)

Cheers,

**Comment by kelseiv** [comment]
Thank you, @Poutshi!
