### ISSUE TITLE
Create and manage explicit bucket schemas

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#2470]
**PR:** https://github.com/influxdata/influx-cli/pull/52

The `influx` CLI will soon allow you to create "explicit" bucket schemas. These only allow specific columns to be written to a bucket and reject write requests that include columns/fields not explicitly defined as part of the bucket schema.

Initially this will only work with InfluxDB Cloud, but it will likely make its way into OSS shortly after.

[Video demo (in Slack)](https://influxdata.slack.com/files/U4S2P15T3/F020QF5FS6Q/cleanshot_2021-04-30_at_19.04.03.mp4)

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.0/organizations/buckets/

**Comment by timhallinflux** [comment]
this is not intended to land in OSS.
