### ISSUE TITLE
Kapacitor 1.6 will have the ability to communicate with InfluxDB Enterprise for LDAP authentication

### ISSUE THREAD

**Issue by lesam** [influxdata/docs-v2#2475]
This was previously a Kapacitor Enterprise feature and is being open-sourced.

The config is the same as Kapacitor Enterprise's was, except we add an 'enabled' flag:
https://github.com/influxdata/kapacitor/pull/2512#discussion_r600725219

**Comment by pierwill** [comment]
Closed in https://github.com/influxdata/docs-v2/pull/2756.
