### ISSUE TITLE
Line Protocol Tutorial doesn't list differences between Tags and Field values in terms of quotes

### ISSUE THREAD

**Issue by bogo666** [influxdata/docs-v2#2487]
In the "Tag Set" section, the docs do not discuss the differences between Tag and Field value string quoting. When performing an INSERT query, double quotes for Tag field values get included in the InfluxDB data, unlike Field values.

The docs need to make it clear that for Tag values, double quotes should not be used.

##### Relevant URLs
https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/

**Comment by sanderson** [comment]
Thanks @bogo666. The line protocol docs in the 1.x line could use some updating. In the mean time, you may be better served to use the line protocol reference in the 2.0 docs: https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/

I believe the only difference between line protocol in 1.x vs 2.0 is that 2.0 supports unsigned integers. I don't believe 1.8 does.

**Comment by sanderson** [comment]
Oh, to address your specific question, here's the section on quoting: https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/#quotes
