### ISSUE TITLE
Add further help on increasing ulimit in later OSX versions

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#2491]
* As mentioned in content/influxdb/v2.0/write-data/developer-tools/csv.md, increasing ulimit on Mac OS is required when importing data. But, as of OSX High Sierra, further environment config is required in order to change ulimit. See https://wilsonmar.github.io/maximum-limits/

##### Relevant URLs
- _Provide relevant URLs_

**Comment by kelseiv** [comment]
Sounds good, and makes sense!
