### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Thrinadh-Kumpatla** [influxdata/docs-v2#2507]
_Describe the issue here._

##### Relevant URLs
https://www.influxdata.com/blog/introduction-to-influxdatas-influxdb-and-tick-stack/

**Comment by jstirnaman** [comment]
@Thrinadh-Kumpatla Thank your for pointing this out.

### Details

The broken link to the Getting Started guide in

> To learn more about InfluxDB and the TICK Stack, read through the InfluxDB Getting Started guide. Then take a look at the InfluxDB key concepts doc, which is a great overview of the InfluxDB data model.

points to https://docs.influxdata.com/influxdb/latest/introduction/getting_started/. It seems we're missing a route for "/latest/".

Additionally, we may want to update the link to the "key concepts doc" and any others.
