### ISSUE TITLE
Request to add telegraf agent configuration example with rate limits in mind

### ISSUE THREAD

**Issue by bckeene** [influxdata/docs-v2#2512]
Starting to receive a lot of questions about running the default telegraf.conf, and running into challenges with rate limits under free and usage-based tiers. I often recommend users configure `flush_interval`,`metric_batch_size`, and `metric_buffer_limit` to prevent rate limit events (or to hold data in memory while the api reopens after 5 min. Many users if start by uploading historical data or naturally have spiky ingest. The added hostname is another default that causes confusion with some users outside of DevOps use cases and they're wondering why excess data is being sent to their instance (the user would need to find the `omit_hostname` flag).

I'm sure each case will be unique but I'd love for us to offer a boilerplate telegraf.conf with [best practices](https://docs.influxdata.com/influxdb/cloud/write-data/best-practices/optimize-writes/) implemented for the free and usage-based tiers. For example, I went through our canonical example of monitoring my system metrics with the free tier using a default configuration and hit the data-in limit after a few mins. Perhaps the free tier example slows the rate of data output to avoid hitting the 5Mb in 5 min threshold. Sure the telegraf team could provide much better guidance on this topic.

##### Relevant URLs
- [Use Telegraf to write data](https://docs.influxdata.com/influxdb/cloud/write-data/no-code/use-telegraf/) - sample telegraf.conf files would be available here.
- [InfluxDB Cloud pricing plans](https://docs.influxdata.com/influxdb/cloud/account-management/pricing-plans/) - rate limit explanation.
- [Agent configuration](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent) - telegraf configurations.

**Comment by russorat** [comment]
connect https://github.com/influxdata/ui/issues/1172

**Comment by daviddkkim** [comment]
@sjwang90 if this is to be included in the epic for telegraf uI refresh, could you add this in there?

**Comment by sjwang90** [comment]
https://github.com/influxdata/ui/issues/1406

**Comment by daviddkkim** [comment]
Chatted with Samantha, we will not make changes on the UI for this but rather make this a boilerplate config change

**Comment by sjwang90** [comment]
@bckeene we've implemented these improvements on the UI (https://github.com/influxdata/ui/pull/2762) - is having them in the docs something that'd still be helpful?

**Comment by bckeene** [comment]
@sjwang90 - It will be great to have the UI implement best practices under the hood. I think it'd also still be helpful to have a more complete example shown in the docs. We have [this example](https://docs.influxdata.com/influxdb/cloud/write-data/no-code/use-telegraf/manual-config/#example-influxdb_v2-configuration) showing the output configuration but there's no guidance on best practices for the [agent configuration](https://docs.influxdata.com/telegraf/v1.20/administration/configuration/#agent-configuration) which is often where users get tripped up. 

Realize this is a tough problem with all the different inputs/use-cases telegraf supports.

**Comment by sjwang90** [comment]
closed in #3300
