### ISSUE TITLE
Document autorefresh feature for cloud 2

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#2513]
https://github.com/influxdata/ui/pull/1226

We have added back the ability to configure auto refresh behind a feature flag `newAutoRefresh`

currently, it is only on in tools.

we will need to document this before turning it on in cloud prod.

FYI @ShmuelLotman

**Comment by kelseiv** [comment]
Thank you, @russorat, @ShmuelLotman! Closing per @noramullen1 [PR](https://github.com/influxdata/docs-v2/pull/2761)
