### ISSUE TITLE
`influx restore` docs show commands that are guaranteed to fail

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#2546]
A community member recently reported that `influx restore` doesn't work with the `--input` flag. When I investigated I found that the help text for `restore` is incredibly misleading, and the command actually expects/requires the path to backed-up data to be specified as a single positional arg. For example, instead of:
```
influx restore --input <path>
```
The command requires:
```
influx restore <path>
```
Any flags passed to `restore` must be passed before the positional arg:
```
influx restore --full <path>
```
All of the examples in our `influx restore` docs show use of `--input`.

##### Relevant URLs
- Original community report: https://community.influxdata.com/t/restore-says-must-specify-path-to-backup-directory/19879
- influxdata/influxdb#21475

**Comment by pierwill** [comment]
Closed in https://github.com/influxdata/docs-v2/commit/42d6288c71149f479c38e6d44371f3fb3117aa1f#diff-987db08473d99507c30afabfbcec3a4d2ef8f5b062d2408129e0f63da364092d
