### ISSUE TITLE
Chronograf: Fix spelling of --htpasswd command line option

### ISSUE THREAD

**Issue by janilahti** [influxdata/docs-v2#2550]
Chronograf documentation provides two ways to write command line option `--htpasswd` wrong. Using the provided example opens a security hole by not enabling any authentication upon startup. Command line option `--htpasswd` is written first as `-htpasswd` and then as `—-htpasswd`.

##### Relevant URLs
- https://docs.influxdata.com/chronograf/v1.8/administration/managing-security/#configure-chronograf-to-authenticate-with-a-username-and-password

**Comment by pierwill** [comment]
Thanks, @janilahti! Fixing this now.
