### ISSUE TITLE
typo in timedMovingAverage example

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [influxdata/docs-v2#2551]
The docs for moving average indicates
```
timedMovingAverage(
  every: 1d,
  period: 5d,
  column="_value"
)
```
while it should be
```
timedMovingAverage(
  every: 1d,
  period: 5d,
  column: "_value"
)
```

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/transformations/timedmovingaverage/

**Comment by sanderson** [comment]
Thanks @mirkocomparetti-synesis! Updated.
