### ISSUE TITLE
Flux task support in Kapacitor

### ISSUE THREAD

**Issue by lesam** [influxdata/docs-v2#2564]
https://github.com/influxdata/kapacitor/pull/2555
https://github.com/influxdata/kapacitor/pull/2544

This feature allows users to run flux tasks using Kapacitor. There is a detailed demo video available.

Config example:

```
[fluxtask]
  enabled = true
  task-run-influxdb = ""
  task-run-bucket = "taskbucket"
  task-run-org = ""
  task-run-orgid = ""
  task-run-measurement = "runs"
  [fluxtask.secrets]
    my_token = "a_very_secret_token"
    my_other_token = "a_different_one"
```

Note `task-run-bucket` is required config (it defaults to the empty string, which is invalid if `enabled=true`), and Kapacitor does not create this bucket automatically, it must be created in the associated influxdb instance (`task-run-influxdb` or else the `default` influxdb).

The exact API endpoints are TBD but it will conform to:

https://docs.influxdata.com/influxdb/cloud/api/#tag/Tasks

except that Kapacitor does not have `owners`, `members`, or `labels` related APIs. Kapacitor also does not have a fine grained ACL, so any user that has permission to use the Kapacitor API can view / update / delete all tasks from all users.

**Comment by sanderson** [comment]
@lesam Is this slated for Kapacitor 1.6.0?

**Comment by lesam** [comment]
Yes, 1.6

**Comment by lesam** [comment]
Added a config feature: `task-run-influxdb = "none"` means you don't have an influxdb to store analytic data in, so you can't access historical task runs and logs, only run and log info for currently running tasks.
