### ISSUE TITLE
Add a note that you cannot use specific fields when you delete with predicate

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#2571]
https://docs.influxdata.com/influxdb/cloud/reference/syntax/delete-predicate/#limitations

As reported in this issue https://github.com/influxdata/influxdb/issues/20704 and the related issues, it is not possible to delete a specific _field value in InfluxDB. We should update the docs to reflect this.

**Comment by aldas** [comment]
@russorat will deleting/dropping field will be implemented in InfluxDB ever?

https://github.com/influxdata/influxdb/issues/6150 is from 2016
https://github.com/influxdata/influxdb/issues/20399 is 6 months old
