### ISSUE TITLE
Demo data revamp

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2588]
Discussion with @noramullen1 and @sanderson 
resulted in a few items to clarify/improve in our demo data docs:
- Change header from ["Demo data for InfluxDB Cloud"](https://docs.influxdata.com/influxdb/cloud/write-data/#demo-data-for-influxdb-cloud) to "Use demo data in InfluxDB Cloud"
- Change header from ["Demo data sets"](https://docs.influxdata.com/influxdb/cloud/write-data/#demo-data-sets) to Choose demo data set
- In same doc above, explicitly clarify distinction between demo data and sample data.
- Remove video in [Sample data doc](https://docs.influxdata.com/influxdb/cloud/reference/sample-data/)
- Also in Sample data doc, remove link in this sentence: Use InfluxDB Cloud demo data buckets for quick, free access to different types of sample data.
- Add link in ["Sample data" doc](https://docs.influxdata.com/influxdb/cloud/reference/sample-data/#influxdb-cloud-demo-data) to ["Write data to InfluxDB - Using demo data in InfluxDB Cloud"](https://docs.influxdata.com/influxdb/cloud/write-data/#use-demo-data-in-influxdb-cloud)
- Also in Sample data doc, remove this statement: InfluxData provides many sample time series datasets to use with InfluxDB Cloud. Add link to Website Monitoring template
- Update related and tags on conceptual, procedural, and reference demo data docs as applicable

**Comment by timhallinflux** [comment]
Consider creating a set of notebooks which can be offered to users as a InfluxDB template.  Meaning, within the docs...create a notebook which can be imported to provide an interactive means of exploring the data and functionality.

**Comment by timhallinflux** [comment]
Another issue is accessing Demo Data via API.   It appears that this is not possible and we should call out this limitation in the docs.  Demo Data is only available through interactive exploration via the UI.
