### ISSUE TITLE
InfluxDB Enterprise 1.9 - influx  examples

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#2595]
Within Tools there is a standalone page for `influx` and all of its various parameters.
However, there is a page for using `influx` which is further down the menu tree.  I would suggest two things:
1) make using influx a page underneath the influx page (and command syntax)
2) hyperlink the command syntax examples to the using page so that for example... if you click on -import, it takes you to the using Influx page where the -import flag is used.

**Comment by pierwill** [comment]
Will tackle this after #2608 merges.
