### ISSUE TITLE
Can we document that the 2.0 CLI doesn’t have an interactive shell?

### ISSUE THREAD

**Issue by mssach** [influxdata/docs-v2#2601]
1. Do we have anywhere in 2.0 doc stating that the 2.0 CLI doesn’t have an interactive shell? If not, please add.
2. Do we have anywhere in 2.0 doc stating what changes done from 1.x to 2.x that it combines database and retention policy in an object called a bucket & doesn't has DB? If not, please add.

I got the info regarding these after connecting to influxdb slack community channel.

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/get-started/

**Comment by noramullen1** [comment]
Hi @mssach,

Thanks for reaching out. 

> 1. Do we have anywhere in 2.0 doc stating that the 2.0 CLI doesn’t have an interactive shell? If not, please add.

We've added this in PR #2758 .

> 2\. Do we have anywhere in 2.0 doc stating what changes done from 1.x to 2.x that it combines database and retention policy in an object called a bucket & doesn't has DB? If not, please add.

This information is already mentioned throughout the [upgrade docs](https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/), with the most detail [here](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/dbrp/). Let us know if you have further questions.

Thanks,
Nora
