### ISSUE TITLE
Typo in date.truncate

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [influxdata/docs-v2#2611]
There is a typo in the example for date.truncate

Current:
```
import "date"

date.truncate(
  t: 2019-07-17T12:05:21.012Z
  unit: 1s
)
```

Expected:
```
import "date"

date.truncate(
  t: 2019-07-17T12:05:21.012Z,
  unit: 1s
)
```

##### Relevant URLs
- Doc page https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/date/truncate/

**Comment by pierwill** [comment]
Thanks, @mirkocomparetti-synesis !
