### ISSUE TITLE
Document the `kapacitor/v1/users` API

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2617]
Document `kapacitor/v1/users` API used to create users in Kapacitor locally. Useful for OSS users given they won't have a meta-node to authenticate against.

Work with @lesam

**Comment by lesam** [comment]
Some examples of commands:

```
curl -XPOST "http://localhost:9092/kapacitor/v1/users" -d '{ "name": "stan", "password": "pass", "type":"normal", "permissions":["config_api"] }'

curl -XPATCH "http://localhost:9092/kapacitor/v1/users/bob" -d '{ "password": "pass", "type":"admin", "permissions":["all"] }'

curl GET "http://stan:pass@localhost:9092/kapacitor/v1/users"

curl -XDELETE "http://bob:pass@localhost:9092/kapacitor/v1/users/steve"
```

Valid user types: "user", "admin"
Valid permissions: "none", "api", "config_api", "write_points", "all"

**Comment by jstirnaman** [comment]
> Some examples of commands:
> 
> ```
> curl -XPOST "http://localhost:9092/kapacitor/v1/users" -d '{ "name": "stan", "password": "pass", "type":"normal", "permissions":["config_api"] }'
> 
> curl -XPATCH "http://localhost:9092/kapacitor/v1/users/bob" -d '{ "password": "pass", "type":"admin", "permissions":["all"] }'
> 
> curl GET "http://localhost:9092/kapacitor/v1/users"
> 
> curl -XDELETE "http://localhost:9092/kapacitor/v1/users/steve"
> ```
> 
> Valid user types: "user", "admin"
> Valid permissions: "none", "api", "config_api", "write_points", "all"

Hi, @lesam. I haven't been able to test 1.6 yet. Can you clarify user `type` for me? Your example uses `normal`, but your list of valid user types says `user` and `admin`.
Thanks.

**Comment by lesam** [comment]
Ah oops - yes the example is correct, it should be `normal` and `admin`. Though in practice setting anything but `admin` I believe will result in a 'normal' user.

https://github.com/influxdata/kapacitor/blob/793204b1f29ee9adbe507bd2a07176bc58b15435/client/v1/client.go#L72
