### ISSUE TITLE
Missing basic concepts in Flux docs?

### ISSUE THREAD

**Issue by dandv** [influxdata/docs-v2#2621]
I'm transitioning from InfluxQL to Flux and am having a harder time than I think is warranted.

I've read the [Get started with Flux](https://docs.influxdata.com/influxdb/v2.0/query-data/get-started/), [Query InfluxDB with Flux](https://docs.influxdata.com/influxdb/v2.0/query-data/get-started/query-influxdb/), [Query data with Flux](https://docs.influxdata.com/influxdb/v2.0/query-data/flux/) pages several times, as well as [Querying fields and tags](https://docs.influxdata.com/influxdb/v2.0/query-data/flux/query-fields/).

I haven't seen it mentioned anywhere explicitly,
* Why some record fields in the filter `fn` start with an underscore. Presumably `_measurement` is reserved, but why also `_field`? In InfluxDB, a record has a [field set](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#field-set), so there should be multiple fields?
* What all these `_`-prefixed record fields are
* How to query for a record with a given field value (I know that's not a recommended practice in InfluxQL, but it's possible)

I also miss the examples from v1, and IMO the [key concepts explanation from v1.8](https://docs.influxdata.com/influxdb/v1.8/concepts/key_concepts/) was far clearer and better illustrated with the butterflies and water levels examples. The v2 Flux docs feel more arid, seem to assume the reader is familiar with a lot of concepts, and its [Key concepts](https://docs.influxdata.com/influxdb/v2.0/query-data/get-started/#key-concepts) section is tiny.

**Comment by timhallinflux** [comment]
thanks @dandv appreciate your take and feedback on this.  We will take a look at adding more conceptual overviews to the docs.  I think another missing item is the InfluxDB to Relational DB comparison that existed in v1.8 and we didn't update that for either Cloud or OSS in v2.
