### ISSUE TITLE
Add a note to the influx write csv content about incompatible line endings

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#2623]
i ran into this issue trying to load a csv file today: https://github.com/influxdata/influx-cli/issues/106

It boiled down to having a file with incompatible line endings.

Is there a place in the docs where we can add a message about troubleshooting this? Maybe somewhere on this page https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/write/ or one of the loading csv guides?

**Comment by pierwill** [comment]
Addressed in https://github.com/influxdata/influx-cli/pull/109.
