### ISSUE TITLE
Add content about setting up and configuring influx cli with your cloud account

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#2624]
I was trying to provide instructions to a cloud user about setting up the influx command line tools, and i couldn't find a good page to link them to in the cloud docs.

There's this: https://docs.influxdata.com/influxdb/cloud/reference/cli/ but it doesn't tell you anything about setting up and configuring it. Same with this page: https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/ there's no real install instructions or guidance on how to use it with cloud.

I propose a dedicated page for setting up the influx cli tool to work with your cloud account. the outline would be as follows:
- Intro
- Download and install the influx cli tool
- Configure the cli tool to connect to your cloud instance
- Additional references and/or examples

**Comment by timhallinflux** [comment]
Is this addressed as part of the new get started content?

**Comment by noramullen1** [comment]
Hi @russorat and @timhallinflux , 

We have this information documented in the following places:

- Download and install CLI is in the [Cloud Sign Up doc](https://docs.influxdata.com/influxdb/cloud/sign-up/#optional-download-install-and-use-the-influx-cli). 
- Configure CLI tool to connect to cloud is on the [reference index page ](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/#provide-required-authentication-credentials). This page is also linked from every CLI example page in the related section.

Does that cover the content you're looking for? Let me know what you think.

Thanks,
Nora

**Comment by timhallinflux** [comment]
I think the answer is no.  We need to be a bit stronger in terms of using the CLI with Cloud.
