### ISSUE TITLE
Remove usage api ref from oss docs

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#2652]
https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/experimental/usage/from/
https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/experimental/usage/limits/

These are only relevant to InfluxDB Cloud and should be removed from the OSS docs.

**Comment by sanderson** [comment]
This will be fixed when the `flux-restructure` branch merges.
