### ISSUE TITLE
Check "Static legend" docs

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs-v2#2657]
Static legend: do we need to remove ref to “Legend Orientation” or the “Legend” type  here and convert to “StaticLegend”:
https://docs.influxdata.com/influxdb/v2.0/visualize-data/visualization-types/histogram/#legend

And/or link to?

(One to check for cloud too)

_Originally posted by @kelseiv in https://github.com/influxdata/docs-v2/pull/2654#discussion_r644973703_

**Comment by noramullen1** [comment]
this is part of feature work being tracked in other issues. addressed by #2798
