### ISSUE TITLE
Clarify tasks execute at the top of the following hour, minute, etc 

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2672]
In the [Task configuration options doc](https://docs.influxdata.com/influxdb/cloud/process-data/task-options/), clarify the `every` option determines _when_ a task is initially executed (in addition to the subsequent intervals the task is executed).

If you save the following task in the UI at 2:30pm (or schedule this task to run at 2:30 pm):
`option task = {name: "aggregation", every: 1h}`

The task first executes at 3:00pm, and subsequently every hour after that. 

Likewise, if you schedule the following task at 2:30.05 pm:
`option task = {name: "aggregation", every: 1m}`

The task first executes at 2:31.00 pm, and subsequently every minute after that.

cc @bckeene @rbetts

**Comment by mluu12** [comment]
Thank you @bckeene @rbetts, we've clarified how the every option works.
