### ISSUE TITLE
Add the `allowInsecure` option to UI

### ISSUE THREAD

**Issue by 4N7** [influxdata/docs-v2#2704]
I cannot figure out how to configure the scraper on InfluxDB OSS 2.0.7.
In particular, I am trying to skip the validation on self-signed certificates.

I see that skipping validation on self-signed certificates was made available in [20047](https://github.com/influxdata/influxdb/pull/20047/files). However, I don't see the `allowInsecure` field in the UI. Additionally, I don't see it documented anywhere on how to take advantage of this feature. I could just be misunderstanding something here. 

#### Relevant URLs
The [create a scraper](https://docs.influxdata.com/influxdb/v2.0/write-data/no-code/scrape-data/manage-scrapers/create-a-scraper/) document is vague and does not mention how to allow skipping validation on self-signed certificates.

The [release Notes for v2.0.2](https://docs.influxdata.com/influxdb/v2.0/reference/release-notes/influxdb/) mentions that the following features were added, but nowhere does it mention how to configure them.
- *Allow scraper to ignore insecure certificates on an endpoint.*
- *Allow self-signed certificates for scraper targets.*

**Comment by 4N7** [comment]
This has been acknowledged in [1718](https://github.com/influxdata/ui/issues/1718).

**Comment by sanderson** [comment]
Thanks @4N7. The field is available in the scraper API: https://docs.influxdata.com/influxdb/v2.0/api/#operation/PostScrapers

The API call would look something like:

```sh
curl --request POST http://localhost:8086/api/v2/scrapers \
  --header 'Authorization: Token YOURAUTHTOKEN' \
  --header 'Content-type: application/json' \
  --data '{
  "name": "Scraper name",
  "type": "prometheus",
  "url": "http://localhost:9090/metrics",
  "orgID": "yourOrgID",
  "bucketID": "yourBucketID",
  "allowInsecure": true
}'
```

The **allowInsecure** option hasn't been added to the UI yet, but @jstirnaman, we can probably add this example of adding a scaper via the API to the [Create a scraper](https://docs.influxdata.com/influxdb/v2.0/write-data/no-code/scrape-data/manage-scrapers/create-a-scraper/) page.
