### ISSUE TITLE
Document running InfluxDB as a Windows service

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#2711]
Need a set of instructions for InfluxDB on Windows for setting it up and running it as a service....

Telegraf  example: https://docs.influxdata.com/telegraf/v1.18/administration/windows_service/

**Comment by pierwill** [comment]
Checking with the team, but it looks like this is not currently supported for InfluxDB 2.x.

**Comment by pierwill** [comment]
Closing as possible duplicate of #1060.
