### ISSUE TITLE
404 on time-series-index

### ISSUE THREAD

**Issue by NielsH** [influxdata/docs-v2#2719]
Hello,

The page https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kubernetes mentions "Consider using the Time Series Index." which links to https://docs.influxdata.com/influxdb/latest/concepts/time-series-index/ however this page gives a 404. The 404 error mentioned I should report it here.

Cheers!

**Comment by NielsH** [comment]
Oh, just noticed, the link above that, to https://docs.influxdata.com/influxdb/latest/guides/downsampling_and_retention/ also gives a 404.

Thanks in advance!

**Comment by kelseiv** [comment]
thank you, @NielsH! resolved
