### ISSUE TITLE
The examples are not working any longer

### ISSUE THREAD

**Issue by vertisan** [influxdata/docs-v2#2720]
The examples on the website no longer work.  
We should receive some results but currently, we are getting errors, i.e. for:  
```
from(bucket: "noaa")
  |> group()
  |> keep(columns: ["location"])
  |> unique(column: "location")
```
we are getting an error:
```
error in building plan while starting program: cannot submit unbounded read to "noaa"; try bounding 'from' with a call to 'range'
```
and when we provide a range
```
keep: schema collision: cannot group float and string types together
```

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.0/query-data/common-queries/count_unique_values_for_column/

**Comment by sanderson** [comment]
@vertisan We're updating these examples to include a `range()` call which will fix your first issue, but I'm unable to reproduce your 2nd error. To me that says that your noaa bucket contains data other than the sample data. The sample data only has string values in the `location` column; no floats. Is there any chance you could've unintentionally intermingled data?
