### ISSUE TITLE
InfluxDB Enterprise 1.9 - pushdown functions -- include last, min, max

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#2737]
enterprise_influxdb/v1.9/flux/guides/optimize-queries/

These three functions were added.  Perhaps we borrow https://docs.influxdata.com/influxdb/cloud/query-data/optimize-queries/#start-queries-with-pushdowns
and then advance the chart as the pushdowns land in subsequent releases?

We should indicate that the plan is to advance the pushdown functions in subsequent maintenance releases of InfluxDB Enterprise to deliver parity against what is listed for Cloud and OSS

**Comment by timhallinflux** [comment]
@sanderson  thoughts on this?

**Comment by sanderson** [comment]
I've been using [this sheet](https://docs.google.com/spreadsheets/d/1yNWxrVoL9AEUVdoKVe9ZLWmqdpaSfYtxO2_lvxSk-Fw/edit#gid=0) to track support for pushdowns. Does Enterprise pushdown support now match OSS 2.0?

**Comment by timhallinflux** [comment]
no, it does not.
