### ISSUE TITLE
Delete an Organization using InfluxDB UI

### ISSUE THREAD

**Issue by victor-costa-avancee** [influxdata/docs-v2#2797]
I don't believe it is possible to delete an Organization using InfluxDB UI (I still haven't managed to find how) yet the "Manage organizations" page has this text: "Delete an existing organization from InfluxDB using the InfluxDB UI or the influx CLI.". The "Delete an organization" page also has no reference on how to delete an organization using InfluxDB UI.
Instead of correcting the docs, I believe it is worthwhile to add the delete organization functionality to InfluxDB UI.

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/organizations/
https://docs.influxdata.com/influxdb/v2.0/organizations/delete-org/

**Comment by noramullen1** [comment]
Hi @victor-costa-avancee,

We've updated the docs to clarify that you can only delete using the UI. If you want to submit a feature request to add that, submit an issue to the [InfluxDB repo](https://github.com/influxdata/influxdb). 

Thanks,
Nora
