### ISSUE TITLE
`latest-patch` shortcode not working in PowerShell code block

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs-v2#2809]
Code: 

https://github.com/influxdata/docs-v2/blob/5eb96ebd2ee3accb60bb9efbdeb08efa034d2cf6/content/telegraf/v1.18/administration/windows_service.md#L33-L50

<img width="911" alt="Screen Shot 2021-07-06 at 10 52 13 AM" src="https://user-images.githubusercontent.com/19642016/124630656-431e4180-de48-11eb-9428-47fec10a1747.png">

**Comment by pierwill** [comment]
When I remove the `powershell`, the shortcode works fine.

**Comment by sanderson** [comment]
Have a PR to fix this. I'm not 100% sure why, but to get the `latest-patch` shortcode to render correctly in powershell code blocks, you have to render the shortcode as markdown instead of HTML.

```html
{{% latest-patch %}} <!-- This renders correctly in powershell code blocks -->
{{< latest-patch >}} <!-- This does not -->
```
