### ISSUE TITLE
clarify auth/limits on use of influxdb.api()

### ISSUE THREAD

**Issue by jdstrand** [influxdata/docs-v2#2833]
Our docs for `influxdb.api()` say: "_The influxdb.api() function submits an HTTP request to the specified InfluxDB API path and returns a record containing the HTTP status code, response headers, and response body as a byte array._"

I think it would be helpful to add something about what the query is allowed to do. Eg, change the above to:

"_The influxdb.api() function submits an HTTP request to the specified InfluxDB API path and returns a record containing the HTTP status code, response headers, and response body as a byte array. Queries via influxdb.api() are run under the authorization of the invoking user and have the same limits applied as when directly accessing the API (such as with curl)._"

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/experimental/influxdb/api/
- https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/experimental/influxdb/api/

**Comment by gavincabbage** [comment]
Slight adjustment, because a user can optionally provide a token for the request to use:

> Unless a token argument is provided, requests via influxdb.api() are run under the authorization of the invoking user and have the same limits applied as when directly accessing the API (such as with curl).

Also changed "queries" to "requests" since this applies across all endpoints.
