### ISSUE TITLE
Windows CLI tool can't be downloaded.

### ISSUE THREAD

**Issue by ivanflux** [influxdata/docs-v2#2839]
**Describe the issue here:**

Windows CLI tool can't be downloaded.

**Relevant URLs**
https://docs.influxdata.com/influxdb/cloud/sign-up/?t=Windows#optional-download-install-and-use-the-influx-cli

results in 

Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>influxdb/releases/influxdb2-2.0.7-windows-amd64.tar.gz</Key>
<RequestId>AP261BE5SJBXRYP9</RequestId>
<HostId>fk0+/umpi4k3PPOHnHDxctmpKYW6W1ZM2E+hMXZ7mC8PHQgZF+wOrBE4ae25+GuQAje4P99LFGk=</HostId>
</Error>

**Fix:**
change link to https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.7-windows-amd64.zip

**Comment by pierwill** [comment]
Thanks, @ivanflux!
