### ISSUE TITLE
Broken link for "Write data with client libraries" documentation page.

### ISSUE THREAD

**Issue by brembo97** [influxdata/docs-v2#2869]
Broken link for the "Write data with client libraries" documentation page. Page redirects to 404 not found route.

##### Relevant URLs
Broken link: https://docs.influxdata.com/influxdb/v2.0/tools/client-libraries/
Featured in: https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/client-libraries/

**Comment by kelseiv** [comment]
Thank you, @brembo97 - now is fixed
