### ISSUE TITLE
Mangled "Perform the upgrade" heading

### ISSUE THREAD

**Issue by jplitza** [influxdata/docs-v2#2894]
Commit 4c6beb3d08d555b92521e61f262f2d9340f1569b introduced an unclosed suggestion block (that I'm not even sure is supported, since I didn't find any other occurrence in this repo), which mangles the following heading "Perform the upgrade" and a few following paragraphs.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/automatic-upgrade/#interactive-shell

**Comment by kelseiv** [comment]
Thank you, @jplitza! fixed
