### ISSUE TITLE
Dead link to GitHub issue in location reference

### ISSUE THREAD

**Issue by alekbless** [influxdata/docs-v2#2913]
_Describe the issue here._

When clicking "IMPL#660 Implement Location option" link under location options the issue is not found on GitHub.

Should this be the correct link? https://github.com/influxdata/flux/issues/406

##### Relevant URLs
- _Provide relevant URLs (the doc page in question, project issues, community threads, etc.)_
- https://docs.influxdata.com/influxdb/v2.0/reference/flux/language/options/#location
- https://github.com/influxdata/platform/issues/660

**Comment by kelseiv** [comment]
thank you, @alekbless! resolved
