### ISSUE TITLE
Delete organization in Cloud

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2914]
Document the "Delete organization <username account>" option
In Cloud, select your avatar > About to open the Organization page.

Side note: We won't mention or link to this content in the July Cloud updates. 
Reason being: The primary intention for this feature is a precursory work to the upcoming Multi-user feature, so we'll highlight all the functionality in Cloud updates when the Multi-user feature goes out.

**Comment by kelseiv** [comment]
cc @bpalani and @gunnaraasen for review

**Comment by mluu12** [comment]
This issue was resolved.

**Comment by gunnaraasen** [comment]
@mluu12 where was this added?

**Comment by mluu12** [comment]
@gunnaraasen after some clarification from @bpalani I will be merging this PR https://github.com/influxdata/docs-v2/pull/2997 immediately that deals with 2914. I could've added this issue along with https://github.com/influxdata/docs-v2/issues/2330, but that's my mistake!

**Comment by gunnaraasen** [comment]
Got it. Thanks for the pointers!
