### ISSUE TITLE
Broken link from influx documentation

### ISSUE THREAD

**Issue by AlanTWatson** [influxdata/docs-v2#2915]
Influx documentation page: https://help.influxcloud.net/getting_started_cli/

The link in the words "Command Line Interface" in the sentence "The following steps demonstrate how to use InfluxDB’s Command Line Interface to..." is broken. The link address https://docs.influxdata.com/influxdb/v2.0/tools/shell/ returns a 404.

**Comment by kelseiv** [comment]
Thank you, AlanTWatson! fixed
