### ISSUE TITLE
404 for writeRecord(record)	Write a line of [Line Protocol](https://bit.ly/2QL99fu).

### ISSUE THREAD

**Issue by kakulukia** [influxdata/docs-v2#2921]
https://influxdata.github.io/influxdb-client-js/influxdb-client.writeapi.html includes a not working bit.ly-URL.
Its used 3 times on this page and looks like MD-Syntax coming from somewhere else.

In the First paragraph there also is an escaped HTML token "<p> The data are formatted in [Line Protocol](https://bit.ly/2QL99fu). <p>"

##### Relevant URLs
https://influxdata.github.io/influxdb-client-js/influxdb-client.writeapi.html

**Comment by kelseiv** [comment]
Related https://github.com/influxdata/docs-v2/issues/2817
