### ISSUE TITLE
Add how to load line protocol through the UI

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#2952]
- Add how to load line protocol in the UI on the following pages:
  - https://docs.influxdata.com/influxdb/v2.0/write-data/load-data/
  - https://docs.influxdata.com/influxdb/cloud/write-data/load-data/
 - Group Load data source in UI under "No-code solutions"

**Comment by sjwang90** [comment]
Some conversations about upload LP through the UI here too - https://github.com/influxdata/docs-v2/issues/2007
