### ISSUE TITLE
Update docs to mention Free tier cancelation/account deletion ability

### ISSUE THREAD

**Issue by bckeene** [influxdata/docs-v2#3004]
I believe we now enable self-serve account cancelation/deletion for Free tier accounts:

<img width="1056" alt="Screen Shot 2021-08-11 at 8 34 27 AM" src="https://user-images.githubusercontent.com/3768387/129059563-cd8f14f5-5473-4683-9a09-53043882e033.png">

##### Relevant URLs
- _https://docs.influxdata.com/influxdb/cloud/account-management/offboarding/#cancel-service_

**Comment by kelseiv** [comment]
Thank you, @bckeene - this [PR ](https://github.com/influxdata/docs-v2/pull/2997/files)@mluu12 is working on will resolve this issue.

**Comment by mluu12** [comment]
Hi @bckeene, this issue was solved with #2997!
