### ISSUE TITLE
Typos in example of delete data using the API

### ISSUE THREAD

**Issue by cm0x0x0x0** [influxdata/docs-v2#3035]
*Delete points in a specific measurement with a specific tag value*
```
curl --request POST http://localhost:8086/api/v2/delete/?org=example-org&bucket=example-bucket \
  --header 'Authorization: Token <YOURAUTHTOKEN>' \
  --header 'Content-Type: application/json' \
  --data '{
    "start": "2020-03-01T00:00:00Z",
    "stop": "2020-11-14T00:00:00Z",
    "predicate": "_measurement=\"example-measurement\" AND exampleTag=\"exampleTagValue\""
  }'
```
*Delete all points in a specified time range*
```
curl --request POST http://localhost:8086/api/v2/delete/?org=example-org&bucket=example-bucket \
  --header 'Authorization: Token <YOURAUTHTOKEN>' \
  --header 'Content-Type: application/json' \
  --data '{
    "start": "2020-03-01T00:00:00Z",
    "stop": "2020-11-14T00:00:00Z"
  }'
```
In the above, there should be no slash("/") after "delete" at `http://localhost:8086/api/v2/delete/?org=example....`

<img width="884" alt="스크린샷 2021-08-19 오전 10 08 51" src="https://user-images.githubusercontent.com/57793065/129992993-bb27708b-60cf-4e61-9eed-4c247f26c4dd.png">

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.0/write-data/delete-data/

**Comment by jstirnaman** [comment]
Fixed in 1db152f5ab
