### ISSUE TITLE
Link goes to unexpected destination

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#3050]
On [this page](https://docs.influxdata.com/influxdb/cloud/tools/chronograf/), step 3 of connection configuration has a link to example OSS URLs.  This link goes to Cloud URLs only.

**Comment by noramullen1** [comment]
@sanderson -- This looks correct in the source file and it works as expected in the 2.x docs, but in the duplicate-oss version it changes `/influxdb/v2.1/reference/urls` to `/influxdb/cloud/reference/urls`. Is there a way around this?

**Comment by sanderson** [comment]
@noramullen1 yeah, you can use the cloud-only and oss-only short idea to add unique links for each context.

**Comment by sanderson** [comment]
Ohhhh, ok. I see the problem... I've run into the same issue and have a really hacky way of getting around it. So the `duplicate-oss` shortcode looks for "v2.x"  in URLs and replaces them with "cloud". If you ascii-encode the "v" in "v2.1", it makes is so the link doesn't get updated, but still works.

```
/influxdb/%762.1/reference/urls/
```

Actually, while you're at it @noramullen1, could you do a quick find and replace for `/influxdb/%762.0/` in the 2.1 docs and replace them with `/influxdb/%762.1/`?
