### ISSUE TITLE
SHOW CONTINUOUS QUERY now respects database permissions

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/docs-v2#3054]
`SHOW CONTINUOUS QUERY` will now only show queries in databases that would be visible to the user via `SHOW DATABASES`

Original issue: https://github.com/influxdata/influxdb/issues/10292
PR in the 1.9 branch: https://github.com/influxdata/influxdb/pull/22289

This will first be released in 1.9.4

**Comment by pierwill** [comment]
Covered in https://github.com/influxdata/docs-v2/pull/3126.
