### ISSUE TITLE
Investigate using Coveo to power search in the docs

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#3061]
Coveo provides search results from all InfluxData content sources (docs, community, blog, etc.) and is currently being used by the support team to help with customer questions. There are plans to integrate Coveo-powered search in other places including the InfluxDB Cloud UI and the InfluxData community.

We should look into either replacing or augmenting our current Algolia-powered search functionality with Coveo.

##### Relevant Coveo documentation links
- [Use the Coveo JavaScript Search Framework](https://docs.coveo.com/en/375/)
- [Perform a Simple Query (API)](https://docs.coveo.com/en/114/)
- [Search Token Authentication (API)](https://docs.coveo.com/en/56/)

**Comment by kelseiv** [comment]
tagging @mavarius for visibility

**Comment by sanderson** [comment]
As a stop-gap, we've added #3534 and will close this issue for now.
