### ISSUE TITLE
Missing information to add a new/2nd admin

### ISSUE THREAD

**Issue by gn0m3r4l** [influxdata/docs-v2#3086]
For Versions below 2.0, there was a documentation how to add a 2nd admin user. Is there a way to do so by using the cli?

**Comment by sanderson** [comment]
@gn0m3r4l For 1.x, adding a 2nd admin user is still possible (as shown [here](https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/#create-another-admin-user)).

In 2.0, permissions and authorizations are handled through [API tokens](https://docs.influxdata.com/influxdb/v2.0/security/tokens/). There are three different types of API tokens: operator, all-access, and read/write. I'm assuming the type of permissions you're looking for are operator token permissions (all access across all organizations). Currently, the only time an operator token is created is during the initial InfluxDB setup process. There currently isn't a way to manually create a new operator token.

If you just need full access within the scope of a single organization, the all-access token is what you're looking for.

If being able to add more operator tokens and associate those with users is functionality you're interested in, go ahead and file a [feature request on the InfluxDB repo](https://github.com/influxdata/influxdb/issues/new?assignees=&labels=&template=feature_request.md).
