### ISSUE TITLE
InfluxQL compatibility docs -- Cardinality meta queries are missing/incomplete

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#3098]
We have not implemented:
SHOW SERIES
or 
SHOW CARDINALITY (and the associated CARDINALITY meta queries)[https://docs.influxdata.com/influxdb/v1.8/query_language/explore-schema/#show-cardinality]

as part of InfluxDB Cloud or OSS 2.x

We should add these two to the unsupported list.

We should highlight these the equivalent Flux-based approach.

For example:
Cloud supports: https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb/cardinality/

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud/query-data/influxql/

**Comment by lwandzura** [comment]
We will be publishing InfluxQL for 2.x in the next 2 weeks, and have updated the supported/unsupported statements.  SHOW SERIES and SHOW SERIES EXACT CARDINALITY are implemented.
