### ISSUE TITLE
Enterprise full restore claims not to restore metadata

### ISSUE THREAD

**Issue by lesam** [influxdata/docs-v2#3101]
This note looks wrong:

https://docs.influxdata.com/enterprise_influxdb/v1.9/administration/backup-and-restore/#:~:text=Restoring%20from%20a%20full%20backup%20does%20not%20restore%20metadata.%20To%20restore%20metadata%2C%20restore%20a%20metadata%20backup%20separately

> Restoring from a full backup does not restore metadata. To restore metadata, restore a metadata backup separately.

I don't think this is correct. I tried a backup and restore:

```
/ # ./influxd-ctl backup -full /root/.influxdb/backup_dir
Backing up meta data... Done. 199227 bytes transferred
Backing up node from_data_1_1:8088, db _internal, rp monitor, shard 1... Done. Backed up in 58.5833ms, 505856 bytes transferred
Backing up node from_data_0_1:8088, db _internal, rp monitor, shard 2... Done. Backed up in 69.3602ms, 457216 bytes transferred
Backing up node from_data_0_1:8088, db test, rp autogen, shard 3... Done. Backed up in 22.9709ms, 2048 bytes transferred
Backing up node from_data_0_1:8088, db telegraf, rp autogen, shard 4... Done. Backed up in 48.1072ms, 33792 bytes transferred
Backed up to /root/.influxdb/backup_dir in 215.2971ms, transferred 1198139 bytes

/ # ./influxd-ctl restore -full /root/.influxdb/backup_dir/20210909T152629Z.manifest
Using manifest: /root/.influxdb/backup_dir/20210909T152629Z.manifest
Restoring meta data... Done. Restored in 49.8315ms, 2 shards mapped
Restoring db test, rp autogen, shard 3 to shard 3...
Copying data to to_data_0_1:8088... done.
Copying data to to_data_1_1:8088... done.
Done. Restored shard 3 into shard 3 in 345.3278ms, 4096 bytes transferred
Restoring db telegraf, rp autogen, shard 4 to shard 4...
Copying data to to_data_0_1:8088... done.
Copying data to to_data_1_1:8088... done.
Done. Restored shard 4 into shard 4 in 719.4041ms, 67584 bytes transferred
Restored from /root/.influxdb/backup_dir in 1.1150891s, transferred 71680 bytes
```

It says it is restoring the metadata, and continuous queries and empty databases are restored properly, so it looks like the metadata is really applied.

**Comment by lesam** [comment]
Why was this added in the first place? I wonder if there is some aspect of the metadata that is not restored that I am missing.

**Comment by pierwill** [comment]
> I wonder if there is some aspect of the metadata that is not restored that I am missing.

Possibly... I tried hunting in the git history and couldn't come up with anything useful. Let's remove this since the weight of evidence is against it.
