### ISSUE TITLE
Weird redirect

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/docs-v2#3118]
Reproduce:

Firefox on MacOS
Navigate to https://docs.influxdata.com/influxdb/cloud/write-data/delete-data/
Click link `/api/v2/delete`
Observe correct navigation, a page describing the delete API at https://docs.influxdata.com/influxdb/cloud/api/#operation/PostDelete

Wait a couple of seconds...

**Be redirected to https://docs.influxdata.com/influxdb/cloud/api/**

Ping @sanderson and ask "What's up with this?"
Write this issue

**Comment by sanderson** [comment]
I was able to replicate this in Firefox, but not in Chrome or Safari. I've seen this happen in Chrome after an update to `redoc-cli`, but rolling back to and locking to a previous version seemed to fix the issue. It appears that not all the redoc JS is getting loaded and crashes the page.

Here's the browser errors from Firefox:

![image](https://user-images.githubusercontent.com/181484/133287437-b45b31be-1517-4357-a545-8491037c30c8.png)

**Comment by kelseiv** [comment]
Thanks for reporting, @jacobmarble & thank you for sharing background, @sanderson. How long would it take to test if locking redoc-cli version (to the same version that fixed Chrome?) resolves this firefox issue?

**Comment by noramullen1** [comment]
@sanderson, just following up on Kelly's note above (when you have time). Thanks!

**Comment by sanderson** [comment]
This is something that breaks in the JS execution as it renders the page. Currently, the API docs contain a ton of Javascript that render all the API doc HTML client-side. We're looking into ways to pre-render the HTML so it doesn't really on JS to build the page on load.

We don't have a quick fix, but this is something we're aware and looking into fixing. cc @jstirnaman

**Comment by noramullen1** [comment]
Thanks @sanderson! Closing this issue for now.
