### ISSUE TITLE
New Third Party Links

### ISSUE THREAD

**Issue by edgebroker** [influxdata/docs-v2#3165]
_Describe your proposal here._

Can you please add Flow Director to the list of third-party integrations? We have recently released MQTT / InfluxDB and Kafka / InfluxDB and will provide further integrations soon.

##### Relevant URLs
- _Provide relevant URLs_

All:
https://www.flowdirector.io/apps/?tags=InfluxDB

Available:
https://www.flowdirector.io/apps/?tags=InfluxDB&tags=Buy%20Now

MQTT:
https://www.flowdirector.io/apps/injection/mqttinfluxdb/

MQTT docs:
https://help.flowdirector.io/mtidi/

Kafka:
https://www.flowdirector.io/apps/injection/kafkainfluxdb/

Kafka docs:
https://help.flowdirector.io/ktidi/

**Comment by jstirnaman** [comment]
Apologies we didn't get back to you sooner. I can't add your products to our docs at this time, but, if you're interested, please consider contributing an article for the [InfluxDB blog](https://www.influxdata.com/blog/) that illustrates a use case for your integration.
