### ISSUE TITLE
Wrong file name in the tar command for the CLI in Linux

### ISSUE THREAD

**Issue by jentrialgo** [influxdata/docs-v2#3190]
In the description of the commands to install the influx CLI for Linux the name of the file is missing a "2". It says

> tar xvfz influxdb-client-2.1.0-linux-amd64.tar.gz

And it should be:

> tar xvfz influxdb2-client-2.1.0-linux-amd64.tar.gz

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud/sign-up/?t=Linux#optional-download-install-and-use-the-influx-cli

**Comment by pierwill** [comment]
Thanks, @jentrialgo!
