### ISSUE TITLE
SHOW MEASUREMENTS ON *.*

### ISSUE THREAD

**Issue by lesam** [influxdata/docs-v2#3201]
https://github.com/influxdata/influxdb/pull/22388
https://github.com/influxdata/influxdb/pull/22396
https://github.com/influxdata/plutonium/pull/3632

_Describe the new feature here._

See issue comments:

https://github.com/influxdata/influxdb/issues/3318#issuecomment-719841659 
https://github.com/influxdata/influxdb/issues/3318#issuecomment-721117864
https://github.com/influxdata/influxdb/issues/3318#issuecomment-912809271

This will be in Enterprise 1.10, OSS 2.1, and a future release of Cloud (date undecided).

**Comment by davidby-influx** [comment]
This needs to be **_removed_** from the 1.8 Docs: https://docs.influxdata.com/influxdb/v1.8/query_language/explore-schema/#show-measurements

It is not in 1.8, and will not be in 1.8 or 1.9

@pierwill
