### ISSUE TITLE
Optionally dump queries to log on SIGTERM

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/docs-v2#3230]
https://github.com/influxdata/influxdb/pull/22638 (influxdb OSS)
https://github.com/influxdata/plutonium/pull/3664 (Enterprise)

In order to support debugging of out-of-memory failure in
containers, optionally dump all active queries to the log
when a SIGTERM is received and the termination-query-log
flag is true in the coordinator/cluster section of the config. The
default is false.

- If a database is killed by a container or `kill` command, it can dump the current queries to the log. This will help debug out-of-memory situations (OOM)
- Set the configuration flag noted above, kill the `influxd` process with SIGTERM. 

##### Relevant URLs
https://github.com/influxdata/influxdb/issues/22636
https://github.com/influxdata/plutonium/issues/3393

influxdb 1.9.6, Enterprise 1.10

**Comment by samhld** [comment]
@kelseiv @lwandzura I think the config data nodes page suffices for this.

That said -- in general -- it might be good to maintain a troubleshooting section in the docs. That's probably a larger effort and should involve support/SE so just food for thought. Could also be something we leave for the next gen.

**Comment by lwandzura** [comment]
@davidby-influx Hi David - these updates should go here, yes?
 https://docs.influxdata.com/enterprise_influxdb/v1.9/administration/configure/config-data-nodes/#termination-query-log--false

**Comment by davidby-influx** [comment]
@lwandzura - that's right.

**Comment by lwandzura** [comment]
branch is log-queries-SIGTERM off the enterprise.1.10 branch
