### ISSUE TITLE
Cloud 2 write limits clarification

### ISSUE THREAD

**Issue by noramullen1** [influxdata/docs-v2#3252]
A note to clarify that while PAYG supports an unlimited number of tasks, the data written into InfluxDB via the task counts towards the Data in pricing vector. If the task writes to another bucket in the same organization, this does not count towards Data In usage. 
Using external scripts and writing data using the API (for example, to query and write to a different bucket), does count towards Query Count pricing vector and Data In.

https://github.com/influxdata/EAR/issues/2692

**Comment by timhallinflux** [comment]
https://github.com/influxdata/docs-v2/pull/3355-- should address this.
