### ISSUE TITLE
New behaviour in InfluxDB Enterprise 1.10 for `influxd-ctl show`

### ISSUE THREAD

**Issue by lesam** [influxdata/docs-v2#3351]
https://github.com/influxdata/plutonium/issues/3708
https://github.com/influxdata/plutonium/pull/3707

_Describe the new feature here._

The proposed new format:

```
> ./influxd-ctl show
Data Nodes
==========
ID      TCP Address             HTTP Address            Version Labels
3       metatest_data_0_1:8088  metatest_data_0_1:8086  unknown {}

Meta Nodes
==========
ID      Raft Address            HTTP Address            Version Labels
1       metatest_meta_0_1:8089  metatest_meta_0_1:8091  unknown {}
2       metatest_meta_1_1:8089  metatest_meta_1_1:8091          {}

Raft Status
==========
Leader  metatest_meta_0_1:8089
Peers   ["metatest_meta_0_1:8089", "metatest_meta_1_1:8089"]
```

Improvements in the new format:
 * The meta node HTTP address was previously mis-named the “TCP Address”, this appears to have been a typo in the past as the actual /show-cluster endpoint calls the raft address the TCP address. I have changed the names for both in the show output to add clarity.
 * Add the data node HTTP address to the output
 * The whole “Raft Status” section
 * A warning is added (not shown) if the raft peers do not match the stored metadata.

##### Relevant URLs
https://influxdata.slack.com/archives/CPYJNHM4K/p1636033639038400

**Comment by lwandzura** [comment]
branch is new-influxdctl-show

**Comment by lwandzura** [comment]
Updated the format in docs, just need to create a PR to publish when ready
