### ISSUE TITLE
flux spec link broken

### ISSUE THREAD

**Issue by viraptor** [influxdata/docs-v2#3352]
The "flux specification" link on https://www.influxdata.com/products/flux/ points to https://docs.influxdata.com/flux/v0.65/ which gives 404.

##### Relevant URLs
- https://docs.influxdata.com/flux/v0.65/

**Comment by kelseiv** [comment]
Thank you, @viraptor! We'll get this link updated to point to the latest Flux spec doc here: https://docs.influxdata.com/flux/v0.x/spec/

Flux docs recently had a major restructure, and you can now find the new Flux landing page @ https://docs.influxdata.com/flux/v0.x/

Regarding specific Flux versions/releases, you can now see tags on each Flux function doc, so you know which version the function was released (or deprecated).

Thanks to @sanderson for these Flux doc improvements!

**Comment by kelseiv** [comment]
resolved
