### ISSUE TITLE
link name and url inconsistent

### ISSUE THREAD

**Issue by gt-nyc** [influxdata/docs-v2#3353]
When reading this tutorial "Using the HTTP input plugin with Citi Bike data", this text doesn't seem to make sense:

"For the following example to work, configure **influxdb output plugin**" and the link points to the influxdb input plugin:  https://docs.influxdata.com/telegraf/v1.15/plugins/#influxdb

##### Relevant URLs
- _Provide relevant URLs (the doc page in question, project issues, community threads, etc.)_

https://docs.influxdata.com/telegraf/v1.20/guides/using_http/

**Comment by kelseiv** [comment]
maybe related to other open citi bike issues?:
https://github.com/influxdata/docs-v2/issues?q=is%3Aissue+is%3Aopen+citi

**Comment by noramullen1** [comment]
Closed by #3640
