### ISSUE TITLE
Broken link to Geo package docs

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#3398]
Top of page, doc links to this address: https://docs.influxdata.com/flux/v0.x/stdlib/experimental/to/geo

I believe the indended is: https://docs.influxdata.com/flux/v0.x/stdlib/experimental/geo/

**Comment by kelseiv** [comment]
Thanks, @samhld 

@lwandzura here we can search for all occurrences of `/experimental/to/geo` and replace with `/experimental/geo`
