### ISSUE TITLE
sqlite3 more info link does not link anywhere

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#3402]
In the sqlite3 bullet, the `below` link is set to current page: https://docs.influxdata.com/flux/v0.x/stdlib/sql/from/

**Comment by kelseiv** [comment]
- [ ] On this page: https://docs.influxdata.com/flux/v0.x/stdlib/sql/from/

    **Change this:**  sqlite3 – _Does not work with InfluxDB OSS or InfluxDB Cloud. More information [below](#query-an-sqlite-database)._
        
    **To:**. sqlite3 – _Does not work with InfluxDB OSS or InfluxDB Cloud. For more information, see [Query SQLite](/flux/v0.x/query-data/sql/sqlite/)._

- [ ] On this page: https://docs.influxdata.com/flux/v0.x/stdlib/sql/to/

     **Change this:** sqlite3 – _Does not work with InfluxDB OSS or InfluxDB Cloud. More information [below](#write-data-to-an-sqlite-database)._

     **To:** sqlite3 – _Does not work with InfluxDB OSS or InfluxDB Cloud. For more information, see [Write to SQLite](/flux/v0.x/write-data/sql/sqlite/)._
