### ISSUE TITLE
Page does not exist

### ISSUE THREAD

**Issue by jonrabe1** [influxdata/docs-v2#3403]
_Describe the issue here.
Web Page link does not exists.
##### Relevant URLs
[- _Provide relevant URLs_]
(https://docs.influxdata.com/influxdb/v2.1/introduction/getting_started/#creating-a-database)

**Comment by noramullen1** [comment]
Hi @jonrabe1, thanks for letting us know.  Where did you find this link?

**Comment by jonrabe1** [comment]
From the Homeassistant web page for influxdb setup instructions


Sent from Yahoo Mail for iPhone


On Tuesday, November 16, 2021, 2:44 PM, noramullen1 ***@***.***> wrote:




Hi @jonrabe1, thanks for letting us know. Where did you find this link?
