### ISSUE TITLE
Add Season 1 videos to docs

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#3407]
@lwandzura, updated YouTube links below, so we can use existing video short code cc @sanderson

Phase 1:
On the Get started (Cloud and OSS) docs:
- (Cloud) https://docs.influxdata.com/influxdb/cloud/get-started/
- (OSS) https://docs.influxdata.com/influxdb/v2.1/get-started/

Add the following videos:

- [ ] _IoT Monitoring with InfluxDB_: https://www.youtube.com/watch?v=EzFEy-xJYhM
To learn more about working with geolocation and InfluxDB, see how to [work with geo-temporal data](https://docs.influxdata.com/influxdb/cloud/query-data/flux/geo/).
- [ ] _Geolocation and InfluxDB_:
https://www.youtube.com/watch?v=Mj1KdzC6EKU 
To learn more about how to work with geolocation and InfluxDB, see [Work with geo-temporal data](https://docs.influxdata.com/influxdb/cloud/query-data/flux/geo/).
- [ ] _Time Series 101_: https://www.youtube.com/watch?v=VJvinU8_f00
- [ ] _Time to Awesome_: https://www.youtube.com/watch?v=k0lubyBNMlQ
- [ ] _The Spirit of Open Source_: https://www.youtube.com/watch?v=Ymp28MxosFQ

**Comment by lwandzura** [comment]
It would be nice to have a Videos, Tutorials and Other Resources page at some point

**Comment by lwandzura** [comment]
"Time to Awesome" has changed to "What is 'Time to Awesome'" so the youtube link above no longer works - her is the new one:

https://www.youtube.com/watch?v=iMKCe3WKFo0

**Comment by lwandzura** [comment]
Moved into production on 12/17/2021
