### ISSUE TITLE
Notebooks docs are out of date

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/docs-v2#3408]
The documentation on notebooks needs to be updated as we have changed some notebook features:

1. Preview/Run is gone - we just have run now (it was too confusing and people couldn't tell the difference)
2. The metric selector is gone - it was too slow for larger buckets. We now have the query builder and the flux editor.
3. Column editor is gone
4. Output to bucket is gone (as a standalone panel) - you now do that in the flux editor if that's what you want to do.

**Comment by jstirnaman** [comment]
[Overview](https://docs.influxdata.com/influxdb/v2.1/notebooks/overview) could use a description of what a "cell" is.
