### ISSUE TITLE
Port InfluxQL docs into 2.x and Cloud

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#3417]
With InfluxQL support in both 2.x and Cloud, we need to port the Enterprise 1.9 InfluxQL documentation (the most recent InfluxQL docs) into 2.x and Cloud. Certain InfluxQL operations are not possible (such as administrative tasks) and we need to call those out.

##### Relevant URLs
- https://docs.influxdata.com/enterprise_influxdb/v1.9/query_language
- https://docs.influxdata.com/influxdb/v2.1/query-data/influxql/
- https://docs.influxdata.com/influxdb/v2.1/reference/syntax/flux/flux-vs-influxql/

**Comment by kelseiv** [comment]
For now, InfluxQL is only supported in API. @sanderson @lwandzura and @kelseiv met today to discuss plan for porting InfluxQL doc 1.x content to 2.x and Cloud:

- [ ] Create an InfluxQL branch and copy and paste the enterprise_influxdb/v1.9/query_language/ file into v2.0, v2.1, and Cloud.
- [ ] Move the following docs to an InfluxQL section under Reference:
       - Functions
       - Mathematical operators
       - InfluxQL reference (and rename to InfluxQL specification)
- [ ] Drop Continuous queries doc (figure out where/if it makes sense to refer to "tasks" in the InfluxQL context)
- [ ] Remove unsupported commands throughout (much of Manage your database using InfluxQL doc goes away--do we want to keep this doc now/retitle?)
- [ ] Remove CQ content throughout and retention policies. Do we support create a database? how does this translate to bucket?
- [ ] Remove cli examples.
- [ ] Drop Sample data doc, and update other docs where appropriate to use 2.x/Cloud sample data, and create a DBRP mapping.
- [ ] Reorganize and rewrite Explore data using InfluxQL to be more procedural and step-by-step instruction; verb phrase headers. Update intro and remove table format, update all examples to reflect API calls and new sample data. Break out into new docs if it makes sense to do so.
- [ ] Remove (or identify) unsupported InfluxQL queries in 2.x/Cloud in context. Do we want to remove associated content altogether, or note that the content is "only supported in 1.x"?
- [ ] Editorial sweeps.
- [ ] Review keywords; test search.

**Comment by lwandzura** [comment]
ensure the following is added:

SHOW MEASUREMENTS grouping/filtering by RP
