### ISSUE TITLE
SHOW SHARDS -- doesn't have any example output

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#3436]
We should provide sample output from SHOW SHARDS and describe what the various output elements mean.

##### Relevant URLs
https://docs.influxdata.com/enterprise_influxdb/v1.9/query_language/spec/#show-shards
https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-shards

**Comment by lwandzura** [comment]
@kelseiv Fixing the SHOW SERIES CARDINALITY section in the 1.9 docs as part of this update, there's missing info as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/51929958/156839867-1b88af33-573f-48e0-bfe4-40c3ed909aba.png)
