### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by VJYavar** [influxdata/docs-v2#3439]
I'm not able to access the page

##### Relevant URLs
- https://docs.influxdata.com/telegraf/cloud/administration/troubleshooting/ 

##### What products and version are you using?
I'm using InfluxDB cloud

![InfluxDBBugScreenshot](https://user-images.githubusercontent.com/93216848/143191169-7b0e0462-bac1-437a-a5cc-8e97c269b3f9.png)

**Comment by sanderson** [comment]
@VJYavar Where did you get this link? Was it inside of the docs or from an external source?

**Comment by VJYavar** [comment]
I've created a Telegraf Configuration and tried to test it once it is created using the "Listen for Data" Option. The data isn't received successfully so it showed an option to Troubleshoot. When I clicked on the Troubleshooting option, it redirected to the above link. Then I faced the above image on my screen. I got this link within the InfluxDB Cloud Portal - Telegraf Configuration.

**Comment by VJYavar** [comment]
Cool. It was a very quick fix.
