### ISSUE TITLE
Remove any references to Demo Data in the cloud application - it has been removed

### ISSUE THREAD

**Issue by nanderson6** [influxdata/docs-v2#3441]
**PR:** _Provide PR URL(s) for this feature (if available)_
You used to be able to add demo data from the buckets page
https://us-west-2-1.aws.cloud2.influxdata.com/orgs/7a3d27f6e5129d33/load-data/buckets

_Describe the new feature here._
The UI teams recently removed demo data from the cloud application, moving in favor of building out a better experience with sample data in notebooks for users.

It seems like there would certainly be some things that could get removed on the docs side around this.
So it seemed prudent to get a ticket filed on the topic.

Existing demo data for users will not be touched, but it just won't be available for any new users to add.

Ping Nick Anderson and Daniel Campbell with more questions.

##### Relevant URLs
- _Provide relevant URLs (issues, community threads, existing doc pages, etc.)_

**Comment by kelseiv** [comment]
- [ ] Remove query demo data doc: https://docs.influxdata.com/influxdb/cloud/query-data/execute-queries/query-demo-data/
- [ ] Verify with Nick Anderson that demo data references in api docs have been removed and update references in API docs accordingly 
- [ ] Remove demo data from get started doc: https://docs.influxdata.com/influxdb/cloud/get-started/
- [ ] Verify Downsample data with notebooks has removed demo data: https://docs.influxdata.com/influxdb/cloud/notebooks/downsample/
- [ ] Remove reference in Query sample data doc: https://docs.influxdata.com/influxdb/cloud/query-data/execute-queries/query-sample-data/
- [ ] Remove reference in Sample data doc: https://docs.influxdata.com/influxdb/cloud/reference/sample-data/
- [ ] Remove reference in Write data to InfluxDB: https://docs.influxdata.com/influxdb/cloud/write-data/
