### ISSUE TITLE
JSON data format docs pointing to old JSON parser

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#3453]
##### Relevant URLs
https://docs.influxdata.com/telegraf/v1.20/data_formats/input/json/

**Comment by noramullen1** [comment]
Hi @samhld , can you elaborate on this? :)

**Comment by samhld** [comment]
@noramullen1 the JSON parser plugin that users _should_ be using is the v2 one. The v1 exists still so I would recommend linking to both but at the very least, the docs should link to the v2 version.  That link is here: https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json_v2

**Comment by timhallinflux** [comment]
yeah, we really need to update that page with a v2 (as the recommended) and v1 (as legacy....). 

This is a huge and important new parser which makes working with JSON infinitely easier than the previous.

**Comment by timhallinflux** [comment]
I also think we need to review any examples that we might have in the 1.21 (and beyond) docs  where     `data_format = "json"` and ensure that we update these to    ` data_format = "json_v2"`
