### ISSUE TITLE
Replications feature InfluxDB OSS

### ISSUE THREAD

**Issue by mcfarlm3** [influxdata/docs-v2#3459]
**Issue for this epic:** https://github.com/influxdata/influxdb/issues/21918

This feature will allow users to replicate data at the bucket level to one or more remote instances of InfluxDB. The following user stories illustrate why this feature is useful:

- As a user, I have multiple edge deployments of InfluxDB OSS that are collecting data locally. I would like an easy way to analyze this data in aggregate.

- As a user, I have multiple edge deployments of InfluxDB OSS that are collecting data locally with limited or no connectivity to the cloud. I would like an easy way to analyze this data in aggregate once network connection is restored.

API Endpoints:

```
GET /api/v2/remotes                # List/find
POST /api/v2/remotes               # Create
GET /api/v2/remotes/<id>           # Get
PATCH /api/v2/remotes/<id>         # Update
DELETE /api/v2/remotes/<id>        # Delete

GET /api/v2/replications                # List/find
POST /api/v2/replications               # Create
GET /api/v2/replications/<id>           # Get
PATCH /api/v2/replications/<id>         # Update
DELETE /api/v2/replications/<id>        # Delete
POST /api/v2/replications/<id>/validate # Validate connection (sends a no-op write)
```

CLI Commands:

There are two top-level commands related to this feature - `influx remote` and `influx replication`.

<img width="476" alt="Screen Shot 2021-12-03 at 1 20 07 PM" src="https://user-images.githubusercontent.com/58636946/144675731-c63cc8eb-2414-45ff-a6fe-4d4fe5799c59.png">

`remote create` subcommand options:
`name`, `remote-url`, `remote-api-token`, and `remote-org-id` are required

```
   --org-id value                 The ID of the organization [$INFLUX_ORG_ID]
   --org value, -o value          The name of the organization [$INFLUX_ORG]
   --name value, -n value         Name for the new remote connection
   --description value, -d value  Description for the new remote connection
   --remote-url value             The url for the remote database
   --remote-api-token value       The API token for the remote database
   --remote-org-id value          The ID of the remote organization
   --allow-insecure-tls           Allows insecure TLS
```

`remote delete` subcommand options:
`id` is required

``` 
  --id value, -i value  ID of the remote connection to be deleted
```

`remote list` subcommand options:
no options are required
```
   --name value, -n value  Filter results to only connections with a specific name
   --org-id value          Local org ID [$INFLUX_ORG_ID]
   --org value, -o value   Local org name [$INFLUX_ORG]
   --remote-url value      Filter results to only connections for a specific remote URL
```

`remote update` subcommand options:
`id` is required
```
   --id value, -i value           Remote connection ID
   --name value, -n value         New name for the remote connection
   --description value, -d value  New description for the remote connection
   --remote-url value             New url for the remote database
   --remote-api-token value       New API token for the remote database
   --remote-org-id value          New ID of the remote organization
   --allow-insecure-tls           Allows insecure TLS
```

<img width="604" alt="Screen Shot 2021-12-03 at 1 20 40 PM" src="https://user-images.githubusercontent.com/58636946/144675739-efd67c3d-ae3a-4556-89fc-a790f505da70.png">

`replication create` subcommand options:
`name`, `remote-id`, `local-bucket`,  and `remote-bucket` are required
```
   --name value, -n value         Name for new replication stream
   --description value, -d value  Description for new replication stream
   --org-id value                 The ID of the local organization [$INFLUX_ORG_ID]
   --org value, -o value          The name of the local organization [$INFLUX_ORG]
   --remote-id value              Remote connection the new replication stream should send data to
   --local-bucket value           ID of local bucket data should be replicated from
   --remote-bucket value          ID of remote bucket data should be replicated to
   --max-queue-bytes value        Max queue size in bytes (default: 67108860)
   --drop-non-retryable-data      Drop data when a non-retryable error is encountered instead of retrying
   --no-drop-non-retryable-data   Do not drop data when a non-retryable error is encountered
```

`replication delete` subcommand options:
`id` is required
```
   --id value, -i value  ID of the replication stream to be deleted
```

`replication list` subcommand options:
no options are required
```
   --name value, -n value  Filter results to only replication streams with a specific name
   --org-id value          Local org ID [$INFLUX_ORG_ID]
   --org value, -o value   Local org name [$INFLUX_ORG]
   --remote-id value       Filter results to only replication streams for a specific remote connection
   --local-bucket value    Filter results to only replication streams for a specific local bucket
```

`replication update` subcommand options:
`id` is required
```
   --id value, -i value           ID of the replication stream to be updated
   --name value, -n value         New name for the replication stream
   --description value, -d value  New description for the replication stream
   --remote-id value              New ID of remote connection the replication stream should send data to
   --remote-bucket value          New ID of remote bucket that data should be replicated to
   --max-queue-bytes value        New max queue size in bytes (default: 0)
   --drop-non-retryable-data      Drop data when a non-retryable error is encountered instead of retrying
   --no-drop-non-retryable-data   Do not drop data when a non-retryable error is encountered
```

How to use:

In order to create a new replication stream, you must have a remote connection that the replication will be associated with set up first. You can either use one you have previously registered (use `influx remote list` command to view existing connections) or create a new one. 

Example: 
`influx remote create --name <name> --remote-url <url> --remote-api-token <token> --remote-org-id <id>`

Once you have a remote connection registered, you can then create a replication stream to be associated with that remote connection. 

Example: 
`influx replication create --name <name> --remote-id <id> --local-bucket <id> --remote-bucket <id>`

Once a replication stream is created, you can view information such as the current queue size, max queue size, and latest status code using the `influx replication list` command. 

Things to Note:
- Only writes are streamed. Other data operations (e.g. deletes, backup restores) do not affect replication. This can cause data in the local bucket to be different than the remote.
- Large writes are always written together locally, but they will be batched when sent to the remote bucket. The maximum batch size is 500 kB, which is typically about 250 to 500 lines. This may result in scenarios where some batches fail, and others do not.

**Comment by wbaker85** [comment]
Some info related to observability/troubleshooting that might be useful:

#### Metrics available at the `/metrics` endpoint:
- `replications_queue_total_points_queued`: Sum of all points that have been successfully added to the replication stream queue
- `replications_queue_total_bytes_queued`: Sum of all bytes that have been successfully added to the replication stream queue
- `replications_queue_current_bytes_queued`: Current number of bytes in the replication stream queue remaining to be processed
- `replications_queue_remote_write_errors`: Error codes returned from attempted remote writes
- `replications_queue_remote_write_bytes_sent`: Bytes of data successfully sent to the remote by the replication stream
- `replications_queue_remote_write_bytes_dropped`: Bytes of data dropped due to remote write failures
- `replications_queue_points_failed_to_queue`: Sum of all points that could not be added to the local replication queue
- `replications_queue_bytes_failed_to_queue`: Sum of all bytes that could not be added to the local replication queue

#### Remote write failures
If there are errors encountered while transferring data to the remote, the transfer will be continuously retried with an increasing delay between transfer attempts, up to a maximum of 15 minutes delay between attempts. The latest error code encountered by a replication is available via the CLI `replication list` command. The sum of all error codes encountered is available on the `/metrics` endpoint via the `replications_queue_remote_write_errors` metric.

If data is not able to be processed by the remote connection and results in a `400 Bad Response` error, the replication can be configured to drop this data rather than continuously retry sending it using the `--drop-non-retryable-data` CLI flag when updating the replication.

**Comment by wbaker85** [comment]
We changed this limitation:

```
Large writes are always written together locally, but they will be batched when sent to the remote bucket. The maximum batch size is 500 kB, which is typically about 250 to 500 lines. This may result in scenarios where some batches fail, and others do not.
```

It should now be something like:
```
Large writes are always written together locally, but they may be batched when sent to the remote bucket. The maximum batch size is 2.5mb or 5000 points. It is possible that a local write for a batch exceeding these limitations will succeed, with the remote write happening in multiple batches. For optimal performance, local writes to buckets with replications configured should not exceed 2.5mb / 5000 points.
```

**Comment by mcfarlm3** [comment]
Based on feedback from some of our initial testers, we thought it might be useful to include a section in the docs similar to what I've written below. There was some confusion between local orgs/tokens vs. remote orgs/tokens.

**Note: Local vs. Remote orgs and tokens**

When working with remote connections and replication streams, it is important to distinguish between local and remote instances, and their corresponding flags. The `--org`, `--org-id`, and `--local-bucket` flags are all referring to the local OSS instance, while the `--remote-org-id` and `--remote-bucket` flags are referring to the destination instance where writes are being replicated to. Similarly, there are two tokens involved in this process - the token used for the CLI to communicate with the local OSS instance (`--token`) and the token used by the local OSS instance to communicate with the remote instance (`--remote-api-token`).
