### ISSUE TITLE
Document replications data in `/metrics` endpoint

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs-v2#3468]
Some info related to observability/troubleshooting that might be useful:

#### Metrics available at the `/metrics` endpoint:
- `replications_queue_total_points_queued`: Sum of all points that have been successfully added to the replication stream queue
- `replications_queue_total_bytes_queued`: Sum of all bytes that have been successfully added to the replication stream queue
- `replications_queue_current_bytes_queued`: Current number of bytes in the replication stream queue remaining to be processed
- `replications_queue_remote_write_errors`: Error codes returned from attempted remote writes
- `replications_queue_remote_write_bytes_sent`: Bytes of data successfully sent to the remote by the replication stream
- `replications_queue_remote_write_bytes_dropped`: Bytes of data dropped due to remote write failures
- `replications_queue_points_failed_to_queue`: Sum of all points that could not be added to the local replication queue
- `replications_queue_bytes_failed_to_queue`: Sum of all bytes that could not be added to the local replication queue

#### Remote write failures
If there are errors encountered while transferring data to the remote, the transfer will be continuously retried with an increasing delay between transfer attempts, up to a maximum of 15 minutes delay between attempts. The latest error code encountered by a replication is available via the CLI `replication list` command. The sum of all error codes encountered is available on the `/metrics` endpoint via the `replications_queue_remote_write_errors` metric.

If data is not able to be processed by the remote connection and results in a `400 Bad Response` error, the replication can be configured to drop this data rather than continuously retry sending it using the `--drop-non-retryable-data` CLI flag when updating the replication.

_Originally posted by @wbaker85 in https://github.com/influxdata/docs-v2/issues/3459#issuecomment-988983567_

**Comment by pierwill** [comment]
@jstirnaman Looks like these would be added to this page (but for 2.2): https://docs.influxdata.com/influxdb/v2.1/reference/internals/metrics/

**Comment by lwandzura** [comment]
add here:

https://docs.influxdata.com/influxdb/v2.2/reference/internals/metrics/
