### ISSUE TITLE
Improved meta-node HTTP access logging

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/docs-v2#3470]
**PR:** https://github.com/influxdata/plutonium/pull/3734

HTTP logging for meta-node has been improved, and now prints sanitized POST form values to show actual commands:

We need to more fully document:
- How to turn this on in the config file ([already documented inadequately](https://github.com/influxdata/plutonium/issues/3240#issuecomment-975862153))
- What we see when we do
- Differences from data node HTTP logging (see link above)

- This feature logs all HTTP requests to meta nodes. It existed before, but did not print the contents of POST requests, which tell what the command was and the arguments (like CREATE USER, etc.).
- Already documented, but needs to be much improved. The current Doc says the feature is only for debugging RAFT state.
- See here: https://github.com/influxdata/plutonium/issues/3240#issuecomment-985108963
- Tips or tricks:  How annoyingly overwhelming the announcement log entries are

##### Relevant URLs
[Original Issue](https://github.com/influxdata/plutonium/issues/3240 is the original issue.)

**Comment by davidby-influx** [comment]
@timhallinflux - I'm sure you have good thoughts here.

**Comment by pierwill** [comment]
Thanks, @davidby-influx!
