### ISSUE TITLE
Column description text overlaps with inline code labels

### ISSUE THREAD

**Issue by Franky1** [influxdata/docs-v2#3476]
https://docs.influxdata.com/telegraf/v1.20/administration/commands/#flags

In the column `description` the text overlaps with the inline code labels.

**Comment by noramullen1** [comment]
@sanderson how do I fix this? thank you!

**Comment by sanderson** [comment]
@noramullen1 a simple, but somewhat "hacky" way to do this would be to update the id of the "Flags" heading just before the table of commands:

```
## Flags {id="telegraf-cli-flags"}
```

**Comment by noramullen1** [comment]
Thanks for letting us know @Franky1! This is now fixed.
