### ISSUE TITLE
icomoon.woff2 font download redirect and 404

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#3517]
Do we need to whitelist "woff2" in our server config?

Console error:
`downloadable font: download failed (font-family: "icomoon" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: https://docs.influxdata.com/fonts/icomoon.woff2`

The woff2 referenced in our _icon.scss:
`https://docs.influxdata.com/fonts/icomoon.woff2`
always redirects to
`https://docs.influxdata.com/fonts/icomoon.woff2/`
which returns a 404. 

##### Relevant URLs
All https://docs.influxdata.com/ URLs

**Comment by sanderson** [comment]
Yeah, we do. I'll add it really quick.
