### ISSUE TITLE
Analytics request to (defunct?) engagio.com always returns 404

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#3518]
We have a script in public/index.html that sends requests to `web-analytics.engagio.com` and always gets a 404. Is it still valid?

Console error:
`ei_track_all_packed.js:1 GET https://web-analytics.engagio.com/api/stat?page_url=https%3A%2F%2Fdocs.influxdata.com%2F&page_title=InfluxData%20Documentation&track_type=page&action=ei_view&category=ei_page_tracking&client_id=&account_id=e9b11baeb0d0dda444c3105e7cf0877955e378ca&method=post&callback=EI.api._callbacks.s18511115 net::ERR_ABORTED 404`

##### Relevant URLs
All https://docs.influxdata.com URLs.

**Comment by sanderson** [comment]
We installed a few marketing tools a while ago that I'm not sure we're using any more.

@ChrisChurilo Are we still using Engagio and Marketo?
