### ISSUE TITLE
Document OSS-only `/api/v2/config` endpoint and CLI commands

### ISSUE THREAD

**Issue by wbaker85** [influxdata/docs-v2#3523]
With the OSS 2.2 release, we are adding a new endpoint `/api/v2/config` to display the run-time server configuration.
- `openapi` PR: https://github.com/influxdata/openapi/pull/255
- `influxdb` PR: https://github.com/influxdata/influxdb/pull/23003

The next CLI release will also include the CLI command `server-config` for displaying this configuration:
- https://github.com/influxdata/influx-cli/pull/346

This issue is to update the docs for this new endpoint and CLI command, to be effective upon the release of OSS 2.2 and the next CLI.

**Comment by wangshuang0220** [comment]
Hi, May I know when will the OSS 2.2 release?

**Comment by jstirnaman** [comment]
See the difference b/w the new `influx server-config` and `influxd print-config`: [The present version of the print-config command does not output the config of the running server. Rather, it is able to evaluate the current environment, config file, and flags passed to the print-config command itself. The last part is maybe not ideal - for example, if you run influxd print-config --bolt-path /some/path you will see the different bolt path in the printed configuration. If you have run the daemon with the --bolt-path flag separately, the influxd print-config command is unable to to pick up that flag.](https://github.com/influxdata/influxdb/issues/22917#issuecomment-976701488)
