### ISSUE TITLE
Incorrect link in Prometheus Remote Write data input format page

### ISSUE THREAD

**Issue by LeviHarrison** [influxdata/docs-v2#3525]
_Describe the issue here._

The hyperlink "Prometheus Remote Write Endpoint" at the top of the page points to https://github.com/react-monaco-editor/react-monaco-editor/, which I don't think is the link that's supposed to be there.

https://github.com/influxdata/docs-v2/blob/cd824beb58d99d4c1a1dc0c7834e9c340204dcb6/content/telegraf/v1.21/data_formats/input/prometheus-remote-write.md#L16

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1.21/data_formats/input/prometheus-remote-write/

**Comment by lwandzura** [comment]
I believe this is the correct URL:

https://github.com/influxdata/telegraf/tree/97826bdc73252c232924fc2db013b00301259e0a/plugins/parsers/prometheusremotewrite
