### ISSUE TITLE
Missing URL in Prometheus Remote Write data input format page

### ISSUE THREAD

**Issue by LeviHarrison** [influxdata/docs-v2#3526]
_Describe the issue here._

At the top of the page, "here" is a hyperlink but has no corresponding URL.

https://github.com/influxdata/docs-v2/blob/cd824beb58d99d4c1a1dc0c7834e9c340204dcb6/content/telegraf/v1.21/data_formats/input/prometheus-remote-write.md#L18

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1.21/data_formats/input/prometheus-remote-write/

**Comment by lwandzura** [comment]
this is the missing URL:

https://github.com/influxdata/telegraf/blob/master/plugins/processors/starlark/README.md
