### ISSUE TITLE
Wrong export command syntax

### ISSUE THREAD

**Issue by Kortenbach** [influxdata/docs-v2#3529]
_I'm by no means a linux expert, but I noticed that the syntax for the export commands on this page are probably wrong._

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v1.5/query_language/authentication_and_authorization/

Proposed commands:
export INFLUX_USERNAME todd
export INFLUX_PASSWORD influxdb4ever
echo $INFLUX_USERNAME $INFLUX_PASSWORD
todd influxdb4ever

Should have looked like:
export INFLUX_USERNAME=todd                             //note the added "=" sign
export INFLUX_PASSWORD=influxdb4ever              //note the added "=" sign
echo $INFLUX_USERNAME $INFLUX_PASSWORD
todd influxdb4ever

Running Docker Desktop CLI under WIndows 10.

**Comment by timhallinflux** [comment]
Yes, that is a very old version.  This was addressed in more recent versions of the doc: https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/

**Comment by timhallinflux** [comment]
@Kortenbach are you still running InfluxDB 1.5?? anything preventing you from upgrading to 2.x??

**Comment by Kortenbach** [comment]
Upgraded to v2 now...

Op wo 5 jan. 2022 00:11 schreef timhallinflux ***@***.***>:
