### ISSUE TITLE
max-index-log-file-size parsed differently between config and environment

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs-v2#3649]
See https://github.com/influxdata/influxdb/issues/22974.

**Comment by lesam** [comment]
This is for the following fields:

```
tsdb/config.go: CacheMaxMemorySize             toml.Size     `toml:"cache-max-memory-size"`
tsdb/config.go: CacheSnapshotMemorySize        toml.Size     `toml:"cache-snapshot-memory-size"`
tsdb/config.go: CompactThroughput              toml.Size     `toml:"compact-throughput"`
tsdb/config.go: CompactThroughputBurst         toml.Size     `toml:"compact-throughput-burst"`
tsdb/config.go: MaxIndexLogFileSize toml.Size `toml:"max-index-log-file-size"`
```

**Comment by pierwill** [comment]
@lesam @davidby-influx Let me make sure I understand this correctly:

We're having trouble parsing these config values. But giving raw bytes without units works fine. So let's change the recommended values in the configuration docs to use raw bytes.

Is this correct?

**Comment by davidby-influx** [comment]
Basically yes.  We just don't have the parsing of environment variables as a high priority, so it didn't get fixed for the most recent release.
