### ISSUE TITLE
Add example output for password change with Enterprise API

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs-v2#3658]
Follow-up to https://github.com/influxdata/docs-v2/pull/3657.

##### Relevant URLs
https://docs.influxdata.com/enterprise_influxdb/v1.9/administration/manage/users-and-permissions/authorization-api/#change-a-users-password

**Comment by pierwill** [comment]
Looks like there is no output for a successful password change request through the API. Is that correct @lesam?

**Comment by lesam** [comment]
Yes that's correct - just a `200 OK` in the response
