### ISSUE TITLE
can not download Telegraf v1.21

### ISSUE THREAD

**Issue by GitBaymin** [influxdata/docs-v2#3660]
when click _InfluxData download page._ in the page 
- https://docs.influxdata.com/telegraf/v1.21/introduction/downloading/

then jump into 
- https://portal.influxdata.com/downloads/

but I can not find download button.

did i do it wrong?

**Comment by kelseiv** [comment]
Hi @GitBaymin, you're correct there's no download button.
1. Scroll down a bit, and you'll see _**Telegraf** open source data collector_. Select the Telegraf version to install, and then select your platform **to see the appropriate install command**.
2. To install most platforms, you'll have to open your terminal and enter this install command. Except for macOS Intel or macOS ARM64 platforms, in which case you can hover+click the command to download a .dmg file.

**Comment by GitBaymin** [comment]
> Hi @GitBaymin, you're correct there's no download button.
> 
> 1. Scroll down a bit, and you'll see _**Telegraf** open source data collector_. Select the Telegraf version to install, and then select your platform **to see the appropriate install command**.
> 2. To install most platforms, you'll have to open your terminal and enter this install command. Except for macOS Intel or macOS ARM64 platforms, in which case you can hover+click the command to download a .dmg file.

Thank you for the reply!
