### ISSUE TITLE
Question about hardware sizing for influxdb 2.x

### ISSUE THREAD

**Issue by AlessandroBravo** [influxdata/docs-v2#3706]
The documentation for InfluxDB v2 is missing the section about hardware sizing.

Can i follow the guide for the 1.x version of this section for capacity planning or there's something different between the two versions (1.x and 2.x) in terms of hardware requirements?

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v1.8/guides/hardware_sizing

**Comment by sanderson** [comment]
@AlessandroBravo the 1.x hardware sizing guidelines are a safe place to start with InfluxDB 2.x, but there are differences between the two that may affect hardware requirements. These include the built-in UI, Flux query and task engines, and other underlying services added to support 2.x functionality.

This has been a common question/request and we hope to provide tested 2.x-specific hardware recommendations soon.

**Comment by AlessandroBravo** [comment]
Thanks @sanderson for the explanation. I’ll try to follow the 1.x guide keeping in mind the differences you have mentioned.
