### ISSUE TITLE
PagerDuty: Influxdata integration instructions on pagerduty site are out of date. 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/docs-v2#3726]
_Describe the issue here._

##### Relevant URLs
- https://www.pagerduty.com/docs/guides/influxdata-integration-guide/

Tried to follow the instructions at pager duty, but step 3 suggests using controls that have changed. 

![PagerDutyInstructions01](https://user-images.githubusercontent.com/25881301/151561403-17067668-bf4f-4c07-ace2-fe030b437473.png)

The current UI selects Events API v2 like this...

![PagerDutyInstructions02](https://user-images.githubusercontent.com/25881301/151561488-95da6564-b380-4113-8eca-7b2a9e000c27.png)

**Comment by sanderson** [comment]
@karel-rehor We don't maintain or have access to the PagerDuty documentation. I've looked for a public repository to report this issue to so their documentation team can make the necessary updates, but I haven't been able to find the repository where this documentation is stored.

As there isn't anything our team can do to make these updates, I'm going to go ahead and close this issue.
