### ISSUE TITLE
Explain how schema.tagValues() interacts with deletes and retention policies 

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/docs-v2#3730]
Users need to know when tag values will enter and drop out of their results. For example":
1. if they delete with predicate all the tag values, for how long can they expect to see tag value in their results?
2. if tag values ages out due to retention policies, for how long can they be expected to be in the results

##### Relevant URLs
- https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/schema/tagvalues/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
@influxdata/edge looking at the [Flux implementation of `schema.tagValues()`](https://github.com/influxdata/flux/blob/master/stdlib/influxdata/influxdb/schema/schema.flux#L81-L93), from what I can tell, this function isn't doing anything special. It's using raw Flux to just extract out unique tag values that exist for a specific tag in the queried dataset.  It's just using the data returned from the `api/v2/query` endpoint.

It doesn't appear that `schema.tagValues()` interacts (directly) with the index so updating or rebuilding the index shouldn't be required to see that tag values are removed. So a few questions:

- After you delete points with a delete predicate, are the changes instantaneous or is there a delay? If so, how long is the delay.
- With data aging out, I know this is up to the retention enforcement service. In OSS, by default, this runs every 30 minutes and can be configured with the `storage-retention-check-interval`. How often does retention enforcement run in Cloud?

**Comment by lesam** [comment]
Deletes are complete when the delete query completes successfully. We put in a tombstone, which will affect queries immediately, and then compaction will eventually remove the 'deleted' data from disk.

@influxdata/compute-team could maybe speak to retention enforcement in Cloud.

**Comment by sanderson** [comment]
Thanks @lesam, I've confirmed the delete behavior locally.

**Comment by sanderson** [comment]
@lesam I just learned that in Cloud, when the retention enforcer runs, it tombstones points that are beyond the retention period just as if there were delete. My understanding of OSS is that the retention enforcer doesn't tombstone or remove data until the entire shard group expires, so data is still queryable after it "expires" and will be until the shard it's on fully expires. Is my understanding correct?

**Comment by lesam** [comment]
Yes that is correct.
