### ISSUE TITLE
InfluxDB Admin page updates

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#3734]
On the InfluxDB Admin page, we added a new button to download CSV data, and a new status column. 

![image](https://user-images.githubusercontent.com/47797004/151865912-7603795f-527f-412d-b3da-e6a97e9a67ae.png)

cc @timhallinflux 
Glancing through the docs, looks like we allude to [viewing queries running on your database](https://docs.influxdata.com/chronograf/v1.9/#database-management.)...but don't see related/expanded content elsewhere, with this relevant screenshot. 

It may make sense to add a new landing page under Administration for "Managing databases" and then move  "Restoring a Chronograf database" under that, and include whatever pertinent info is on the InfluxDB Admin > Database and Queries tabs under there. Let's consider the options and determine the best strategy.

**Comment by lwandzura** [comment]
Queries page has changed in 1.10 - will try to get this added as part of 1.10
