### ISSUE TITLE
Provide Documentation for Download as PNG / PDF in Notebooks Presentation Mode

### ISSUE THREAD

**Issue by jzahnd** [influxdata/docs-v2#3739]
We have provided the ability to download a Notebooks presentation mode as a PNG / PDF. We would like to update our Cloud documentation to reference this updated functionality. 

### Related Links

- influxdata/ui#3325

**Comment by noramullen1** [comment]
Thanks @jzahnd! Just to be clear: this is in Cloud only, not in OSS?
