### ISSUE TITLE
`influx` not available in docker container

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#3756]
This doesn't work: [Open a shell in the influxdb container](https://docs.influxdata.com/influxdb/v2.1/install/#open-a-shell-in-the-influxdb-container)
Likely since the CLI was extracted from influxdb

##### Relevant URLs
- _Provide relevant URLs (the doc page in question, project issues, community threads, etc.)_

**Comment by jstirnaman** [comment]
Need to follow up with Edge team

**Comment by timhallinflux** [comment]
https://github.com/influxdata/influxdata-docker/pull/554
