### ISSUE TITLE
Document the max age config for data in replications queue

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#3765]
Clarify in the Data replications docs that folks can set a max age for replications data...in cases where the remote node doesn't accept data, this ensures replication data doesn't get stuck in the queue (and block other requests).

cc @lesam for review
https://github.com/influxdata/influxdb/issues/23109

**Comment by lesam** [comment]
@DStrand1 should review this one, he has taken over the max age work.

**Comment by lwandzura** [comment]
@kelseiv I believe this exists already on this page:  https://docs.influxdata.com/influxdb/v2.2/reference/cli/influx/replication/update/

![image](https://user-images.githubusercontent.com/51929958/167152995-72ee8941-28c9-4bce-91d2-b0e8989b8340.png)

Did you want the description updated?
