### ISSUE TITLE
example |> getRow(idx: 0) wrong ???

### ISSUE THREAD

**Issue by antonmeyer** [influxdata/docs-v2#3781]
_Describe the issue here._

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/query-data/flux/scalar-values/
- _Provide other relevant URLs (project issues, community threads, etc.)_

I wonder if the field values is missing.
|> getRow(idx: 0)

idx:0 is set as default in the declaration, but field is missing
getRow = (tables=<-, field, idx=0) => {

as I'm still a newbee I could be wrong

oh now, it is the other way around. in the function definition field is not needed
again: examples with errors are a pain for beginners

**Comment by sanderson** [comment]
@antonmeyer Thanks! You are absolutely right. I'll update the example.

**Comment by antonmeyer** [comment]
|> getRow(field: "temp") does not cause an error message,
but field is not used in getRow
