### ISSUE TITLE
Delete-by-predicate works to delete by field in Cloud, but not in OSS

### ISSUE THREAD

**Issue by lesam** [influxdata/docs-v2#3786]
This is a long-standing and known issue in OSS but is somewhat difficult to resolve on the code side. Until it is resolved, the docs should mention it.

In Cloud, the field key is similar to a tag value, and so delete-by-predicate works with field keys.

In OSS, there is special indexing for field keys and so delete-by-predicate does not (currently) work with field keys.

##### Relevant URLs
InfluxDB OSS issue to actually fix the behaviour: https://github.com/influxdata/influxdb/issues/20399
Previous docs issue: https://github.com/influxdata/docs-v2/issues/2025
Current docs: https://docs.influxdata.com/influxdb/v2.1/reference/syntax/delete-predicate/

@DStrand1 @dgnorton FYI

**Comment by lesam** [comment]
So after some more discussion, it looks like the plan is to (eventually) make Cloud match OSS, as this will also match IOx.

This makes things difficult for users that want to delete / rename / change the type of an existing field.

I believe the general suggestion for this is to do a `from() |> filter(.. filter out the bad field ...) |> to(... new bucket ... )` to re-write the data with the desired field changes, possibly followed by dropping the old data.

**Comment by timhallinflux** [comment]
that is correct and it is also the way that this kind of issue continues to be handled by support while TSM is the underlying storage mechanism.
