### ISSUE TITLE
new flag: influxd-ctl add-data -p

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/docs-v2#3794]
https://github.com/influxdata/plutonium/pull/3779

We have added the ability to have passive nodes in Enterprise clusters.  These act as load balancers, accepting WRITE calls, doing the shard lookup and RPC calls to distribute the writes to the owning data nodes.  Passive nodes are simply data nodes which cannot own shards, and when present they should be the write endpoint for all data ingest.  There may be multiple passive nodes in a cluster.

- This moves hinted-handoff and shard lookup off the nodes which own shards.
- Overall, we expect CPU and memory usage reduction on active data nodes
- `influxd-ctl add-data -p <address>`
- Change to `influxd-ctl show` output, adding new boolean `Passive` column

##### Relevant URLs
https://github.com/influxdata/plutonium/issues/2405
https://github.com/influxdata/plutonium/pull/1529

InfluxDB Enterprise 1.9.7, 1.10

**Comment by lwandzura** [comment]
doc to update:
https://docs.influxdata.com/enterprise_influxdb/v1.9/tools/influxd-ctl/#add-data

**Comment by lwandzura** [comment]
Met with David Byrne on March 3 to gather more info.  Based on that conversation:

If passive node configuration does work (currently testing this out with a customer) we'll need to update a few different places:

glossary:
https://docs.influxdata.com/enterprise_influxdb/v1.9/concepts/glossary/

add a a paragraph explaining what passive nodes are in one or more of the following docs:
https://docs.influxdata.com/enterprise_influxdb/v1.9/features/clustering-features/

https://docs.influxdata.com/enterprise_influxdb/v1.9/administration/configure/config-data-nodes/

influxd-ctl add-data command will need to be updated:
https://docs.influxdata.com/enterprise_influxdb/v1.9/tools/influxd-ctl/#add-data

influxd-ctl show command will need to be updated:
https://docs.influxdata.com/enterprise_influxdb/v1.9/tools/influxd-ctl/#show

**Comment by lwandzura** [comment]
Created branch add-passive-node

**Comment by lwandzura** [comment]
@davidby-influx Can you provide a screenshot or example of the output of influxd-ctl show with passive nodes?  Thanks!

**Comment by davidby-influx** [comment]
```
> influxd-ctl show
Data Nodes
==========
ID	TCP Address						HTTP Address						Version		Labels	Passive
4	influxdb_data_0_1.influxdb.ear.influxdata.edge:8088										{}	false
5	influxdb_data_1_1.influxdb.ear.influxdata.edge:8088	influxdb_data_1_1.influxdb.ear.influxdata.edge:8086	1.9.6-c1.9.6	{}	true
6	influxdb_data_2_1.influxdb.ear.influxdata.edge:8088										{}	false

Meta Nodes
==========
ID	TCP Address						Version		Labels
1	influxdb_meta_0_1.influxdb.ear.influxdata.edge:8091	1.9.6-c1.9.6	{}
2	influxdb_meta_1_1.influxdb.ear.influxdata.edge:8091	1.9.6-c1.9.6	{}
3	influxdb_meta_2_1.influxdb.ear.influxdata.edge:8091	1.9.6-c1.9.6	{}

```

This is actually faked up, but is what the output looks like.....
