### ISSUE TITLE
Enhance isType() documentation

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/docs-v2#3807]
Referring to this function: https://docs.influxdata.com/flux/v0.x/stdlib/types/istype/

Could we please add:
1. Some content that explains the purpose(s) of the function?
2. An example that shows how to exclude strings and other types of downsampling queries?

**Comment by pierwill** [comment]
Added to Flux documentation in https://github.com/influxdata/flux/pull/4523. Will add to main docs site as well.
