### ISSUE TITLE
to() docs page doesn't indicate what it returns

### ISSUE THREAD

**Issue by wz2b** [influxdata/docs-v2#3808]
The to() documentation doesn't indicate what it returns.  It seems to return whatever went into it, to allow you to pipe the output of the to() somewhere else, or to do some additional processing on it.  If that's the design decision I'm fine with it, but I would suggest that this page should explicitly state that.  (Apparently it also drops null timestamps - if we can confirm that, then that fact should be documented as well).

##### Relevant URLs
- https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/to/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
Thanks @wz2b. `to()` returns the input stream unmodified, so you can perform further processing. I'll add this to the documentation.

Information about `null` timestamps is already noted in the documentation: https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/to/#output-data-requirements
