### ISSUE TITLE
Add Kapacitor 1.6.4 release notes

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#3826]
Add release notes
https://docs.influxdata.com/kapacitor/v1.6/about_the_project/releasenotes-changelog/

and related docs as needed
per [Kapacitor 1.6.4 changelog](https://github.com/influxdata/kapacitor/blob/master/CHANGELOG.md)

cc @samhld @timhallinflux @docmerlin @dgnorton

**Comment by kelseiv** [comment]
@lwandzura, the following feature will be going into this Kapacitor release: https://github.com/influxdata/kapacitor/pull/2677 
please work with @docmerlin 

cc @samhld for docs review and release announcement

**Comment by lwandzura** [comment]
branch for this is kapa-v1.6.4-release-notes

**Comment by tara-influxdata** [comment]
Very excited about this. 🙌
