### ISSUE TITLE
Fix broken link - Install and Deploy link in v1.9x doc

### ISSUE THREAD

**Issue by lwandzura** [influxdata/docs-v2#3837]
The link in the Next Steps section of the "InfluxDB Enterprise 1.9 documentation" is broken:

![image](https://user-images.githubusercontent.com/51929958/157107436-d7d5b3b3-46a6-4f3d-9167-1c857c40363c.png)

The link is in this doc:

https://docs.influxdata.com/enterprise_influxdb/v1.9/

**Comment by sanderson** [comment]
We need to fix this in two ways:

- Global find and replace inside of `content/enterprise_influxdb/v1.9`: `/enterprise_influxdb/v1.9/introduction/installation/` => `/enterprise_influxdb/v1.9/introduction/installation/`.
- Add `/enterprise_influxdb/v1.9/install-and-deploy/` as an alias on `/enterprise_influxdb/v1.9/introduction/installation/` to catch any external links that may be pointing to the old page pattern.
