### ISSUE TITLE
smc_ipmi plugin removed; link persists

### ISSUE THREAD

**Issue by tkyocum** [influxdata/docs-v2#3841]
`smc_ipmi` is listed as a native plugin. It has been removed to an external plugin by the author and should not be listed in the docs, which currently returns a 404. 

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1.21/plugins/#smc_ipmi
- https://github.com/influxdata/telegraf/issues/9418

**Comment by rishvantsingh** [comment]
Allot it to me . I will do it.

**Comment by rishvantsingh** [comment]
Hii @tkyocum . Can you tell me from where should i remove the link ?

**Comment by kelseiv** [comment]
thank you, @tkyocum! removed
