### ISSUE TITLE
Doc issue: InfluxDB Cloud comparison table

### ISSUE THREAD

**Issue by dmarcocdw** [influxdata/docs-v2#3842]
The table has two columns with the same heading, I believe they are not supposed to be the same as the row data is different.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/query-data/optimize-queries/#pushdown-functions-and-function-combinations
- https://docs.influxdata.com/influxdb/cloud/query-data/optimize-queries/

**Comment by sanderson** [comment]
Thanks for reporting @dmarcocdw. I just pushed a fix for this and it should be live soon.
