### ISSUE TITLE
Provide example explaining 3 query endpoints from usage.from()

### ISSUE THREAD

**Issue by bckeene** [influxdata/docs-v2#3859]
It would be helpful to have an example showing and explaining what these endpoints represent:

```
/api/v2/query
/query
/tasks/query
```

##### Relevant URLs
- https://docs.influxdata.com/flux/v0.x/stdlib/experimental/usage/from/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
@bckeene AFAIK, there isn't a `/tasks/query` endpoint. Where are you seeing this?

We can add the example. Just a few quick notes:

- `/api/v2/query`: Flux query endpoint
- `/query`: InfluxQL query endpoint (v1 compatibility API)
- `/tasks/query`: ??

**Comment by bckeene** [comment]
I believe `/tasks/query` captures the number of queries associated with tasks running in the background:
<img width="1039" alt="Screen Shot 2022-03-14 at 4 19 01 PM" src="https://user-images.githubusercontent.com/3768387/158276467-816d0d27-8143-469b-826c-7ba5d1be5329.png">

Although, I think the default field name of "req_bytes" is mislabeled. Maybe we should get confirmation from someone on the Flux team.

**Comment by sanderson** [comment]
The `req_bytes` label isn't a Flux bug. It's how it gets reported at the usage endpoint. Here's the related issue: https://github.com/influxdata/idpe/issues/12875

**Comment by sanderson** [comment]
@bckeene I got some more information on the `/tasks/query` endpoint. It's an internal API used in Cloud to help track task executions, but they are going to map it's usage back to the `/api/v2/query` endpoint for public consumption. So the updated examples only need to include `/api/v2/query` and `/query`.

**Comment by bckeene** [comment]
Thanks for looking into this - I think it could be beneficial to separate your query count from Tasks but just my two cents. Glad we got confirmation on this though.
