### ISSUE TITLE
Document new InfluxDB OSS --hardening-enabled feature

### ISSUE THREAD

**Issue by jdstrand** [influxdata/docs-v2#3866]
**PR:** https://github.com/influxdata/influxdb/pull/23207

A new `--hardening-enabled` option is added to influxd turn on IP address verification and limit both flux and template fetching HTTP requests to non-private addresses. In the future, we plan to enable new security features that aren't suitable for the default install with this option. Put another way, this new option is intended to be used to make it easy to turn on all security options when running in production environments.

It's enabled by starting InfluxDB with the `--hardening-enabled` command line flag.

It's useful because certain flux functions (eg, `to()`, `from()`, etc) and template fetching cause InfluxDB to make HTTP requests over the network. When private IP validation is enabled, InfluxDB will first verify that the IP address of the URL is not a private IP address.

Milestoning to InfluxDB OSS 2.2, but we plan to backport this to 2.1 as well.

**Comment by jdstrand** [comment]
FYI, https://github.com/influxdata/docs-v2/pull/3873 was merged into [oss-2.2-base](https://github.com/influxdata/docs-v2/tree/oss-2.2-base) so this is all queued up.

**Comment by samhld** [comment]
@sanderson @jdstrand what needs to be done with this issue if the #3873 was merged, if anything?

**Comment by sanderson** [comment]
Nothing. This is all wrapped up. Closing.
