### ISSUE TITLE
Formatting issue on Page FAQ

### ISSUE THREAD

**Issue by XiaozhanYang** [influxdata/docs-v2#3868]
Some part of the document has been mistakenly used example format. This happens from the question:

[Why do my queries return no data or partial data?](https://docs.influxdata.com/influxdb/v1.7/troubleshooting/frequently-asked-questions/#why-do-my-queries-return-no-data-or-partial-data)

Point 4.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v1.7/troubleshooting/frequently-asked-questions/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
Thanks @XiaozhanYang! Just pushed a fix for this and it will be live in the next few minutes.
