### ISSUE TITLE
Document new Flux script builder in Chronograf

### ISSUE THREAD

**Issue by lwandzura** [influxdata/docs-v2#3887]
https://github.com/influxdata/chronograf/pull/5852

The Flux query builder in Chronograf has changed.  

The key features of the new query builder include:

- always builds a complete flux query/script
- always scoped to a selected time range
- offers new tag keys and values based on already selected tag keys and tag values
- scales well even with big tag name/value spaces, the background queries are limited to 200; the user can search for key names/values.

See PR for additional detail

#### Relevant URLs
Doc to update:

https://docs.influxdata.com/chronograf/v1.9/guides/querying-data/#explore-data-with-flux

**Comment by kelseiv** [comment]
remove the Flux Script Wizard from this page as well--it's been replaced with the Script Builder (similar to what's in influxdb)
