### ISSUE TITLE
Document ability to set time range on schema data

### ISSUE THREAD

**Issue by lwandzura** [influxdata/docs-v2#3888]
**PR:** _Provide PR URL(s) for this feature (if available)_

https://github.com/influxdata/chronograf/pull/5858

_Describe the new feature here._

Users can now set different time range in Flux schema explorer.  Previously explorer always used -30d as a time range to show schema data.  Users can now set other date range options.

#### Relevant URLs
- _Provide relevant URLs (issues, community threads, existing doc pages, etc.)_

https://docs.influxdata.com/chronograf/v1.9/guides/querying-data/#explore-data-with-flux

**Comment by kelseiv** [comment]
I believe we're calling this the Script Builder (and the other view is the Script Editor)

**Comment by kelseiv** [comment]
> Query Builder and Script Editor

Thank you, @sanderson!
