### ISSUE TITLE
Support /v2/api/delete in 1.X

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/docs-v2#3914]
**[PR: 23247](https://github.com/influxdata/influxdb/pull/23247)**

This implements a /v2/api/delete endpoint that supports a subset of the V2 delete functionality 

- This will permit common code to run against V1 and V2.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.1/reference/syntax/delete-predicate
- https://docs.influxdata.com/influxdb/cloud/api/#tag/Delete
- https://docs.influxdata.com/influxdb/cloud/reference/syntax/delete-predicate/

**Comment by samhld** [comment]
This should include an example similar to the current v2 endpoints in Enterprise docs.

**Comment by lwandzura** [comment]
see this example:

https://docs.influxdata.com/influxdb/cloud/write-data/delete-data/#delete-data-using-the-api

**Comment by lwandzura** [comment]
Replace 2.0 with 2.x here where applicable:
https://docs.influxdata.com/enterprise_influxdb/v1.10/tools/api/
