### ISSUE TITLE
Add release notes for influx-cli 2.3

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#3937]
This docs page: https://docs.influxdata.com/influxdb/v2.2/reference/release-notes/influx-cli/

I think we can just link to this section of the release notes for the DB, yeah?

**Comment by kelseiv** [comment]
- Add `influx remote` and `influx replication` (link to existing docs)
- Add the following options to `influx auth create` https://github.com/influxdata/influx-cli/pull/325/files (need to update this doc):
   - `drop-non-retryable-data` https://github.com/influxdata/influx-cli/pull/330
   - ` max-age`: https://github.com/influxdata/influxdb/issues/23109

**Comment by lwandzura** [comment]
remote: https://docs.influxdata.com/influxdb/v2.2/reference/cli/influx/remote/
(https://influxdata.slack.com/archives/C03A54M4GLD/p1649349588378439)
replication: https://docs.influxdata.com/influxdb/v2.2/reference/cli/influx/replication/
(https://influxdata.slack.com/archives/C03A54M4GLD/p1649349618594509)
hardening-enabled: https://docs.influxdata.com/influxdb/v2.2/reference/config-options/#hardening-enabled

**Comment by DStrand1** [comment]
Features:
- **feat: Added `influx replication` and `influx remote` commands**
    - Lots of different steps of the work, but all of this could just be adding these commands 
    - https://github.com/influxdata/influx-cli/pull/325
    - https://github.com/influxdata/influx-cli/pull/330
    - https://github.com/influxdata/influx-cli/pull/333
    - https://github.com/influxdata/influx-cli/pull/336
    - https://github.com/influxdata/influx-cli/pull/341
    - https://github.com/influxdata/influx-cli/pull/347
    - https://github.com/influxdata/influx-cli/pull/360
    - https://github.com/influxdata/influx-cli/pull/367
    - https://github.com/influxdata/influx-cli/pull/369
- **feat: enhanced error messages for cloud and oss specific commands**
    - PR: https://github.com/influxdata/influx-cli/pull/347
    - Issue Closed: https://github.com/influxdata/influx-cli/issues/142
- **feat: add server-config command**
    - PR: https://github.com/influxdata/influx-cli/pull/346
    - Issue from InfluxDB that describes it more: https://github.com/influxdata/influxdb/issues/22917
    - Docs issue for this feature: https://github.com/influxdata/docs-v2/issues/3523

Bug Fixes:
- **fix: v1 auth create command supports multiple buckets**
    - PR: https://github.com/influxdata/influx-cli/pull/328
    - Issue Closed: https://github.com/influxdata/influx-cli/issues/327
- **fix: Use influx-debug-id header**
    - PR: https://github.com/influxdata/influx-cli/pull/338
- **fix: duration parser shows duration missing units on error**
    - PR: https://github.com/influxdata/influx-cli/pull/348
    - Issue Closed: https://github.com/influxdata/influx-cli/issues/171
- **fix: template apply uses better diff checking**
    - PR: https://github.com/influxdata/influx-cli/pull/358
    - Issue Closed: https://github.com/influxdata/influx-cli/issues/233
- **fix: `influx apply` with `-e jsonnet` fails**
    - PR: https://github.com/influxdata/influx-cli/pull/370
    - Issue Closed: https://github.com/influxdata/influx-cli/issues/351
