### ISSUE TITLE
Influx CLI 2.3.1 release notes

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#3953]
### Features
  -  [ ] Add --extra-http-header flag? (TBD)

### Bug fixes
  - [ ] Add mutual exclusion for OrgID and OrgName parms

**Comment by kelseiv** [comment]
@samhld has this release been scheduled?

**Comment by samhld** [comment]
@kelseiv nope :)

**Comment by lwandzura** [comment]
did not make the release
