### ISSUE TITLE
Support for /v2/api/buckets endpoints

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/docs-v2#3961]
**ETA:** May 2022
**PR:** https://github.com/influxdata/influxdb/pull/23284

Support for /v2/api/buckets endpoints. The PR above encompasses create, delete, list, and retrieve.

- This allows some client code using buckets to run against 1.X and 2.X and Cloud 2 without modification

Example:
```
curl --request GET "http://localhost:8086/api/v2/buckets"   --header "Content-type: application/json" -H 'Authorization: Token <user>:<password>'

curl --request DELETE "http://localhost:8086/api/v2/buckets/stress/autogen"   --header "Content-type: application/json"   -H 'Authorization: Token <user>:<password>'
```
##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/api/#tag/Buckets
- https://docs.influxdata.com/enterprise_influxdb/v1.9/tools/api/?t=Auth+Enabled#influxdb-20-api-compatibility-endpoints

Release:
InfluxDB 1.10

**Comment by samhld** [comment]
Can we include an example API call for each of the methods supported similar to current v2 endpoint docs?
