### ISSUE TITLE
Missing admin/config page for 1.22

### ISSUE THREAD

**Issue by mchandler-wowcorp** [influxdata/docs-v2#3983]
_404 for Telegraf 1.22 admin/config page_

Check the installation page, linked below, for the text "For more advanced configuration details, see the [configuration documentation](https://docs.influxdata.com/telegraf/v1.22/administration/configuration/)."

##### Relevant URLs
- [ Broken Telegraf 1.22 admin config page ](https://docs.influxdata.com/telegraf/v1.22/administration/configuration/)
- [ Referring page - Telegraf 1.22 Installation](https://docs.influxdata.com/telegraf/v1.22/install/)
 

##### What products and version are you using?

Telegraf 1.22

**Comment by kelseiv** [comment]
thank you, @mchandler-wowcorp! 
@noramullen1 is on the case https://github.com/influxdata/docs-v2/issues/3955

**Comment by sanderson** [comment]
Related to #3947
