### ISSUE TITLE
Document the v2 storage engine

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#399]
The 2.0 storage engine is essentially the same as 1.7 with some key changes:

1. Only TSI is supported. There is no more in-memory index.
2. The configuration interface and options have changed. Configuration options are not currently exposed, but will be.
3. Buckets replace DB + RP.
4. Retention is done by delete, not by evicting time-partitioned data.

**Comment by pierwill** [comment]
Closed by #556.
