### ISSUE TITLE
404 on Install the InfluxData page

### ISSUE THREAD

**Issue by dixanms** [influxdata/docs-v2#3996]
On page [Install the InfluxData](https://docs.influxdata.com/platform/install-and-deploy/install/oss-install/) you get 404 error when clicking on [Telegraf installation instructions](https://docs.influxdata.com/telegraf/v1.22/introduction/installation/)

##### Relevant URLs
- [Telegraf installation instructions](https://docs.influxdata.com/telegraf/v1.22/introduction/installation/)

**Comment by lwandzura** [comment]
this needs to be updated as well:
https://docs.influxdata.com/platform/install-and-deploy/install/
