### ISSUE TITLE
Map performance is poor in a large amount of data?

### ISSUE THREAD

**Issue by sea-007** [influxdata/docs-v2#3998]
_Describe the issue here._

##### Relevant URLs
- https://docs.influxdata.com/flux/v0.x/stdlib/universe/map/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
@sea-007 Thanks for reporting this. This isn't necessarily a documentation issue, so I'm going to go ahead and close it. I'd encourage you to create a new issue on the [Flux project repo](/influxdata/flux/).

I do know the Flux team is currently working on optimizing common operations performed with `map()`, but even with optimizations, the larger your dataset is, the longer any `map()` operation is going to take. Map iterates over all input rows and either updates or replaces them. The more rows it has to iterate over, the longer it will take.
