### ISSUE TITLE
Remove data backup request section 

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs-v2#4005]
We will be replacing the manual archive request process with bulk export tooling, once it's available. We should remove the section on requesting a data backup from the docs.

##### Relevant URLs
- [Account cancellation doc](https://docs.influxdata.com/influxdb/cloud/account-management/offboarding/#request-a-data-backup)

##### What products and version are you using?

InfluxDB Cloud

**Comment by lwandzura** [comment]
@gunnaraasen Do you have an ETA on when this tool will be available?

**Comment by sanderson** [comment]
We've already removed this text and replaced it with content pointing to the manual migration doc. Once bulk export is available, we'll revisit this.
