### ISSUE TITLE
Enterprise 1.10 release notes

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#4011]
## Features
- Add `/v2/api/buckets` support for `create`, `delete`, `list`, `retrieve`, and `update` operations
- Add `/v2/api/delete` support
- Add wildcard support for retention policies in `SHOW MEASUREMENTS`
- Log slow queries even when query logging is not enabled
- Add `--start` and `--stop` flags to backup procedure to break up the work by time
- Add `Raft Status` output to `inflxud-ctl show`

## Maintenance updates
 - Upgrade Flux to 0.170.0
 - Upgrade Go to 1.18.3
 - Fixes issue with OSXCross and Darwin builds. This results in the new minimum OSX version being MacOSX10.14/darwin18

### Flux updates
- Add `preview()` to `experiemental` package for limiting return rows and tables (as opposed to just rows with `limit()`)
- Add `date.scale()` to let users dynamically scale durations in dates
- Add [OpenTracing spans](https://opentracing.io/docs/overview/spans/) to Flux transformations. This allows developers to more precisely monitor Flux scripts.
- Add trace option to Flux CLI
- Move `addDuration()` and `subDuration()` out of `expterimental` to `date` package.
- Add location support to `date.truncate()`
- Vectorize arithmetic operators in `map()`

### Backup
  - Fix backup estimation so it dynamically updates with known information as progress is made
  - Working backup now created when only `-shard` flag is passed to `influxd-ctl backup`
### Influx_Inspect
  - Now properly exports multiple RPs on the same DB
  - `verify` subcommand no longer appends` /data` to the `-dir` flag path parameter
### Other
  - Grow tag index buffer if needed. This avoids a panic in the rare case of exactly 100 tags in a record.
  - Fix multiple results returned per timestamp for some nested InfluxQL queries 
  - Sync index file before close to avoid a shard reload error on instance restart
  - Fix rare case of `numMeasurements` reporting as less than 0 in `/debug/vars`
  - Fix `influxd config` panic
  - Fix shard confusion when multiple sub-queries reference different retention policies

**Comment by samhld** [comment]
@lwandzura release not ready yet, just priming it. Will notify you.

**Comment by lwandzura** [comment]
@samhld please confirm we'll need to update these two FLUX docs and remove the experimental verbiage:

https://docs.influxdata.com/flux/v0.x/stdlib/experimental/subduration/

https://docs.influxdata.com/flux/v0.x/stdlib/experimental/addduration/

**Comment by samhld** [comment]
@nathanielc can you help verify this for docs? ^^

**Comment by kelseiv** [comment]
Hi @lwandzura @samhld --this came up in the [OSS 2.3 release](https://docs.influxdata.com/influxdb/v2.3/reference/release-notes/influxdb/#v23-2022-6-17)--we can reuse the following verbiage:

Rename `addDuration()` to [`add`](https://docs.influxdata.com/flux/v0.x/stdlib/date/add/) and `subDuration()` to [`sub`](https://docs.influxdata.com/flux/v0.x/stdlib/date/sub/), and moved both of these functions from the experimental package to the [date package](https://docs.influxdata.com/flux/v0.x/stdlib/date/).

@samhld, are any other [Flux advancement highlights](https://docs.influxdata.com/influxdb/v2.3/reference/release-notes/influxdb/#flux-advancement-highlights) we added to the OSS 2.3 applicable to this Enterprise release that @lwandzura can reuse? Thanks!

**Comment by samhld** [comment]
@kelseiv Yeah, any that are overlapping can be re-used IMO.

**Comment by lwandzura** [comment]
@kelseiv Thanks for pointing me to the OSS Flux updates!

**Comment by lwandzura** [comment]
@samhld these were part of OSS 2.3 release, do they apply to Enterprise as well?

- Vectorize logical operations in `map()`.
- Enable `movingAverage()` and `cumulativeSum()` optimizations by default.

**Comment by samhld** [comment]
Yes, actually. Looks like Flux got another update since I last updated this! Good catch.
