### ISSUE TITLE
Formatting broken in the middle of the document

### ISSUE THREAD

**Issue by tinbert** [influxdata/docs-v2#4018]
Just after the video on the "GROUP BY clause", the formatting of the document runs havoc. The heading "INTO clause" is already buried inside a wrong "format" type, the html target for the INTO clause does not work as well.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v1.3/query_language/data_exploration/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by lwandzura** [comment]
fixed version 1.4, 1.5 and 1.6 pages on data exploration as well
