### ISSUE TITLE
homebrew package name

### ISSUE THREAD

**Issue by bjarne-hansen** [influxdata/docs-v2#4022]
_Describe the issue here._

##### Relevant _URLs_
- https://docs.influxdata.com/influxdb/v2.2/install/
- _Provide other relevant URLs (project issues, community threads, etc.)_

_Homebrew also installs influx-cli as a dependency. For information about using the influx CLI, see the [influx CLI reference documentation](https://docs.influxdata.com/influxdb/v2.2/reference/cli/influx/)._

The homebrew name is **influxdb-cli**

**Comment by sanderson** [comment]
Thanks @bjarne-hansen!
