### ISSUE TITLE
InfluxDB Cloud FAQ

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#4029]
**ETA:** Already in production

The InfluxDB Cloud left nav now includes a "help bar" with links to documentation, specifically FAQ. Right now, FAQ points to the InfluxDB 1.8 FAQ. This certainly isn't ideal. We need to create 2.x and Cloud FAQ page with questions specifically for 2.x and Cloud.

**Comment by lwandzura** [comment]
Some things to add to an FAQ page:

Maybe add links to the following:
How do I change (reset) my password (https://docs.influxdata.com/influxdb/cloud/account-management/change-password/) 
How do I view data my data usage (https://docs.influxdata.com/influxdb/cloud/account-management/data-usage/)
How do I switch accounts (https://docs.influxdata.com/influxdb/cloud/account-management/switch-account/)
How do I manage billing (https://docs.influxdata.com/influxdb/cloud/account-management/billing/)
Who do I contact for billing issues?
How do I manage tokens?


From EARS:

What do I do if I need to have limits increased?
How do I get a backup of my data?
If using InfluxQL, how do I create DBRP mappings? (this is also documented)
Common error messages and what they mean (not sure if we have this officially documented)

**Comment by lwandzura** [comment]
From Nora:
Q: Can you change the permission level of members in your organization?
A: No, InfluxDB Cloud has only one permission level for users: Owner. With Owner permissions, a user can delete resources and other users from your organization. Take care when inviting a user.
