### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by MikeP-NZ** [influxdata/docs-v2#4042]
_Describe the issue here._
I'm trying to connect Grafana Cloud to InfluxDB2 -cloud. 
The info here does not reflect current version of the Grafana add data source form.
The form layout and section names have changed and there is now an auth section

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/tools/grafana/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sunbryely-influxdata** [comment]
Additional user-feedback for the same issue
https://github.com/influxdata/docs-v2/issues/4105
