### ISSUE TITLE
Download/Install instructions no longer match download page

### ISSUE THREAD

**Issue by imasoninflux** [influxdata/docs-v2#4056]
The referenced downloads page has changed and the docs no longer reflect the way a user would go about installing InfluxDB2
https://portal.influxdata.com/downloads/ now uses exclusively repositories to install on Linux

Additionally links like `https://dl.influxdata.com/influxdb/releases/influxdb2-2.2.0-amd64.rpm` look to no longer exist and thus cannot be used for downloads.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.2/install/

**Comment by imasoninflux** [comment]
Additionally, we direct users to the downloads page _to obtain the downloads url_ when we no longer list a download url, due to preferring repositories. I'm not sure how best to correct that, but I don't think we should be pointing them to that page to find a package to download anymore.

**Comment by kelseiv** [comment]
thank you, @imasoninflux @jdstrand, we'll update the filenames and verbiage to address
and cc you both and @bnpfeife for review
