### ISSUE TITLE
Large Windows buttons on Telegraf installation page

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#4067]
_Describe the issue here._
Windows button is oddly long in the Telegraf installation instructions. Windows isn't any more important than the others so no need for it to be so big.

![image](https://user-images.githubusercontent.com/32681364/170349939-bcd22ac5-3781-4a7d-adbd-e5159136dc1d.png)

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1.22/install/#installation

**Comment by sanderson** [comment]
@sjwang90 Bug? Don't you mean feature? 😉 I'll look into it.

**Comment by sanderson** [comment]
These now look like this:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/181484/170517259-721d9761-c9db-4736-8c3f-90070424717b.png">
