### ISSUE TITLE
Configuration documentation link is broken

### ISSUE THREAD

**Issue by maWberg** [influxdata/docs-v2#4078]
The link which provides detailed information about the telegraf documentation is not working anymore. 
It is located at the end of the website between "Create a configuration file with specific inputs and outputs" and "Was this page helpful?"

Links:
page: https://docs.influxdata.com/telegraf/v1.22/install/
not working link: https://docs.influxdata.com/telegraf/v1.22/administration/configuration/

**Comment by noramullen1** [comment]
Thanks @maWberg, this is now fixed.
