### ISSUE TITLE
Command "print-config" is deprecated

### ISSUE THREAD

**Issue by micjat** [influxdata/docs-v2#4112]
_Describe the issue here._

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.2/tools/influx-cli/
- _Provide other relevant URLs (project issues, community threads, etc.)_

I'm getting :
"Command "print-config" is deprecated, use the influx-cli command server-config to display the configuration values from the running server"

Please update instructions.
Thanks

**Comment by lwandzura** [comment]
deleting from 2.3 and 2.4, adding print-config 2.2 as an alias

influxd print-config was changed to influx server-config after OSS 2.2
