### ISSUE TITLE
Add alert about known bug in Replications in v2.2

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#4120]
_Describe the issue here._

There is a known bug having to do with replications not persisting after remote connection is lost. This should be called out on release notes and the replications procedure page, I would think.

@kelseiv @sanderson @lwandzura Thoughts?

**Comment by kelseiv** [comment]
We could add a warning in the InfluxDB 2.2 release notes, under [this heading](https://docs.influxdata.com/influxdb/v2.2/reference/release-notes/influxdb/#technical-preview-replicate-data-remotely).

Known issue: 
Occasionally, `remote-write` failures cause data in the replication queue to get stuck. 
<insert how they will know this is happening--will certain errors appear?>
To resolve this issue, restart the edge node <restart InfluxDB service?> to ensure remote writes are successfully processed.

**Comment by samhld** [comment]
@kelseiv thanks!

I believe the only way they'll know it's happening is buy checking the presence of data in the target. You could also get a "hint" if the queue size is growing while your local bucket ingest is not....but again that's just a hint. 

Something like:
"""
#### Known issue:
On rare occasions, remote-write failures will cause the data in the replication queue to get stuck. You'll be able to identify this is happening by checking the presence of data you expect in the replication target bucket. A less exact indication that this may be happening would be a buildup of the queue size. You can view this size with `influx replication list[|ls\`.

Preceding the fix to this issue, you can remediate the issue by restarting your node. We recommend doing this earlier rather than later as the queue can build up, resulting in dropped data.
"""
