### ISSUE TITLE
Update release notes for Enterprise 1.9.8 

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#4124]
Copy hidden content in InfluxDB Enterprise 1.9.7 release notes to 1.9.8 and revert the passive node docs PR.
Update to the latest Flux version (verify with Edge team what version is being included).

cc @samhld @davidby-influx for review

**Comment by samhld** [comment]
Update with:

### Maintenance
 - Update to Go 1.17.11

### Bug fixes
- Do not back-off on RPC retries for non-RPC errors. Resolves a case where hinted handoff would build constantly.

**Comment by lwandzura** [comment]
@samhld if additional features need to be added please add here.

**Comment by samhld** [comment]
@lwandzura the comment above yours is where I put them. Does that work?
