### ISSUE TITLE
OSS 2.3 Release Notes

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#4133]
### Maintenance
- Upgrade Flux from 0.161.0 to 0.171.0
- Upgrade Go to 1.18.3

### Features
- Add `--instance-id` flag to `influxd` runtime for adding `_instance_id` Tag to outgoing metrics via remote replications. This will help users ID where metrics came from and ensure two instances don't overwrite each others data in some cases.
- Add signifier to replication `user-agent` when replication write requests are made. This helps ID that the metric was written via replications.

##### Performance:
- Vectorize arithmetic operators in `map()`
- Vectorize logical operations in `map()`
- Enable `movingAverage()` and `cumulativeSum()` optimizations by default
##### Other:
- Add `preview()` to experimental package for limiting return rows and tables (as opposed to just rows with `limit()`)
- Add `date.scale()` to let users dynamically scale durations in dates
- Add [OpenTracing spans](https://opentracing.io/docs/overview/spans/) to Flux transformations. This allows developers to more precisely monitor Flux scripts.
- Add trace option to Flux CLI
- Move `addDuration()` and `subDuration()` out of experimental to date package.
- Add location support to `date.truncate()`
- Add `_status` Tag to PagerDuty record
- Refactor operator profile to be in the query statistics

### Bug Fixes
- Fix race condition when remote replicating that deadlocks the remote writer, resulting in no more writes to the target.
- Error when creating v1 auth with a nonexistent bucket ID
- Add fields to `_tasks` bucket to match schema of the same bucket in InfluxDBCloud. Provides consistency for clients accessing both.
- Fix rare case where Measurement cardinality reported less than zero
- No longer panic on cleaning up failed iterators

**Comment by admco** [comment]
> ### Maintenance
> * Upgrade Flux from 0.161.0 to 0.171.0
> * Upgrade Go to 1.18.3
> 
> ### Features
> * Add `--instance-id` flag to `influxd` runtime for adding `_instnace_id` Tag to outgoing metrics via remote replications. This will help users ID where metrics came from and ensure two instances don't overwrite each others data in some cases.
> * Add signifier to replication `user-agent` when replication write requests are made. This helps ID that the metric was written via replications.
> 
> #### Flux advancement
> ##### Performance:
> * Vectorize arithmetic operators in `map()`
> * Vectorize logical operations in `map()`
> * Enable `movingAverage()` and `cumulativeSum()` optimizations by default
> 
> ##### Other:
> * Add `preview()` to experimental package for limiting return rows and tables (as opposed to just rows with `limit()`)
> * Add `date.scale()` to let users dynamically scale durations in dates
> * Add [OpenTracing spans](https://opentracing.io/docs/overview/spans/) to Flux transformations. This allows developers to more precisely monitor Flux scripts.
> * Add trace option to Flux CLI
> * Move `addDuration()` and `subDuration()` out of experimental to date package.
> * Add location support to `date.truncate()`
> * Add `_status` Tag to PagerDuty record
> * Refactor operator profile to be in the query statistics
> 
> ### Bug Fixes
> * Fix race condition when remote replicating that deadlocks the remote writer, resulting in no more writes to the target.
> * Error when creating v1 auth with a nonexistent bucket ID
> * Add fields to `_tasks` bucket to match schema of the same bucket in InfluxDBCloud. Provides consistency for clients accessing both.
> * Fix rare case where Measurement cardinality reported less than zero
> * No longer panic on cleaning up failed iterators
