### ISSUE TITLE
getting the config - command is deprecated :-(

### ISSUE THREAD

**Issue by bnachtwey** [influxdata/docs-v2#4163]
_Describe the issue here._

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.3/install/

# Problem:
issueing `docker run --rm influxdb:2.3.0 influxd print-config > config.yml` I got an error the command is deprecated:

```
/Docker/MountPoints/influxdb2-etc# docker run \
  --rm influxdb:2.3.0 \
  influxd print-config > config.yml
Command "print-config" is deprecated, use the influx-cli command server-config to display the configuration values from the running server
```
BUT nevertheless the file was created.

trying to use the suggested `influx server-config` inside the running container I got another error:
```
root@3d807eaa7253:/# influx server-config
Error: failed to retrieve config: 401 Unauthorized: unauthorized access
```
Beeing a newbee to influx, I do not have any idea what's wrong.

thx
Bjørn

**Comment by kelseiv** [comment]
Welcome, Bjørn! 
Yes, the [influxd print-config](https://docs.influxdata.com/influxdb/v2.3/reference/cli/influxd/print-config/) has been deprecated in _InfluxDB OSS 2.3_. Will let our team know that this file is still being created.

To use the [influx server-config](https://docs.influxdata.com/influxdb/v2.3/reference/cli/influx/server-config/), you must use an [operator token](https://docs.influxdata.com/influxdb/v2.3/security/tokens/#operator-token). Please see how you can [view existing tokens](https://docs.influxdata.com/influxdb/v2.3/security/tokens/view-tokens/) or  [create a new token](https://docs.influxdata.com/influxdb/v2.3/security/tokens/view-tokens/).
