### ISSUE TITLE
Document Enterprise FIPS build

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#4168]
Issue description
We will be releasing a new build of Enterprise that have compatibility with [FIPS standards](https://www.nist.gov/standardsgov/compliance-faqs-federal-information-processing-standards-fips). Specifically, the Enterprise FIPS build is uses FIPS 140-2 compliant cryptography libraries. Note that Enterprise itself is not "certified" as FIPS compliant, but can help companies who need to be FIPS compliant reach that designation.
________________

Good reference docs: https://docs.oracle.com/database/121/DBSEG/asoappe.htm#DBSEG1041

Another example to possibly borrow ideas from: https://www.mongodb.com/docs/manual/tutorial/configure-fips/

**Comment by lwandzura** [comment]
Additional links
Github epic: https://github.com/orgs/influxdata/projects/68/views/1?filterQuery=epic%3AFIPS

What product(s) and version(s) does this apply to?
InfluxDB Enterprise 1.11 FIPS build

Link(s) to documentation that needs to be changed
https://docs.influxdata.com/enterprise_influxdb/v1.11/

What needs to be added or updated?
For FIPS documentation, we would like to have a section very similar to [Hashicorp's FIPS documentation](https://developer.hashicorp.com/vault/docs/enterprise/fips).

**Comment by lwandzura** [comment]
Additional info from @gwossum below. 

FIPS build limitations:
- Direct upgrade path from non-FIPS to FIPS is not currently supported (related to password hashing)
- Flux does not support mssql / sqlserver or snowflake databases in from() and to()
- TLS uses a restricted set of functionality (mandated by FIPS):
    - TLS 1.2 only
    - TLS only supports the following cipher suites:
        - ECDHE_RSA_WITH_AES_128_GCM_SHA256 
        - ECDHE_RSA_WITH_AES_256_GCM_SHA384,
        - ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
        - RSA_WITH_AES_128_GCM_SHA256
        - RSA_WITH_AES_256_GCM_SHA384
- Restrictions on digital signatures supported (mandated by FIPS). This impacts TLS certificates. The following signatures are supported:
    - PSSWithSHA256
    - PSSWithSHA384
    - PSSWithSHA512
    - PKCS1WithSHA256
    - ECDSAWithP256AndSHA256
    - PKCS1WithSHA384
    - ECDSAWithP384AndSHA384
    - PKCS1WithSHA512
    - ECDSAWithP521AndSHA512
- Restrictions on RSA key size (manded by FIPS). This impacts TLS certificates. The following RSA key sizes are supported:
    - 2048
    - 3072
- Restrictions on EC curves supported (mandated by FIPS). This impacts TLS certificates. The following EC curves are supported:
    - P-256
    - P-384
    - P-521

If you start with a fresh install without a config file that sets the password hash, it will default to a FIPS-compliant password hash that conforms to NIST SP 800 and OWASP guidelines. In fact, it will not let you configure a non-FIPS password hash. It will crash out on startup if you specify something like `bcrypt`.
