### ISSUE TITLE
Influx CLI 2.4 Release Notes

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#4170]
### Features
- Allow setting membership type in with `influx org members add` where only `member` was available before
- Add back the InfluxQL Shell (REPL) from v1 with an enhanced experience
- **[Cloud only]** Allow for calling [Invokable Scripts](https://docs.influxdata.com/influxdb/cloud/api-guide/api-invokable-scripts/)
- **[OSS only]** Add username and password authentication as alternative to token
- **[OSS only]** Add username and password signin
- Add `--extra-http-header` flag
- Add `skipRowOnError` handling for raw line protocol files
- Prevent deletion of replications when deleting remotes. Support this with a `--delete-replications` flag to the `influx remote delete` command instead of automatically deleting replications associated with that remote.

### Maintence
- Upgrade to Go 1.18.3

### Bug fixes
- User and org permissions no longer scoped to an individual org. Removes an unwanted restriction
- Properly handle tokens starting with a hyphen (`-`) passed to CLI without `=` (i.e., `influx cmd --token <token>`)
- Add mutual exclusion for `--org`/`$INFLUX_ORG` and `org_id`/`$INFLUX_ORG_ID`. Eliminate confusion on which to use and whether env vars were overriding flags
- Show remotes and replications flags in `auth create` command

**Comment by samhld** [comment]
Not urgent. Creating CLI 2.4 docs issues early for lead time.

**Comment by lwandzura** [comment]
Do we have an ETA on this release?  Mid July? Late July?

**Comment by samhld** [comment]
Mid July

**Comment by lwandzura** [comment]
Update the following:

https://docs.influxdata.com/influxdb/v2.3/reference/release-notes/influx-cli/

**Comment by lwandzura** [comment]
@samhld for this:
Add back the InfluxQL Shell (REPL) from v1 with an enhanced experience

What does enhanced experience entail? Can we additional detail on that?

**Comment by samhld** [comment]
@lwandzura it's just a bunch of UX things. We could instead say:
- Add back the InfluxQL Shell (REPL) from v1. This comes with the original `column` result layout but also a new interactive `table` format, JSON, and csv.

**Comment by lwandzura** [comment]
release was Friday 8/19/2022, docs were published
