### ISSUE TITLE
Add username password auth CLI docs

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#4175]
Placeholder. TBD on exact experience.

**Comment by sanderson** [comment]
Is this part of the `v1` set of subcommands? If so, these commands already exist.

**Comment by samhld** [comment]
@sanderson No, it's not. This is include signing in with a username and password for v2. The same way you would in the UI but with the CLI. This `/signin` API uses this: https://docs.influxdata.com/influxdb/v2.3/api/#tag/Authentication

**Comment by samhld** [comment]
@sanderson bits are in. This is ready to go in.
