### ISSUE TITLE
Wrong function used in example

### ISSUE THREAD

**Issue by terjereinertsen** [influxdata/docs-v2#4187]
The function used in the Example query with stateCount() is wrong I believe.

Should it not be stateCount()

from(bucket: "doors")
    |> range(start: -5m)
    |> **_stateDuration_**(fn: (r) => r._value == "closed", column: "door_closed")

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.3/query-data/flux/monitor-states/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
Thanks for reprot @terjereinertsen!
