### ISSUE TITLE
How to match Data Explorer graph size (width) to the range of the query

### ISSUE THREAD

**Issue by Kortenbach** [influxdata/docs-v2#4189]
I read the docs on how to use the Data Explorer but I cannot find how to match the graph size to the (time) size of the query result. My query:
~~~
from(bucket: "FirstBucket")
//  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> range(start: 2022-07-06T13:00:00Z, stop: 2022-07-06T13:10:00Z)
  |> filter(fn: (r) => r["_measurement"] == "PLC1/Reg400004")
~~~
is only 10 mins long, but the x-axis of the graph is 16h long. I don't want to manually zoom in on the graph every time I view it.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/query-data/execute-queries/data-explorer/

**Comment by sanderson** [comment]
@Kortenbach unfortunately, there isn't a way to control this right now. There is an open issue related to this however: https://github.com/influxdata/influxdb/issues/17611

I'm going to close this issue for now. Feel free to add your thoughts to the issue linked above.
