### ISSUE TITLE
How to override default (optional) start, stop parameters?

### ISSUE THREAD

**Issue by PeterMilovcik** [influxdata/docs-v2#4193]
I'd like to override the default start, stop parameters and provide `start: v.timeRangeStart, stop: v.timeRangeStop` instead (in Grafana v8.5.5.).
Based on the function type signature of `schema.measurementTagValues()` function, I understand that start, stop parameters are optional. I understand that they have a default value and are not required. It also means (for me) that I can also change them to different than default values. However, if I try to add them to the call like that:

```flux
import "influxdata/influxdb/schema"

schema.measurementTagValues(bucket: "<bucket>", measurement: "<measurement>", tag: "<tag>", start: -15d)
```
I have the following error message:

```
invalid: type error @3:1-3:120: found unexpected argument start
```

If I try to add them to the call like that:

```flux
import "influxdata/influxdb/schema"

schema.measurementTagValues(bucket: "<bucket>", measurement: "<measurement>", tag: "<tag>", ?start: -15d)
```
I have the following error message:

```
invalid: compilation failed: error at @3:108-3:120: unexpected token for property key: QUESTION_MARK (?)
```

How can one override the optional default parameters?

##### Relevant URLs
- https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/schema/measurementtagvalues/
- https://docs.influxdata.com/flux/v0.x/function-type-signatures/

**Comment by sanderson** [comment]
@PeterMilovcik These functions in the schema package were updated with configurable `start` and `stop` parameters in [Flux 0.155.0](https://docs.influxdata.com/flux/v0.x/release-notes/#v01550-2022-02-14). What version of InfluxDB are you using. It could be that the version of Flux packaged with your specific version of InfluxDB doesn't support the updated/added parameters on the schema functions.

**Comment by PeterMilovcik** [comment]
Hi, we are using official docker image influxdb:2.0.8.

**Comment by PeterMilovcik** [comment]
Just updated to InfluxDB 2.3.0. and it works great. Thank you.
