### ISSUE TITLE
New Feature: Multi-Org - Switch Accounts & Switch Orgs

### ISSUE THREAD

**Issue by Luckette** [influxdata/docs-v2#4200]
**ETA:** Aug 18 2022
**PR:** https://github.com/influxdata/ui/issues/3968

The user will have the ability to:
- Switch accounts from a new global header at the top of the screen
- Switch organizations from a new global header at the top of the screen
- Navigate to their user profile from a new global header at the top of the screen

Users will no longer have to navigate to account > settings in order to switch accounts

**Comment by gunnaraasen** [comment]
Feature flag is `influx.toggle('multiOrg')`.

**Comment by ALuckette** [comment]
@gunnaraasen we need to review the changes that @noramullen1 made to the docs so that she can merge them.
