### ISSUE TITLE
error @1:1-1:25: invalid import path date/boundaries

### ISSUE THREAD

**Issue by Marek-maxs** [influxdata/docs-v2#4202]
_Describe the issue here._

##### Relevant URLs
- https://docs.influxdata.com/flux/v0.x/stdlib/date/boundaries/week/
- _Provide other relevant URLs (project issues, community threads, etc.)_

According to the documentation, I can't use date/boundaries;

error @1:1-1:25: invalid import path date/boundaries
influxdb version is 2.3

**Comment by sanderson** [comment]
@Marek-maxs The `date/boundaries` package was introduced in Flux 0.172.0. InfluxDB 2.3 ships with Flux 0.171.0. To use a newer version of Flux, you can either use the [nightly InfluxDB build](https://portal.influxdata.com/downloads/) or [build InfluxDB from source](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#building-from-source).
