### ISSUE TITLE
Kapa 1.6.5 release notes

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#4207]
Ref: https://github.com/influxdata/kapacitor/pull/2704/files

**Comment by lwandzura** [comment]
@samhld Is the ballpark next week?  or week after?

**Comment by samhld** [comment]
@lwandzura I don't know yet. It's up to support.

**Comment by samhld** [comment]
@lwandzura I posed that question as well so will defer to @docmerlin

**Comment by docmerlin** [comment]
@lwandzura @samhld newer influxql is updating the version of influxql so kappa can handle subqueries etc.  It now has full influxql support same as 1.9.x

**Comment by samhld** [comment]
@docmerlin Ah thank you!
