### ISSUE TITLE
Documentation of creating a task with script reference

### ISSUE THREAD

**Issue by yquansah** [influxdata/docs-v2#4209]
**ETA:** _Provide an estimated completion date for the feature (if available)_
**PR:** _Provide PR URL(s) for this feature (if available)_

_Describe the new feature here._

We are in the midst of releasing the new feature of creating a Task with a script reference to support reuse of code. Here is the openapi PR: https://github.com/influxdata/openapi/pull/349.

The purpose of this issue is to request some documentation on how to use this new feature in general. Any questions/answers will be tracked in this issue.

##### Relevant URLs
- [openapi Pull Request](https://github.com/influxdata/openapi/pull/349)

**Comment by jstirnaman** [comment]
Working with @evinaku on this. OpenAPI docs are done for now. Docs-v2 guides are on hold until future support of `flux` params is finalized.
