### ISSUE TITLE
Add InfluxQL docs to v2 docs

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#4213]
InfluxQL is a feature of v2 now (both OSS and Cloud). Pointing at 1.8 OSS is one thing but there are features in InfluxQL implemented in Enterprise, OSS, Cloud that are not in OSS 1.8. If we don't want to point people at new version of 1.X OSS nor point them at incomplete documentation for InfluxQL, we should have these docs available in v2 docs as well IMO.

The current feature that is not in 1.8 is `SHOW MEASURMENTS` grouping/filtering by RP.

**Comment by kelseiv** [comment]
related to https://github.com/influxdata/docs-v2/issues/3417

**Comment by lwandzura** [comment]
@samhld There's already an issue open for moving InfluxQL to 2.x, and I am about half done with the move. I am behind on this due to multiple re-prioritizations.

**Comment by samhld** [comment]
@lwandzura whoops, sorry -- should've looked first! We can close this out and just make sure we capture that `SHOW MEASUREMENTS` addition in the new version ported over.
