### ISSUE TITLE
Chronograf has a new reader role

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/docs-v2#4214]
**ETA:** _Provide an estimated completion date for the feature (if available)_

The feature is implemented, and new in the upcoming 1.10.

**PR:** _Provide PR URL(s) for this feature (if available)_

https://github.com/influxdata/chronograf/pull/5904

_Describe the new feature here._

Chronograf 1.10 adds a new `reader` role. Users in this role can see just Dashboards and see them in `read-only` mode.

Include pertinent details, such as:

- What the feature does and why it is useful

Viewers can see more than just Dashboards. Readers cannot and this is useful for some users who are not (or should not be) interested in seeing other artifacts such as tasks and alerts, management, logs, home page..

See the details and screenshots in the PR.

##### Relevant URLs
- _Provide relevant URLs (issues, community threads, existing doc pages, etc.)_

**Comment by lwandzura** [comment]
update this page with reader role:
https://docs.influxdata.com/chronograf/v1.9/administration/managing-chronograf-users/#manage-chronograf-users-and-roles
