### ISSUE TITLE
Chronograf 1.10 adds GUI for user, role, and permissions management for OSS and Enterprise

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/docs-v2#4215]
**ETA:** _Provide an estimated completion date for the feature (if available)_

This feature is implemented, pending a review form Support. ETA one week from now.

**PR:** _Provide PR URL(s) for this feature (if available)_

Feature request: <https://github.com/influxdata/chronograf/issues/5834>

PRs map incremental changes in the GUI:
* https://github.com/influxdata/chronograf/pull/5916
* https://github.com/influxdata/chronograf/pull/5920
* https://github.com/influxdata/chronograf/pull/5921
* https://github.com/influxdata/chronograf/pull/5923
* https://github.com/influxdata/chronograf/pull/5925
* https://github.com/influxdata/chronograf/pull/5926
* https://github.com/influxdata/chronograf/pull/5927

_Describe the new feature here._

Please see the well described details in PRs.

Please ask also @samhld for the mp4 recorded demo.

- What the feature does and why it is useful

New UI makes it easy for admins to manage users, roles and group permissions on database level. Main benefit is the comfort, because up until 1.10, the management could not be done otherwise than via CLI.

##### Relevant URLs
- _Provide relevant URLs (issues, community threads, existing doc pages, etc.)_

**Comment by lwandzura** [comment]
update the following:

https://docs.influxdata.com/chronograf/v1.9/administration/managing-influxdb-users/
