### ISSUE TITLE
Error: must specify org ID or org name

### ISSUE THREAD

**Issue by leqii-com** [influxdata/docs-v2#4225]
_Describe the issue here._

##### Relevant URLs
- _Provide relevant URLs (the doc page in question, project issues, community threads, etc.)_

in docker container input command" influx user create   --name example-username   --password ExAmPl3PA55W0rD"
ouput "Error: must specify org ID or org name"
why?

我输入命令"" influx user create   --name example-username   --password ExAmPl3PA55W0rD"
输出："Error: must specify org ID or org name"
为什么？

**Comment by sanderson** [comment]
@leqii-com Token and organization are required to perform this command. Generally, these credentials are inherited from the [active `influx` CLI config](https://docs.influxdata.com/influxdb/v2.3/reference/cli/influx/#provide-required-authentication-credentials). The example in the documentation assumes a config has been created and is active, as noted [here](https://docs.influxdata.com/influxdb/v2.3/reference/cli/influx/user/create/#authentication-credentials).
