### ISSUE TITLE
Typo on rate limit amount

### ISSUE THREAD

**Issue by bckeene** [influxdata/docs-v2#4237]
_Describe the issue here._
There seems to be a type on our [service quota documentation](https://docs.influxdata.com/influxdb/cloud/account-management/limits/#usage-based-plan):
<img width="487" alt="Screen Shot 2022-07-20 at 4 23 10 PM" src="https://user-images.githubusercontent.com/3768387/180099897-e341849c-19eb-49fb-bbef-3e9515fa8f62.png">

 I believe "Rate of 3 GB per 5 minutes" should be "Rate of 300 MB per 5 minutes" looking at our pricing page.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/account-management/limits/

**Comment by kelseiv** [comment]
thank you, @bckeene 
for data-in/writes specifically? @veereshhosakere brought this to our attn last month cc @bpalani 

at that point, we had wondered if it was a typo re this [PR](https://github.com/influxdata/docs-v2/pull/3355/files#), and then @veereshhosakere said SE team pinged data-in limit has been increased and does not reflect in our product 

will stay tuned on numbers specifically we need to change--thank you!

**Comment by bckeene** [comment]
Yep, I believe "Rate of 3 GB per 5 minutes" should be "Rate of 300 MB per 5 minutes" looking at our pricing page.

Thanks for looking into this!

**Comment by bpalani** [comment]
@kelseiv - can we please update the rate limit to be 300MB/5 min for Data In for usage based accounts?

**Comment by bpalani** [comment]
@sanderson - FYI.
