### ISSUE TITLE
Chronograf 1.10 release notes

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#4240]
### Features

- Overhaul admin UI to provide database-level role-based access control. UI also shows the permissions mappings more intuitively -- includes:
  - Improved user creation
  - Improved role creation
  - Improved visualization of effective permissions on Users/Roles pages
- Add `reader` role for users that should only see dashboards
- Add convenient redirection back to an original URL after OAuth authentication.
- Allow InfluxDB connection with context path
- Allow for customizing annotation color

### Bug Fixes
- Repair table visualization of string values.
- Improve InfluxDB Enterprise detection.
- Improve InfluxDB Enterprise user creation process.
- Avoid stale reads in communication with InfluxDB Enterprise meta nodes.
- Properly detect unsupported values in Alert Rule builder.
- Inform the user to use v2 administration.
- Make markdown cell content selectable.

### Maintenance
- Upgrade to node 16 LTS
- Upgrade dependencies
- Upgrade golang to 1.18

**Comment by lwandzura** [comment]
https://github.com/influxdata/chronograf/blob/master/CHANGELOG.md

**Comment by sranka** [comment]
@samhld @lwandzura verified and updated the description part herein, now it looks good to me.

**Comment by lwandzura** [comment]
@bpalani @sranka are we ready to deploy this release?
