### ISSUE TITLE
Improve get-started and install  instructions for OSS

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#4249]
OSS [Get-started](https://docs.influxdata.com/influxdb/v2.3/get-started/), install, and install CLI pages should be clearer: 

- remove redundant instructions
- provide clean step-by-step with introductions
- provide explanation and introductory statement for each example command.
- provide explanations of CLIs (influx and influxd)

Specifics:

- This note seems redundant and is confusing given it's followed by instructions:

   > Note:* To run InfluxDB, start the influxd daemon ([InfluxDB service]. 
      (https://docs.influxdata.com/influxdb/v2.3/reference/cli/influxd/)) using the [InfluxDB command line interface]. 
      (https://docs.influxdata.com/influxdb/v2.3/reference/cli/influx/). Once you’ve started the influxd daemon, use 
      localhost:8086 to log in to your InfluxDB instance.
- Clearly list the default or likely log locations for each OS here or in administration/logs and link to there.
User feedback comment:
- Test docker install, add context, explain each step.

(https://influxdata.slack.com/archives/C03HRU09PHA/p1658689800885219)
Page: https://docs.influxdata.com/influxdb/v2.3/get-started/
Feedback: How do I jump into the influx CLI or create a database?

**Comment by lwandzura** [comment]
addressed in this PR - https://github.com/influxdata/docs-v2/pull/4628
