### ISSUE TITLE
InfluxDB OSS 2.4 Release Notes

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#4255]
### Features
- Support v1 dbrp names as bucket IDs in replications API. This makes the creation of replications easier and adds support for replicating to an Enterprise cluster's v2 `/write` endpoint.
- feat: add back the InfluxQL REPL --- https://github.com/influxdata/influx-cli/pull/386
- Change to operator model such that admin user has instance-level permissions without operator token  ---[#23371](https://github.com/influxdata/influxdb/issues/23371)

### Flux advancement
- Add multiple new `join` functions to the `join` package such as `join.full()`
- Promote `experimental.to()` to `influxdata.influxdb.wideTo()`
- Add `initialZero` param to `derivative()` function
- Add builtin function `time` to the `date` packae to convert any timeable into datetime
- Deprecate `experimental.http.get()` and `experimental.csv.from()`
- Promote the following functions from experimental.array into the `array` package: `array.concat()`, `array.filter()`, `array.map()`
- Promote the following functions from `experimental.http.requests` into the `http.requests`: `http.requests.do()`, `http.requests.get()`, `http.requests.peek()`, http.requests.post()`
- Promote `experimental.bitwise` into the `bitwise` package
- Add new function `experimental.catch()` and `testing.shouldError()`
- Support conditional expressions, constants, and literals in vectorized `map()`
- Optimizations: `holtWinters()` and redundant sorts.
- Improve errors messages opening index partitions

### Bug fixes
- Log the log level at startup
- Panic from CreateIterator in Flux query ----[#23073](https://github.com/influxdata/influxdb/issues/23073)
- very naive fix for #23126 : avoid error-caching in bufio.Writer --- [#23127](https://github.com/influxdata/influxdb/pull/23127)
- removed the MATCHER_BEHAVIOR environment variable

### Maintenance
Upgrade to [Go 1.18.4](https://go.dev/doc/go1.18)
Upgrade Flux from 0.171.0 to 0.179.0

CLI release notes are here (this will be separate PR):
[CLI release notes](https://github.com/influxdata/docs-v2/issues/4170)

**Comment by lwandzura** [comment]
@samhld please review the features I added to make sure they are correct, and I will need bug fixes and maintenance updates

**Comment by lwandzura** [comment]
change log for OSS:
https://dl.influxdata.com/platform/nightlies/master/CHANGELOG.md

**Comment by jeffreyssmith2nd** [comment]
We will also want to document the removal of the MATCHER_BEHAVIOR option in this release from PR #23497.

There was an undocumented environment variable `MATCHER_BEHAVIOR` that slightly changed the logic around permissions mappings. Given its undocumented nature, we believe that is likely not used. We would like to call this out in the release notes on the slight chance of it being used in the wild.

**Comment by lwandzura** [comment]
@samhld is this release slated to go out this week?

**Comment by lwandzura** [comment]
@samhld please review the features and add additional detail

**Comment by samhld** [comment]
@lwandzura @sanderson  removed Auto DBRP mappings from this as we are pushing it to 2.5.

**Comment by lwandzura** [comment]
@sam do we want to include so much under Flux advancement?  That's covered in the Flux release notes.

**Comment by lwandzura** [comment]
@samhld what does this look like:

Support v1 dbrp names as bucket IDs in replications API (is this db/rp? need an example) - https://github.com/influxdata/docs-v2/issues/4257 is a separate issue opened for this, same question there

 Does this need to be a DBRP combo? Would specify one in Flux? db/rp or db/ to use the default RP?

**Comment by lwandzura** [comment]
@samhld @dgnorton Can you please review the features, bug fixes and maintenance updates prior to the release tomorrow to make sure they are still accurate?  Thanks!

**Comment by lwandzura** [comment]
@samhld  for this:
Promote the following functions from experimental.array into the array package: array.concat(), array.filter(), array.map()

should we also include `array.from`?

**Comment by sanderson** [comment]
@lwandzura No, `array.from` was already promoted.

**Comment by lwandzura** [comment]
released Friday Aug 19, 2022, closing as release notes were published
