### ISSUE TITLE
Grafana update screenshot and token auth for Flux

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#4264]
user feedback on https://docs.influxdata.com/influxdb/cloud/tools/grafana/:

_The screenshot under step three of "Configure your InfluxDB connection" denotes an incorrect HTTP header name. It should be "Authorization" (as noted in step two under "Token authentication")._

I believe we need to add the [token authentication step](https://docs.influxdata.com/influxdb/cloud/tools/grafana/?t=InfluxQL#token-authentication) in the InfluxQL section to the Flux section. And update the screenshot in the Flux section to reflect the Authorization header, similar to the InfluxQL screenshot:

![image](https://user-images.githubusercontent.com/47797004/181380115-5f10894e-1da7-4937-b13f-893569010986.png)

**Comment by sanderson** [comment]
These screenshots have already been updated to address the user-feedback. Closing this.
