### ISSUE TITLE
Modify Write data to InfluxDB page for clarification

### ISSUE THREAD

**Issue by peterreg** [influxdata/docs-v2#4282]
User is asking "How to write data to InfluxDB?" about the Write data to InfluxDB page.
The links are there but maybe we could change the language to make them more clear. Removing "Discover how to..." would make the first links more immediately noticeable.

New user feedback!
Page: https://docs.influxdata.com/influxdb/v2.2/write-data/
Feedback: HOW to write data to InfluxDB ?

**Comment by lwandzura** [comment]
addressed in this PR:

https://github.com/influxdata/docs-v2/pull/4628
