### ISSUE TITLE
Add instructions for creating a user in UI

### ISSUE THREAD

**Issue by peterreg** [influxdata/docs-v2#4284]
https://docs.influxdata.com/influxdb/v2.3/users/create-user/

This link describes how to create a user in CLI. We should add description for UI.

New user feedback!
Page: https://docs.influxdata.com/influxdb/v2.3/users/create-user/
Feedback: How to create user in web UI?

**Comment by jstirnaman** [comment]
@peterreg For which version? How do you create users in v2.3 UI?

**Comment by peterreg** [comment]
Sorry my mistake! Closing this proposal.

**Comment by jstirnaman** [comment]
@peterreg Sorry if my reply came across poorly - I sincerely thought I might be missing something.

**Comment by peterreg** [comment]
@jstirnaman No worries, I did not think you came across poorly in any way.
