### ISSUE TITLE
All examples just say "us-west-2-1.aws.cloud2.influxdata.com"

### ISSUE THREAD

**Issue by joar** [influxdata/docs-v2#4288]
_Describe the issue here._

All examples in the documentation seem to have been replaced by the string "us-west-2-1.aws.cloud2.influxdata.com"

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/query-data/flux/rate/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
@joar What browser/version are you using? Do you have a screenshot you could provide?

**Comment by joar** [comment]
Can't reproduce the issue, Firefox 104.0b4 (64-bit) on Windows at the moment, Firefox ~102 on Linux at the time.

**Comment by sanderson** [comment]
Thank you for the details. We've seen one other report of this, but have been unable to reproduce it.

I have a hunch it's browser specific. There is JS that runs on page load that updates the examples with the selected InfluxDB OSS/Cloud URL in codeblocks on the page. It appears that in some browsers, it replaces the full content of codeblocks. We haven't been able to identify the specific browser/version, but this gives us something to look into, so thank you.

**Comment by joar** [comment]
I'm able to reproduce it on my Linux system:
![image](https://user-images.githubusercontent.com/20814/182557160-e1e0b1a5-0530-4b63-89ef-6ba3e1e80b76.png)

To reproduce:
- Go to https://docs.influxdata.com/influxdb/cloud/query-data/flux/rate/
- You might need to either wait 5 seconds or reload the page for the code example to be replaced by us-west-2-1.aws.cloud2.influxdata.com

Arch Linux ([btw](https://knowyourmeme.com/memes/btw-i-use-arch))
Firefox 103.0 (64-bit)

This is how the DOM ends up looking for the code snippet: https://gist.github.com/joar/4888d62f41176452c248d554924e8b54

Looking through a my Developer Tool, the part responsible for modifying he code seems to be in `footer-bundle.[...].js`.

My influxdb URL seems to be set to `https+influxdb://@foo-bar-foo-bar-foo.foobar.com:23123/defaultdb`.

- o.replace.origin is `"null"` (a String), so `fuzzyOrigin` becomes `/null(:[0-9]+)?/g`
- o.with.origin is `"https://us-west-2-1.aws.cloud2.influxdata.com/"`

**Comment by sanderson** [comment]
Awesome! Thanks for these details @joar!
