### ISSUE TITLE
Add instructions for deleting a free InfluxDB Cloud account

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#4298]
**Feedback**: Need information about deleting a Cloud account as a free user

The current InfluxDB Cloud offboarding docs only address PAYG users. We need to add information about how to delete an account as a free user.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/account-management/

**Comment by sanderson** [comment]
@bpalani As I explored the Cloud UI, closing my account wasn't obvious. How do free users cancel their accounts?

**Comment by sanderson** [comment]
Nevermind. I found it:

1. Click your organization avatar in the left nav bar.
2. Select **Organization** -> **Settings**
3. Under **Delete Organization**, click **Delete**.
4. _(Optional) Provide any relevant feedback about why you're deleting your organization.
5. Select "I understand and agree to these conditions." 
6. Click **Delete Organization**.

**Comment by lwandzura** [comment]
related:  https://github.com/influxdata/docs-v2/issues/4536
