### ISSUE TITLE
Add link from Telegraf Get started page to Plugin directory page

### ISSUE THREAD

**Issue by peterreg** [influxdata/docs-v2#4319]
The Chinese feedback comment below translates to:
"I don't know Telegraf output information Each field is meaningless"

We might add a link to the Plugin directory page

To find input and output data for each Telegraf plugin, see the Plugin directory page [https://docs.influxdata.com/telegraf/v1.23/plugins/.](https://docs.influxdata.com/telegraf/v1.23/plugins/) Select a plugin to see details about metrics that are ingested (input plugins) and metrics that are output (output plugins).

New user feedback!
Page: https://docs.influxdata.com/telegraf/v1.23/get_started/
Feedback: 我不知道Telegraf输出信息 每个字段都不什么意思

**Comment by noramullen1** [comment]
hi @peterreg,

That's already linked multiple times from the getting started doc, most prominently at the top of the page in step 3. Closing this issue.
