### ISSUE TITLE
InfluxDB v2 ignores retention setting, reverts to default

### ISSUE THREAD

**Issue by BKFCAW** [influxdata/docs-v2#4321]
_Describe the issue here._

I have a bucket (netspeed, using Ookla) set to "Retention: 7 days" in the web interface.  When I plot the data with grafana, all data more than 24 hours old is deleted.

##### Relevant URLs
- _Provide relevant URLs_

##### What products and version are you using?

InfluxDB v2.3.0 arm64
Telegraf 1.21.4-1 arm64
Grafana 9.0.0 arm64 

![Retention](https://user-images.githubusercontent.com/102564515/183683214-fc20d2f0-f50c-44a8-a54f-f180c4f98885.jpg)
![24 hours](https://user-images.githubusercontent.com/102564515/183683741-86a100ec-5cb6-4469-875a-217acce9dafd.jpg)

**Comment by sanderson** [comment]
@BKFCAW This is more of a product issue than a documentation issue, so I'm going to go ahead and close this issue. However, some things to look into:

- What is your query's time range?
- Can you successfully run the same query in the InfluxDB 2.3 Data Explorer?
