### ISSUE TITLE
Cronograf install page needs additional download instructions

### ISSUE THREAD

**Issue by peterreg** [influxdata/docs-v2#4326]
User is trying to download Cronograf and is confused when sent to the InfluxDB dowloads page. 
"The latest Chronograf builds are available on InfluxData’s [Downloads page]"(https://portal.influxdata.com/downloads).

We should clarify Cronograf page to include specific instructions for downloading 1.x from this page. Something like:

“Scroll to bottom of download page, and then expand Are you interested in InfluxDB 1.x Open Source? to find your install.

Page: https://docs.influxdata.com/chronograf/v1.9/introduction/installation/
Feedback: Outdated. It says go to Download page to find a binary, but nothing there. Just generic download everything stuff.

**Comment by lwandzura** [comment]
I can link to instructions here:
https://docs.influxdata.com/chronograf/v1.9/introduction/downloading/

or augment on this actual page
