### ISSUE TITLE
Add note that date.sub() will only work with Flux 0.162.0 or later

### ISSUE THREAD

**Issue by peterreg** [influxdata/docs-v2#4336]
User is receiving an error when trying to use date.sub function. The user feedback does not say what product he is using but this error has been seen before while trying to use date.sub() with OSS:
https://community.influxdata.com/t/weird-error-returned-when-using-date-sub/25286

We should note that this function will not work with the latest versions of Flux and for OSS experimental.subDuration() can be used.

New user feedback!
Page: https://docs.influxdata.com/flux/v0.x/data-types/basic/time/
Feedback: date.sub returns "record is missing label sub" error

**Comment by sanderson** [comment]
This was addressed with functionality recently added to the Flux standard library pages. Almost all function and package pages show the version of Flux they were introduced and what versions of InfluxDB currently support the function/package. 

This addition was made after the linked community issue was opened. I’m going to go ahead and close this issue.
