### ISSUE TITLE
1621726200000000000 is not a Unix timestamp

### ISSUE THREAD

**Issue by rinmalavi** [influxdata/docs-v2#4381]
Unless you want the date to be 51392427-06-25 18:00:00.0

##### Relevant URLs
- https://docs.influxdata.com/flux/v0.x/stdlib/universe/range/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
@rinmalavi `1621726200000000000` is a nanosecond Unix timestamp 2021-05-22T23:30:00.000000000Z. We can update the title of the example to clearly state the precision.

**Comment by rinmalavi** [comment]
Not sure what is expected, but if I use
range(start: 1621726200000000000, stop: 1621728000000000000)
expecting a some results from 2021, i get nothing but if i take those excess 0 out, i could get some results.

**Comment by sanderson** [comment]
You are correct. In most cases when dealing with time, Flux treats integers as nanosecond timestamps, which is what I was assuming. `range()` is an exception. It treats them as second timestamps, so the example is inaccurate. I'll update the timestamps in the example.

**Comment by rinmalavi** [comment]
I have a problem making this work.

The results are passing the stop timestamp.
Also limit function doesn't seem to limit result count.

**Comment by sanderson** [comment]
@rinmalavi What is they query you're running?

**Comment by rinmalavi** [comment]
> @rinmalavi What is they query you're running?

    from(bucket:"m2_devel") 
      |> range(start: 1651183140, stop: 1671183260)  
      |> filter(fn: (r) => r._measurement == "default") 
      |> filter(fn: (r) => r.vid == "some_tag") 
      |> filter(fn: (r) => r._field == "some_field") 
      |> sort(columns: ["_time"], desc: false) 
      |> limit(n:100)

returned 256 results,
not filtering on field will return 2000+.
Can't give you exact example/data would have to hash it first.
About range filter, seems i cant reproduce it since update from 2.2 to 2.4.

**Comment by sanderson** [comment]
Your `stop` timestamp is equivalent to `2022-12-16T09:34:20Z`, so it's in the future. `limit()` limits the number of rows per table. InfluxDB returns data grouped by series, so you have a table for each unique series in your result. Also, you shouldn't need to sort by time. `from() |> range() |> filter()` return data sorted by time by default.
