### ISSUE TITLE
Add table or list of available geographical locations to use for timezone.location()

### ISSUE THREAD

**Issue by sunbryely-influxdata** [influxdata/docs-v2#4473]
New user feedback!
Page: https://docs.influxdata.com/flux/v0.x/stdlib/timezone/location/
Feedback: Where can I find a list of locations that are used? Are they the standard ones or are there specific ones?

-----
timezone.location() can take in a geographic location as input. but the docs doesnt show which geographic locations are valid inputs. Create a list or table showing the list of valid inputs.  

```timezone.location(name: "America/Los_Angeles")``` is available but what are the other possible options?

##### Relevant URLs
https://docs.influxdata.com/flux/v0.x/stdlib/timezone/location/

**Comment by sanderson** [comment]
This wholly depends on the TZ database provided by the host OS. This is something that should and will be outlined in the doc about time mechanics in Flux. Related to https://github.com/influxdata/docs-v2/issues/3394.

**Comment by sunbryely-influxdata** [comment]
Ill close this ticket out as duplicate.
