### ISSUE TITLE
Telegraf custom builder docs

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#4478]
**ETA:** No later than November 2nd - Feature is complete but marketing announcement is InfluxDays

_Describe the new feature here._
Telegraf custom builder - tool to select the plugins compiled into the Telegraf binary. By doing so, Telegraf can become smaller, saving both disk space and memory if only a sub-set of plugins is selected.

##### Relevant URLs
- https://github.com/influxdata/telegraf/tree/master/tools/custom_builder
- Blog: https://docs.google.com/document/d/1kXFFA526BMP50dWrqFVyHgOac-i4iXlRQHLtdXyY4-c/edit#

Telegraf custom builder
---------

### 0. Before you start
Make sure your Go version is up to date. At the time of publishing, this tool requires Go version 1.18.0+.

Create your Telegraf configuration with the plugins you want to use. This could be stored locally or remotely. This can technically be done any time before step 4. 

### 1. Clone the Telegraf repository

```bash 
git clone https://github.com/influxdata/telegraf.git
```

### 2. Change directories into the top-level of the Telegraf repository:
```bash
cd telegraf
```

### 3. Build the Telegraf custom builder tool
We now need to build the custom builder. To do this open a terminal within the top-level directory of the Telegraf repository and enter the command:

```bash
make build_tools
```

### 4. Point the custom builder at your Telegraf configuration(s) that include the plugins you want to build
Depending on how you have built/stored your Telegraf config(s) you have a few options here:

- Single Telegraf config
```bash
./tools/custom_builder/custom_builder --config /etc/telegraf.conf
```
- Single Telegraf config + Telegraf config directory
```bash
/tools/custom_builder/custom_builder --config     /etc/telegraf.conf --config-dir /etc/telegraf/telegraf.d
```
- Remote Telegraf config
```bash
./tools/custom_builder/custom_builder --config http://url-to-remote-telegraf/telegraf.conf
```
This will run both phases of the custom builder (running the builder configuration and building the Telegraf binary). Resulting in the creation of your customized Telegraf binary. 

### 5. View customized Telegraf binary
You should now be able to find your new smaller Telegraf binary within the top level of your Telegraf repository. 

### 6. Add or remove plugins from your customised Telegraf (optional)
If you wish to add or remove plugins from your customised Telegraf build. You can just edit your configuration and rerun the `./tools/custom_builder/custom_builder --config path/to/config.conf` command.

**Comment by dasturiasArista** [comment]
Hey this is awesome! Super useful. One small recomendation is that right now the google doc blog post has edit access to the world. It might make sense to make it read only.
