### ISSUE TITLE
Documentation points to downloads page but no Chronograf download exists

### ISSUE THREAD

**Issue by KidA001** [influxdata/docs-v2#4481]
Multiple places on InfluxDB site and within the [Installation instructions ](https://docs.influxdata.com/chronograf/v1.10/introduction/installation/) point users to `https://portal.influxdata.com/downloads` to download Chronograf. The installation page even references a file `chronograf-<version#>_darwin_amd64.tar.gz`. Nowhere on the  linked downloads page is there any reference to Chronograf or where it can be downloaded from other than docker.

Maybe it's bundled in another package? Unclear. Any clarity would be helpful.

**Comment by sranka** [comment]
Doc could clarify how to find the chronograf download links on the page.

**Comment by lwandzura** [comment]
For some reason the instructions are in 1.9, but not 1.10:

On the Downloads page, scroll to the bottom and click Are you interested in InfluxDB 1.x Open Source? to expand the 1.x options. Scroll to the Chronograf section and select your desired Chronograf version and operating system. Execute the provided download commands.

Will add to 1.10 page
