### ISSUE TITLE
Correct steps to delete an org

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#4514]
Change ..."select About" to "under Organization, select "Settings" -- note, this only applies to Cloud---for OSS "select About" is still accurate

Page: https://docs.influxdata.com/influxdb/cloud/organizations/delete-org/
Feedback: Can't find "Delete Organization"

**Comment by lwandzura** [comment]
closed via this PR:  https://github.com/influxdata/docs-v2/pull/4597
