### ISSUE TITLE
Add note clarifying limits for deleting data

### ISSUE THREAD

**Issue by peterreg** [influxdata/docs-v2#4524]
User is asking how to delete field values in a given time range. Can we add a note that delete cannot be used to delete field values, only points?

We might add the note in one or all of the following locations:
https://docs.influxdata.com/influxdb/cloud/write-data/delete-data/
https://docs.influxdata.com/influxdb/v2.4/reference/cli/influx/delete/
https://docs.influxdata.com/influxdb/v2.4/reference/syntax/delete-predicate/

New user feedback!
Page: https://docs.influxdata.com/influxdb/v2.2/reference/cli/influx/delete/
Feedback: info about how to manage/delete field values in given timerange

**Comment by sanderson** [comment]
InfluxDB Cloud supports the deletion of field values in a given time range. OSS does not support deleting fields.
