### ISSUE TITLE
Telegraf: Provide directory information (default, etc.) for the config file

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#4533]
Doc the Docs Bot
APP  [10:20 AM](https://influxdata.slack.com/archives/C03HRU09PHA/p1664983201880939)
New user feedback!
Page: https://docs.influxdata.com/telegraf/v1.24/install/
Feedback: telegraf config > telegraf.conf what directory do i need to be.  where does telegraf.conf need to be to be useful.

**Comment by noramullen1** [comment]
This info is already in the doc, right after the first mention of the telegraf.conf file:

"For Linux distributions, this file is located at /etc/telegraf for default installations.

For Windows distributions, the configuration file is located in the directory where you unzipped the Telegraf ZIP archive. The default location is C:\InfluxData\telegraf."
