### ISSUE TITLE
Delete org: navigation has changed; update instructions

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#4536]
Cloud navigation has changed. Update docs for Deleting an organization. To find the Delete icon, click on your org name (pull-down) in the breadcrumbs at top and choose `Settings`--example URL path: - https://us-east-1-1.aws.cloud2.influxdata.com/orgs/12ecfe5b8de761f8/org-settings

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/organizations/delete-org/

Doc the Docs Bot
APP  [7:10 AM](https://influxdata.slack.com/archives/C03HRU09PHA/p1664971805998009)
New user feedback!
Page: https://docs.influxdata.com/influxdb/cloud/organizations/delete-org/
Feedback: There ist no Delete Organisation.

**Comment by lwandzura** [comment]
related issue:  https://github.com/influxdata/docs-v2/issues/4536
