### ISSUE TITLE
The example CSV file for defining an explicit schema bucket is invalid

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/docs-v2#4563]
If you create a CSV file using the example on this page (usage-resources.csv) and try to apply it to a cloud 2 bucket, you will get an error - csv headers are not correct: they need to be: "name, type, dataType"

If you change data_type to dataType and re-upload the schema file, you will get an error - column file is not formatted correctly.

##### Relevant URLs
- _Provide relevant URLs (the doc page in question, project issues, community threads, etc.)_
https://docs.influxdata.com/influxdb/cloud/organizations/buckets/bucket-schema/

**Comment by sanderson** [comment]
Thanks @barbaranelson. The CSV example did include an incorrect header. The error after that appears to have be causes by a newline at the end of the CSV. I removed it and validated that the updated example does work.
