### ISSUE TITLE
Telegraf 1.24 Plugin Upgrades - Update Docs

### ISSUE THREAD

**Issue by ALuckette** [influxdata/docs-v2#4572]
##### Request
- Update docs to reflect telegraf 1.24 plugin upgrades

**1.24 Plugins Upgraded on September 30, 2022**

- [AWS CloudWatch Metric Streams Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cloudwatch_metric_streams)
- [Linux CPU Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/linux_cpu)
- [Supervisor Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/supervisor)
- [UPSD Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/upsd)

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1.24/plugins/

**Comment by sjwang90** [comment]
@ALuckette Are you saying these plugins are missing from the docs plugin page or somewhere else? They're all listed with `New` next to them: 
AWS cloudwatch: https://docs.influxdata.com/telegraf/v1.24/plugins/#input-cloudwatch_metric_streams
Linux CPU: https://docs.influxdata.com/telegraf/v1.24/plugins/#input-linux_cpu
Supervisor: https://docs.influxdata.com/telegraf/v1.24/plugins/#input-supervisor
UPSD: https://docs.influxdata.com/telegraf/v1.24/plugins/#input-upsd

**Comment by ALuckette** [comment]
Hi,

No.

The plugins were just upgraded/updated.

If we don't typically document that, feel free to close this ticket.

**Comment by sjwang90** [comment]
@ALuckette If you're talking about that the plugins were updated in the UI then no we don't document that. Just when plugins get added to Telegraf itself we'll update the plugin directory. 

I'll close this
