### ISSUE TITLE
Create Telegraf Configuration

### ISSUE THREAD

**Issue by kmfriedt** [influxdata/docs-v2#4576]
After creating a telegraf configuration a page opened up that would allow me to test my telegraf configuration. 
I tried to listen for data and there was an error. I then clicked on the "Telegraf Troubleshooting" link "https://docs.influxdata.com/telegraf/latest/administration/troubleshooting/" and I got a 404 error. 

##### Relevant URLs
- _Provide relevant URLs_

**Comment by sjwang90** [comment]
@kmfriedt where did you click on a Telegraf Troubleshooting link? Was this in the UI or the documentation page?

**Comment by kmfriedt** [comment]
I can't remember for sure, but I believe that it was on the documentation page.
