### ISSUE TITLE
Influx cli 2.5 release notes

### ISSUE THREAD

**Issue by lwandzura** [influxdata/docs-v2#4582]
**ETA:** October 21, 2022

See changelog for all PRs associated with this release:

### Bug Fixes
1. [3a593e7](https://github.com/influxdata/influx-cli/commit/3a593e7): Don't allow creating an auth with instance resources
1. [e2aa4d2](https://github.com/influxdata/influx-cli/commit/e2aa4d2): Fix stack error typo
1. [77cca94](https://github.com/influxdata/influx-cli/commit/77cca94): Fixes an error where stdin could not be used to create tasks
### Features
1. [6142b7a](https://github.com/influxdata/influx-cli/commit/6142b7a): Support username-password in config update
### Other
1. [e39e365](https://github.com/influxdata/influx-cli/commit/e39e365): Chore: go1.19
1. [188c393](https://github.com/influxdata/influx-cli/commit/188c393): Chore: fix go version in `go.mod`

Doc to update:
https://docs.influxdata.com/influxdb/v2.4/reference/release-notes/influx-cli/
https://docs.influxdata.com/influxdb/v2.4/reference/cli/influx/auth/create/
https://docs.influxdata.com/influxdb/v2.4/security/tokens/create-token/

**Comment by kelseiv** [comment]
@jeffreyssmith2nd to verify--the new feature [6142b7a](https://github.com/influxdata/influx-cli/commit/6142b7a)
means we can remove the workaround in [this hotfix](https://github.com/influxdata/docs-v2/pull/4556/files)?

**Comment by jeffreyssmith2nd** [comment]
That is correct, we should not need that workaround anymore.

**Comment by jeffreyssmith2nd** [comment]
These are the latest notes, we're planning to get the process going today. Thanks!

**Comment by kelseiv** [comment]
thanks, @jeffreyssmith2nd --updated
