### ISSUE TITLE
InfluxDB OSS 2.5 release notes

### ISSUE THREAD

**Issue by lwandzura** [influxdata/docs-v2#4583]
**ETA:** October 21, 2022

InfluxDB OSS 2.5 changelog:

### Features
1. [485968c](https://github.com/influxdata/influxdb/commit/485968c): Unpin ui to point at latest
1. [b72848d](https://github.com/influxdata/influxdb/commit/b72848d): Optimize saving changes to fields.idx
1. [f36646d](https://github.com/influxdata/influxdb/commit/f36646d): Bump to latest UI

### Bug Fixes
1. [daaf866](https://github.com/influxdata/influxdb/commit/daaf866): Several minor quality issues
1. [ee8ca45](https://github.com/influxdata/influxdb/commit/ee8ca45): Use copy of loop variable in parallel test
1. [11019d2](https://github.com/influxdata/influxdb/commit/11019d2): Check that user IDs are not in use in user create
1. [b87deb4](https://github.com/influxdata/influxdb/commit/b87deb4): Don't allow creating an auth with instance resources
1. [b51fefd](https://github.com/influxdata/influxdb/commit/b51fefd): Set limited permissions on package installs
1. [663d43d](https://github.com/influxdata/influxdb/commit/663d43d): Allow backup of all buckets
1. [a0f1184](https://github.com/influxdata/influxdb/commit/a0f1184): Manually scheduled task runs now run when expected
1. [4ed184d](https://github.com/influxdata/influxdb/commit/4ed184d): Fixes an error querying virtual dbrps
1. [2ad8995](https://github.com/influxdata/influxdb/commit/2ad8995): Improve delete speed when a measurement is part of the predicate
1. [b0430cf](https://github.com/influxdata/influxdb/commit/b0430cf): Sql scan error on remote bucket id when replication to 1.x

### Other
1. [accce86](https://github.com/influxdata/influxdb/commit/accce86): Chore: update CHANGELOG_frozen.md for 2.4
1. [785a465](https://github.com/influxdata/influxdb/commit/785a465): Refactor: remove reference to flux.Spec in query tests
1. [728070e](https://github.com/influxdata/influxdb/commit/728070e): Chore: upgrade Rust to 1.63.0
1. [aa9c49e](https://github.com/influxdata/influxdb/commit/aa9c49e): Build(flux): update flux to v0.180.1
1. [8f15620](https://github.com/influxdata/influxdb/commit/8f15620): Build(flux): update flux to v0.181.0
1. [1c6fbf9](https://github.com/influxdata/influxdb/commit/1c6fbf9): Chore: add protoc-gen script to releng (2.x)
1. [c433342](https://github.com/influxdata/influxdb/commit/c433342): Chore: remove duplicate word in comments
1. [91623dd](https://github.com/influxdata/influxdb/commit/91623dd): Docs(logger): fix incorrect doc string
1. [c40ad64](https://github.com/influxdata/influxdb/commit/c40ad64): Feat(security): set SameSite=strict on session cookie
1. [43c2e08](https://github.com/influxdata/influxdb/commit/43c2e08): Chore: upgrade to Go 1.18.6
1. [635f8d8](https://github.com/influxdata/influxdb/commit/635f8d8): Build(flux): update flux to v0.184.2
1. [eada36b](https://github.com/influxdata/influxdb/commit/eada36b): Test: remove group skips
1. [aa5c1c0](https://github.com/influxdata/influxdb/commit/aa5c1c0): Docs: cleanup CONTRIBUTING.md - clarify instructions and output.
1. [a321e72](https://github.com/influxdata/influxdb/commit/a321e72): Build(flux): update flux to v0.185.0
1. [d8553c0](https://github.com/influxdata/influxdb/commit/d8553c0): Test(flux): use vanilla flagger for fluxtest
1. [34254ee](https://github.com/influxdata/influxdb/commit/34254ee): Build(flux): update flux to v0.186.0
1. [a0c3703](https://github.com/influxdata/influxdb/commit/a0c3703): Build(flux): update flux to v0.187.0
1. [89d9207](https://github.com/influxdata/influxdb/commit/89d9207): Chore: update to use scheduled pipeline (2.x)
1. [0389d51](https://github.com/influxdata/influxdb/commit/0389d51): Chore: upgrade to Go 1.18.7
1. [9a3d90e](https://github.com/influxdata/influxdb/commit/9a3d90e): Chore: fix issues in test files

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.4/reference/release-notes/influxdb/

**Comment by lwandzura** [comment]
@jeffreyssmith2nd Can you add detail as to what UI changes were made?  Does it look more like the cloud 2 product?  I'll need  more detail than what has been provided as I will most likely need to update a couple of different docs here.

**Comment by jeffreyssmith2nd** [comment]
Basically we brought up to spec with the Cloud UI as of Sept 16. The previous UI was from Dec 2021, so the list of changes is quite large.

**Comment by lwandzura** [comment]
What major/noticeable changes can we highlight?

**Comment by jeffreyssmith2nd** [comment]
- One noticeable change is the token UI now operates the way that it does in Cloud. So it shows you the token at creation and then you can't see it again. That's a big departure from how OSS did it before.

- Many improvements to notebooks especially in adding flux queries
    - Save as notebook from data explorer

- Improved homepage navigation
    - First Mile onboarding improvements

- Major overhaul of Telegraf configuration
    - Added support for Telegraf 1.22 plugins/changes

-

**Comment by lwandzura** [comment]
@gunnaraasen @jeffreyssmith2nd Any updates on when this release is going out?

**Comment by jeffreyssmith2nd** [comment]
Sorry for the delay, we think we'll be ready to go with it tomorrow.

**Comment by lwandzura** [comment]
Please include any additional updates here

**Comment by jeffreyssmith2nd** [comment]
Here are the new updates, we are beginning the release process today. Thanks!
