### ISSUE TITLE
Native MQTT Certificate Support

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#4595]
**ETA:**Currently in production, Marketing release Nov 6

**Summary:** Added certificate support for Native MQTT - ~currently behind the `subscriptionsCertificateSupport` flag~

Support secure authentication between InfluxDB cloud and your MQTT Broker. Some brokers will require certificates in order to connect to them. 

**Steps:** 
1. Download Certificates from MQTT Broker. Need to minimally download the following: CA (Certificate authority), Private Key (ending in `private.pem.key`),  Device certificate (ending in `certificate.pem.crt`)

2. Copy and paste the corresponding certificate into the Certificate section of the Security Details
- Certificate authority = AmazonRootCA1.pem
- Private Key = xxxxxx.private.pem.key
- Certificate = xxxxx.certificate.pem.crt
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/32681364/198157730-dc43e48f-cd75-48d4-a662-37aa6cf3a09b.png">

##### Relevant URLs
- _Provide relevant URLs (issues, community threads, existing doc pages, etc.)_

**Comment by lwandzura** [comment]
MQTT no longer supported, closing this out
