### ISSUE TITLE
Document JWT authentication

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#468]
PRs: https://github.com/influxdata/influxdb/pull/15152, https://github.com/influxdata/influxdb/issues/15229

Document how to use JWT authentication tokens to auth with 2.0.

**Comment by pierwill** [comment]
(Update: https://github.com/influxdata/influxdb/issues/15229 closed.)

**Comment by pierwill** [comment]
Closing this for now, as auth via JWT in OSS in not currently supported.
