### ISSUE TITLE
InfluxDB 2.6.1

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [influxdata/docs-v2#4681]
ETA: Dec 29 2022

## v2.6.1 [unreleased]
----------------------

### Bug Fixes

1. [29b0cde](https://github.com/influxdata/influxdb/commit/29b0cde): Update UI to resolve Dashboard crash and All Access Token creation

**Comment by jeffreyssmith2nd** [comment]
This is entirely a bug fix release. It fixes 2 main things:
1. The Dashboard page could crash under certain conditions.
2. Users were unable to create All Access Tokens.

**Comment by lwandzura** [comment]
any maintenance items, like Go version?

**Comment by jeffreyssmith2nd** [comment]
No, not for this release
