### ISSUE TITLE
Influx CLI 2.6.1

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [influxdata/docs-v2#4684]
ETA: Dec 29 2022

## v2.6.1 [unreleased]
----------------------

### Other

1. [61c5b4d](https://github.com/influxdata/influx-cli/commit/61c5b4d): Chore: update to go 1.19

**Comment by lwandzura** [comment]
maintenance update from 2.6.0 states that Go was upgraded to Go to 1.19.4.

**Comment by jeffreyssmith2nd** [comment]
That was unfortunately incorrect, the actual binaries that were shipped were still built with an older version.

**Comment by lwandzura** [comment]
OK, I'm going to wait for Scott's return to see how best to add this to the release notes
