### ISSUE TITLE
Querying iox data will require use of special identifiers.

### ISSUE THREAD

**Issue by wiedld** [influxdata/docs-v2#4694]
**ETA:** Before 1.31 marty release of iox to cloud2.

Data written into influxdb, under iox, can have capitalization and whitespace. This means that the user needs to know to use SQL special identifiers (a.k.a. double quotes) when their measurements, field names, or tag name have these features.

## Relevant URLs
Examples:
`SELECT * FROM "airSensors";`
`SELECT * FROM "quarry blast";`

See detailed examples as shown when exploring [this ticket](https://github.com/influxdata/ui/issues/6183). This ticket is where we have the UI building example SQL queries using special identifiers. However, not all users will start writing SQL within the UI. Therefore, we may want to have the docs updated to highlight this need; specifically, when using SQL to query their data in iox.

**Comment by lwandzura** [comment]
Can you clarify when single quotes are needed?

**Comment by wiedld** [comment]
> The above has been included in the sql reference.
> 
> Can you clarify when single quotes are needed? You need them with RFCC timestamps, are there other times when single quotes are needed?

Users are still writing data with influx schema identifier rules, which permit identifiers (e.g. for buckets, measurements, field names, and tag keys) as influxDB identifiers. These identifiers are case sensitive (e.g. `airSensors`) and can have whitespace (`my measurement`). Querying via SQL requires these identifiers to be double quoted.

Examples:
`SELECT * FROM my measurement;` will fail.
`SELECT * FROM "my measurement";` is valid.
`SELECT * FROM "my measurement" WHERE tagKey = 'tagValue';` will query for lowercase `tagkey`.
`SELECT * FROM "my measurement" WHERE "tagKey" = 'tagValue';` will query for (and correctly find) `"tagKey"`.

**Comment by lwandzura** [comment]
Also, is this using the influx cli?  What command line or SQL shell are we recommending that customers use?

**Comment by lwandzura** [comment]
why does the following work with single quotes and not double:

SELECT 
selector_last(degrees, time)['time'],
selector_last(degrees, time)['value']
FROM h2o_temperature
WHERE time >= timestamp '2019-09-15T00:00:00Z' AND time <= timestamp '2019-09-19T00:00:00Z'

**Comment by wiedld** [comment]
Underscore does not equal whitespace. Look at `level description`.

This one (use double quoted string) will pass:
![Screen Shot 2023-01-18 at 5 10 24 PM](https://user-images.githubusercontent.com/10232835/213332224-f72f61ca-be59-40ba-ac10-54ea33e8d525.png)


This one, without the double quotes, will error:
![Screen Shot 2023-01-18 at 5 10 37 PM](https://user-images.githubusercontent.com/10232835/213332237-9c868eed-f26e-4f19-96ff-4b202b82fde2.png)

**Comment by wiedld** [comment]
The selector_last is a user-defined-aggregate which iox defines ([here](https://github.com/influxdata/influxdb_iox/blob/57f08dbccde9d7ae8eb331cbf0173f2d16fa33bd/query_functions/src/selectors.rs#L71-L90) and [here](https://github.com/influxdata/influxdb_iox/blob/57f08dbccde9d7ae8eb331cbf0173f2d16fa33bd/query_functions/src/selectors.rs#L162-L188)). Looking at the testcases (example [here](https://github.com/influxdata/influxdb_iox/blob/034d9b371d86d076078ea3aab1114011f9e93e70/query_tests/cases/in/selectors.expected#L57-L61)), it appears that the `['value']` and `['time']` are keys in the returned json object --> so that's different from a column identifier.

**Comment by wiedld** [comment]
Here is an example of the camelCase identifiers (or anything that uses case sensitivity), requiring SQL special identifiers (a.k.a. double quotes).

Identifier `"airSensors"` found the measurement/table:
<img width="691" alt="Screen Shot 2023-01-18 at 7 53 40 PM" src="https://user-images.githubusercontent.com/10232835/213351618-c1a2d00f-36f3-4d8f-9215-57326f10e6b6.png">



Identifier `airSensors` did not find it. Because sql lowercases all identifiers which are not special identifiers (with double quotes).
<img width="704" alt="Screen Shot 2023-01-18 at 7 54 03 PM" src="https://user-images.githubusercontent.com/10232835/213351629-9469a0bf-da72-4169-bed0-77f64e73ae02.png">

**Comment by wiedld** [comment]
If you run `show tables` query, it becomes more evident. The identifiers on the WRITE path (when data is written in) use the InfluxDB format, which includes case sensitivity and whitespace.

Whereas we query out via SQL, requiring the use of special identifiers (double quotes).
<img width="679" alt="Screen Shot 2023-01-18 at 7 56 54 PM" src="https://user-images.githubusercontent.com/10232835/213351845-5f936209-efe0-4fe8-867f-7f66fa7bf6fa.png">


If you don't think it's worth putting in the docs -- then that's your team's call. We've experienced almost every dev figuring this out on their own, so I guess maybe the users will have to figure it out too?

**Comment by lwandzura** [comment]
This needs to be documented for our users, I just need to make sure the info is accurate and clear

**Comment by lwandzura** [comment]
created a PR for the SQL reference, will close this out as PR has been approved
