### ISSUE TITLE
Document SQL keywords

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#4699]
We need to document SQL keywords in our new SQL documentation. I've compiles the following list from standard SQL keywords as wells as keywords taken from the DataFusion source code:

```
ADD
ADD CONSTRAINT
ALL
ALTER
ALTER COLUMN
ALTER TABLE
AND
ANY
AS
ASC
BACKUP DATABASE
BETWEEN
CASE
CHECK
COLLATE
COLUMN
COMPRESSION
CONSTRAINT
CREATE
CREATE DATABASE
CREATE INDEX
CREATE OR REPLACE VIEW
CREATE PROCEDURE
CREATE TABLE
CREATE UNIQUE INDEX
CREATE VIEW
DATABASE
DEFAULT
DELETE
DELIMITER
DESC
DESCRIBE
DISTINCT
DROP
DROP COLUMN
DROP CONSTRAINT
DROP DATABASE
DROP DEFAULT
DROP INDEX
DROP TABLE
DROP VIEW
EXEC
EXISTS
EXTERNAL
FOREIGN KEY
FROM
FULL OUTER JOIN
GROUP BY
HAVING
HEADER
IF
IN
INDEX
INNER JOIN
INSERT INTO
INSERT INTO SELECT
IS NOT NULL
IS NULL
JOIN
LEFT JOIN
LIKE
LIMIT
LOCATION
NOT
NOT NULL
OPTIONS
OR
ORDER BY
OUTER JOIN
PARTITIONED BY
PRIMARY KEY
PROCEDURE
RIGHT JOIN
ROW
ROWNUM
SELECT
SELECT DISTINCT
SELECT INTO
SELECT TOP
SET
STORED
TABLE
TOP
TRUNCATE TABLE
TYPE
UNION
UNION ALL
UNIQUE
UPDATE
VALUES
VIEW
WHERE
WITH
```

We need to confirm whether or not all of these truly are keywords in the SQL implementation we're using.

**Comment by sanderson** [comment]
@alamb Is there an easy to confirm if these all are in fact keywords in our SQL implementation? I looked through the source code but couldn't find a comprehensive list. Most of this list was pulled from standard SQL keywords.

**Comment by lwandzura** [comment]
I have most of the ones you have included, but I am not including any DDL keywords since this is not supported.

**Comment by alamb** [comment]
Here is the list of keywords in the parser used by datafusion :https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/keywords.rs

Note that using many of them / the constructs within which they appear will result in unsupported errors
