### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by CTaylor-1** [influxdata/docs-v2#4715]
The hyperlink for "Telegraf Official Docs" leads to the below broken link on the docker hub registry

##### Relevant URLs
Broken Link: https://docs.influxdata.com/telegraf/v1.24/introduction/getting-started/
Source of Broken Link: https://registry.hub.docker.com/_/telegraf/

**Comment by jstirnaman** [comment]
PR for fix: https://github.com/docker-library/docs/pull/2296

**Comment by jstirnaman** [comment]
> PR for fix: [docker-library/docs#2296](https://github.com/docker-library/docs/pull/2296)

Closed this and opened a new one with the proper file.

**Comment by jstirnaman** [comment]
Fixed.
