### ISSUE TITLE
InfluxDB 1.8 apt repo key returns 404

### ISSUE THREAD

**Issue by a-h-85** [influxdata/docs-v2#4718]
Go to https://docs.influxdata.com/influxdb/v1.8/introduction/install/?t=curl

The Debian instruction says to download a key file, however the link returns a 404:
https://repos.influxdata.com/influxdata-archive_compat.key

Impact: InlfuxDB 1.8 cannot be installed via apt on Debian

**Comment by powersj** [comment]
Hi,

The key should be available. I know there was a bit of a delay from the time the blog post went up and instructions were updated.

**Comment by a-h-85** [comment]
thank you!
