### ISSUE TITLE
Completly wrong setup for InfluxQl for Grafana

### ISSUE THREAD

**Issue by nachocpol** [influxdata/docs-v2#4722]
The page explains that you have to provide a "Custom HTTP Header" with:
- Header: "Authorization"
- Value:  "Your Token"

This as of right now doesn't work at all. Getting a 401 error from within Grafana. However, if you change the Header name to "token" it works! 

This was mentioned in the Grafana github a while ago, so I'm surprised nobody mentioned it (https://github.com/grafana/grafana/issues/32252#issuecomment-809531689)

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.6/tools/grafana/

**Comment by sanderson** [comment]
@nachocpol Are you referring to this section specifically? https://docs.influxdata.com/influxdb/v2.6/tools/grafana/?t=InfluxQL#configure-your-influxdb-connection

<img width="926" alt="image" src="https://user-images.githubusercontent.com/181484/215201711-abd9bd08-6117-4d4f-997b-1c4368802ff7.png">

The header name should be `Authorization` and the header value should be `Token <yourauthotoken>`.

**Comment by nachocpol** [comment]
@sanderson yup, that section.

Using "Authorization" returns a 401 when you "Save and test". Setting it to "token" seems to work (I'm able to see measurements)

**Comment by sanderson** [comment]
Can you paste a screenshot your Grafana config?

**Comment by nachocpol** [comment]
Sure thing:
Sure: 

![image](https://user-images.githubusercontent.com/11047511/215203232-29c41c40-1692-4a25-b923-837438297556.png)

![image](https://user-images.githubusercontent.com/11047511/215203309-b13369c5-4586-4803-964d-eec0ee8d01ef.png)

**Comment by sanderson** [comment]
What version of InfluxDB are you connecting to?

**Comment by nachocpol** [comment]
nachocpol@raspberrypi:~ $ influx version
Influx CLI 2.6.1 (git: 61c5b4d) build_date: 2022-12-29T15:41:09Z

That's the CLI. Not sure how to get the actual service version.

**Comment by sanderson** [comment]
Run `influxd version`

**Comment by nachocpol** [comment]
Ah yes, here you go:


```
nachocpol@raspberrypi:~ $ influxd version
InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:52:06Z
```

**Comment by sanderson** [comment]
I'm seeing the opposite behavior. If I use `token` as the header name, I get a 401 error. But if I use `Authorization` as the header name, it works.

I see in your configuration that you have the username and password configured. I'm guessing the username and password are being used to authenticate rather than the token. I'm betting that if the `Authorization` header isn't sent with the request, it will check for basic auth credentials and use those.

One thing to double check is that the token you're using actually is authorized to query the buckets you're trying to query. You may also need to set up some DBRP mappings as well.

**Comment by nachocpol** [comment]
I can confirm that if I remove the entire header it still works in the same way (so using the username and password as you mentioned).

Does using basic auth have any drawbacks? If not, I imagine I could leave it as it is...

I did setup the DBRP mappings like:

`influx v1 dbrp create \
  --db pedalesDB \
  --rp autogen \
  --bucket-id <MyID>\
  --default
`

How could I check that the token is authorized to query the bucket?

**Comment by sanderson** [comment]
Nope, no drawbacks. It's just a way to authorize with InfluxDB 2.x using 1.x conventions.

**Comment by nachocpol** [comment]
Anyways, I'll go ahead and close the thread as seems that the docs are right.
