### ISSUE TITLE
InfluxDB CLI Hyperlink

### ISSUE THREAD

**Issue by MrkTrussell** [influxdata/docs-v2#4744]
CLI references, "A full list of influxql commands can be found at:..."
Hyperlink is not up-to-date

##### Relevant URLs
https://docs.influxdata.com/influxdb/latest/query_language/spec/

##### What products and version are you using?

InfluxDB  Shell version 1.8.10

**Comment by jstirnaman** [comment]
Thanks for reporting this.

For my own benefit:
- alias /influxdb/v2.4/query_languages/spec/ -> https://docs.influxdata.com/influxdb/v2.4/reference/syntax/influxql/spec/
- alias /influxdb/v2.5/query_languages/spec/ -> https://docs.influxdata.com/influxdb/v2.5/reference/syntax/influxql/spec/
- alias /influxdb/v2.6/query_languages/spec/ -> https://docs.influxdata.com/influxdb/v2.6/reference/syntax/influxql/spec/

- https://docs.influxdata.com/influxdb/v2.4/query_language/spec/ -> https://docs.influxdata.com/influxdb/v1.8/query_language/spec/
- https://docs.influxdata.com/influxdb/v2.5/query_language/ -> 404, no redirect
- https://docs.influxdata.com/influxdb/v2.6/query_language/ -> 404, no redirect

**Comment by jstirnaman** [comment]
Fixed with a rewrite on the docs server. https://docs.influxdata.com/influxdb/latest/query_language/spec/ -> https://docs.influxdata.com/influxdb/v1.8/query_language/spec/
