### ISSUE TITLE
Cannot generate config.yml file

### ISSUE THREAD

**Issue by naymore** [influxdata/docs-v2#4747]
I cannot connect to the freshly started docker container using the method outlined in the docs.

user@tc:/userdata/influxdb# docker run -d --restart unless-stopped --name=influxdb -p 8086:8086 -v /userdata/influxdb/data:/var/lib/influxdb2 influxdb:2.6.1 --reporting-disabled
2afc2fb3c3cb1f10cde39d34ec4a09115ab367be4f0de1456c5fc97d81e10523
user@tc:/userdata/influxdb# docker run --rm influxdb:2.6.1 influx server-config > config.yml
Error: failed to retrieve config: Get "http://localhost:8086/api/v2/config": dial tcp 127.0.0.1:8086: connect: connection refused
user@tc:/userdata/influxdb#

Influxdb is running though. Pointing a browser to http://192.168.1.10:8086 will redirect to [/onboarding/0](http://192.168.1.10:8086/onboarding/0)

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.6/install/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by naymore** [comment]
Pointing a browser to http://192.168.1.10:8086/api/v2/config will return 401 Unauthorized. Do I need to set up an organization first?

**Comment by sanderson** [comment]
@naymore This endpoint requires authentication (as mentioned in the [API documentation](https://docs.influxdata.com/influxdb/v2.6/api/#operation/GetConfig). You don't specifically need an organization, but you do need an operator token to authenticate with. The operator token is generated and provided during the initialization process. A default org is also created during the initialization process, but the org isn't required to use the `api/v2/config` endpoint, just a token is.
