### ISSUE TITLE
In iox SQL example, should  time >= INTERVAL '1 day' be time > now

### ISSUE THREAD

**Issue by johndunderhill** [influxdata/docs-v2#4765]
In the example for iox.sql() at the bottom of the page, seems like the query is wrong:

`query = "SELECT * FROM \"example-measurement\" WHERE time >= INTERVAL '1 day'"`

Maybe this should be something like:

`query = "SELECT * FROM \"example-measurement\" WHERE time >= now() - INTERVAL '1 day'"`

Am I missing something here?  Is there some kind of magic happening with INTERVAL?

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud-iox/reference/flux/

**Comment by sanderson** [comment]
Thanks @johndunderhill! You are correct. I've just pushed the fix.
