### ISSUE TITLE
Simple math operations on multiple fields and new column's name

### ISSUE THREAD

**Issue by naymore** [influxdata/docs-v2#4766]
I can't set a column name, in fact the column appears to have no name at all. There is no "_field" column anymore.
I also cannot rename the colum in the map() statement as suggested [here](https://docs.influxdata.com/influxdb/cloud/query-data/common-queries/operate-on-columns/).

I'd like to name the new (calculated) field for example "SolarPowerDcTotal".

```
from(bucket: "myBucket")
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "inverter")
  |> filter(fn: (r) => r["DeviceId"] == "x" and r["Type"] == "y")
  |> filter(fn: (r) => r._field == "SolarPowerDc1" or r._field == "SolarPowerDc2")
  |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> map(fn: (r) => ({r with _value: r.SolarPowerDc1 + r.SolarPowerDc2}))
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
```

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/query-data/common-queries/multiple-fields-in-calculations/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
@naymore, when you use `pivot()` to pivot fields into columns, the `_field` column is lost in this transformation. In your `map()` function, you can add the field column back in:

```js
// ...
    |> map(fn: (r) => ({r with _field: "SolarPowerDcTotal", _value: r.SolarPowerDc1 + r.SolarPowerDc2}))
```
