### ISSUE TITLE
Broken link from GCP Marketplace email

### ISSUE THREAD

**Issue by eriknolte** [influxdata/docs-v2#4789]
Broken link from GCP Marketplace email

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.6/introduction/getting-started/

From email:

> To get started with your solution:
> --
> 1. View the getting started documentation for InfluxDB:
>     * InfluxDB Documentation.   <- bad link here

##### What products and version are you using?
2.6.1 (the latest in Google Cloud Platform Marketplace)

Looks like the url contains an extraneous "/introduction/"

**Comment by sanderson** [comment]
Thanks for reporting @eriknolte. The fix for this is currently deploying.
