### ISSUE TITLE
Examples on docs page "Extracting Scalar Values" do not work

### ISSUE THREAD

**Issue by David00** [influxdata/docs-v2#4795]
Hi,

I'm running InfluxDB v2.6 OSS via Docker, and I'm following along in the docs to extract a scalar value from the sample dataset.

Basically, I am trying to execute the `findColumn()` example here using the `influx query` REPL: https://docs.influxdata.com/influxdb/cloud/query-data/flux/scalar-values/#extract-a-column

Here's exactly what I'm doing:
```
david@influx:~$ docker exec -it influxdb influx query
import "csv"

sampleData = csv.from(csv: "
#datatype,string,long,dateTime:RFC3339,string,string,double
#group,false,true,false,true,true,false
#default,,,,,,
,result,table,_time,location,_field,_value
,,0,2019-11-01T12:00:00Z,sfo,temp,65.1
,,0,2019-11-01T13:00:00Z,sfo,temp,66.2
,,0,2019-11-01T14:00:00Z,sfo,temp,66.3
,,0,2019-11-01T15:00:00Z,sfo,temp,66.8
,,1,2019-11-01T12:00:00Z,kjfk,temp,69.4
,,1,2019-11-01T13:00:00Z,kjfk,temp,69.9
,,1,2019-11-01T14:00:00Z,kjfk,temp,71.0
,,1,2019-11-01T15:00:00Z,kjfk,temp,71.2
,,2,2019-11-01T12:00:00Z,kord,temp,46.4
,,2,2019-11-01T13:00:00Z,kord,temp,46.3
,,2,2019-11-01T14:00:00Z,kord,temp,42.7
,,2,2019-11-01T15:00:00Z,kord,temp,38.9
")

sampleData
    |> findColumn(
        fn: (key) => key._field == "temp" and key.location == "sfo",
        column: "_value",
    )
Error: failed to execute query: 400 Bad Request: error in query specification while starting program: this Flux script returns no streaming data. Consider adding a "yield" or invoking streaming functions directly, without performing an assignment
```

The example in the docs say that this is supposed to return an array, like so:

```
// Returns [65.1, 66.2, 66.3, 66.8]
```

But you can see, it is failing.  I've tried to add a `|> yield()`, but that is complaining about expecting a stream but finding an array:

```
david@influx:~$ docker exec -it influxdb influx query
import "csv"

sampleData = csv.from(csv: "
#datatype,string,long,dateTime:RFC3339,string,string,double
#group,false,true,false,true,true,false
#default,,,,,,
,result,table,_time,location,_field,_value
,,0,2019-11-01T12:00:00Z,sfo,temp,65.1
,,0,2019-11-01T13:00:00Z,sfo,temp,66.2
,,0,2019-11-01T14:00:00Z,sfo,temp,66.3
,,0,2019-11-01T15:00:00Z,sfo,temp,66.8
,,1,2019-11-01T12:00:00Z,kjfk,temp,69.4
,,1,2019-11-01T13:00:00Z,kjfk,temp,69.9
,,1,2019-11-01T14:00:00Z,kjfk,temp,71.0
,,1,2019-11-01T15:00:00Z,kjfk,temp,71.2
,,2,2019-11-01T12:00:00Z,kord,temp,46.4
,,2,2019-11-01T13:00:00Z,kord,temp,46.3
,,2,2019-11-01T14:00:00Z,kord,temp,42.7
,,2,2019-11-01T15:00:00Z,kord,temp,38.9
")

sampleData
    |> findColumn(
        fn: (key) => key._field == "temp" and key.location == "sfo",
        column: "_value",
    )
        |> yield()
Error: failed to execute query: 400 Bad Request: error @29:5-29:12: expected stream[A] but found [A] (array) (argument tables)
```

I do see the warning message in the docs that says:

> The InfluxDB user interface (UI) does not currently support raw scalar output. Use [map()](https://docs.influxdata.com/flux/v0.x/stdlib/universe/map/) to add scalar values to output data.

... but I am not using the UI, so I don't think that applies, unless the UI also includes the `influx query` REPL.

It seems promising that the error message does indeed suggest there's an array there - but why can't I see it?

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/query-data/flux/scalar-values/

**Comment by sanderson** [comment]
@David00 The Flux runtime itself can return an array, but the InfluxDB query API can only return a stream of tables. If you were to run the examples in the Flux REPL, it would return the array.

I'll update this page a bit to clearly explain this limitation. I'll also mention that you can use `array.from()` and `display()` to return the array literal as a string and structure it a table:

```js
// ...

columnValues = sampleData
    |> findColumn(
        fn: (key) => key._field == "temp" and key.location == "sfo",
        column: "_value",
    )

array.from(rows: [{ outputArray: display(v: columnValues) }])
```

**Comment by David00** [comment]
Thanks @sanderson. I was mixed up between the `influx query` and the actual REPL, which I've educated myself on now.

Thank you for the details on `array.from()` and `display()`. I'll give them a try!
