### ISSUE TITLE
Add sustainable URL rewrites for v1.8 sections

### ISSUE THREAD

**Issue by mwnbrggithub** [influxdata/docs-v2#4809]
_Describe the issue here._

##### Relevant URLs
- _Provide relevant URLs (the doc page in question, project issues, community threads, etc.)_

**Comment by mwnbrggithub** [comment]
https://docs.influxdata.com/influxdb/v2.6/introduction/getting_started/#creating-a-database

![image](https://user-images.githubusercontent.com/67144134/225645629-e1a16ffd-ceab-4e09-bb9a-4eb1659c9b7a.png)

**Comment by sanderson** [comment]
Thanks for reporting @mwnbrggithub. Where did you click on this link?

**Comment by jstirnaman** [comment]
Possibly via `/content/influxdb/v1.8/introduction/get-started.md`? It aliases `latest/introduction/...`, but not `v2.5/introduction` or `v2.6/introduction`.  This is likely to be a recurring problem.
