### ISSUE TITLE
Updated to reflect multi-org?

### ISSUE THREAD

**Issue by bcorbett6** [influxdata/docs-v2#4810]
This page suggests that only a single organisation is available in InfluxDB Cloud, which i do not believe is the case now the new multi-org feature is GA.

Users can create / switch organisation via the UI
<img width="500" alt="Screenshot 2023-03-17 at 11 11 38" src="https://user-images.githubusercontent.com/98112442/225889081-620f31ca-68ac-46a7-8b24-478eccdc6e7d.png">

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/organizations/

**Comment by jstirnaman** [comment]
Related to #4642
