### ISSUE TITLE
Data Explorer SQL alias handled differently than example

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#4812]
1. In the UI Data Explorer for SQL (cloud-iox Version 2.0.0 (8ca52d0)), run the following snippet taken from the example in https://docs.influxdata.com/influxdb/cloud-iox/query-data/sql/aggregate-select/#downsample-data-by-applying-interval-based-aggregates:

     ```sql
     SELECT
       DATE_BIN(INTERVAL '1 day', time, '1970-01-01T00:00:00Z'::TIMESTAMP) AS time,
       room
    FROM home
    GROUP BY time, room
    ```

   Results aren't grouped by the calculated column named `time`. 
  
   ![image](https://user-images.githubusercontent.com/212227/226441612-d701682a-d9a1-4731-86e4-b777c4f6ae14.png)

2. In the Data Explorer, give the calculated column a different alias and re-run the query:

     ```sql
     SELECT
       DATE_BIN(INTERVAL '1 day', time, '1970-01-01T00:00:00Z'::TIMESTAMP) AS time_bin,
       room
     FROM home
     GROUP BY time_bin, room
     ```

    Results are grouped by time and room as expected.

- Is this a documentation error or a true difference in behavior?
- Didn't test with a different client yet.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud-iox/query-data/sql/aggregate-select/#downsample-data-by-applying-interval-based-aggregates

**Comment by sanderson** [comment]
Thanks for creating an issue for this. This is the `date_bin` issue with aliases columns I was talking about. All the examples that use `date_bin() AS time` need to be updated.

Rows also lose their ordering with this operation so we also need to add an `ORDER BY time_bin` statement.

**Comment by sanderson** [comment]
This is related to a known bug in DataFusion: https://github.com/influxdata/idpe/issues/16841

**Comment by alamb** [comment]
There is a subtle but important difference between the following two queries

SQL is logically evaluated like
1. `FROM` 
2. `GROUP BY`
3. `SELECT`

This gets tricky when there is `time` both as the output of the `FROM` and there is a (different)`time` that is the output of the `GROUP BY` 

So  this query groups by the `time` column from the `home` table

```sql
SELECT
  DATE_BIN(INTERVAL '1 day', time, '1970-01-01T00:00:00Z'::TIMESTAMP) AS time,
  room
FROM home
GROUP BY time, room -- "time" here is the "home.time"
```

And this query groups by the `time_bin` expression
```sql
SELECT
  DATE_BIN(INTERVAL '1 day', time, '1970-01-01T00:00:00Z'::TIMESTAMP) AS time_bin,
  room
FROM home
GROUP BY time_bin, room -- "time_bin" here is DATE_BIN ...
```

And is shorthand for this

```sql
SELECT
  DATE_BIN(INTERVAL '1 day', time, '1970-01-01T00:00:00Z'::TIMESTAMP) AS time_bin,
  room
FROM home
GROUP BY 
  DATE_BIN(INTERVAL '1 day', time, '1970-01-01T00:00:00Z'::TIMESTAMP) AS time_bin, 
  room
```

I believe IOx is correctly implementing the SQL semantics here, but those semantics is somewhat confusing

# Suggestions:
Perhaps we can change the doc example to use  positional expressions to avoid the footgun of re-defining `time`:


```sql
SELECT
  DATE_BIN(INTERVAL '1 day', time, '1970-01-01T00:00:00Z'::TIMESTAMP) AS time,
  room
FROM home
GROUP BY 1, 2
```

**Comment by jstirnaman** [comment]
@alamb Thanks for the analysis and suggestion.

> Perhaps we can change the doc example to use positional expressions

I agree. That seems like the best way to avoid ambiguity and any future change in semantics.
Although, it likely requires a bit of explanation for SQL newbies.

> I believe IOx is correctly implementing the SQL semantics here

I couldn't find a definitive answer for this either, but apparently it's common for implementations to prioritize alias names in `GROUP BY` if they collide with column names.

**Comment by jstirnaman** [comment]
To recap the related discussion in https://github.com/influxdata/idpe/issues/16841 (thanks, @btasker, for the push back and helping improve the docs!):

After digging a little more into behavior of other engines and "best" practice, I agree... sort of. IMO, it's better to explicitly include the calculation, and avoid column number and aliases, in the `GROUP_BY` clause:

```sql
SELECT
  DATE_BIN(INTERVAL '1 day', time, '1970-01-01T00:00:00Z'::TIMESTAMP) AS "time",
  room
FROM home
GROUP BY DATE_BIN(INTERVAL '1 day', time, '1970-01-01T00:00:00Z'::TIMESTAMP), room
```

While it's not DRY, it's probably the clearest representation of what the query is executing.
Also, some popular engines (Microsoft, Oracle) don't allow aliases in `GROUP_BY` at all.

A DRYer alternative would be to use a subquery, which might be preferred in production code but adds cognitive load to otherwise simple examples:

```sql
SELECT time, room
FROM
  (SELECT
    DATE_BIN(INTERVAL '1 day', time, '1970-01-01T00:00:00Z'::TIMESTAMP) AS "time",
    room
  FROM home)
GROUP BY time, room
```

**Comment by alamb** [comment]
> it's better to explicitly include the calculation, and avoid column number and aliases, in the GROUP_BY clause:

This makes sense to me 👍
