### ISSUE TITLE
Get started - first simple sample write, can't work wihout variable host.

### ISSUE THREAD

**Issue by stratanic** [influxdata/docs-v2#4842]
_Describe the issue here._

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.6/get-started/write/
- _Provide other relevant URLs (project issues, community threads, etc.)_

Hello, I spent some time on the documentation (2.6) to start using influxdb, because I had errors when I use the influx command.

I have uninstalled and reinstalled. and even the error. 

"Error: failed to list buckets: Get "/api/v2/buckets?limit=20&org=xxx": unsupported protocol scheme ""

can you specify in the documentation that if this message occurs, it is because the variable is missing: INFLUX_HOST

or else:
add the parameter in the command :

influx write \
  --bucket get-started
  --precision s "
home,room=Living\ Room temp=21.1,hum=35.9,co=0i 1641024000

I explain: I followed the instructions well, it is said that this variable is optional! or else there is a bug in the startup of the database...
so it is mandatory this variable.

Thank you for your great product very simplified. with a pleasant interface Gui.

**Comment by jstirnaman** [comment]
Closing. The current v2.6 instructions say 
> As you go through this tutorial, interactions with InfluxDB 2.6 require your InfluxDB host, organization name or ID, and your API token.
and explain how to configure the credentials.
