### ISSUE TITLE
Download and install the influx CLI page not found

### ISSUE THREAD

**Issue by vshvidler-dn** [influxdata/docs-v2#4843]
[Download and install the influx CLI](https://docs.influxdata.com/influxdb/cloud-iox/reference/cli/influx/#download-and-install-the-influx-cli) does not exist 
Getting 404 error with the following wording:
<img width="1728" alt="Screen Shot 2023-04-03 at 13 19 26" src="https://user-images.githubusercontent.com/103421008/229482476-9b6d094d-7b46-455e-855a-64e86d0ffc48.png">
Whoops! Looks like this page doesn't exist. If a link brought you here, [let us know](https://github.com/influxdata/docs-v2/issues/new). We'd like to fix it.

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud-iox/tools/influx-cli/

##### What products and version are you using?
[InfluxDB Cloud powered by IOx](https://docs.influxdata.com/influxdb/cloud-iox/)
Version 2.0.0 (d1bf6df)

**Comment by jstirnaman** [comment]
Fixed.
