### ISSUE TITLE
Influx CLI 2.7.0

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [influxdata/docs-v2#4844]
ETA: April 5 2022

See changelog for all PRs associated with this release:

### Bug Fixes

1. [4ce9053](https://github.com/influxdata/influx-cli/commit/4ce9053): Updated api for deleting secrets so "influx secret delete" command works again
1. [4046d99](https://github.com/influxdata/influx-cli/commit/4046d99): Typo in alias of bucket update command

### Features

1. [625273a](https://github.com/influxdata/influx-cli/commit/625273a): Add new replication field to better show queue sync progress

### Other

1. [5546ab6](https://github.com/influxdata/influx-cli/commit/5546ab6): Chore: upgrade go releaser to v1.13.1
1. [48e8f5b](https://github.com/influxdata/influx-cli/commit/48e8f5b): Chore: update to go 1.19.6
1. [1164ca5](https://github.com/influxdata/influx-cli/commit/1164ca5): Chore: use fpm for packaging
1. [88517ea](https://github.com/influxdata/influx-cli/commit/88517ea): Chore: version bump sys to support riscv
1. [2aea3fc](https://github.com/influxdata/influx-cli/commit/2aea3fc): Chore: update openapi

**Comment by sanderson** [comment]
Thanks @jeffreyssmith2nd. Prepping everything today, although, thanks to your efforts (🙏🏻), I think this is mostly already done.

**Comment by jeffreyssmith2nd** [comment]
Closing as resolved by #4847
