### ISSUE TITLE
InfluxDB OSS 2.7.0

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [influxdata/docs-v2#4845]
ETA: April 5 2023

See changelog for all PRs associated with this release:

### Bug Fixes

1. [6b60728](https://github.com/influxdata/influxdb/commit/6b60728): Update UI to resolve Dashboard crash and All Access Token creati…
1. [ec7fdd3](https://github.com/influxdata/influxdb/commit/ec7fdd3): Show Replication Queue size and Replication TCP Errors
1. [06a5902](https://github.com/influxdata/influxdb/commit/06a5902): Prevent unauthorized writes in flux "to" function
1. [77fd64a](https://github.com/influxdata/influxdb/commit/77fd64a): Handle replication missing queue
1. [b819edf](https://github.com/influxdata/influxdb/commit/b819edf): Rename replication fields for better clarity
1. [e1d0102](https://github.com/influxdata/influxdb/commit/e1d0102): Add error message when attempting to delete by field
1. [5a7ce07](https://github.com/influxdata/influxdb/commit/5a7ce07): Scraping failed when Content-Type header is not set
1. [96d6dc3](https://github.com/influxdata/influxdb/commit/96d6dc3): Removed timeout which is hit with large databases or slow servers #22803
1. [c854e53](https://github.com/influxdata/influxdb/commit/c854e53): Chmod'ing the manifest is unnecessary

### Other

1. [8ed55e7](https://github.com/influxdata/influxdb/commit/8ed55e7): Build(flux): update flux to v0.192.0
1. [109bc88](https://github.com/influxdata/influxdb/commit/109bc88): Chore: update package repo GPG key
1. [e2f835b](https://github.com/influxdata/influxdb/commit/e2f835b): Build(deps): bump github.com/aws/aws-sdk-go from 1.30.12 to 1.33.0
1. [8ad6e17](https://github.com/influxdata/influxdb/commit/8ad6e17): Chore: add additional error logging when deleting shard
1. [f74c69c](https://github.com/influxdata/influxdb/commit/f74c69c): Chore: update to go 1.20
1. [260d88b](https://github.com/influxdata/influxdb/commit/260d88b): Chore: bump testcontainers-go to 0.18.0
1. [4fc73ea](https://github.com/influxdata/influxdb/commit/4fc73ea): Feat(monitor-ci/415): get oss-e2es working locally in UI repo
1. [a035bcf](https://github.com/influxdata/influxdb/commit/a035bcf): Build(flux): update flux to v0.193.0
1. [23446cc](https://github.com/influxdata/influxdb/commit/23446cc): Build(deps): bump golang.org/x/net from 0.5.0 to 0.7.0
1. [569e84d](https://github.com/influxdata/influxdb/commit/569e84d): Chore: use go 1.20.1
1. [22d698b](https://github.com/influxdata/influxdb/commit/22d698b): Fix(sec): upgrade containerd to 1.6.18
1. [387d900](https://github.com/influxdata/influxdb/commit/387d900): Chore: fix typo in functions.go
1. [903d30d](https://github.com/influxdata/influxdb/commit/903d30d): Test: use `T.TempDir` to create temporary test directory
1. [eac0ee0](https://github.com/influxdata/influxdb/commit/eac0ee0): Build(deps): bump github.com/opencontainers/runc from 1.1.3 to 1.1.5

**Comment by jeffreyssmith2nd** [comment]
I have at least one more PR that will go in with some UI changes. I will update this ticket with a screenshot and writeup of those changes once they go in.

Highlights of this release:

- UI Changes (will update here once finalized.)
- Many security fixes
- Replications now show the bytes on disk and the remaining bytes to be synced. This should prevent confusion for developers. (This PR has some write up about the new fields https://github.com/influxdata/docs-v2/pull/4777/files)

**Comment by sanderson** [comment]
Thanks @jeffreyssmith2nd. Prepping everything today, although, thanks to your efforts (🙏🏻), I think this is mostly already done.
