### ISSUE TITLE
Link to OSS 2.7 API docs is broken

### ISSUE THREAD

**Issue by jeffmagill** [influxdata/docs-v2#4856]
Go to: https://docs.influxdata.com/influxdb/v2.7/reference/api/

Click button for 2.7 API documentation

Actual: Brought to 404
Expected: Brought to API docs.

### Screencast:

https://user-images.githubusercontent.com/810074/230678547-800e1b24-2216-4a35-ba89-ae26fbc3c15f.mov

**Comment by sanderson** [comment]
Thanks for reporting this @jeffmagill. I have a PR in to fix it.
