### ISSUE TITLE
Document gap filling queries for IOx SQL

### ISSUE THREAD

**Issue by wolffcm** [influxdata/docs-v2#4870]
I added a new feature to IOx SQL, which is gap fililng queries.

This feature makes use of a few new scalar functions:
- `date_bin_gapfill`
- `interpolate`
- `locf` (last observation carried forward)

This feature works pretty much the same as it does for TimeScale:
https://www.timescale.com/blog/sql-functions-for-time-series-analysis/

With a few important differences:
- instead of `time_bucket_gapfill` we call the function `date_bin_gapfill`, as it's analogous to our function `date_bin`
- The functions `interpolate` and `locf` only accept one argument as of yet (the column to be filled)
- A predicate on `time` in the `WHERE` clause is required with both upper and lower bounds

I made a demo in `#showme` that might be the best explanation of how it works:
https://influxdata.slack.com/archives/CG8NACC8M/p1680828088955949

There is also a technical document that may prove useful:
https://docs.google.com/document/d/1vIcs9uhlCX_AkD9bemcDx-YhBOVe_TW5sBbXtKCHIfk/edit#heading=h.6fymbftc19xe

It would be possible to document just the scalar functions by themselves, but the topic of gap filling probably deserves a more comprehensive article that shows how everything works together.

Happy to chat or have a meeting to discuss the best way to document this or provide any additional info.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud-iox/query-data/sql/basic-query/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by rickspencer3** [comment]
# Gap Filling Queries in IOx SQL

Learn how to use gap filling queries in IOx SQL for time-series analysis, including the new scalar functions and their usage.

## Overview

Gap filling queries in IOx SQL allow you to handle missing data in time-series analysis by filling in gaps with interpolated values or by carrying forward the last available observation. This feature is designed to provide a powerful and flexible solution for dealing with missing data points in your time-series datasets.

This document will cover the new scalar functions, their usage, and a brief example to demonstrate how to use gap filling queries in IOx SQL.

## Scalar Functions

The gap filling feature in IOx SQL makes use of three new scalar functions:

1. **date_bin_gapfill**: This function is used to define the interval for binning the data and filling the gaps.
```date_bin_gapfill(interval, time_column)```

2. **interpolate**: A function to linearly interpolate missing values in a specified column.
```interpolate(column_to_be_filled)```

3. **locf** (last observation carried forward): A function that carries forward the last available observation to fill the gaps in the specified column.
```locf(column_to_be_filled)```


## Usage

To use gap filling queries in IOx SQL, follow these steps:

1. Use the `date_bin_gapfill` function to define the interval for binning the data and filling the gaps.
2. Choose either the `interpolate` or `locf` function to fill the missing values in the specified column.
3. Include a predicate on time in the `WHERE` clause, with both upper and lower bounds.

## Example

Assume we have a table called `temperature_data` with columns `time`, `location`, and `temperature`. We want to fill the missing temperature values with linear interpolation.

```sql
SELECT
  date_bin_gapfill('1 hour', time) AS time,
  location,
  interpolate(temperature) AS temperature
FROM temperature_data
WHERE time >= '2023-04-01 00:00:00' AND time < '2023-04-02 00:00:00'
GROUP BY location, time
ORDER BY location, time;
```

In this example, the date_bin_gapfill function is used to create hourly bins for the data, and the interpolate function is used to fill missing temperature values with linear interpolation. The query is limited to a specific date range using the WHERE clause.

**Comment by wolffcm** [comment]
Very nice first draft.

> To use gap filling queries in IOx SQL, follow these steps:

I think the steps should be something like:
- Write an aggregate query that uses `date_bin` to group rows by a time interval, something like
```sql
SELECT
  date_bin('1 hour', time) AS time,
  location,
  avg(temperature)
FROM temperature_data
WHERE time >= '2023-04-01 00:00:00' AND time < '2023-04-02 00:00:00'
GROUP BY location, time;
```
- Change `date_bin` to `date_bin_gapfill` to fill in the gaps in time where there were no rows
- By default, gaps are filled with null values. To choose a different strategy for filing gaps:
  - Use `locf` to carry forward the last observation
  - Use `interpolate` to use linear interpolation

Would be great if the example had input and output data. Also note:
```sql
interpolate(temperature)
```
 by itself won't work, it needs to use an aggregate function:
```
interpolate(avg(temperature))
```
By nudging the user to create a normal aggregate query first, they're more likely to have success on the first try.
