### ISSUE TITLE
Update documentation about tokens

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#488]
Add the content below (where it fits best, perhaps the Manage authentication tokens page https://v2.docs.influxdata.com/v2.0/security/tokens/):

- Describe how to “use” authentication tokens after you’ve created one. Specifically in the UI, when you double-click a token, and then click Copy to clipboard…why? ...to paste the token into your write request header/when writing data to InfluxDB? 

- Koen Verschaeren also suggests (within the context of the Token page on InfluxCloud https://us-west-2-1.aws.cloud2.influxdata.com/orgs/03d32c9d1ad8f000/load-data/tokens)  that we add a links to:
   - the API (https://v2.docs.influxdata.com/v2.0/reference/api/) 
   - client documentation (https://v2.docs.influxdata.com/v2.0/reference/client-libraries/) 
   - and/or adding examples?

**Comment by gunnaraasen** [comment]
It would be nice to have a section on [this page](https://v2.docs.influxdata.com/v2.0/security/tokens/create-token/) that describes how to create a token directly via API calls.
