### ISSUE TITLE
Page not found ERROR 404

### ISSUE THREAD

**Issue by m4riu** [influxdata/docs-v2#4902]
_Describe the issue here._
Wanted to get started with Telegraf, but the link is an error 404

##### Relevant URLs
- _Provide relevant URLs_
- https://docs.influxdata.com/telegraf/latest/introduction/getting-started/

**Comment by m4riu** [comment]
The link was on this page : https://www.influxdata.com/time-series-platform/

**Comment by sanderson** [comment]
Thanks for reporting @m4riu. I just pushed a fix for this. It should go to https://docs.influxdata.com/telegraf/v2.6/get-started/.
