### ISSUE TITLE
Document the InfluxDB IOx queries measurement

### ISSUE THREAD

**Issue by btasker** [influxdata/docs-v2#4919]
When using an external visualisation tool (such as Grafana), a call to list available tables/measurements will include one from the `system` namespace called `queries`.

This table shows queries which have been executed  for that namespace on the querier node answering the query against .`queries`

This may lead to confusion as users will see a measurement they did not create and/or may not understand that the response will not necessarily include all of their queries.

Related to https://github.com/influxdata/influxdb_iox/issues/7119

**Comment by jstirnaman** [comment]
@btasker Thanks for requesting this. I'm still not clear on which queries `queries` contains or doesn't contain. Can you give examples?

Using Grafana, I can see that `queries` contains queries that I ran today using the Grafana plugin. It doesn't contain queries that I ran outside Grafana (using a different client).

![image](https://github.com/influxdata/docs-v2/assets/212227/c1e6258d-f1ab-424c-8ba0-c041295eec2c)

**Comment by crepererum** [comment]
Cross-ref https://github.com/influxdata/influxdb_iox/issues/7119 . I'll try to tackle this in the coming 2 weeks, so it stops confusing people.
