### ISSUE TITLE
Cloud Dedicated Go sample hardcodes bucket name

### ISSUE THREAD

**Issue by btasker** [influxdata/docs-v2#4974]
In the [Write line protocol data to InfluxDB Cloud Dedicated](https://docs.influxdata.com/influxdb/cloud-dedicated/write-data/line-protocol/) docs, most settings are driven by environment variables, but the bucket name is hardcoded

The hardcoded name is first mentioned in the code sample, at which point the user will likely already have created the database
```go
writeAPI := client.WriteAPI(os.Getenv("INFLUX_ORG"), "get-started")
```

It would be better to update that to be
```go
writeAPI := client.WriteAPI(os.Getenv("INFLUX_ORG"),os.Getenv("INFLUX_BUCKET"))
```

There's a similar example for serverless which would probably benefit from the same
##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud-dedicated/write-data/line-protocol/
- https://docs.influxdata.com/influxdb/cloud-serverless/write-data/line-protocol/

**Comment by jstirnaman** [comment]
> but the bucket name is hardcoded

There are a couple of (non-obvious) reasons for this. Historically, client libraries, etc. haven't used an bucket env var b/c ( I assume), in practice, you may be writing to multiple buckets from a single app--for example, an `auth` bucket and a `data` bucket. Also, in this case, [we refer](https://docs.influxdata.com/influxdb/cloud-dedicated/write-data/line-protocol/#set-up-your-project) to the Get Started tutorial that guides the user to create a "get-started" bucket, tokens, etc.

That said, we have a new feature for customizable placeholders that the user can edit in-page before copying the code. We're slowly incorporating the feature into examples, but it will eventually apply to the bucket name here as well.

The feedback is much appreciated!
