### ISSUE TITLE
time is invalid dataType

### ISSUE THREAD

**Issue by argonui** [influxdata/docs-v2#5029]
when creating a new csv upload in a bucket: https://us-east-1-1.aws.cloud2.influxdata.com/orgs/1313aab1f87f4f24/load-data/file-upload/annotated_csv "time" is reported as an invalid dataType. 

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/reference/syntax/annotated-csv/#time-columns

It's not clear to me when uploading the csv which version of influx I am using.

Input I'm using: 1482669077000000000 (open to changing this)

What i've tried:
* using time
* dateTime
* dateTime:number
* dateTime:RFC3339
* dateTime:RFC3339Nano

**Comment by jstirnaman** [comment]
@argonui Given your timestamp is in unix format and appears to be nanoseconds, any of the following should be correct when using annotated CSV:

- `time`
- `dateTime`
- `time:number`
- `dateTime:number`

I recommend trying your upload via the `influx` CLI. It's more flexible than the UI and allows for annotation options.
If you're using Cloud Serverless, you can use the `influx3` CLI.

The version number in the lower right corner of the UI will tell which InfluxDB version you're on:

![image](https://github.com/influxdata/docs-v2/assets/212227/a9e4cdfd-4404-4e80-aa69-581d314c20a1)

- More information about InfluxDB versions: https://docs.influxdata.com/influxdb/cloud-serverless/
- `influx` CLI reference: https://docs.influxdata.com/influxdb/cloud-serverless/reference/cli/influx/
