### ISSUE TITLE
Chronograf usage with Cloud Dedicated is unclear

### ISSUE THREAD

**Issue by jdstrand** [influxdata/docs-v2#5037]
https://docs.influxdata.com/influxdb/cloud-dedicated/get-started/query/ lists Chronograf as a query tool for Cloud Dedicated (though the [link is broken](https://github.com/influxdata/docs-v2/issues/5036)). Looking around in https://docs.influxdata.com/chronograf/v1.10/guides/querying-data/ it isn't clear how to use chronograf successfully with Cloud Dedicated.

It is possible to setup an InfluxDB connection with the `https://<uuid>.a.influxdb.io` URL with username blank and password as the token, but nothing I could find actually says to do that or to make sure that 'InfluxDB v2 Auth' is unchecked or to omit the org name.

While that appears to work, going to http://localhost:8888/sources/0/chronograf/data-explorer and entering a query always results in `database name required` when doing `SELECT.` It isn't clear (to me at least) how to fix that (note `ON` doesn't work with `SELECT`). Adjusting the InfluxDB connection to instead use `https://<uuid>.a.influxdb.io?db=<database name>` does not seem to work either.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud-dedicated/get-started/query/ 
- https://docs.influxdata.com/chronograf/v1.10/guides/querying-data/ ?

##### What products and version are you using?
Cloud Dedicated

**Comment by sanderson** [comment]
Thanks @jdstrand. Just pushed a fix for this.

**Comment by jdstrand** [comment]
@sanderson - thanks! Did you mean to close https://github.com/influxdata/docs-v2/issues/5036 instead (that's the broken link which you've fixed). This one is about the instructions for how to use chronograf with Dedicated are unclear.

**Comment by sanderson** [comment]
Ope, you're right. Wrong issue. I'll document using Chronograf with Dedicated.
