### ISSUE TITLE
Missing page

### ISSUE THREAD

**Issue by jerry1333** [influxdata/docs-v2#5059]
See what happens when you click on Writing to the /write v1 compatibility endpoint
![image](https://github.com/influxdata/docs-v2/assets/984193/c2f64d38-4a85-40b3-a860-7dfd7150770e)
![image](https://github.com/influxdata/docs-v2/assets/984193/f9b7f876-150b-4b32-afde-9a0b7ea97114)

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud-serverless/query-data/influxql/dbrp/?t=InfluxDB+HTTP+API
https://docs.influxdata.com/influxdb/cloud-servereless/reference/api/influxdb-1x/write/

##### What products and version are you using?
Doesn't matter? It's doc issue not application one.

**Comment by jstirnaman** [comment]
Thanks for reporting this! You can find info about the v1 `/write` API endpoint at https://docs.influxdata.com/influxdb/cloud-serverless/api-compatibility/v1/#write-data
