### ISSUE TITLE
Guides around handling "states"

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#509]
There are many use cases that involve tracking states reported in metrics. We should create a set of guides around state-related use cases.

- Track the duration of a state using [`stateDuration()`](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/stateduration/).
- Count state within a given period of time ([`stateCount()`](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/statecount/)).
- Query state changes only ([`monitor.statechanges()`](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/monitor/statechanges/)).

**Comment by kelseiv** [comment]
1.x content we may be able to glean use cases from:

**stateDuration()**: https://docs.influxdata.com/kapacitor/v1.5/nodes/state_duration_node
**stateCount()**: https://docs.influxdata.com/kapacitor/v1.5/nodes/state_count_node
**monitor.statechanges()**: https://docs.influxdata.com/kapacitor/v1.5/nodes/change_detect_node/
