### ISSUE TITLE
LInux is missing 

### ISSUE THREAD

**Issue by mdraja786786** [influxdata/docs-v2#5091]
Below link is missing from InfluxDB upgrade documentation (https://docs.influxdata.com/influxdb/v2.7/upgrade/v1-to-v2/automatic-upgrade/) under section user migration.

https://docs.influxdata.com/influxdb/v1.3/administration/authentication_and_authorization/#admin-users -- it gives 404 error.

##### Relevant URLs
- _Provide relevant URLs_

**Comment by sanderson** [comment]
Fixed in https://github.com/influxdata/docs-v2/pull/5133
