### ISSUE TITLE
A minor error

### ISSUE THREAD

**Issue by Ji-Shao** [influxdata/docs-v2#5113]
_Describe the issue here._
The following text should be "The **left** operand must be a string. The **right** operand must be a regular expression."
Not 
The **right** operand must be a string. The **left** operand must be a regular expression.

##### Relevant URLs
[- https://docs.influxdata.com/flux/v0.x/data-types/basic/regexp/
- _Provide other relevant URLs (project issues, community threads, etc.)_](https://docs.influxdata.com/flux/v0.x/data-types/basic/regexp/)

**Comment by sanderson** [comment]
Thanks @Ji-Shao! I just pushed a fix for this.
