### ISSUE TITLE
403 Permissions error

### ISSUE THREAD

**Issue by Ramadel** [influxdata/docs-v2#5130]
This article doesn't specify what permissions are needed. Using admin rights, I get a 403 Forbidden: insufficient permission to delete.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/write-data/delete-data/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by jstirnaman** [comment]
@Ramadel `delete` requires an API token with write permission to the bucket. InfluxDB API tokens can have _read_, _write_, or both permissions to resources.  Also see the API documentation https://docs.influxdata.com/influxdb/cloud/api/#operation/PostDelete
