### ISSUE TITLE
Kapacitor 1.6 release

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs-v2#5150]
- [x] Update release notes for [Kapacitor 1.7 release](https://github.com/influxdata/kapacitor/blob/master/CHANGELOG.md) (@davidby-influx).
- [ ] Review Kapacitor 1.6 milestone issues to make sure all feature doc updates have an associated issue.

**Comment by davidby-influx** [comment]
`CHANGELOG.md` updated: https://github.com/influxdata/kapacitor/pull/2780
