### ISSUE TITLE
Link to Influx DB Community Slack is Broken

### ISSUE THREAD

**Issue by stevebissett** [influxdata/docs-v2#5158]
This [page](https://docs.influxdata.com/flux/v0/get-started/) links to the InfluxDB Slack Community - yet the link is not working.
"This link is no longer active"

##### Relevant URLs
- https://docs.influxdata.com/flux/v0/get-started/

**Comment by jstirnaman** [comment]
@stevebissett Is this working for you now? I don't see the problem.
