### ISSUE TITLE
Write: partial writes write good lines and reject bad lines

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#5160]
See detail in https://github.com/influxdata/influxdb_iox/issues/5226#issuecomment-1716158763

Response:
`400`

```
{
  "code": "invalid",
  "line": 123,
  "message": "human-readable error message"
}
```
[Slack Message](https://influxdata.slack.com/archives/C04768675QD/p1696034786933909?thread_ts=1695822639.441929&cid=C04768675QD)

**Comment by wiedld** [comment]
Note that partial writes is not the default. It has to be [specifically enabled](https://github.com/influxdata/influxdb_iox/issues/5226#issuecomment-1741239380) per cluster. Currently it's only on in stag101  stag102. Not sure who/how we decide where else to turn on.

**Comment by wiedld** [comment]
For anything with an iox backend:
```
{
  "code": "invalid",
  "line": 123, // line number of first error encountered
  "message": "<human-readable error message for 1st line error>\n<human-readable error message for 1st line error>\n<human-readable error message for Nth line error up to N=100 lines>"
}
```

This^^ error is returned regardless of whether or not partial writes is enabled.
