### ISSUE TITLE
Does the sql "SHOW COLUMNS IN home" support syntax in the influxdb which is the version of 1.7+?

### ISSUE THREAD

**Issue by Watson-kubernetes** [influxdata/docs-v2#5185]
_Describe the issue here._

##### Relevant URLs
- https://docs.influxdata.com/influxdb/clustered/query-data/sql/explore-schema/
- _Provide other relevant URLs (project issues, community threads, etc.)_
i use the java api to query,but the result throw the exception that error parsing query: found columns, expected CONTINUOUS, DATABASES, DIAGNOSTICS, FIELD, GRANTS, MEASUREMENT, MEASUREMENTS, QUERIES, RETENTION, SERIES, SHARD, SHARDS, STATS, SUBSCRIPTIONS, TAG,

**Comment by sanderson** [comment]
@Watson-kubernetes the InfluxDB 1.x SQL-like query language is InfluxQL. With InfluxDB 3.0 (Cloud Serverless, Cloud Dedicated, and Clustered), InfluxDB supports native SQL. The `SHOW COLUMNS` query is a SQL query, not an InfluxQL query. The InfluxDB v1 Java client library only supports InfluxQL.

If you're using InfluxDB Clustered, you should use the [InfluxDB v3 Java client library](https://docs.influxdata.com/influxdb/clustered/reference/client-libraries/v3/java/). This allows you to execute SQL queries.

If you want to use InfluxQL, you can continue to use the InfluxDB v1 Java client library, but you'll need to use [InfluxQL commands](https://docs.influxdata.com/influxdb/clustered/reference/influxql/) such as `SHOW FIELD KEYS` and `SHOW TAG KEYS`.

**Comment by Watson-kubernetes** [comment]
got it ,thanks a lot @sanderson
