### ISSUE TITLE
Document Tree is displayed when clicked on the Download button

### ISSUE THREAD

**Issue by kritamd** [influxdata/docs-v2#5204]
_D![button1](https://github.com/influxdata/docs-v2/assets/19722630/32e40b5c-f363-48ac-bf53-67e8720747ac)

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2/install/
- _Provide other relevant URLs (project issues, community threads, etc.)_
![Error](https://github.com/influxdata/docs-v2/assets/19722630/393e303d-1ebe-4954-a956-0514744c1c62)

**Comment by jstirnaman** [comment]
@kritamd Thanks for reporting this - we're getting it sorted out. You can find the latest release for Windows at https://github.com/influxdata/influxdb/releases/tag/v2.7.3.

**Comment by jstirnaman** [comment]
v2.7.3 for Windows isn't listed at dl.influxdata.com or portal.influxdata.com.
