### ISSUE TITLE
Fix typo in plugin catalogue

### ISSUE THREAD

**Issue by bbergshaven** [influxdata/docs-v2#5228]
The description of the Clarify Output plugin contains a typo.

`Write data to Clairfy` => `Write data to Clarify`

https://github.com/influxdata/docs-v2/blob/fdd97071bab1b2abf7bff199e5726bce40075b57/data/telegraf_plugins.yml#L2331

**Comment by sanderson** [comment]
Thanks @bbergshaven! I just pushed a fix for this.
