### ISSUE TITLE
Example Data math.copysign

### ISSUE THREAD

**Issue by deReutzel** [influxdata/docs-v2#5229]
The example data doesn´t really show what the function does, as there is no negative input value.

##### Relevant URLs
- https://docs.influxdata.com/flux/v0/stdlib/math/copysign/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
Thanks @deReutzel! I just merged a fix for this in the docs repo. I also have a PR upstream in the Flux repo that will make sure this stays fixed in the future: https://github.com/influxdata/flux/pull/5441
