### ISSUE TITLE
APT key for Telegraf varies with Ubuntu version.

### ISSUE THREAD

**Issue by obscherler** [influxdata/docs-v2#5231]
APT key for Telegraf varies with Ubuntu version.

Documentation doesn’t distinguish between Ubuntu version.

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1/install/

**Comment by jstirnaman** [comment]
Thank you for submitting this. According to https://repos.influxdata.com/ubuntu/, newer OS versions should use influxdata-archive.key. I'll test and update.

**Comment by jstirnaman** [comment]
@powersj Can you point me to what's required for using `influxdata-archive.key`, as recommended by https://repos.influxdata.com/ubuntu/?

I'm trying to use it for Debian. All our install examples use `influxdata-archive_compat.key`.

**Comment by powersj** [comment]
> APT key for Telegraf varies with Ubuntu version.
> Documentation doesn’t distinguish between Ubuntu version.

The documented compat key should work for any version of Ubuntu. The non-compat key is meant for newer releases, which at this point is any Ubuntu in standard support (e.g. Ubuntu 20.04 LTS and newer).

To use the non-compat key, the instructions need to update the key filename + sha256:

```s
wget -q https://repos.influxdata.com/influxdata-archive.key
echo '943666881a1b8d9b849b74caebf02d3465d6beb716510d86a39f6c8e8dac7515 influxdata-archive.key' | sha256sum -c && cat influxdata-archive.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive.gpg > /dev/null
echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
sudo apt-get update && sudo apt-get install telegraf
```
