### ISSUE TITLE
Link from Google Cloud Services Error

### ISSUE THREAD

**Issue by okazagi** [influxdata/docs-v2#5244]
_Describe the issue here._
The InfluxDB Documentation link in the InfluxDB Cloud(Official Version) product details page is broken.
##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/cloud/get-started/#sign-up

**Comment by jstirnaman** [comment]
@sanderson broken URL: https://v2.docs.influxdata.com/v2.0/cloud/get-started/#sign-up

**Comment by jstirnaman** [comment]
@okazagi Thanks for pointing this out!
