### ISSUE TITLE
Incorrect Apache arrow package version 

### ISSUE THREAD

**Issue by ericmccorkle** [influxdata/docs-v2#5271]
_Describe the issue here._

The example go code that imports apache arrow points to the incorrect version. It should be v13, which is an indirect module in the go.mod when the influx3 go client library is downloaded. 

##### Relevant URLs
- https://docs.influxdata.com/influxdb/clustered/get-started/query/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by jstirnaman** [comment]
Thanks for calling this out!
