### ISSUE TITLE
influxd upgrade is not a command that works

### ISSUE THREAD

**Issue by chili-bean** [influxdata/docs-v2#5295]
influxd has no upgrade option

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2/install/upgrade/v1-to-v2/automatic-upgrade/
- _Provide other relevant URLs (project issues, community threads, etc.)_

It says to run 'influxd upgrade' to upgrade from 1.x to 2.7.  I'm running 1.6.7~rc0 and there is no 'upgrade' option available.  The available options are backup, config, help, restore, run, and version.

**Comment by sanderson** [comment]
@chili-bean I'll update the documentation to make this more clear. `influxd upgrade` is part of the [v2 `influx` CLI](https://docs.influxdata.com/influxdb/v2/reference/cli/influxd/upgrade/).
