### ISSUE TITLE
Link broken / doesn't exist

### ISSUE THREAD

**Issue by ArtMattner** [influxdata/docs-v2#5306]
If you click on "Load Data" -> "Telegraf" -> "Create Configuration" you will see links to the documentation.
The broken link is the "Telegraf Plugins".

##### Relevant URLs
[Telegraf Plugins](https://v2.docs.influxdata.com/v2.0/reference/telegraf-plugins/#input-plugins)

##### What products and version are you using?

Version 2.0.x (a3fa943) @ RaspberryPi 4 4GB Ubuntu 23.10 ARM

**Comment by jstirnaman** [comment]
This appears to be replaced/fixed in more recent versions of v2 OSS. For example, v2.7.5, I don't see the link text "Telegraf Plugins" or the problem URL.
