### ISSUE TITLE
Incorrect syntax - --template-time

### ISSUE THREAD

**Issue by MaduMitha-Ravi** [influxdata/docs-v2#5347]
The syntax `--template-time` is incorrect, the correct one is `--template-timeformat`.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud-dedicated/admin/tables/create/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
Thanks @MaduMitha-Ravi! I have a fix for this in flight right now.
