### ISSUE TITLE
Proposed Document partition and file limits for Serverless free and PAYG

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#5375]
> As a service protection measure we would like to enable some query limits in Serverless environments.

For Free:
> Free:
> 500 partitions
> 1000 parquet files

For PAYG:
> The suggested default values for these limits were 2000 partitions and 10000 parquet files. In Serverless a partition is currently all the data for a table for 1 day. 

Analysis conclusion:

> The proposed limits of 2000 partitions and 10000 parquet files are unlikely to cause our users undue stress. In many cases queries that would be prevented from running were generated from our own UI... There are a few cases where long timeframe queries are running that may not affect other users unduly. Here we can increase the limit from the default. 

Query response:

> The flight request will return the gRPC error code ResourceExhausted and the error message will contain Query would process more than 500 partitions or Query would process more than 1000 parquet files for example.

https://influxdata.slack.com/archives/CDBJ35NBV/p1710788601880619?thread_ts=1709570873.537529&cid=CDBJ35NBV

**Comment by sanderson** [comment]
Related to #5372 which addresses an already-in-place but undocumented write limit.
