### ISSUE TITLE
File influxdb2-client-2.7.3-linux-amd64.tar.gz referenced in documentation have the wrong client version

### ISSUE THREAD

**Issue by jaimeventura-eaton** [influxdata/docs-v2#5377]
Documentation here: https://docs.influxdata.com/influxdb/v2/tools/influx-cli/

After downloading file (Linux client for amd64 arch):
wget https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.3-linux-amd64.tar.gz

And decompressing the files, the inclosed client refers to version `1.6.7~rc0` (not `2.7.3`)
``` root@my-shell:/lixo# wget https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.3-linux-amd64.tar.gz
--2024-03-21 18:46:00--  https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.3-linux-amd64.tar.gz
Resolving dl.influxdata.com (dl.influxdata.com)... 13.227.219.38, 13.227.219.49, 13.227.219.46, ...
Connecting to dl.influxdata.com (dl.influxdata.com)|13.227.219.38|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11454321 (11M) [application/x-tar]
Saving to: 'influxdb2-client-2.7.3-linux-amd64.tar.gz'

influxdb2-client-2.7.3-linux-amd64.tar.g 100%[==================================================================================>]  10.92M  --.-KB/s    in 0.05s

2024-03-21 18:46:00 (222 MB/s) - 'influxdb2-client-2.7.3-linux-amd64.tar.gz' saved [11454321/11454321]

root@my-shell:/lixo# tar xvzf influxdb2-client-2.7.3-linux-amd64.tar.gz
./
./LICENSE
./README.md
./influx
root@my-shell:/lixo# influx -version
InfluxDB shell version: 1.6.7~rc0
root@my-shell:/lixo#
```

**Comment by sanderson** [comment]
@jaimeventura-eaton From the following series of commands, I think you have previously installed the 1.6.2 `influx` CLI on your system $PATH.

```sh
root@my-shell:/lixo# tar xvzf influxdb2-client-2.7.3-linux-amd64.tar.gz
./
./LICENSE
./README.md
./influx
root@my-shell:/lixo# influx -version
```

When you run that last command, you don't use the local directory context `./`, so it's defaulting to the `influx` CLI in your $PATH. Try running the following command from the directory where you unpackaged the CLI:

```
root@my-shell:/lixo# ./influx --version
```

**Comment by jaimeventura-eaton** [comment]
So sorry, I ended up figuring that out myself.
As an experienced linux user, I feel ashamed with that newbie mistake.
Thank you and sorry for the trouble.
