### ISSUE TITLE
Docs: broken URL

### ISSUE THREAD

**Issue by NorbNorb** [influxdata/docs-v2#5448]
When clicking on the link "Delete predicate" it navigates to a webpage showing an HTTP 404 error.
![Error screen](https://github.com/influxdata/docs-v2/assets/4516977/42b3c8c5-090c-46e5-81e2-d33e0770618b)

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud-serverless/reference/syntax/delete-predicate/
Linked here: https://docs.influxdata.com/influxdb/cloud-serverless/reference/cli/influx/delete/

**Comment by jstirnaman** [comment]
@sanderson Do we want to add https://docs.influxdata.com/influxdb/cloud/reference/syntax/delete-predicate/ to cloud-serverless?
