### ISSUE TITLE
csv.from(file ) is not available in InfluxDB Cloud.

### ISSUE THREAD

**Issue by nisley** [influxdata/docs-v2#545]
https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/csv/from/

csv.from(file) is not available in InfluxDB Cloud, but csv.from(csv) is available.

**Comment by noramullen1** [comment]
Hi @nisley ,

This is called out in blue right below the example.

**Comment by sanderson** [comment]
Thanks @nisley. I'll update this and make the distinction.
