### ISSUE TITLE
vault input doc points to nomad github repo

### ISSUE THREAD

**Issue by jhrcz-ls** [influxdata/docs-v2#5457]
at https://docs.influxdata.com/telegraf/v1/plugins/
both hashicorp nomad and hashicorp vault input plugins have same section div/anchor name `#input-nomad`

vault input points to nomad github repo instead its own (ex. https://github.com/influxdata/telegraf/tree/release-1.30/plugins/inputs/vault)

**Comment by sanderson** [comment]
Thanks @jhrcz-ls! Just pushed a fix for this.
