### ISSUE TITLE
Cross reference/mention now & system.time and how they differ

### ISSUE THREAD

**Issue by nisley** [influxdata/docs-v2#546]
I was stuck digging into now:
https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/misc/now/

and disappointed I could not get timings between two different calls to now() in a script as now() is cached in a query builder script to synchronize queries between different stanzas.

Turns out there is a function to get the actual time:
https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/system/time/

If I'm looking at one in the docs it would be good to know about the other and when one might want now vs. system.time

**Comment by sanderson** [comment]
Good call. I'll add cross-references to each.
