### ISSUE TITLE
We need rust sdk for influxdb2, thanks!

### ISSUE THREAD

**Issue by rcitsz** [influxdata/docs-v2#5469]
_Describe the issue here._

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2/api-guide/client-libraries/
- _Provide other relevant URLs (project issues, community threads, etc.)_
We need rust sdk for influxdb2, thanks!

**Comment by jstirnaman** [comment]
I recommend starting a discussion in the [Influx Community #client-libraries Slack channel](https://influxcommunity.slack.com/archives/C02UDUPLQKA). Thanks for the suggestion!
