### ISSUE TITLE
Docs page mentions WriteOptions when it seems to be WriteParameters

### ISSUE THREAD

**Issue by programmatix** [influxdata/docs-v2#5476]
Url: https://docs.influxdata.com/influxdb/cloud-serverless/get-started/write/?t=Java

The doc mentions a WriteOptions class that doesn't appear to exist.

**Comment by jstirnaman** [comment]
https://github.com/InfluxCommunity/influxdb3-java/blob/main/src/test/java/com/influxdb/v3/client/write/WriteOptionsTest.java

I don't see `WriteParameters` in the `influxdb3-java` client library.
