### ISSUE TITLE
Silenteye

### ISSUE THREAD

**Issue by masterpink0** [influxdata/docs-v2#5482]
_Describe the issue here._

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1/plugins/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
@masterpink0 No content was included in this issue. What problems are you having on the [Telegraf plugins page](https://docs.influxdata.com/telegraf/v1/plugins/)?
