### ISSUE TITLE
broken link on 2.x migration docs

### ISSUE THREAD

**Issue by tennox** [influxdata/docs-v2#5483]
##### Relevant URLs
Source:
https://docs.influxdata.com/influxdb/v2/install/upgrade/v2-to-v2/?t=Docker

Text:
> If you’re upgrading from InfluxDB 2.0 beta-16 or earlier, you must first [upgrade to InfluxDB 2.0](https://docs.influxdata.com/influxdb/v2/upgrade/v2-beta-to-v2/), and then complete the steps below.

Broken link:
https://docs.influxdata.com/influxdb/v2/upgrade/v2-beta-to-v2/

**Comment by davidby-influx** [comment]
I have no idea....

**Comment by jeffreyssmith2nd** [comment]
The code [here](https://github.com/influxdata/influxdb/blob/031f394d2ccbdc32e5e6befaaf6a0398c57169a6/cmd/influxd/downgrade/downgrade.go#L36) shows each of the versions that require migrations. 

With the caveat of not having tested this at all, I think it should be valid to go from v2 beta to v2.0, then walk through each upgrade to the next version in order.

I definitely **would not** recommend jumping from v2 beta to something newer, that would likely lead to a very bad time.
