### ISSUE TITLE
Document how to save query as variable in UI

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#550]
In Data Explorer, create a query, click Save As. New variable button.

**Comment by noramullen1** [comment]
@kelseiv -- It looks like we already have this documented here: https://v2.docs.influxdata.com/v2.0/visualize-data/variables/create-variable/#create-a-variable-in-the-data-explorer

Is there somewhere else you think it belongs too?

**Comment by kelseiv** [comment]
thank you @noramullen1! let's add here:
https://v2.docs.influxdata.com/v2.0/visualize-data/explore-metrics/#save-your-query-as-a-dashboard-cell-or-task

**Comment by kelseiv** [comment]
for this procedure: https://v2.docs.influxdata.com/v2.0/visualize-data/variables/create-variable/#create-a-variable-in-the-data-explorer

after step 6, we could add step to "select variable type".... perhaps add (or link to) details about what to enter for each type of variable?

think step 3 is optional?
