### ISSUE TITLE
“You cannot write to the same bucket you are reading from.” is out of date

### ISSUE THREAD

**Issue by mkarlesky** [influxdata/docs-v2#555]
#### Issue
Statements quoted below in the next section from within the InfluxDB v2.0 documentation seem to be out of date.

I started [a support forum thread](https://community.influxdata.com/t/you-cannot-write-to-the-same-bucket-you-are-reading-from/11199) on this limitation as stated in the documentation. Paul Dix replied explaining that the limitation should be reconsidered. I've since heard from internal sources that the restriction was lifted or otherwise modified. And, I can confirm from experiments using Influx Cloud v2 that I was entirely able to join two measurements, perform a transformation, and then write the result back to the same bucket from which the input measurements originated.

I can't suggest what edits to make as I don't have details on any internal changes. But, I'm quite confident this documentation is out of date as the limitation as stated does not appear to exist or is not otherwise enforced.

#### Relevant URLs
A. [Process Data > Get started with InfluxDB tasks](https://v2.docs.influxdata.com/v2.0/process-data/get-started/)
>**Important notes**
>* You cannot write to the same bucket you are reading from.

B. [Process Data > Common tasks > Downsample data](https://v2.docs.influxdata.com/v2.0/process-data/common-tasks/downsample-data/)
>By design, tasks cannot write to the same bucket from which they are reading. You need another bucket where the task can store the aggregated, downsampled data.

#### Typos
At link (A.) above the statement quoted below is made. A word seems to be missing in the last clause. I'd guess it's intended to read “… it needs to **_be_** sent and stored…“

>In the vast majority of task use cases, once data is transformed, it needs to sent and stored somewhere.

**Comment by pierwill** [comment]
Thanks for pointing this out!
