### ISSUE TITLE
Clustered: Docs need to be updated - claim hard limit of 250 columns per database. 

### ISSUE THREAD

**Issue by ericmccorkle** [influxdata/docs-v2#5568]
_Describe the issue here._

Please clarify this portion of the docs. This seems to be in conflict with the ability to set maximum columns per database using the `influxctl`. 

https://docs.influxdata.com/influxdb/clustered/write-data/best-practices/schema-design/#tables-can-contain-up-to-250-columns 

##### Relevant URLs
- https://docs.influxdata.com/influxdb/clustered/write-data/best-practices/schema-design/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by jstirnaman** [comment]
Thanks for submitting this! InfluxDB v3 maximum columns per table was recently revised to `1000` and is the default for new databases in Clustered and Cloud Dedicated. The setting isn't overridden for existing databases. We'll update the docs ASAP.
