### ISSUE TITLE
"npm init -y influx-node-app" Not found

### ISSUE THREAD

**Issue by masterj63** [influxdata/docs-v2#5619]
I follow the first step of the instruction but receive error from npm:
```
$ npm -v
10.8.2
$ npm init -y influx-node-app
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/create-influx-node-app - Not found
npm error 404
npm error 404  'create-influx-node-app@*' is not in this registry.
```

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/api-guide/client-libraries/nodejs/install/

**Comment by jstirnaman** [comment]
Thanks for pointing this out. `npm init -y <new-package-name>` no longer works the same way. 

The command `npm init -y <new-package-name>` is incorrect and causes npm to search for a package named create-<new-package-name> in the npm registry, which results in a 404 error if such a package does not exist.

Correct Usage

Creating a New Directory for the Package
If you want to create a new directory for your package and initialize it there, you should first create the directory and then run npm init inside it. If you want to use package defaults, include the -y  flag:

```sh
mkdir influx-node-app
cd influx-node-app
npm init -y
```

**Comment by jstirnaman** [comment]
You can also do something like the following to configure the package:

```
npm init -y; npm pkg set type="module"
```
