### ISSUE TITLE
Docs for setting up Grafana connection are unusable

### ISSUE THREAD

**Issue by mathieucaroff** [influxdata/docs-v2#5640]
##### Context

I'm trying to have my Grafana instance load its data from my InfluxDB instance. (Both instances are docker images I run locally.)

##### Problem

_The Grafana screenshot in the documentation does not match the UI I get running Grafana 11.2.0_ The InfluxDB documentation is based on that screenshot version of Grafana and not on the fields present in Grafana 11.2.0.

##### Relevant URL

- https://docs.influxdata.com/influxdb/v2/tools/grafana/

##### Grafana screenshot in the documentation

![v2-tools-grafana-flux](https://github.com/user-attachments/assets/a862f048-1550-457b-af88-8e05e67cb091)

##### Grafana 11.2.0 screenshot I took

![image](https://github.com/user-attachments/assets/83a58130-5c91-4ef7-9870-f1be5dfba02f)

As you can see, the InfluxDB Detail sections do not match at all. The documentation lists: "Organization", "Token", "Default bucket" while the UI of Grafana 11.2.0 contains: "Database", "User", "Password", "HTTP Method".

##### What to do

Please update the documentation to explain how to connect InfluxDb2 to Grafana 11.2. Also, please tell which version of Grafana the doc was written for.

**Comment by sanderson** [comment]
@mathieucaroff This difference is the query language you have selected. Flux and InfluxQL use different APIs that require differently named credentials. If you switch to the "InfluxQL" tab on the page you linked, you'll see instructions for using Grafana and InfluxQL to query data from InfluxDB v2: https://docs.influxdata.com/influxdb/v2/tools/grafana/?t=InfluxQL

**Comment by mathieucaroff** [comment]
Thanks, I guess the fault fallls on me and the designt of the tabs because I did not see them :-/. Have a good day
