### ISSUE TITLE
telegraf: Broken core product promise: missing documentation how to setup more than one input stream

### ISSUE THREAD

**Issue by wolfgangr** [influxdata/docs-v2#5643]
maybe I posted my issue to the wrong repo?

https://github.com/influxdata/telegraf/issues/16004

In short, I think the fact that multiple inputs are lumped together to all the outputs is not visible while climbing the learning curve. 

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1/configuration/

**Comment by srebhan** [comment]
Let's keep it over in `influxdata/telegraf`.
