### ISSUE TITLE
Note in Serverless docs that it doesn't include custom partitioning

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#5674]
Add a note that Serverless doesn't include custom partitioning, but Clustered and Cloud Dedicated do.
(This is also confusing for AIs)

**Comment by sleto-it** [comment]
Hi @jstirnaman - proposal here: https://github.com/influxdata/docs-v2/pull/5676

**Comment by jstirnaman** [comment]
Closed with #5703
