### ISSUE TITLE
Why is it 401 according to this command

### ISSUE THREAD

**Issue by lazy-bum** [influxdata/docs-v2#5678]
_Describe the issue here._

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2/admin/backup-restore/backup/
- _Provide other relevant URLs (project issues, community threads, etc.)_

./influx backup ./backup -t 6CQ1LkeIvMJeVwirFU7aLC6DMvRzteUldYi4SVDgjgU6HkywMm0kyl9Kx8-3-uc3bVBx8h_1odsHdyzCe_tjAQ==

**Comment by jstirnaman** [comment]
`401` means "unauthorized". It indicates your token isn't the root token or doesn't have necessary permissions.
