### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by d2box** [influxdata/docs-v2#5687]
_Describe the issue here._
the link for "upload a CSV file" at the top of this page is: http://localhost:1313/influxdb/cloud/write-data/no-code/load-data/ (unreacheable as it refers to localhost)

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/reference/syntax/annotated-csv/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by jstirnaman** [comment]
Doh, thanks for reporting this!
