### ISSUE TITLE
Backup and Restore 

### ISSUE THREAD

**Issue by kalexdobler** [influxdata/docs-v2#5694]
_Describe the issue here._
<img width="889" alt="Screenshot 2024-12-02 at 17 33 38" src="https://github.com/user-attachments/assets/db9c48be-adfe-4cfb-bfc2-9b9e3094f1f8">
<img width="895" alt="Screenshot 2024-12-02 at 17 28 41" src="https://github.com/user-attachments/assets/dd745d04-50f5-4042-b849-70f3152289ce">
Can this be true? If there is no incremental OR full backup then an incremental would be performed as a full right?
Also for the backup / restore example I do not get the point here....backing up and restoring on 1.11.8 is clear but whats the point of it?
##### Relevant URLs
- https://docs.influxdata.com/enterprise_influxdb/v1/administration/backup-and-restore/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by jstirnaman** [comment]
> Can this be true? If there is no incremental OR full backup then an incremental would be performed as a full right?
Right, and that agrees with the doc text.

> backing up and restoring on 1.11.8 is clear but whats the point of it?
Restoring to a new/separate instances (OSS to OSS, Enterprise to OSS, etc.)

**Comment by kalexdobler** [comment]
https://docs.influxdata.com/enterprise_influxdb/v1/administration/backup-and-restore/#perform-an-incremental-backup
Here it says: _If there are any existing backups the current directory, the system performs an incremental backup_
which makes more sense.
