### ISSUE TITLE
Single-node enterprise meta node flag missing in docs?

### ISSUE THREAD

**Issue by danatinflux** [influxdata/docs-v2#5695]
The existing 'single node enterprise setup docs' found [here](https://docs.influxdata.com/enterprise_influxdb/v1/introduction/installation/single-server) do not appear to have a mention of a flag that's recommended in the plutonium docs [here](https://github.com/influxdata/plutonium/blob/master/README.md#single-node-setup), specifically the `-single-server` flag that ensures that the single meta node is able to become leader. 

Should we add that to the setup docs, along with an example how to alter the service to add the flag?

**Comment by jstirnaman** [comment]
@gunnaraasen Recommend `-single-server flag` for Enterprise setup?

**Comment by danatinflux** [comment]
We have a whole doc literally named `Install InfluxDB Enterprise on a single server`, soooo???
