### ISSUE TITLE
Guide for converting TICKscript to Flux

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#587]
Flux is designed to perform most tasks that Kapacitor currently performs. Unlike InfluxQL, there will be no TICKscript transpiler. We need to create a guide that covers how to convert a TICKscript into a Flux script. Important things to cover:

- Flux only supports batch data; no streaming data.
- Walk through how to replicate each TICKscript node in Flux along with properties/parameters.

This will also help to determine TICKscript/Flux parity.

**Comment by gabzim** [comment]
i'm learning kapacitor right now, should i learn TICKscript or go straight for flux? am I able to use Flux for alerts? all the tutorials i see use TICKscript but it seems very similar to Flux so I'm confused.

**Comment by sanderson** [comment]
@gabzim TICKscript is specific to Kapacitor. Kapacitor is a data processing engine designed to provide robust alerting for InfluxDB (specifically 1.x). Flux is a data query/scripting language that can do almost everything that TICKscript can do as well as things that TICKscript can't. It's really a matter of preference and workflow. Do you want to use Kapacitor as a sidecar to InfluxDB 1.x or 2.0? Both support it. (Here's documentation for using Kapacitor with InfluxDB 2.0: https://docs.influxdata.com/influxdb/v2.0/tools/kapacitor/)

If I were making the choice, I'd focus on learning Flux. Flux is incredibly flexible and can send alerts really easily. Building out more documentation around building raw Flux checks and alerts is in my backlog, so it will be coming soon.

**Comment by gabzim** [comment]
I'm on influx cloud (I think that's 1.8?), Right now I'm setting up our own kapacitor instance in our infra. But if I can do everything (or almost everything) with flux and not have to use kapacitor that's one less moving piece I need to monitor/worry about.

**Comment by sanderson** [comment]
If you're on InfluxDB Cloud, I'd go the Flux route. Shipping all the data to Kapacitor is just unnecessary overhead.
