### ISSUE TITLE
Document 'influx pkg' command

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#607]
PR: https://github.com/influxdata/influxdb/pull/15937

We need to document the new `influx pkg` command when allows users to create custom packages of dashboards, buckets, lables, tasks, etc. We also need to create a doc that walk through how to use the `pkg` system in general.

- [x] `influx pkg` doc
- [ ] Using InfluxDB packages

**Comment by russorat** [comment]
The pkg command work is wrapping up, so you should be good to doc it. let me know if you have questions.

**Comment by sanderson** [comment]
The `influx pkg` command has been fully documented. Closing this issue and linking it to #706.
