### ISSUE TITLE
Dead links in docs

### ISSUE THREAD

**Issue by jwblaney** [influxdata/docs-v2#636]
3 links at the bottom of https://v2.docs.influxdata.com/v2.0/reference/key-concepts/data-elements/ lead to 404s.

##### Relevant URLs
Main page: https://v2.docs.influxdata.com/v2.0/reference/key-concepts/data-elements/

Dead links:
https://v2.docs.influxdata.com/influxdb/v0.10/introduction/getting_started/
https://v2.docs.influxdata.com/influxdb/v0.10/guides/writing_data/
https://v2.docs.influxdata.com/influxdb/v0.10/guides/querying_data/

##### What products and version are you using?
 v2 docs

**Comment by sanderson** [comment]
Thanks @jwblaney. We'll get these fixed.

**Comment by kelseiv** [comment]
thank you, @jwblaney! Updated.
