### ISSUE TITLE
Update ECS Telegraf Plugin info to "Amazon ECS"

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#638]
Update ECS plugin title to "Amazon ECS" and all description information

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/reference/telegraf-plugins/

Reference to [1.x Docs issue #2527](https://github.com/influxdata/docs.influxdata.com/issues/2527)

**Comment by kelseiv** [comment]
thank you, @sjwang90! Updated.
