### ISSUE TITLE
Does we have plan to translate document to other language?

### ISSUE THREAD

**Issue by Turing-Chu** [influxdata/docs-v2#642]
_Describe the issue here._

Does we have plan to translate document to other language?
##### Relevant URLs
- _Provide relevant URLs_

##### What products and version are you using?

InfluxDB v2.0

**Comment by sanderson** [comment]
@Turing-Chu In the short-term, no. The InfluxDB 2.0 documentation is in a rapid development cycle and will continue to be for the foreseeable future. Translation is a large undertaking that I believe will be something we need to undertake in the future, but for now, all documentation is written and published in English. Thanks for reaching out!
