### ISSUE TITLE
Error in "Use and manage variables" page

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#643]
_Describe the issue here._

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/visualize-data/variables/

##### What products and version are you using?

In the source code snippet:

`  |> filter(fn (r) => r._measurement == v.measurement and r._field == v.field)

... I believe you're missing a colon after _fn_. So the snippet should be:

`  |> filter(fn: (r) => r._measurement == v.measurement and r._field == v.field)

**Comment by sanderson** [comment]
Thanks @alsargent!
