### ISSUE TITLE
Document Flux VS Code plugin

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#678]
We have a Flux VS Code plugin!

##### Relevant URLs
https://marketplace.visualstudio.com/items?itemName=influxdata.flux

**Comment by jademcgough** [comment]
Let me know if you'd like help with this.

Someone in our community slack also mentioned that they'd like documentation on our language server (which powers the Flux VS Code plugin), and how to use it with various editors.

**Comment by jademcgough** [comment]
Brandon wrote up a bit on setting up the language server with different editors: https://docs.google.com/document/d/1fPVT0ExenIhnrsbwBakJBJYUqGO4wbUYnxISWOpEhdQ/edit?usp=sharing
