### ISSUE TITLE
List all Cloud2 URLs for Telegraf config

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#681]
_Describe the issue here._

On https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/manual-config/, we only list the URL for AWS Oregon (https://us-west-2-1.aws.cloud2.influxdata.com). We should also list the URLs for AWS Frankfurt and Google Cloud.

That should look something like this:

```
# Use this to write to AWS Oregon:
[[outputs.influxdb_v2]]
  urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  token = "$INFLUX_TOKEN"
  organization = "example-org"
  bucket = "example-bucket"

# Use this to write to AWS Frankfurt:
[[outputs.influxdb_v2]]
  urls = ["https://eu-central-1-1.aws.cloud2.influxdata.com"]
  token = "$INFLUX_TOKEN"
  organization = "example-org"
  bucket = "example-bucket"

# Use this to write to Google Cloud Iowa:
[[outputs.influxdb_v2]]
  urls = ["https://prod01-us-central-1.gcp.cloud2.influxdata.com"]
  token = "$INFLUX_TOKEN"
  organization = "example-org"
  bucket = "example-bucket"

```

##### Relevant URLs

https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/manual-config/

##### What products and version are you using?

InfluxDB Cloud 2.0

**Comment by tkyocum** [comment]
I would suggest not hard-coding URLs in docs but instead explaining where a user might look for the right address to put in their configuration. 

My rationale is that today we have only three clusters, but in time we will have dozens across many providers including multiple clusters per provider and even region.

Further, DNS names may change in time. Any change to address would then require a manual documentation update.

**Comment by alsargent** [comment]
Agreed, DRY is good since it means less to update. Someone needs to create that canonical page of InfluxDB Cloud URLs.
