### ISSUE TITLE
Users can be viewed in 2.0 OSS

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#687]
https://v2.docs.influxdata.com/v2.0/users/view-users/#view-users-in-the-influxdb-ui

Users can be viewed in OSS under Settings > Members

![image](https://user-images.githubusercontent.com/4805997/71601248-6d7e9880-2b07-11ea-9f23-f69230c402b6.png)

**Comment by sanderson** [comment]
@Russ, the screenshot you provided is for viewing members of an organization, which is documented here: https://v2.docs.influxdata.com/v2.0/organizations/members/view-members/

"Users" exist outside of organizations. A user is created, then added to an organization. To my knowledge, there currently isn't a way to see users who haven't been added as members of an org.

**Comment by russorat** [comment]
ok, i understand the distinction. it feels like we are overcomplicating this though. There's no reason to create a user outside of an organization. 

Also, trying to do so on the command line results in an error:
```
➜ ./bin/darwin/influx user create -n someone
Error: Must specify org-id, or org name.
```

which means these docs also need to be updated: https://v2.docs.influxdata.com/v2.0/users/create-user/#create-a-user-using-the-influx-cli

**Comment by sanderson** [comment]
Gotcha. A use case for creating a user outside of an org is so that a single user can belong to multiple organizations, but I guess that is still the case. You just have to assign a user to an organization whenever you create a new user.
