### ISSUE TITLE
searching for "change password" should show better results

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#696]
You can change your password using the "Update User" command, but it isn't immediately obvious IMO and searching for "change password" doesn't show anything useful.

https://v2.docs.influxdata.com/v2.0/users/update-user/#update-a-user-using-the-influx-cli

![image](https://user-images.githubusercontent.com/4805997/71837257-d071b180-306a-11ea-863e-df88b98bd521.png)

![image](https://user-images.githubusercontent.com/4805997/71837276-d9fb1980-306a-11ea-81d3-e5cf25fa7a2e.png)

**Comment by sanderson** [comment]
This currently isn't possible. Here's the related issue: https://github.com/influxdata/influxdb/issues/16440
