### ISSUE TITLE
Document UI keyboard shortcuts

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#707]
There are a few keyboard shortcuts in the InfluxDB UI:

**Script Editor**  
`ctrl + /` comments out the current line or selected lines
`ctrl + return/enter` submits the query

**General UI**  
`esc` to close modal windows (proposed, but not implemented)

**Comment by pierwill** [comment]
On my Mac, with influx built from https://github.com/influxdata/influxdb/commit/f897c1518768f326962a3c257b1645ad3e68c411, the current behavior in the script editor is:

- `⌘ + /` for comments
- `ctrl + enter` to submit query
