### ISSUE TITLE
Document reserved tag keys

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#713]
Review topics related to:

key concepts
writing data
line protocol
Add the following content where applicable:

"Avoid using the following reserved tag keys:
_field
_measurement
time

If reserved tag keys are included, the associated point is discarded."

**Comment by sanderson** [comment]
Restrictions on keys that begin with underscores are already documented in the line protocol doc, but there are probably places we could cross reference them.

https://v2.docs.influxdata.com/v2.0/reference/syntax/line-protocol/#naming-restrictions
