### ISSUE TITLE
Add example docker compose file to getting started docs

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#729]
https://v2.docs.influxdata.com/v2.0/get-started/#download-and-run-influxdb-v2-0-beta

Right now, we have instructions on how to manually pull the Docker image, but we should add instructions for getting influxdb running via a docker-compose file. 

the goal should be that a user should be able to run the docker compose file from our docs and get to a point where influxdb 2.0 is writing data without manual intervention.

**Comment by pierwill** [comment]
Closing in favor of https://github.com/influxdata/docs-v2/issues/2700.
