### ISSUE TITLE
Document using Grafana Cloud with InfluxDB 2.0

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#737]
The Grafana guide currently only covers using the open source version of Grafana with InfluxDB 2.0, but users should be able to use Grafana Cloud as well. The biggest difference that I'm aware of is how the Flux data source plugin is installed, but I'm not 100% sure of the process.

##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/visualize-data/other-tools/grafana/

**Comment by timhallinflux** [comment]
We should move this up the priority list...

**Comment by rickspencer3** [comment]
aui, the current plan is that the Grafana UI will have a version dropdown. When they select version 2, they will be prompted to supply:

 * bucket name
 * org
 * token

Previously, this would have been database, username, password. 

Perhaps we should consider specific documentation that tells them where to get this information in the InfluxDB UI and CLI.

**Comment by sanderson** [comment]
@rickspencer3 When is the updated plugin supposed to roll out?
