### ISSUE TITLE
Include "How to Write a Telegraf Plugin" documentation

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#738]
_Describe the issue here._
Include a page for How to Write a Telegraf Plugin in docs for easier and more formal discovery for users.  Can use existing content in blogs/webinars. 

##### Relevant URLs
- https://www.influxdata.com/blog/how-to-write-telegraf-plugin-beginners/
- https://www.influxdata.com/training/write-your-own-telegraf-plugin/

##### What products and version are you using?

Would be included in v1 and v2 docs

**Comment by sjwang90** [comment]
@mhall119 add any discussion points

**Comment by sanderson** [comment]
Thanks for this @sjwang90. This would be a good addition.

To open a larger can of worms... we need to decide exactly how to handle Telegraf docs in 2.0. Telegraf is on a different version track than InfluxDB and doesn't easily fit into the current 2.0 versioned content structure. When we first architected the 2.0 docs, the plan was to spin Telegraf and Flux docs into their own documentation sites, but I don't think that's the plan anymore (at least in the short term).

**Comment by sjwang90** [comment]
Definitely makes sense... @noramullen1 is working on another How to HTTP plugin doc for Telegraf so we were thinking we could have a list of guides fall under the 1.x docs.  As long as there's somewhere in v2 docs linking to the v1 docs I'm fine keeping most of these Telegraf doc enhancements in v1.

**Comment by noramullen1** [comment]
Here's the branch where I'm working on this in the 1.x docs repo

https://github.com/influxdata/docs.influxdata.com/compare/write-telegraf-plugin
