### ISSUE TITLE
Updates to `influx pkg` and subcommands need doc updates

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/docs-v2#745]
_Describe the issue here._

The influx pkg commands had some updates today that will need to be updated in the docs.

relevant issues from influxdb: 
- https://github.com/influxdata/influxdb/pull/16767 
- https://github.com/influxdata/influxdb/pull/16765

##### Relevant URLs
- _Provide relevant URLs_
https://v2.docs.influxdata.com/v2.0/reference/cli/influx/pkg/
https://v2.docs.influxdata.com/v2.0/reference/cli/influx/pkg/summary/
https://v2.docs.influxdata.com/v2.0/reference/cli/influx/pkg/validate/

##### What products and version are you using?

OSS v2 master

**Comment by sanderson** [comment]
Thanks @jsteenb2!
