### ISSUE TITLE
Create a single doc for common Flux queries/tasks

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#770]
We need to provide a page that shows how to run common queries in Flux. This can be used as a go-to resource as people are getting used to Flux and should act as a copy/paste source.

- [x] SELECT-like commands
- [x] Median/Percentile
- [x] Cumulative Sum
- [x] Moving Average
- [x] Increase
- [x] Rate
- [ ] Delta
- [x] Window
- [x] First/Last
- [x] Histogram
- [x] Gap filling
- [ ] ~Last observation carried forward~ _(currently not supported)_
- [x] Last point

**Comment by rickspencer3** [comment]
I think the goal should be to ensure that the documentation is task based. Not "this is a list of common flux queries" more like "these are common tasks and how to accomplish them."
