### ISSUE TITLE
Flux Join does not actually support any of the documented Methods

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/docs-v2#779]
The documentation for join() includes that method parameter, which does indeed exist. However, the join function only accepts "inner" which is the default. This renders the parameter useless, and the documentation confusing.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/join/

\

**Comment by sanderson** [comment]
Thanks @rickspencer3, I fixed part of this yesterday, but I missed something else that will be fixed shortly.
