### ISSUE TITLE
Add flux query example to variables page

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#782]
The variables section of the documentation should show how to use a variable in the query. This has come up specifically with the map variable type, but could be useful for the others as well.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/visualize-data/variables/variable-types/#map

**Comment by timhallinflux** [comment]
@russorat do you have a sample query that shows this?  and potentially shows how to reference the input value vs. output value.
