### ISSUE TITLE
Prometheus Telegraf plugin typo

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/docs-v2#787]
Typo: "input plugin" is repeated in Prometheus Telegraf plugin listing

## URL
https://v2.docs.influxdata.com/v2.0/reference/telegraf-plugins/#prometheus

![image](https://user-images.githubusercontent.com/56005508/75589863-cd72bc00-5a30-11ea-9182-e23001d996fd.png)

**Comment by noramullen1** [comment]
Thanks @mnorriswalker! This is fixed.
