### ISSUE TITLE
Footer refers to nonexistent Feedback link

### ISSUE THREAD

**Issue by mleonhard** [influxdata/docs-v2#790]
The 2.0 Getting Started page has a footer that says:
"In the InfluxDB UI, click Feedback in the left navigation bar."
But the navigation bar has no Feedback option.

##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/get-started/

**Comment by sanderson** [comment]
@mleonhard The feedback icon exists in the left nav in both InfluxDB 2.0 OSS and InfluxDB Cloud 2.0.

![image](https://user-images.githubusercontent.com/181484/75900982-0fb64780-5dfb-11ea-9568-4a84594f7dfc.png)

**Comment by mleonhard** [comment]
It's not showing in Safari 13.0.5 (15608.5.11) on MacOS 10.15.3 (19D76).  Nor in Firefox 73.0.1 (64-bit).  Nor in Chrome Version 80.0.3987.116 (Official Build) (64-bit).  Here's the Safari screenshot:

![Screen Shot 2020-03-06 at 01 25 52](https://user-images.githubusercontent.com/520739/76070598-a85add80-5f49-11ea-9fd1-6f0486eda140.png)

**Comment by sanderson** [comment]
The feedback button is in the InfluxDB UI navigation, not in the documentation navigation.

**Comment by mleonhard** [comment]
I apologize.  I didn't read it carefully.
