### ISSUE TITLE
Unable to switch to 1.x docs

### ISSUE THREAD

**Issue by mleonhard** [influxdata/docs-v2#791]
The Getting Started page has a blue selection box in the upper-right corner that says "2.0".  Clicking it reveals a "1.x" option.  But clicking "1.x" takes me to the root 2.0 docs page:
https://v2.docs.influxdata.com/v2.0/

How can I find the 1.x docs?

##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/get-started/

**Comment by mleonhard** [comment]
I found the proper URL: https://docs.influxdata.com/influxdb/v1.7/

**Comment by sanderson** [comment]
Thanks for reporting this @mleonhard. I'm updating the template to more predictably generate the 1.x docs URL.
