### ISSUE TITLE
Add retention policy duration to bucket create CLI documentation

### ISSUE THREAD

**Issue by mia-krause** [influxdata/docs-v2#793]
The `influx bucket create` command expects the retention policy with explicit duration, but the documentation states that the duration is set to nanoseconds.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/organizations/buckets/create-bucket/

**Comment by sanderson** [comment]
Thanks @mia-krause. This was a small change that slipped through the cracks. We'll make sure to update this.

**Comment by sanderson** [comment]
Also related: https://github.com/influxdata/influxdb/issues/17107
