### ISSUE TITLE
Explain strict when describing geo.strictFilter() function

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#802]
_Describe the issue here._

On the page:

https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/experimental/geo/strictfilter/

... the term "strict" is used, but not defined. 

Please explain that strict filters out points that might have bled outside the boundary, due to the way that the s2 geometry library works. It'd also be good to provide some visual examples of strict on, and strict off.

##### Relevant URLs
- _Provide relevant URLs_

https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/experimental/geo/strictfilter/

**Comment by russorat** [comment]
@alsargent thanks. i believe this will be part of the updates to docs for the next beta release.
