### ISSUE TITLE
Docker Volume Examples and Guidelines

### ISSUE THREAD

**Issue by shiggins8** [influxdata/docs-v2#816]
This section of documentation (https://v2.docs.influxdata.com/v2.0/reference/config-options/) includes default values for all relevant pieces of persistent storage, however the Docker section doesn't make any mention of how to set up volumes or mounts for persistent storage from within Docker. That would be very helpful! I'd be happy to help write or contribute if y'all would like, just let me know!

**Comment by sanderson** [comment]
Thanks @shiggins8! Any insight and guidance you can provide would be greatly appreciated.

**Comment by shiggins8** [comment]
@sanderson sure thing! According to the docs I linked earlier, the main requisites for persistence are: `--bolt-path` (defaults to: `~/.influxdbv2/influxd.bolt`) and `--engine-path` (defaults to `~/.influxdbv2/engine`). So the easiest solution for the Docker container is to add a mount like this:

`... -v <path to mount or name of docker volume>:/root/.influxdbv2 ...`

This will allow for persistence when the container is re-created.
