### ISSUE TITLE
Typo in content/v2.0/query-data/get-started/_index.md

### ISSUE THREAD

**Issue by joeyhagedorn** [influxdata/docs-v2#822]
Line 27 in: content/v2.0/query-data/get-started/_index.md

reads "last 5 minutes" but I think it should read "last hour". 
The code example says "-1h" but the textual description says 5 minutes.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/query-data/get-started/

##### What products and version are you using?
2.0 docs on the website.

**Comment by sanderson** [comment]
Thanks @joeyhagedorn! Nice catch! Fixing...

**Comment by joeyhagedorn** [comment]
Thanks for the quick fix!
