### ISSUE TITLE
Flux json.encode documentation does not list object as a valid input parameter type

### ISSUE THREAD

**Issue by mcassaniti** [influxdata/docs-v2#843]
The list of valid values for parameter `v` for `json.encode` currently does not include `object`. The following code snippet is valid, but the documentation suggests it is not.

```
json.encode(v: {"key1": "value1", "key2": 6, "key3": 4.95})
```

##### Relevant URLs
- [json.encode](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/json/encode/)
- Issue #393

##### What products and version are you using?

I've confirmed that this undocumented behaviour works on Flux version 0.59.6

**Comment by russorat** [comment]
@mcassaniti thanks for the issue! we will take a look.
