### ISSUE TITLE
Missing comma in geo.filterRows() example

### ISSUE THREAD

**Issue by nisley** [influxdata/docs-v2#844]
https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/experimental/geo/filterrows/

Need a comma at the end of the region: line:
```
geo.filterRows(
  region: {lat: 40.69335938, lon: -73.30078125, radius: 20.0}
  minSize: 24,
```

**Comment by kelseiv** [comment]
thanks, @nisley!
