### ISSUE TITLE
Add example for manually adding Telegraf plugins

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#845]
We need to walk users through the process of:

1. Find the plugin you want to enable (plugins list)
2. Visit the plugin page on GH
3. Copy and paste the example config into your `telegraf.conf`
4. Restart Telegraf

##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/manual-config/

**Comment by noramullen1** [comment]
@sjwang90

**Comment by noramullen1** [comment]
Include MQTT as a clear example and keyword tag

**Comment by noramullen1** [comment]
Reopening after reviewing with Tim to make further updates
