### ISSUE TITLE
Update CLI to use config profiles instead of setting env vars

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#846]
https://v2.docs.influxdata.com/v2.0/reference/cli/influx/#usage

the note on this page should reference setting up an influx config instead of setting config vars and the authorizations file.

**Comment by russorat** [comment]
This also should be updated in the getting started page

**Comment by kelseiv** [comment]
Thank you, @russorat, @noramullen1. Addressed in https://github.com/influxdata/docs-v2/pull/1105.
