### ISSUE TITLE
Add option to Kubernetes getting started for using the helm chart for InfluxDB2

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#850]
Once this pr is merged: https://github.com/influxdata/helm-charts/pull/35

I'd like to update the kubebrnetes getting started in the docs to show this as an option as well.

**Comment by russorat** [comment]
This has been merged.

**Comment by rawkode** [comment]
@sanderson Happy to pair with someone on @influxdata/docs-team on this

**Comment by sanderson** [comment]
Thanks @rawkode! @pierwill ☝️
