### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by thisiswhereitype** [influxdata/docs-v2#855]
When browsing another page in the documentation, the `how-to guides` section links to the current page.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/backup-restore/
In my browser, the how-to guide in the left-side menu links back to the current page.

##### What products and version are you using?
na

**Comment by sanderson** [comment]
@thisiswhereitype Thanks for the heads up! The how-to section was recently restructured and it some of the menu restructuring got missed. I'm pushing a fix shortly. How to guides can be access in the [Query with Flux section](https://v2.docs.influxdata.com/v2.0/query-data/flux/).
