### ISSUE TITLE
Document new '#linepart' annotation in annotated CSV

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#857]
PR: https://github.com/influxdata/influxdb/pull/17398

There is a new `#linepart` annotation that allows users to identify measurement, tag, field and time columns in annotated CSV.

##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/reference/syntax/annotated-csv/
- https://github.com/bonitoo-io/influxdb-csv-import

**Comment by sranka** [comment]
Note that #linepart is never returned in CSV response format, it can be added to CSV files for "influx write" cli
