### ISSUE TITLE
Have all pages that mention localhost:9999 also point to our cloud URLs

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#866]
There are about 180 pages on our v2 docs site that talk about accessing an InfluxDB OSS instance using localhost:9999. We should ensure that these pages, when appropriate, also point to our InfluxDB Cloud 2 URLs page, so that we make it easier for our Cloud 2 users to access their database.

The Cloud 2 URLs page is at https://v2.docs.influxdata.com/v2.0/cloud/urls/

For example, this page: https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/auto-config/#create-a-telegraf-configuration -- is early in our Cloud 2 email sequence for new users. But it doesn't even talk about how to access Cloud 2. Only how to access a local InfluxDB instance. This sets up friction that makes things harder for Cloud 2 users.

##### Relevant URLs
You can find all ~180 pages that mention InfluxDB OSS using this google search:

https://www.google.com/search?q=site%3Av2.docs.influxdata.com+9999

**Comment by sanderson** [comment]
Thanks for this @alsargent. This is part of a larger strategy to put cloud first. Side note is that many of these are CLI docs where `localhost:9999` is listed as the default value for the global `--host` flag. But there are still plenty of pages that could use this update.

**Comment by noramullen1** [comment]
Closing this in favor of master version of this issue, #939
