### ISSUE TITLE
Update influxd configuration options

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#916]
New configurations options have been added to the `influxd` agent. I don't exactly when they were added, but the following are missing:

---

- [x] **--new-meta-store**  
    enables the new meta store

- [x] **--new-meta-store-read-only**  
    toggles read-only mode for the new meta store, if so, the reads are duplicated between the old and new store (has meaning only if the new meta store is enabled) (default true)

- [x] **--no-tasks**  
    disables the task scheduler

- [x] **--query-concurrency**  
the number of queries that are allowed to execute concurrently (default 10)

- [x] **--query-initial-memory-bytes**  
    the initial number of bytes allocated for a query when it is started. If this is unset, then query-memory-bytes will be used

- [x] **--query-max-memory-bytes**  
    the maximum amount of memory used for queries. If this is unset, then this number is query-concurrency * query-memory-bytes

- [x] **--query-memory-bytes**  
    maximum number of bytes a query is allowed to use at any given time. This must be greater or equal to query-initial-memory-bytes (default 10485760)

- [x] **--query-queue-size**  
    the number of queries that are allowed to be awaiting execution before new queries are rejected (default 10)

- [x] **--tls-cert**  
    TLS certificate for HTTPs

- [x] **--tls-key**  
    TLS key for HTTPs

---

##### Relevant URLs
_Both the following pages need to be udpated:_
- https://v2.docs.influxdata.com/v2.0/reference/cli/influxd/
- https://v2.docs.influxdata.com/v2.0/reference/config-options/

**Comment by pierwill** [comment]
The TLS  options are on https://v2.docs.influxdata.com/v2.0/reference/cli/influxd/, but not https://v2.docs.influxdata.com/v2.0/reference/config-options/. Will update—
