### ISSUE TITLE
Decision Tree under Write Data

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#920]
When a user looks into "Write Data" section on different methods on how to write data into InfluxDB.  Provide a decision tree to determine what product is the best (Telegraf, Client libs, etc...)

Write your own telegraf plugin would be the last branch if the user does not have any alternatives. Dave from the Telegraf team is outlining a decision tree for a "how to write a telegraf plugin portion"

**Comment by sanderson** [comment]
I think the recent Write data reorg addresses this issue. Closing for now. Feel free to re-open if wen want to revisit this.
