### ISSUE TITLE
Work with Google to publish documentation to cloud.google.com/docs

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#94]
As we work through the rollout of InfluxDB Cloud v2, we will deploy on GCP Marketplace.  As part of our relationship with Google, we are required to publish our documentation into their site.

We will need to determine:
1) format for the content (output from Hugo?)
2) publishing process and frequency (limits?, controls?)

We will need to work with @gunnaraasen very closely on this effort.

**Comment by kelseiv** [comment]
@gunnaraasen checking back on/doing research to see if we need any updates at this point
