### ISSUE TITLE
Show Cloud 2 configuration in write-data/use-telegraf/manual-config/

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#949]
In https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/manual-config/, the directions default to local OSS configuration.

When explaining to users on how to setup Cloud 2 configuration to customers, I need to tell customers:

1. Go to https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/manual-config/
2. Search through all the instances of text "InfluxDB Cloud", and click on the one that lets you see the Cloud 2 configuration.

Step 1 is easy, but step 2 can be difficult for users to do properly. There are currently 12 instances of "influxdb cloud" on this page, and the one they need to click on is #10 out of 12.

All this complexity is because we hide the Cloud 2 configuration behind a tab that the user needs to click on; see below:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/20701/79370961-6d64a600-7f08-11ea-89e0-fd5a5d9e14de.png">

Can we simply move the Cloud 2 configuration to a section below the OSS configuration, so that we don't have to go through this complexity in giving directions to users?

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/manual-config/

**Comment by sanderson** [comment]
This is part of what will be covered by #939. Closing in favor of that issue.
