### ISSUE TITLE
Provide example Cloud 2 configuration in write-data/use-telegraf/manual-config/

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#950]
I continue to get emails from new Cloud 2 users that are struggling to connect Telegraf to their Cloud 2 instance. 

One challenge I see is that, in https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/manual-config/, we don't provide an example of Telegraf output configuration for Cloud 2. Here's the section of the page I'm talking about:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/20701/79371286-fbd92780-7f08-11ea-9344-e86f99482bad.png">

While this is succinct, it's also a bit abstract. For this reason, at the bottom of this section, it'd be great if we could provide a working example along the lines of the following:

_For example, if your Telegraf agent needs to send data to AWS Oregon, you'd have the following in your Telegraf configuration file:_

```
[[outputs.influxdb_v2]]
  # Below is for AWS Oregon
  # Complete list is at https://v2.docs.influxdata.com/v2.0/cloud/urls/
  urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]

  # Find this in Data > Tokens menu
  token = "$INFLUX_TOKEN"

  # In Cloud 2, your default organization is the email you signed up with.
  organization = "youremail@yourcompany.com"

  # Find this in Data > Buckets menu
  bucket = "example-bucket"
```

_Note that your InfluxDB Cloud 2 URL should not in ":9999", as with InfluxDB OSS._

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/write-data/use-telegraf/manual-config/

**Comment by sanderson** [comment]
This is part of what will be covered by #939. Closing in favor of that issue.
