### ISSUE TITLE
Link to Cloud URLs on v2.0/reference/cli/influx/

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#951]
On https://v2.docs.influxdata.com/v2.0/reference/cli/influx/, it only shows the way to access a local InfluxDB OSS instance; it doesn't provide any reference to our InfluxDB Cloud 2 URLs on this page: https://v2.docs.influxdata.com/v2.0/cloud/urls/

Please provide a reference to this page.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/reference/cli/influx/

**Comment by sanderson** [comment]
This is part of what will be covered by #939. Closing in favor of that issue.
