### ISSUE TITLE
Wrong flag on "Add a member to an organization using the influx CLI"

### ISSUE THREAD

**Issue by andersekbom** [influxdata/docs-v2#955]
The example in step 2 reads:
`influx org members add -n <org-name> -o <user-ID>`

but that gives the error:
"Error: unknown shorthand flag: 'o' in -o"

The example should read
`influx org members add -n <org-name> -m <user-ID>`
according to `influx org members add -h`

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/organizations/members/add-member/

**Comment by pierwill** [comment]
Thanks for this, @andersekbom!
