### ISSUE TITLE
Document feature flags

### ISSUE THREAD

**Issue by gavincabbage** [influxdata/docs-v2#976]
Document procedure for adding, consuming and changing feature flags.

The PR below adds feature flag capabilities to InfluxDB to allow users to exercise experimental features before they are enabled by default.

A feature flag is **created** by updating `flags.yml` and running `make flags`. It includes a default value.

A feature flag is then **consumed** in code:
- On the backend, a flag can be used like this
```go
if feature.MyFeatureFlag().Enabled(ctx) {
    // new code path...
} else {
    // old code path...
}
```
- On the frontend, a similar pattern can be used based on the response from `/api/v2/flags`

Finally, the value of a flag can be **changed** from the default using the `INFLUXD_FEATURE_FLAGS` environment variable or `--feature-flags` CLI flag. In the first case, the environment variable should be formatted as a JSON map of string keys to string values, e.g.
```
env INFLUXD_FEATURE_FLAGS="{\"flag1\":\value1\",\"key2\":\"value2\"}" influxd
```
In the the second case, the flag value should be formatted as a comma-delimted list of key-value pairs, with an equals sign as an assignment operator, e.g.
```
influxd --feature-flags flag1=value1,flag2=value2
```

##### Relevant URLs
- [InfluxDB PR](https://github.com/influxdata/influxdb/pull/17851)
- [Existing internal documentation may provide a starting point (private link)](http://docs.internal/operations/guides/feature-flags/)
- [Code documentation](https://github.com/influxdata/influxdb/pull/17851/files#diff-1a27d6fe9284b98afad5ee8b1d8a3a85)

##### What products and version are you using?

InfluxDB 2.0

**Comment by noramullen1** [comment]
Hi @gavincabbage , is this a feature just for internal use?

**Comment by sanderson** [comment]
@noramullen1 @gavincabbage There has been discussion around leaving this feature undocumented. I don't know that we've come to a consensus yet, but I think we better put this on hold.
