### ISSUE TITLE
Teeny Tiny CLI update

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/docs-v2#977]
add usage update to `influx config` command

https://github.com/influxdata/influxdb/pull/17858

**Comment by pierwill** [comment]
Hi @jsteenb2! Looks like we might have this documented already? Can you took a look here and let us know if updates need to be made? https://v2.docs.influxdata.com/v2.0/reference/cli/influx/config/#quickly-switch-between-configurations

**Comment by jsteenb2** [comment]
oh snap, you all are way ahead of the game 😃, closing
