### ISSUE TITLE
CLI page is broken

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#988]
<img width="944" alt="Screen Shot 2020-04-28 at 12 09 51 PM" src="https://user-images.githubusercontent.com/23535264/80527548-5fbc1100-8949-11ea-8e7f-cc9d32f67490.png">

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/reference/cli/

**Comment by sanderson** [comment]
Sorry, this was my fault. I updated the children shortcode and broke this a little bit. It's fixed now.
