### ISSUE TITLE
InfluxDb Table Structure -- Misleading Info

### ISSUE THREAD

**Issue by dp1140a** [influxdata/docs-v2#997]
On the URl below the docs state:
[https://v2.docs.influxdata.com/v2.0/reference/key-concepts/table-structure/](https://v2.docs.influxdata.com/v2.0/reference/key-concepts/table-structure/)

> InfluxDB 2.0 uses the following columnar table structure to store data: 

This is potentially misleading as the DB actually stores data in a TSM file.  Furthermore Influx does not really have "tables".

Rather we may want the docs to state that this is for [annnotated csv](https://v2.docs.influxdata.com/v2.0/reference/syntax/annotated-csv/#tables), and is how data is presented in a response; not how it is actually stored in the DB

This is sort of nuanced but an important delineation.

**Comment by kelseiv** [comment]
interesting, @dp1140a-thank you!
